src/lib/components/column-profile/CollapsibleTableSummary.svelte, src/lib/components/column-profile/ColumnEntry.svelte, src/lib/components/column-profile/ColumnProfile.svelte, src/lib/components/column-profile/NavEntry.svelte, src/lib/components/table/PreviewTable.svelte, src/lib/components/table/PreviewTableHeader.svelte, src/lib/components/table/TableCell.svelte, src/lib/components/tooltip/StackingWord.svelte, src/lib/components/tooltip/TooltipTitle.svelte, src/lib/components/viz/TopKSummary.svelte, src/lib/util/shift-click-action.ts, src/routes/_surfaces/assets/index.svelte
We had a request come in to add more shift+click functionality. This PR adds it to the assets on the left hand side and to tables.
=> DM-257 adds shift+click functionality to tables

src/lib/components/column-profile/ColumnProfile.svelte, src/lib/components/data-types/DataTypeIcon.svelte, src/lib/components/data-types/FormattedDataType.svelte, src/lib/components/data-types/Interval.svelte, src/lib/components/table/PreviewTable.svelte, src/lib/components/table/TableCell.svelte, src/lib/duckdb-data-types.ts, src/lib/util/formatters.ts, src/routes/dev/__layout.svelte, src/routes/dev/data-types.svelte
We had a bug report that intervals cause a rendering issue. This PR will:
- create an `INTERVAL` representation in the table + in the profilers
- re-organize and clean up the other formatted datatypes
=> DM-345 add support for `INTERVAL` data type representations

src/lib/util/model-structure.test.ts, src/lib/util/model-structure.ts, src/routes/_surfaces/inspector/Model.svelte, test/ui/DataModeler.spec.ts
fixes the top right estimates when the query is broken and also when there is a very small row cardinality
this also fixes the issue with source table aliases not working when you don't include `AS`
=> DM-337 DM-336 DM-297 fixes the rollup factor and NaN issues at the top of the inspector

src/common/data-modeler-service/ProfileColumnActions.ts, src/common/database-service/DatabaseColumnActions.ts, src/common/database-service/DatabaseService.ts, src/lib/components/column-profile/ColumnProfile.svelte, src/lib/components/viz/histogram/TimestampHistogram.svelte, test/data/TimeGrain.data.ts, test/functional/EstimateSmallestTimeGrain.spec.ts, test/functional/EstimateTimeGrain.spec.ts
We've come up with a pretty simple heuristic for estimating the smallest time grain of a `TIMESTAMP` column in duckdb. This is part of our general improvements to profiling time columns which will include an M4-like reduction of the line series. This PR implements the estimation heuristic into our services layer.
=> add time grain estimates to column profiling & interface

README.md
There was a missing prerequisite for installation on Ubuntu, added that info to the readme.
=> Update readme to add instructions for Ubuntu installation

src/lib/components/BarAndLabel.svelte
prop `title` is never used in any instantiation of BarAndLabel
Clears console.warn `<BarAndLabel> was created without expected prop 'title'`
=> Remove prop `title` from BarAndLabel

src/lib/components/table/PreviewTableHeader.svelte
Fixes console warnings:
<TableHeader> was created with unknown prop 'name'
<TableHeader> was created with unknown prop 'type'
=> remove invalid props from <TableHeader> invocation

src/lib/components/column-profile/CollapsibleTableSummary.svelte
Fix console.warn "<NavEntry> was created with unknown prop 'icon'"
=> remove unusable prop for NavEntry in CollapsibleTableSummary

src/lib/components/surface/SurfaceControlButton.svelte
fixes console warning about missing prop in `index.svelte`
=> add default value for prop

src/lib/components/column-profile/CollapsibleTableSummary.svelte, src/routes/_surfaces/assets/index.svelte
Add default `undefined` props to clear console warnings:
<CollapsibleTableSummary> was created without expected prop 'icon'
<CollapsibleTableSummary> was created without expected prop 'path'
<CollapsibleTableSummary> was created without expected prop 'sizeInBytes'
Fix typo resulting in warning
<CollapsibleTableSummary> was created with unknown prop 'sizeInByptes'
=> fix console warning for CollapsibleTableSummary

build-tools/build.sh, package.json
Running `npm run build` now shows output of `svelte-kit build`. See:
=> DM-415 remove build script in favor of `svelte-kit build`

package-lock.json, src/common/serverFactory.ts, src/hooks.ts, svelte.config.js
Using sveltekit's handleEvent hook to handle any request to start the backend server if it has not already started.
=> Using sveltkit hooks to start the socket server

src/common/data-modeler-state-service/entity-state-service/EntityStateService.ts
Motivation:
PR #188 breaks `npm run build` on my machine, due to a problem with importing Immer's `produce` function. It's a bit weird since the PR passed the CI/CD tests. One guess for the discrepancy is that the CI/CD tests ran on Linux, and my machine is a Mac. This Github discussion references Immer function imports working differently in different build environments: https://github.com/immerjs/immer/issues/136
Here's the error message of my broken build:
I fixed it by importing the `produce` function as a "named" import not as a "default" one.
@AdityaHegde, would you mind reviewing this? I see you were the one who originally imported `produce`, so would like your eyes to double check this.
=> change Immer's `produce` from a default to named import

src/lib/components/column-profile/ColumnProfile.svelte, src/lib/components/table/PreviewTableHeader.svelte, src/lib/components/table/TableCell.svelte, src/lib/components/viz/TopKSummary.svelte
this removes an extra linebreak + quote + semicolon in a few places that looks like a small typo that was copy/pasted a few places. Making this change doesn't appear to affect rendering or functionality locally.
=> remove typo that was breaking prettier

src/lib/components/Editor.svelte
Fixes the console error below, as well as a warning about Editor being created without prop `componentContainer` (which is never passed in at any of the places this component is used).
=> fix a console error and a warning

.travis.yml
Having deploy in the common config was causing issues with other jobs. Moving it to binary publish jobs.
=> Moving deploy from common config

src/lib/components/Portal.svelte
tiny change -- this fixes a rare bug by unconditionally removing the `portal` element from the DOM, instead of removing it as a child from `body` (which will sometimes fail).
=> fix edge case error deleting node

.travis.yml, build-tools/post_install.cjs, build-tools/replace_package_type.cjs, package-lock.json, package.json
Making sure scripts run when packaged (currently we package as `module: commonjs`)
=> Fixing packaged npm scripts

.travis.yml
Docker publish is failing during `npm ci`. This is not needed in docker publish. Disabling the install script for the docker publish step.
=> Fixing docker-publish step

src/lib/components/Editor.svelte, src/lib/components/column-profile/CollapsibleTableSummary.svelte, src/routes/_surfaces/inspector/Model.svelte, src/routes/_surfaces/workspace/Header.svelte, src/routes/_surfaces/workspace/ModelWorkspaceHeader.svelte, src/routes/_surfaces/workspace/WorkspaceHeader.svelte, src/routes/_surfaces/workspace/WorkspaceHeaderStatusSpinner.svelte, src/routes/_surfaces/workspace/index.svelte, src/routes/index.svelte
this PR reorganizes the workspace component and so that components other than the Modeler workspace can be dropped in more easily. It also modularizes the header in particular so that it's not strongly coupled with Model entities, and so that other entities can be renamed via callback (although I guess you may not need that functionality Eric).
@ericpgreen2 this should enable you to entirely replace the modeler editor and it's container components, because that was the fastest thing to do in the short term and because I wasn't sure whether you'd need those containers for layout. even as I type this, I think it would probably be helpful to have some of that, so maybe I'll push some more commits to make this just a teeeeeny bit more modular so that you don't have to copy/paste a bunch of …
=> Reorganize-workspace-components

src/cli/bump-version.ts
This PR addresses a few bugs:
- The script was generating a `package.json` file where it should have been generating a `package-lock.json` file.
- The script was reading the local `package.json` before not after `git pull`
- The script used a find-replace for the `package-lock.json` file. A better approach is to regenerate the lockfile.
=> Fix bump version script

src/lib/components/overlay/FileDrop.svelte, src/routes/_surfaces/assets/TableAssets.svelte, src/routes/index.svelte
Closes #425 
The below UI feedback is shown to user when a drag event comes into the app
=> Enable source drop on full screen

src/app.css, src/lib/components/Button.svelte, src/lib/components/Input.svelte, src/lib/components/modal/Modal.svelte, src/lib/components/modal/ModalAction.svelte, src/lib/components/modal/ModalActions.svelte, src/lib/components/modal/ModalContent.svelte, src/lib/components/modal/ModalTitle.svelte, src/routes/_surfaces/inspector/Model.svelte
Addresses #431.
To check out how these components look in practice, I use them on the `rename-source` branch: https://github.com/rilldata/rill-developer/tree/rename-source.  If you pull the branch and run the application, you'll find in the Source assets panel, the ellipsis button now includes a "rename {source}" option. Click that and it'll bring up a modal with buttons.
=> Add `Modal` and `Button` components

src/lib/util/file-upload.ts
If you drop an invalid file (non csv, parquet), the UI is stuck at an overlay screen. This got introduced in #436
=> Remove overlay on invalid drop

src/lib/components/table/PreviewTable.svelte, src/lib/components/table/PreviewTableHeader.svelte, src/lib/components/table/TableCell.svelte, src/lib/components/table/TableHeader.svelte
Wide, unbounded columns were mistakenly introduced by #440. This commit adds a `max-width` to the table cells.
=> Set a max column width for the Preview Table

src/server/ExpressServer.ts
Relative path is considered malicious. We get ForbiddenError if we export from a build.
This PR fixes the above issue.
=> Make export work on build

src/lib/components/metrics-definition/DimensionColumns.ts, src/lib/components/metrics-definition/MeasuresColumns.ts, src/lib/components/table-editable/ColumnConfig.ts, src/lib/components/table-editable/EditableTableHeader.svelte, src/lib/components/table-editable/PinnableTable.svelte, src/lib/components/table-editable/PreviewTable.svelte, src/lib/components/table-editable/TableCellInput.svelte, src/lib/components/table-editable/TableCellRenderer.svelte, src/lib/components/table-editable/TableCellSelector.svelte, src/lib/components/table-editable/pinnableUtils.ts, src/lib/util/humanize-numbers.ts, src/routes/_surfaces/workspace/metrics-def/MetricsDefWorkspace.svelte
@hamilton  here are the user-facing labels in the dropdown along with a number of other refinements to the dropdowns, and a few other things sprinkled in. As you suggested this morning, I added in examples of the numeric formatting in the dropdown, but I think my cut of that idea really doesn't work -- if you had something particular in mind, it will be a quick matter for you to experiment with other ways of showing the example, but at this point I'm kind of leaning towards the perspective that we should leave that out for now and find some way to have an overview elsewhere that looks more like @djbarnwal 's demo page in the dev route
=> refinement to editable-table selector dropdown

src/lib/components/metrics-definition/MetricsDefinitionExploreMetricsButton.svelte, src/routes/_surfaces/workspace/metrics-def/MetricsDefWorkspace.svelte
Add a button to go from the metrics designer to explore. New and improved with disabled states and tooltips.
=> add "explore metrics" button to metrics designer

src/lib/components/data-graphic/elements/GraphicContext.svelte, src/lib/redux-store/explore/explore-apis.ts, src/lib/redux-store/explore/explore-selectors.ts, src/lib/redux-store/measure-definition/measure-definition-readables.ts, src/lib/redux-store/measure-definition/measure-definition-selectors.ts, src/lib/redux-store/utils/api-utils.ts, src/routes/_surfaces/workspace/explore/leaderboards/LeaderboardDisplay.svelte, src/routes/_surfaces/workspace/explore/time-series-charts/MetricsTimeSeriesCharts.svelte
Closes #546
Filtering out measures based on `expressionIsValid` for display and related queries.
=> Filtering out errored out measures

src/common/data-modeler-state-service/entity-state-service/MeasureDefinitionStateService.ts, src/common/rill-developer-service/MeasuresActions.ts, src/common/utils/parseExpression.ts, src/server/parse-test.ts, test/unit/parseExpression.spec.ts
closes #552
Adding `expressionValidationError` to give error message and location. Also adds `disallowedSyntax` for syntaxes that are valid but are not allowed in measure expression.
=> Adding expression validation response

src/common/database-service/utils.ts
I noticed one of my datasets wasn't loading metrics. Figured out why. Should be an easy PR review.
=> updates `getFilterFromTimeRange` to have column names in quotes

src/lib/application-config.ts
There appears to be a text rendering difference on Linux that causes overflow issues on our tighter null percentages. This should fix the issue until we move to a non-monospace font.
=> sets null percentage to 72px to accommodate linux users

src/routes/_surfaces/inspector/ModelInspectorHeader.svelte
Noticing that we're doing some sort of timestamp detection. I removed my query (deleted the select statement to start over) and the UI broke. This fixes that issue.
=> model inspector header: fixes issue with timestamp detection when nothing is selected

src/cli/data-modeler-cli.ts
This makes `rill --version` and `rill -v` output the Rill version number.
Closes #410
=> Add `--version` command to Rill CLI

src/lib/components/metrics-definition/MetricsDefinitionGenerateButton.svelte
reworks the "quick metrics" button to fix #625 and #626
new behavior:
- modal only pops if the metrics definition is empty
- a timestamp no longer needs to be manually selected to use "quick metrics"
- if a model with a timestamp is selected, "quick start" will choose the first time column from the model
- if a model with no timestamp is selected, "quick start" is disabled with tooltip "cannot create metrics for a model with no timestamps"
=> Quick metrics tweaks

package-lock.json, src/cli/post-install.ts, src/common/utils/initLocalConfig.ts, src/server/serverFactory.ts
Making installId stable across installs.
If the user's local config is deleted or if it failed to load, recreating it with a new instalId
=> Stable instalId

src/lib/components/Editor.svelte
Addresses #662 
This PR:
- Changes the syntax highlighting SQL dialect to DuckDB
- Adds `exclude` and `all` to our DuckDB keyword list, so they're highlighted and autocompleted
=> Change syntax highlighting SQL dialect to DuckDB

src/lib/components/Editor.svelte
These keywords get added to autocomplete and syntax highlighting.
=> Add `like`, `ilike`, and `glob` to DuckDB keywords

src/lib/components/data-graphic/utils.ts
Remove mid tick in dates to avoid the following placement of ticks
=> Remove mid tick in dates

scripts/example-project.sh, src/common/data-modeler-state-service/entity-state-service/PersistentModelEntityService.ts, src/common/stateInstancesFactory.ts, src/lib/redux-store/source/source-apis.ts, test/functional/DataLoader.spec.ts, test/functional/DatabaseColumnActions.spec.ts, test/functional/DatabasePriorityQueue.spec.ts, test/functional/EntityStatus.spec.ts, test/functional/ModelFileSync.spec.ts, test/functional/ModelQuery.spec.ts
This changes default model names to:
- Use "model" not "query" terminology (e.g. `model_1` not `query_1`). It's more consistent for models to be called models.
- Be a suffix not a prefix when autogenerated from a source (e.g. `mysource_model` not `query_mysource` or `model_mysource`). This makes it easier to scan your list of assets.
=> Change default model names

src/cli/ImportTableCommand.ts, src/common/data-modeler-service/TableActions.ts, src/lib/util/file-upload.ts, src/server/controllers/FileActionsController.ts
closes #740
Importing source from UI was waiting for profiling to finish before giving back control to user. Decoupling it from UI and calling a background profile.
=> Decoupling source profiling from import

src/dev.ts
This PR makes it possible to run dev mode on windows, though there is still some breakage in the dev mode server. However this initial PR is an incremental step towards the rest of the debugging that is required , because without the two subsidiary scripts won't even run at all
=> Makes it possible to run the command `npm run dev` On windows

src/common/database-service/DatabaseMetricsExplorerActions.ts
On a large dataset metrics validation takes lot of time, since it was actually executing the query. 
As we do not need the results, changing to prepare. 
Before - 
After - 
Thanks @AdityaHegde for helping figure this out.
=> Use prepare instead of execute for metrics validation

tailwind.config.cjs
We've been getting this console warning everytime we start the dev server:
This PR follows the Tailwind upgrade guide to remove that warning.
=> Remove tailwind console warning

scripts/druid-import.sh
1. Increase default limit to 5M rows
2. escape datasource name to avoid issues when it has '-'
=> Fix druid import script

src/lib/util/file-upload.ts
When a user uploads a file, automatically view the newly created source.
=> Automatically navigate to newly created source

web-local/src/common/errors/ErrorMessages.ts, web-local/src/common/rill-developer-service/MetricsViewActions.ts
When manually inputting an invalid UUID to the `dashboard/` route, the application falls back to the `dashboard/[UUID]/edit` page. This PR ensures a 404 "dashboard not found" message is displayed instead.
=> Handle requests to non-existent metrics definitions

web-local/src/lib/components/virtualized-table/core/ColumnHeader.svelte
I found this a bit distracting in the modeler. This removes flying.
Example of what the flying in the preview table feels like before this PR. Notice the preview table headers
=> removes the fly transition from the virtualized table header

web-local/src/app.css, web-local/src/lib/components/dimension/DimensionTable.svelte, web-local/src/lib/components/dimension/DimensionTableConfig.ts, web-local/src/lib/components/virtualized-table/core/Cell.svelte, web-local/src/lib/components/virtualized-table/core/ColumnHeader.svelte, web-local/src/lib/components/virtualized-table/core/StickyHeader.svelte, web-local/src/lib/components/workspace/explore/leaderboards/DimensionDisplay.svelte
The UI of the dimension table is now closer to the mock -
=> Revamp UI of Dimension table

web-local/src/lib/components/workspace/explore/leaderboards/Leaderboard.svelte
Increase the current limit from 15 to 250. This enables values selected from the dimension table to be have proper values once the use goes back to the leaderboards.
=> Increase leaderboard value limit

web-local/src/lib/application-state-stores/explorer-stores.ts, web-local/src/lib/components/dimension/DimensionFilterGutter.svelte, web-local/src/lib/components/dimension/DimensionHeader.svelte, web-local/src/lib/components/dimension/DimensionTable.svelte, web-local/src/lib/components/dimension/DimensionTableConfig.ts, web-local/src/lib/components/leaderboard/LeaderboardHeader.svelte, web-local/src/lib/components/leaderboard/LeaderboardOptionsMenu.svelte, web-local/src/lib/components/virtualized-table/core/Cell.svelte, web-local/src/lib/components/virtualized-table/core/StickyHeader.svelte, web-local/src/lib/components/virtualized-table/sections/TableCells.svelte, web-local/src/lib/components/workspace/explore/leaderboards/DimensionDisplay.svelte
@bcolloran This PR creates a new component which adds a row header for each dimension value. This works as is for `include`. For exclude you would have to make the relevant state changes to `DimensionFilterGutter` and `DimensionDisplay`. These components are independent of the `PreviewTable` so you won't have to worry about design conflicts there.
=> Add filter gutter for dimension table

docs/docs/README.md, docs/docs/sql-dialect.md, docs/sidebars.js
This PR tidies up the docs in a few ways:
- Sequences the docs according to how a user would travel through the product: CLI -> SQL Dialect -> Define metrics. This sequencing will make it more clear where future docs pages (like for importing data!) should go.
- Removes an extra layer of nesting to get to our SQL Dialect page
- Cleans up a couple code snippets
=> Edit documentation sequence

web-local/src/lib/components/assets/MetricsDefinitionAssets.svelte, web-local/src/lib/components/assets/ModelAssets.svelte, web-local/src/lib/components/assets/TableAssets.svelte, web-local/src/lib/components/inspector/SourceInspector.svelte, web-local/src/lib/components/inspector/model/ModelInspectorModelProfile.svelte, web-local/src/lib/components/modal/ExportError.svelte, web-local/src/lib/components/modal/RenameEntityModal.svelte, web-local/src/lib/components/table-editable/TableRowWithMenu.svelte, web-local/src/lib/components/virtualized-table/core/Cell.svelte, web-local/src/lib/components/workspace/explore/Explore.svelte, web-local/src/lib/components/workspace/explore/filters/Filters.svelte, web-local/src/lib/components/workspace/metrics-def/MetricsDefWorkspaceHeader.svelte, web-local/src/lib/components/workspace/source/SourceWorkspaceHeader.svelte, web-local/src/routes/(application)/dashboard/[id]/+page.svelte, web-local/src/routes/dev/dialog/index.svelte, web-local/src/routes/dev/tooltips.svelte
PSA @hamilton @AdityaHegde @djbarnwal @ericpgreen2  -- this PR removes a bunch of svelte fragments whose only real purpose was to wrap another component in a slot. Just a heads up that this (anti)pattern has appeared a bunch of places in our code, and I think we've all done it (I know I have), but it's only really necessary in some cases -- in many cases, you can attach a slot attribute directly to the component that will occupy that slot and the fragment is not needed. Anyway, keep your eyes open for this -- in many cases it nicely improves readability by removing boilerplate and a layer of nesting! :-)
This should be a quick review, anyone can take it.
=> Remove unneeded slot fragment 2

go.mod, go.sum, package-lock.json, runtime/cmd/main.go, runtime/server/queries.go, web-local/build-tools/postinstall_runtime.sh
- Fixes bug around big number serialization (just coerces to float)
- Sets the default in-memory sqlite registry to use shared memory (otherwise, it doesn't work on many concurrent requests where new threads are spawned)
- Updates runtime version in `web-local` to incorporate the above
=> Upgrade runtime

web-local/src/lib/components/workspace/Model.svelte
The error pane was hidden below the preview table that expanded too much.
I've changed the parent display to flex and made the error pane `flex-shrink: 0`
=> Fix error pane

web-local/src/common/data-modeler-service/DataModelerService.ts, web-local/src/common/data-modeler-service/minMaxStringLength.spec.ts, web-local/src/common/database-service/DatabaseTableActions.ts, web-local/test/functional/minMaxStringLength.spec.ts
closes #1037
Added some tests which check for column name with single, double and mixed quotes.
Made the query to be optional. Any failures in it will not cause the modeling to be blocked.
=> Fixing min max string length query

web-local/src/lib/components/forms/InformationalField.svelte
Currently, in the GCS & S3 connector forms, pressing the `enter` key opens up the documentation pages, rather than submitting the form. This PR fixes that.
=> Ensure `enter` submits form rather than opens docs

web-local/src/lib/components/assets/sources/RemoteSource.svelte
- There was a bug due to AWS & GCP both returning the same "AccessDenied" text. The attempt to parse the GCP variation was silently failing on the AWS variation.
- Added a few more custom error messages
=> Handle a few more error cases in Remote Sources form

web-local/src/common/errors/ErrorMessages.ts, web-local/src/common/rill-developer-service/MetricsViewActions.ts, web-local/src/lib/components/modal/ModalContainer.svelte, web-local/src/lib/components/navigation/dashboards/MetricsDefinitionAssets.svelte, web-local/src/lib/components/workspace/metrics-def/MetricsDefWorkspace.svelte, web-local/src/lib/redux-store/metrics-definition/metrics-definition-apis.ts, web-local/src/routes/(application)/dashboard/[id]/+page.ts, web-local/src/routes/(application)/dashboard/[id]/edit/+page.svelte, web-local/src/routes/(application)/dashboard/[id]/edit/+page.ts
closes #1144 
404 message on Dashboard has been removed completely. In case of a dashboard error, we redirect to the metrics definition page. If the error is non standard, we show the message in a dialog box (standard message errors are shown in the components themselves).
=> Redirect to metric def on dashboard error

docs/docs/import-data.md, runtime/connectors/gcs/gcs.go, runtime/connectors/s3/s3.go
There were two places we said we didn't support gzipped files:
- The "Limitations" section of the "Import Data" docs page
- Tooltips over the "Path" field in the connector forms for S3 & GCS
=> Remove notes about not supporting gzipped files

web-local/src/lib/components/data-graphic/actions/scrub-action-factory.ts
Right now when you zoom on on a timestamp chart, if you release past the edge of the svg the chart will not zoom
To replicate:
1. start datetime zoom
2. drag past edge of the chart
3. will not actually zoom in 
video of bug: 
https://user-images.githubusercontent.com/13400543/201785378-196f9cc9-d9b1-4d63-af50-e74bb9b6ca4b.mov
Moving the end event listener to the window rather than the node seems to fix
https://user-images.githubusercontent.com/13400543/201785527-c370aa8d-e097-4416-b3be-8e08a79a0179.mov
I noticed this using your timestamp component in https://github.com/cmudig/AutoProfiler and patched the fix in my repo so thought I would suggest here as well
=> Fix timestamp zoom when released outside of svg bounds

web-local/src/app.css, web-local/src/lib/components/chip/removable-list-chip/RemovableListMenu.svelte, web-local/src/lib/components/virtualized-table/core/Cell.svelte, web-local/src/lib/components/workspace/explore/leaderboards/DimensionLeaderboardEntry.svelte
@hamilton, here are those adjustments the visual weight of the leaderboards and dimension tables. Subtle changes, but it's a subtle point, and we can push a bit farther on the blue if we want (this is blue-100, but the blue-"75" option is available to try out as well)
- lighten bars
- lighten font weight
- remove refs to undefined styles `leaderboard-list-item-*`
- fix dimension table excluded text -> italic
after:
before:
after:
before:
=> lighten up leaderboards

web-local/src/lib/components/workspace/explore/ExploreHeader.svelte
also adjusts icon size from 1 rem to 16px to match "go to dashboard" button
addresses part of #1183, but the button can still be pushed off the screen when the window is narrow
=> fixes text wrapping within "edit metrics" button

runtime/server/column_api.go, runtime/server/column_api_test.go, runtime/server/server_test.go
Fix error for Date type columns. Difference of two Dates is a BigInt in duckdb 
```
panic caught: interface conversion: interface {} is int64, not duckdb.Interval
```
=> support date columns for time range summary api

runtime/drivers/registry.go, runtime/drivers/registry_test.go, runtime/drivers/sqlite/registry.go, runtime/server/catalog.go, runtime/server/column_api.go, runtime/server/instances.go, runtime/server/queries.go, runtime/server/repos.go, runtime/server/server.go, runtime/server/services.go
- Context cancelled err mapped to `codes.Canceled` which is logged as Info 
- All status error codes are used as it is and logged as per `DefaultServerCodeToLevel` func in `options.go` file
- Removed `panic` from RegistryStore method implementation to handle context cancelled
=> custom error to code handler

.travis.yml
=> Skip cleanup to find binaries

web-local/src/lib/application-state-stores/file-artifacts-store.ts
Empty statement is technically an error in duckdb. But we need not show it in the UI. So filtering it out in the UI before adding to the store.
=> Filter out empty statement error for models

web-local/src/lib/components/workspace/explore/time-series-charts/MetricsTimeSeriesCharts.svelte
The new (likely correct) `MetricsViewTimeSeries` API returns nulls when the frontend was built expecting 0 values. We will fix this later. This PR fixes the dashboard in the meantime.
=> creates workaround for metric view time series charts

web-local/src/lib/components/workspace/model/inspector/header/CreateDashboardButton.svelte, web-local/src/lib/components/workspace/model/inspector/header/ModelInspectorHeader.svelte
This PR fixes the Create Dashboard button on a model's page. Now, it:
- Avoids name conflicts
- Invalidates relevant queries on success
- Adds an overlay
=> Fix create dashboard button

web-local/src/lib/errors/messages.ts, web-local/src/routes/(application)/dashboard/[name]/+page.svelte, web-local/src/routes/(application)/dashboard/[name]/+page.ts, web-local/src/routes/(application)/dashboard/[name]/edit/+page.svelte, web-local/src/routes/(application)/dashboard/[name]/edit/+page.ts
Before this PR: navigating to a dashboard with an invalid config would result in a 500 error.
After this PR: navigating to a dashboard with an invalid config redirects to the dashboard configuration page.
=> Fix dashboard routing

web-local/src/lib/components/workspace/model/ModelBody.svelte
it appears a typo was introduced into a context, causing the drag bar in the model to be broken.
=> fixes dragbar bug

runtime/queries/column_topk.go, runtime/server/queries_columns_test.go, runtime/server/queries_metrics_test.go, runtime/testruntime/testdata/ad_bids_2rows/dashboards/ad_bids_metrics.yaml, runtime/testruntime/testdata/ad_bids_2rows/data/AdBids_2rows.csv, runtime/testruntime/testdata/ad_bids_2rows/models/ad_bids.sql
This only fixes TopK *hugeint* issue. 
Metrics views are affected too - converting [big.Int](http://big.int/) to float64 is a precision lost, it can backfire when you try to aggregate this one
```
D create table a as select 170141183460469231731687303715884105726 as id, 1 as volume 
union all 
select 170141183460469231731687303715884105727 as id, 2 as volume ;
D select max(volume) from a group by id;
┌─────────────┬─────────────────────────────────────────┐
│ max(volume) │                   id                    │
├─────────────┼─────────────────────────────────────────┤
│ 1           │ 170141183460469231731687303715884105726 │
│ 2           │ 170141183460469231731687303715884105727 │
└─────────────┴─────────────────────────────────────────┘
```
there will be a single group …
=> Using HUGEINT type for dimension fails in TopK 

web-local/src/lib/components/navigation/models/createModel.ts, web-local/src/lib/components/navigation/sources/createSource.ts, web-local/src/lib/svelte-query/actions.ts
A few actions post mutations need not wait for query invalidations to finish. This is most apparent when renaming a heavy model.
=> Making query invalidations non blocking

web-local/src/lib/components/data-graphic/marks/HistogramPrimitive.svelte, web-local/src/lib/components/data-graphic/utils.ts
This should fix a variety of bugs relating to modeling. The `HistogramPrimitive.svelte` component was not handling empty arrays, which is very common when you filter out all data in a result set.
=> catches empty histogram cases in the UI

.github/workflows/cli-release.yml, .goreleaser.yaml, scripts/install.sh
* Use prod CDN
* Version controlled
* Update install script on release
=> Rill Install script

web-local/src/lib/components/workspace/source/SourceWorkspace.svelte
It looks like we have a bit of breakage on `main`. If I have a source with an invalid `type`, the application freezes up.
This check will see if the type is valid, and if not, provide the same kind of messaging we have in the sources flow today.
=> fixes the invalid type source error issue

web-local/src/lib/components/column-profile/column-types/NumericProfile.svelte, web-local/src/lib/components/column-profile/column-types/details/NumericPlot.svelte, web-local/src/lib/components/column-profile/column-types/details/SummaryNumberPlot.svelte, web-local/src/lib/util/formatters.spec.ts, web-local/src/lib/util/formatters.ts
Dominik Moritz suggested that the formatting on the summary plots is way too precise, so we'll go with this approach:
- *look at the number of significant digits,*
- *keep everything before the '.' (the integer portion),*
- *and then at most ~5 digits.*
So you'd get formatted numbers like `12345`, `1234.5`, `123.45`, `12.345`.
=> for integer, reduce to integer; for floating points, utilize `justEnoughPrecision`

runtime/services/catalog/migrations.go, runtime/services/catalog/migrations_test.go, runtime/services/catalog/migrator/migrator.go, runtime/services/catalog/testutils/testutils.go, web-local/src/lib/components/navigation/sources/createSource.ts
closes #1447
Adding a feature where if the local file changes in `data` folder we re-ingest the source. This does not apply to remote sources since we want the user to explicitly refresh it.
=> Refresh when local file changes

web-local/src/lib/components/virtualized-table/sections/TableCells.svelte
closes #1151
@magorlick I tried a few times and this PR seem to have fixed tooltip in preview table not showing after scrolling. Lemme know if you find any edge cases.
@ericpgreen2 Please take a look at the code
=> Fixing tooltips in preview table not showing after scrolling

web-local/src/lib/application-state-stores/explorer-stores.ts, web-local/src/lib/components/workspace/explore/filters/Filters.svelte, web-local/src/lib/components/workspace/explore/leaderboards/DimensionDisplay.svelte
=> [Dashboard] Fix jarring rearrange when include/exclude is toggled from filter pills

web-local/src/lib/components/column-profile/column-types/details/SummaryNumberPlot.svelte
another quick bit of polish @magorlick  and @hamilton 
- puts quantile labels in order (min moved to bottom) for better scanability
- reduces size of red dots next to labels and desaturates them so that they perceptually match the color of the vertical lines going up to the chart.
this branch:
main:
=> fixes Distribution chart tune ups #1498

web-common/src/lib/formatters.ts, web-local/src/lib/components/viz/ExploreChart.svelte
Quick PR to see how the iso date approach to #1480 works. @magorlick and @hamilton, please take a look.
this branch:
main:
=> fixes Format dates with Inter monospace #1480

web-common/src/components/chip/removable-list-chip/RemovableListMenu.svelte
fixes #1261 by darkening the icons in the filter pill
Note: this is a bit of a hack -- it hard codes the color because `currentColor` was not actually being set correctly by the upstream styles. There are a lot of layers of cascading in play here, so I thought this was an expedient solution to get us the look we want until we overhaul our approach to styling
this branch:
main (note lighter gray icons in filter pill menus_:
=> increases visual weight of filter icons in filter pill menu

.github/workflows/cli-release.yml, scripts/install.sh
```
Failing due to
google-github-actions/upload-cloud-storage failed with: EACCES: permission denied, scandir '/home/runner/work/rill-developer/rill-developer/dist/goreleaserdocker1062396503'
```
=> Upload nightly builds to GCS

runtime/queries/metricsview_timeseries.go, runtime/queries/metricsview_toplist.go, runtime/queries/metricsview_totals.go
>  Audit/adapt the analytical APIs to support metrics views without a time dimension (just return an error if a metrics timeseries API is queried)
=> Metrics view support  dashboards with no timestamp

web-common/src/features/onboarding/OnboardingWorkspace.svelte, web-common/src/features/onboarding/index.ts, web-local/src/lib/components/workspace/index.ts, web-local/src/routes/(application)/+page.svelte
This PR continues the refactor from #1505. 
The PR creates a `web-common/features/onboarding` directory, which exports the `OnboardingWorkspace` component. This component is imported into the `web-local/routes/(application)/+page.svelte` file.
Assuming our onboarding surface will evolve over time, it will help to have all of its components colocated in this one directory.
=> Move onboarding into `web-common/features/onboarding` directory

web-local/src/lib/components/workspace/explore/time-controls/time-range-utils.spec.ts, web-local/src/lib/components/workspace/explore/time-controls/time-range-utils.ts, web-local/src/lib/components/workspace/explore/time-series-charts/MetricsTimeSeriesCharts.svelte, web-local/src/lib/temp/time-control-types.ts
This was triggered by https://github.com/rilldata/rill-developer/pull/1553, which shows that we were not handling time ranges correctly. Fixing it on the API-side didn't feel right as it opens some edge cases (I found [this blog post](https://metala.org/posts/api-design-exclusive-vs-inclusive-ranges/) that illustrates one of the problems).
This PR changes how time ranges are calculated and used in the frontend. The rules are:
- Backend
- The time series metrics APIs accept `[start;end)` ranges. The result is grouped using `DATE_TRUNC` (so the groups are floor timestamps).
- The `GetTimeRangeSummary` API returns the min and max timestamp values in the column (so both inclusive).
- Frontend
- The selected time range passed to the API is computed as:
- For all time: `start = floor(mintime, …
=> Improve handling of time ranges

cli/cmd/initialize/init.go
Make `rill init --example <example>` fail instead of quietly using the "default" example project when used instead of `--example=example`.
The latter form is required due to a bug in cobra.  See https://github.com/rilldata/rill-developer/pull/1398#issuecomment-1370228827
=> Make `rill init` When Passed Arguments (Probably By Accident)

web-local/src/lib/components/column-profile/column-types/details/SummaryNumberPlot.svelte
This was causing quite the bug in integer histograms.
=> more from `r` to `f` for integer formatting in summary numbers

web-local/src/lib/components/workspace/core/WorkspaceHeader.svelte
This was brought up in feedback for #1532 . We haven't touched this tooltip in a while, so this cleans it up.
=> changes the edit tooltip

web-common/src/features/models/utils/model-is-empty/index.ts, web-common/src/features/models/workspace/ModelBody.svelte, web-common/src/features/models/workspace/inspector/ModelInspector.svelte, web-local/src/lib/components/column-profile/ColumnProfileIcon.svelte, web-local/src/lib/components/column-profile/column-types/sparks/NumericSpark.svelte, web-local/src/lib/components/column-profile/column-types/sparks/TimestampSpark.svelte
This has been bothering me for a while, so I decided to fix this.
We should not be surfacing the preview table / inspector information if a model query is blank. It's better to hide any information from the user. This is distinct from the case where the query has an error; here, we actually preserve the representations in those surfaces.
=> When a model query is blank, hide the table & inspector

docs/docs/references/project-files.md
=> Add S3/GCS region to docs

web-common/src/features/onboarding/OnboardingWorkspace.svelte, web-common/src/runtime-client/manual-clients.ts, web-local/src/lib/application-state-stores/application-store.ts, web-local/src/lib/components/layouts/RillDeveloperApplicationLayout.svelte, web-local/src/lib/components/navigation/Navigation.svelte, web-local/src/lib/components/navigation/NavigationHeader.svelte, web-local/src/lib/components/navigation/dashboards/MetricsDefinitionAssets.svelte, web-local/src/lib/components/workspace/explore/ExploreHeader.svelte, web-local/src/routes/(application)/dashboard/[name]/+page.ts, web-local/src/routes/(application)/dashboard/[name]/edit/+page.ts, web-local/src/routes/(application)/model/[name]/+page.ts, web-local/src/routes/(application)/source/[name]/+page.ts
This PR provides that when `rill start --readonly`:
- Sources and Models are hidden from the navigation sidebar. Any direct navigation to these pages results in a 404.
- There is no "Add Dashboard" button in the navigation sidebar.
- The `Edit Metrics` button is hidden from the Dashboard workspace.
- The onboarding workspace does not mention Sources, Models, or Metric Definitions
=> Create `readonly` UI

web-common/src/components/data-types/Interval.svelte, web-local/src/lib/components/column-profile/column-types/NumericProfile.svelte, web-local/src/lib/components/column-profile/column-types/index.ts
closes #1648 
This PR is a stopgap that brings back intervals into profiling but does not profile them meaningfully (yet). @magorlick took a look at the UX and we feel this is acceptable for now; we need to show _something_.
=> adds a stopgap for INTERVAL types

web-common/src/features/entity-management/sync-file-system.ts
Disables two scenarios under which we sync the Rill UI with code artifacts: on page navigation & on browser focus.
=> Disable sync-on-navigate & sync-on-focus

web-local/src/lib/components/preview-table/ConnectedPreviewTable.svelte
Looking at a performance assessment of a model workspace render, it seems that rendering even the virtualized table was causing an additional ~240ms to the script + paint. This likely happens because we're also rendering the row & column overscans, which is an additional 40 rows & 10 columns. An extra 400 cells is quite a bit; so this PR reduces the overscan on mount and then applies it a second later, which seems to improve the initial mount time & brings down the render to ~7ms.
=> preview table: punt on overscan for 1 second

web-common/src/features/entity-management/actions.ts, web-common/src/layout/navigation/NavigationEntry.svelte, web-common/src/layout/navigation/stores.ts, web-local/src/lib/components/column-profile/ContextButton.svelte, web-local/src/lib/components/column-profile/ExpanderButton.svelte
closes #1670
The point of this PR is to reduce perceived click latency in the navigation menu.
This PR does the following:
- inverts the `a` tag to be the container element of the `NavigationEntry`, increasing the click area and thus preventing a bad experience on the edges of the nav entry
- adds a `preventDefault` to the inner buttons to prevent navigation when clicking on the expander / context button
- highlights soon-to-be active navigation entry on mousedown
- adds a global `currentHref` store that also applies styling to all nav entries, making it appear that the newly-mousdown entry is the only one selected
- all navigation events will reactively update the `currentHref` store if it doesn't match the current path. For the navigation items, only look at the first two segments of …
=> navigation always registers click (or appears to register it)

web-common/src/lib/duckdb-data-types.ts, web-common/src/lib/formatters.ts
This will treat any `JSON` columns the same as structs or lists, using the same styling / decision criteria as structs.
=> adds `JSON` type to nested types

web-admin/README.md, web-admin/src/client/http-client.ts, web-admin/src/lib/connection.ts
This PR sets the admin server URL to be `http://localhost:8080` in development and `https://admin.rilldata.com` in production.
=> Make admin server host configurable

go.mod, go.sum, runtime/pkg/pbutil/pbutil.go, runtime/pkg/pbutil/pbutil_test.go, runtime/queries/column_timeseries.go, runtime/queries/column_topk.go, runtime/queries/metricsview.go, runtime/queries/table_head.go, runtime/server/pbutil/pbutil.go, runtime/server/queries.go, runtime/server/queries_tables.go, runtime/server/queries_tables_test.go, runtime/server/queries_timeseries_test.go
Closes #1785.
One problem here was that JSON object keys must be strings, but DuckDB maps can have any key type. To address that, I made it serialize the DuckDB map key to a JSON string. However, it won't support complex key types, like using other maps or arrays as map keys ([details here](https://github.com/marcboeker/go-duckdb/pull/74)).
Also refactored a few things:
- Added `TableHead` query type to cache table rows result
- Moved `pbutil` to `runtime/pkg`
- Removed `valToPB` due to duplication
=> Add proto serialization of DuckDB maps

web-common/src/features/metrics-views/metrics-internal-store.ts, web-common/src/features/metrics-views/workspace/MetricsModelSelector.svelte
Addresses the [P0 in Notion "I can’t change a model in the metrics config to a new model"](https://www.notion.so/rilldata/Application-Bugs-and-Polish-for-21-1-6d7f59f3076249f7af64dfbc8acc47df)
The problem in the existing code is that we call `$metricsInternalRep.updateMetricKey(...)` twice in quick succession, which leads to two concurrent calls to `PutAndMigrate`. A race condition results in a malformed dashboard YAML file.
This PR changes the call to `$metricsInternalRep.updateMetricKeys(...)`, which ensures `PutAndMigrate` is only called once.
=> Fix race condition when configuring a dashboard's model

runtime/queries/table_head.go
Fix query cache key for TableHead API to include limit as well.
=> Fix Query cache key for TableHead API

web-common/src/components/modal/dialog/Dialog.svelte
The other dialogs seemed to be too tall, so we need to revert to variable heights unless we use `yFixed`
=> ensures dialog height for other dialogs is same as before, unless using `yFixed`

web-local/src/lib/metrics/service/RillIntakeClient.ts
Rill Intake response is not JSON. Hence not using `fetchWrapper` that assumes a JSON response.
=> Fixing rill intake url not being json

web-common/src/components/virtualized-table/core/Cell.svelte, web-common/src/features/dashboards/leaderboard/DimensionLeaderboardEntry.svelte, web-common/src/features/dashboards/leaderboard/DimensionLeaderboardEntrySet.svelte, web-common/src/layout/config.ts
The leaderboard tooltips were quite bad before. This makes them much more usable.
=> fixes tooltip issue in leaderboards; refines design of leaderboard tooltips

cli/cmd/runtime/start.go, runtime/runtime.go
We might refactor this code again soon, but just wanted to get it in so we don't forget
=> Close runtime metastore on exit

tsconfig.json, web-admin/tsconfig.json, web-admin/vite.config.ts
This PR:
- Adds `web-admin` to our root `tsconfig.json`
- Edits `web-admin/tsconfig.json` to inherit from root
- Wires up aliases for Vite
Part of #1780.
=> Edit Typescript and Vite config in `web-admin`

runtime/queries/column_numeric_histogram.go, runtime/server/queries_columns_test.go
closes #1821
This PR blocks the rest of the diagnostic test integration. I'll need to make a couple other frontend changes before then.
=> fixes case where low-cardinality diagnostic histograms add an extra bucket

web-admin/src/routes/+layout.svelte
This PR adds the Rill theme to the `web-admin` project.
Without this PR, the `web-admin` project currently does not build because `+layout.svelte` references the `app.css` file removed in #1813. (To avoid this state going forward, for code that touches `web-admin`, we should add a CI/CD check to verify that `npm run build -w web-admin` works.)
=> Add Rill theme

runtime/queries/column_time_grain.go, runtime/queries/timeseries_interval.go, runtime/server/queries_columns.go
Hey, sometimes I’m seeing this error message in the logs:
```
2023/03/03 16:36:16 ERROR: [core] [Server #5] grpc: server failed to encode response: rpc error: code = Internal desc = grpc: error while marshaling: proto: Marshal called with nil
```
I think this is when an RPC returns both a `nil` error and a `nil` response.
I noticed it could happen in `RollupInterval` query and the logs appeared correlated.
=> Fix empty response error for column rollup interval

admin/server/server.go, web-admin/src/client/http-client.ts
This PR configures:
- the server to set the "Access-Control-Allow-Credentials" header to "true" on HTTP responses
- the client to set the "withCredentials" property on HTTP requests
Both are required to get our authentication flow working.
=> Allow credentials in requests to admin server

web-common/src/features/dashboards/time-series/MeasureChart.svelte, web-common/src/features/dashboards/time-series/MetricsTimeSeriesCharts.svelte
The goal of this PR is to make it easier to see the date against any chart, rather than have to direct your eyes to the top of the screen to see the tiny date.
@magorlick lmk what you think of this approach.
https://user-images.githubusercontent.com/95735/223933399-5a84b20f-3154-49fe-ad25-29cafa28448c.mp4
=> moves mouseover date into chart

web-admin/src/routes/+page.ts, web-admin/src/routes/[organization]/+page.svelte, web-admin/src/routes/[organization]/[project]/+page.svelte
The admin API/client changed terminology from `FindOrganization` to `GetOrganization`, and `FindOrganizations` to `ListOrganizations`, and the same for Projects. This updates the frontend code to use the new client.
=> Switch to new admin API endpoints

web-admin/src/components/navigation/Breadcrumbs.svelte
This adds the `/-/` prefix to the parameterized routes in the breadcrumb links.
=> Fix breadcrumb links

cli/cmd/auth/login.go, cli/cmd/org/create.go, cli/cmd/org/delete.go, cli/cmd/org/edit.go, cli/cmd/org/list.go, cli/cmd/org/show.go, cli/cmd/org/switch.go, cli/cmd/project/connect.go, cli/cmd/project/delete.go, cli/cmd/project/edit.go, cli/cmd/project/list.go, cli/cmd/project/show.go, cli/cmd/project/status.go
They mess up the terminal state when other messages are printed while a spinner is running. We can add them back when other printed messages have stabilized.
=> Remove CLI spinners

web-admin/src/routes/+layout.ts, web-admin/src/routes/+page.ts, web-admin/src/routes/-/[organization]/[project]/dashboard/[name]/+page.ts
Given #1912 makes the `web-admin` app a single-page application in production, we should set the SvelteKit SSR configuration to ensure the same behavior in development. This PR sets `ssr = false` by default for the whole `web-admin` app, which will ensure our app behaves as a SPA in development.
=> Set SPA in development

web-common/src/components/data-graphic/elements/GraphicContext.svelte, web-common/src/components/data-graphic/guides/PointLabel.svelte, web-common/src/features/dashboards/time-series/MeasureChart.svelte, web-common/src/features/dashboards/time-series/MetricsTimeSeriesCharts.svelte, web-common/src/features/dashboards/time-series/utils.spec.ts, web-common/src/features/dashboards/time-series/utils.ts
This is accomplished by creating a special function that aids in setting "nice" bounds for a measure chart y extents. Also fixes a bug in GraphicContext.svelte that prevents extent values from updating if they were previously 0.
https://user-images.githubusercontent.com/95735/225213395-e607ecc7-fcf4-4043-810d-b0a15eca34c4.mp4
=> fixes negative values in measure charts

web-common/src/features/dashboards/time-controls/TimeControls.svelte, web-common/src/features/dashboards/time-series/MeasureChart.svelte
we're attempting to re-create state from an empty `dashboardState` when a user first navigates to a dashboard. This PR fixes this for now so we can push a patch release.
Not super comfortable with merging this; in the future, it'd be great for us to have more tests around this `dashboardState` store + the protobuf state methods. e2e tests would have also caught this, most likely.
=> fixes broken navigation state

web-common/src/app.css, web-common/src/features/dashboards/workspace/DashboardHeader.svelte, web-common/src/layout/RillTheme.svelte, web-common/static/fonts/fonts.css, web-local/src/app.html
This fixes the flash of unstyled text that people were seeing. In detail:
- preloads the font definition css and the four most used fonts
- moves `fonts.css` to static folder 
- sets `font-display` to `block` rather than `swap` for these key fonts, so text that is supposed to use these fonts will not be shown at all until the font is ready 
- also removed Inter Display, which was only used in the dashboard header. (I can't tell the difference at all)
In my local testing with simulated network throttling on Chrome and FF, I see no unstyled text. @hamilton  and @magorlick  please do an experience pass to confirm that you're seeing the behavior you want.
I'll also mention that in the course of doing research on this topic, I found that this method in this PR (preloading and blocking) is …
=> Fix flash of unstyled font

web-common/src/features/dashboards/dimension-table/DimensionDisplay.svelte, web-common/src/features/dashboards/dimension-table/dimension-table-utils.ts, web-common/src/features/dashboards/leaderboard/DimensionLeaderboardEntrySet.svelte, web-common/src/features/dashboards/leaderboard/Leaderboard.svelte
This PR 
- refactors the `topList` call for comparisons to only include visible values
- Map comparison value to the right label
- Other syntax fixes
=> Fix leaderboard comparisons

web-common/src/components/data-graphic/marks/MultiMetricMouseoverLabel.svelte, web-common/src/features/dashboards/time-series/MeasureChart.svelte, web-common/src/features/dashboards/time-series/MeasureValueMouseover.svelte, web-common/src/features/dashboards/time-series/round-to-nearest-time-unit.ts
Comparison chart fixes  - 
- Put value label on top of timestamp label
- Align label when there's no value
- Fix bug to allow switching between non comparison and comparison charts
- Use `preventVerticalOverlap`
=> Comparison chart fixes

web-common/src/features/dashboards/leaderboard/LeaderboardListItem.svelte
closes #2010
Leaderboards act pretty weird when certain measures (the ones where percent of a dimension value can go above 100% of big number) is selected for leader values. When we click on the dimension to go to the dimension table the if..else in svelte displays both blocks!
This seems to be a know issue with transitions,
https://github.com/sveltejs/svelte/issues/3410
https://github.com/sveltejs/kit/issues/7405
I have fixed the transition based on the above svektekit issue. There was also another issue with the serration not showing up because of broken positioning.
=> Fixing leaderboard dimension table for certain measures

web-admin/src/app.html
PR https://github.com/rilldata/rill-developer/pull/1969 changed the way we load fonts. The PR made the requisite changes for  `web-local`, but not for `web-admin`. This PR mirrors the changes for `web-admin`.
=> Add back Inter to `web-admin`

web-admin/src/routes/+layout.svelte, web-admin/src/routes/-/[organization]/[project]/dashboard/[name]/+page.svelte, web-common/src/features/dashboards/workspace/Dashboard.svelte, web-common/src/features/dashboards/workspace/DashboardContainer.svelte, web-common/src/features/dashboards/workspace/DashboardHeader.svelte, web-local/src/routes/(application)/dashboard/[name]/+page.svelte
In `web-admin`, this PR:
- Removes the title from the dashboard header
- Removes the excess spacing between dashboard header and dashboard charts & leaderboards
- Makes minor padding adjustments, but we'll revisit the alignment soon
=> Improve layout of cloud dashboards

web-common/src/features/sources/add-source/file-upload.ts, web-common/src/features/sources/add-source/possible-file-extensions.spec.ts, web-common/src/features/sources/add-source/possible-file-extensions.ts, web-local/src/lib/types.ts
closes #1978
Adding an abstraction around allowed file extensions to support zipped variations. Currently only .gz is supported.
=> Updating file upload extension filter logic to allow zipped varations

web-admin/src/routes/+layout.svelte, web-admin/src/routes/-/[organization]/[project]/+page.svelte
This PR adds a basic listing of a project's dashboards to the current `/-/{org}/{project}` page.
Adding this as a functional placeholder while we wait for design mocks.
=> Add dashboard listing to `web-admin`

admin/database/postgres/postgres.go, admin/github.go
closes #1987
In the project search by github url the check was totally case insensitive. Added `lower` to both the column and search url.
Also removing temporary logs used in debugging.
=> Fix github url search not being case insensitive

web-common/src/features/dashboards/big-number/MeasureBigNumber.svelte, web-common/src/features/dashboards/dimension-table/dimension-table-utils.ts, web-common/src/features/dashboards/leaderboard/Leaderboard.svelte, web-common/src/features/dashboards/leaderboard/LeaderboardDisplay.svelte, web-common/src/features/dashboards/time-series/MetricsTimeSeriesCharts.svelte
- Align `no available values` in leaderboard
- Add `no data` label to BigNum
- Fix `NaN% change` in tooltip
- Remove various warnings from console
=> No data comparison fixes

web-admin/src/routes/[organization]/[project]/[dashboard]/+page.svelte, web-local/src/routes/(application)/dashboard/[name]/+page.svelte
When we switched to using `useDashboardStore` we didnt change the usage to have a `$` to get the data in the store. Updating the dashboard url code to include the `$`
=> Fixing dashboard url not changing on cloud

runtime/drivers/duckdb/connectors.go
A quick fix to handle CSV ingestion failures due to schema detection. 
By default duckDB limits schema detection to 20480 rows. This fails very often for single files. 
This patch changes the behavior to look at full file instead of sample. 
Note: This does have performance impact on ingesting large files, e.g. A CSV file with ~35M rows (700Mb) took 15 secs instead of 13 secs to load. 
Given that we do not have a way to manually override the schema at present, the performance hit is a reasonable tradeoff for now than failing the ingestion completely.
=> A quick fix to handle CSV ingestion failures due to schema detection. 

web-common/src/lib/time/grains/index.ts
Increasing the min number of points from 2 to 3 so that we can avoid low density charts.
=> Do not show grains causing sparse charts

.github/workflows/cloud-admin.yml
=> Release cloud-admin to netlify when tag

web-local/test/ui/dashboards.spec.ts, web-local/test/ui/models.spec.ts, web-local/test/ui/sources.spec.ts
While we debug the issues with instabilities with e2e we should disable it to not block PRs.
=> Disabling e2e until we figure out the issues

web-admin/src/components/navigation/BreadcrumbItem.svelte, web-admin/src/components/navigation/Breadcrumbs.svelte, web-common/src/components/floating-element/WithTogglableFloatingElement.svelte
This PR brings the top navbar closer to the Figma mock. The PR:
- Uses a different component for the dropdown menu (one with a check mark to denote the current selection)
- Adds a hover animation
=> Edit breadcrumb menus

runtime/drivers/duckdb/olap.go
+ DuckDB query metrics logged at Debug level
+ Logged if `--verbose` is passed
+  Metrics events are generated as jsons if `--log-format=json` is passed
=> Logged the DuckDB query metrics

web-common/src/features/dashboards/workspace/DashboardHeader.svelte
A recent change for cloud tightened up the spacing and fixed the alignment of the dashboard. This created a large space gap in the Rill Developer dashboard. This PR adds a fix for this, plus a note for us to unify the header components in both Rill Developer and Cloud.
=> fix the Rill Developer dashboard header spacing disparity

web-common/src/features/dashboards/humanize-numbers.ts
If the numeric leaderboard value is null our formatter breaks. Handling null along with undefined.
=> Handle null and undefined numeric values

web-admin/src/components/authentication/AuthRedirect.svelte, web-admin/src/components/navigation/TopNavigationBar.svelte, web-admin/src/routes/+layout.svelte, web-admin/src/routes/+page.svelte
This PR moves the auth redirect to the top-level of the layout component so that no content is flashed before we redirect the user to the log-in page.
Contributes toward #2109.
=> Fix content flash when not logged in

web-admin/src/components/home/DashboardList.svelte, web-admin/src/components/home/ProjectList.svelte
This PR adds text to account for the following cases:
- When an organization has 0 projects
- When a project has 0 dashboards
Contributes towards #2109
=> Account for empty lists on homepage

web-admin/src/routes/+layout.svelte, web-admin/src/routes/+page.svelte, web-admin/src/routes/[organization]/+layout.svelte
#2112 introduced a bug where the auth redirect prevents the user from getting to the auth confirmation pages. This PR moves the auth redirect from the top-level into specific pages.
However with this current approach, the top navbar, which is a component placed at the root layout, flashes before the redirect occurs. Should we move the navbar into specific pages too to avoid the flash?
=> Move auth redirect into specific pages

runtime/services/catalog/artifacts/artifacts_test.go, runtime/services/catalog/artifacts/yaml/objects.go
closes #2084
If there is no name specified, default to measure_<index> as before.
=> Support adding measure name in dashboard.yaml

cli/cmd/root.go, cli/pkg/dotrill/dotrill.go
This is an undocumented feature to set the admin server URL in the global config file instead of passing `--api-url` on every call.
=> Support setting `api_url` in `~/.rill/config.yaml`

web-local/src/lib/svelte-query/invalidation.ts
Invalidations were not working since the tanstack query v4 update. Updating the API call to match the new API
=> Updating invalidations to match tanstack query v4

admin/github.go, cli/pkg/dotrill/dotrill.go, go.mod, go.sum, runtime/compilers/rillv1beta/project.go, runtime/drivers/github/github.go, runtime/registry.go, runtime/services/catalog/artifacts/yaml/yaml.go
- closes #2167 (This error was also available in [vulnerability alerts](https://github.com/rilldata/rill-developer/security/dependabot). We should try to address all the alerts mentioned there).
- upgrades yaml pkg to v2.
=> upgrade pkg with vulnerability alerts

web-admin/src/components/CTAButton.svelte, web-admin/src/routes/-/auth/device/+page.svelte, web-common/src/components/icons/RillLogoSquareNegative.svelte
This PR styles the auth code confirmation page.
It also creates a new call-to-action button component, which we should re-use for the other CTAs in `web-admin`.
Contributes to #2109
=> Style the auth code confirmation page

web-admin/src/routes/[organization]/[project]/+layout.svelte, web-admin/src/routes/[organization]/[project]/+page.svelte, web-common/src/runtime-client/RuntimeProvider.svelte
This PR seeks to avoid 401 errors when changing projects via the breadcrumb dropdown. The problem seems to be a race condition when setting a runtime's instance ID and its associated JWT.
The PR makes a few changes to protect against race conditions. The change that ultimately seemed to fix the problem was the change in `web-admin/src/routes/[organization]/[project]/+page.svelte`.
=> Fix race condition in passing JWT to runtime

web-common/src/features/dashboards/dimension-table/DimensionHeader.svelte
The transition on the spinner present in Dimension header is preventing `{#if}{:else}{/if} ` from being exclusive. This is a known sveltekit bug which has been noted here as well - https://github.com/rilldata/rill-developer/pull/2015
Adding a `local` modifier doesn't seem to fix it either. Have removed the transition for now.
=> Remove transition from dimension header

web-common/src/components/data-graphic/marks/MultiMetricMouseoverLabel.svelte
This fixes a console error that is showing up all the time and driving me crazy while debugging other code. There is a subtle bug here where the `container` item may exist when the the `setTimeout` is set, but it may not exist by the time the callback is triggered. This adds a guard _within_ the callback to make sure that the `container` elt exists at the time the callback is fired (just added the `if (container)`, the rest is indentation change)
=> fixes console error

web-common/src/features/dashboards/leaderboard/Leaderboard.svelte, web-common/src/features/dashboards/workspace/Dashboard.svelte, web-common/src/features/metrics-views/workspace/MetricsWorkspace.svelte, web-local/src/routes/(application)/dashboard/[name]/edit/+page.svelte
Any changes done to dashboard.yaml when the editor is open will overwrite it if further changes are made. This is because we do not have a periodic fetch the yaml file.
Adding `refetchOnWindowFocus` to make it refetch when user came back to the app. Periodic refetch might add some other inconstancies when the user is editing the dashboard on the app.
=> Handle dashboard yaml changes outside of our app

web-admin/src/components/home/DashboardList.svelte, web-admin/src/components/navigation/Breadcrumbs.svelte
Fixes an issue where a dashboard's display name went blank. It happened in:
- The homepage list of dashboards
- The breadcrumb dashboard label
- The breadcrumb dashboard options
=> Fix places where dashboard name went blank

runtime/services/catalog/artifacts/artifacts_test.go, runtime/services/catalog/artifacts/yaml/objects.go
For adding backwards compatibility with `display_name` in dashboard we used incorrect `name` key. Updating it to use the correct `display_name` key.
=> Using the correct key for display_name

web-admin/src/components/projects/ProjectDeploymentLogs.svelte
This PR:
- Changes the log colors to match the new Figma mock
- Tweaks the spacing between a long error message and its associated file name
- Adds line breaks so screen-wide strings will break to the next line
=> Adjust contrast in project logs

admin/database/database.go, admin/database/postgres/postgres.go, admin/server/auth/device_code.go
User codes can only be assumed to be unique within their TTL
=> Device auth: guard against user code clashes

.prettierignore, web-admin/src/routes/[organization]/[project]/[dashboard]/+page.svelte, web-common/src/features/dashboards/dashboard-stores.ts, web-common/src/features/dashboards/proto-state/StateSyncManager.ts, web-common/src/features/dashboards/workspace/Dashboard.svelte, web-local/src/routes/(application)/dashboard/[name]/+page.svelte
In cloud since we make a network call for project status, there is a delay in getting the dashboard name. This will lead to some race condition between creating a store entry from meta api vs parsing from url.
Moving the parsing of url to Dashboard component to make sure that data is available when dashboard is navigated to.
=> Moving the url parsing to dashboard component

web-admin/src/components/home/OrganizationList.svelte, web-admin/src/routes/+layout.svelte, web-admin/src/routes/+page.svelte
Using justify-center can break scrolling and make some parts inaccessible while using flex. instead using margin auto to achieve similar behaviour.
Ref: https://bhch.github.io/posts/2021/04/centring-flex-items-and-allowing-overflow-scroll/
=> Fixing home page list getting cut off

cli/cmd/env/configure.go, docs/docs/connectors/_category_.yml, docs/docs/connectors/gcs.md, docs/docs/connectors/s3.md, runtime/connectors/connectors.go, runtime/connectors/gcs/gcs.go, runtime/connectors/s3/s3.go
Initially putting the connector service account docs on `docs.rilldata.com/connectors/NAME` until we've decided how we'll structure the docs for local vs. cloud use cases.
=> Add docs for S3 and GCS service accounts

web-common/src/features/dashboards/dashboard-stores.ts, web-common/src/features/dashboards/proto-state/StateSyncManager.ts, web-common/src/features/dashboards/time-controls/TimeControls.svelte
If starting from a blank filters in a dashboard the default state will not populate the url state.
But if starting from a url then we cannot get the default state right now. We need to do a refactor of time controls to get the default state in one place and address this in a later PR.
Further changes handled in #2285
=> Adding empty url for default dashboard

web-admin/src/components/home/DashboardList.svelte, web-admin/src/components/home/DeploymentStatusChip.svelte, web-admin/src/components/navigation/BreadcrumbItem.svelte, web-admin/src/components/navigation/Breadcrumbs.svelte, web-admin/src/components/projects/dashboards.ts, web-admin/src/components/projects/invalidations.ts, web-admin/src/routes/[organization]/[project]/[dashboard]/+page.svelte
This PR:
- Includes invalid dashboards in listings (home page, project page, breadcrumbs)
- Allows for navigation to valid dashboards in errored projects
To compose the list of valid & invalid dashboards, we have to synthesize the results from two different runtime queries. Currently, the Tanstack Query code is verbose. We should figure out how to make custom hooks from custom hooks, and that'll clean it up.
Aesthetics can probably be improved, but that can be a follow-on item.
=> Account for invalid vs. valid dashboards

cli/cmd/root.go
`status.FromError(err)` doesn't work for wrapped errors. We are wrapping rpc errors in lot of places.
=> common error handling fix

web-common/src/features/dashboards/dimension-table/DimensionDisplay.svelte, web-common/src/features/dashboards/leaderboard/Leaderboard.svelte, web-common/src/features/dashboards/selectors.ts, web-common/src/features/dashboards/time-controls/TimeControls.svelte, web-common/src/features/dashboards/time-series/MetricsTimeSeriesCharts.svelte
This PR fixes the 400 error that's triggered when a dashboard calls the Query Service's `time-range-summary` endpoint when a time series is *not* present.
Because fetching and constructing a model's "all time range" is a common operation, we've created a custom selector hook `useModelAllTimeRange` to contain the transformation logic. To this custom selector hook, I've added the ability to pass TanStack query options (such as the `enabled` flag for dependent queries). I've mirrored the pattern that Orval uses in its generated hooks.
=> Fix 400 error in dashboards without a time series

web-common/src/features/dashboards/workspace/DashboardHeader.svelte, web-common/src/features/dashboards/workspace/DeployDashboardOverlay.svelte
This PR gets the deploy button in Rill Developer closer to the Figma mocks.
It doesn't match the mocks exactly because it's using our current `Dialog` component out-of-the-box. Redesigning our `Dialog` component can be a project for a different day.
=> Improve "Deploy" button dialog

web-common/src/runtime-client/RuntimeProvider.svelte
We had a reactive statement dependant on `$runtime`. Since it changes every time jwt changes this lead to constant refresh of the dashboard.
=> Fixing valid dashboard refresh

web-admin/src/app.html
The extra bold fontface was not added to the pre-load list. As a result, the error code text (which was using extra bold styling) had a delay in it's styling.
That being said, preloading it on all the pages also has it issues. It can slow down the load time of all the pages in the application
The other option is to use `font-display:block` ([more here](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display)), but this hides the error code until the font is fetched while showing other text on the page which is an odd experience.
I am more inclined to keep this as is. Not sure if slight delay in styling is worth loading 100kb on every page.
=> Fix error code styling issue

proto/gen/rill/runtime/v1/queries.pb.go, proto/gen/rill/runtime/v1/queries.pb.validate.go, proto/gen/rill/runtime/v1/runtime.swagger.yaml, proto/rill/runtime/v1/queries.proto, runtime/queries/metricsview.go, runtime/queries/metricsview_timeseries.go, runtime/queries/metricsview_toplist.go, runtime/queries/metricsview_totals.go, runtime/server/queries_metrics.go, runtime/server/queries_metrics_test.go, web-common/src/proto/gen/rill/runtime/v1/queries_pb.ts, web-common/src/runtime-client/gen/index.schemas.ts
Adds a new `inlineMeasures` parameter to the metrics APIs. The initial use case is to allow calculating percentage-of-total for toplists.
Notes:
- In addition to setting `inlineMeasures`, the client must also pass the inline measure name in the `measureNames` array. This is not done automatically to enable the client to control the ordering of result columns.
- If the name of an inline measure overlaps with an existing measure, the inline measure takes precedence. To prevent collisions, use a random/internal name for inline measures.
- The only inline measure currently allowed is `COUNT(*)`. This is to prevent SQL injection. We can relax this constraint when new use cases require it.
=> Implement inlineMeasures for metrics APIs

web-admin/src/components/navigation/Breadcrumbs.svelte
PR #2297 affected all our usage of TanStack Query. Now, by design, the `data` object is `undefined` until data is returned from the server. In many places previously, our code assumed the `data` object would be `{}` until data is returned from the server.
This PR fixes one file where we didn't switch the code to account for `data = undefined`.
=> Fix "organization is undefined" bug

web-admin/src/routes/+layout.svelte, web-admin/src/routes/+page.svelte, web-admin/src/routes/[organization]/+page.svelte, web-admin/src/routes/[organization]/[project]/+page.svelte, web-common/src/features/dashboards/workspace/DashboardContainer.svelte, web-common/src/layout/VerticalScrollContainer.svelte, web-common/src/layout/workspace/WorkspaceContainer.svelte
@ericpgreen2  and @hamilton, in my local testing I think this fixes the scrolling problem in cloud while preserving the behavior we want in developer. In the video below, when my mouse is hovering above the header I'm going nuts with the scroll wheel, and there is no scroll available at that level of the hierarchy.
https://github.com/rilldata/rill-developer/assets/2380975/860d1eaa-5932-4dcb-a9d0-edfc2520e91e
So I think this should be a simple fix, but with that said please please do a QA pass on cloud and dev to make sure I haven't missed anything.
=> resolve scroll issue. fixes #2395

web-admin/src/components/home/DeploymentStatusChip.svelte, web-admin/src/components/home/OrganizationList.svelte, web-admin/src/components/home/WelcomeMessage.svelte, web-admin/src/components/navigation/BreadcrumbItem.svelte, web-admin/src/components/navigation/Breadcrumbs.svelte, web-admin/src/components/projects/ProjectStatus.svelte, web-admin/src/routes/[organization]/+page.svelte
This PR:
- Adds an organization page and links to it on the home page
- Makes the breadcrumbs conventionally clickable – each breadcrumb label corresponds to a page that you can visit
- Retains the redirect so that, from a dashboard page, switching projects redirects you to the new project's first dashboard
- Does some minor cleanup: fixes a doc link & centers project status icons with the project name
=> Add an `/{organization}` page

web-common/src/components/column-profile/column-types/NestedProfile.svelte, web-common/src/components/column-profile/column-types/NumericProfile.svelte, web-common/src/components/column-profile/column-types/TimestampProfile.svelte, web-common/src/components/column-profile/column-types/VarcharProfile.svelte, web-common/src/components/column-profile/column-types/sparks/NullPercentageSpark.svelte
This bug was causing an issue in modeling. The profiling feature components were locking on an `isFetching` parameter, when really we just needed the numerator and denominator to not both be undefined before displaying.
=> removes rough edge around fetching spinner in the null percentage spark

web-common/src/features/dashboards/time-controls/TimeControls.svelte
Temporary patch for bug where no comparison option was not hiding comparison visuals.
Long term, we need to fix the architecture here such that the defaulting logic for store initialization lives with the store, not as part of reactive code in UI control components.
=> fix: broken hide comparisons

web-admin/src/components/authentication/UserButton.svelte
This PR changes the logout redirect logic so that:
- When a user logs out, they're redirected to the login page
- After logging in again, the user is redirected to the page they started on (not the home page)
This design solves for this scenario:
- You get a link to a dashboard that you don’t have access to with your current account. You want to logout & login with the correct account, and land on the link that was shared with you.
This design does not solve for this scenario:
- You’re on a dashboard on one account. You want to switch accounts to work on another project. You want to logout & login with your other account, and be redirected to your home page.
=> Use better logout to login redirect logic

web-common/src/features/models/workspace/ModelBody.svelte
The error window slide transition in the ModelBody is causing the ModelWorkspace to not update with new modelNames during routing when a model is opened initially with errors. Changing the transition to have the `local` modifier fixes the issue. This resolves bugs like https://github.com/rilldata/rill-developer/issues/2435
I am not sure why this would fix this bug; we probably need to do a deeper exercise of reproducing this bug in a REPL and reporting to Svelte team as I don't think this is specific to our application logic.
=> fix: model with errors nav bugs

web-common/src/features/metrics-views/metrics-internal-store.spec.ts, web-common/src/features/metrics-views/metrics-internal-store.ts
This PR fixes the following bug:
- You have a dashboard file that includes measures without a `name` key
- You click the "Add measure" button in the Metrics UI
- The application freezes
=> Add backwards-compatibility for measures without `name` key

web-common/src/features/dashboards/time-controls/TimeControls.svelte
This is a temporary fix that resolves a few bugs relating to the dashboard. Previously, we were not correctly initializing the start / end date, causing issues when using the time controls. This was a recent issue introduced in the last week or so.
We will be refactoring this component to remove rough edges around state initialization. Until then, we need a patch release.
=> fixes non-reactive time range initialization

web-common/src/features/dashboards/leaderboard/Leaderboard.svelte, web-common/src/features/dashboards/leaderboard/LeaderboardDisplay.svelte
While working on other stuff, I noticed that in the file `LeaderboardDisplay.svelte`, the variable `leaderboards` is set, but never passed to anything else nor used to derive anything else. Search ctrl+f in that file to convince yourself the variable only show up in 4 places, and that these 4 places just update the variable without any other effects.
Moreover, in  `Leaderboard.svelte`, we dispatch an event that does nothing other than set the value of `leaderboards` in  `LeaderboardDisplay.svelte`, so that is useless too. Search all files for "leaderboard-value" to convince yourself that this event is only captured by `LeaderboardDisplay.svelte` and only sets the useless variable.
Assigning @djbarnwal -- This should be quick.
=> remove useless var `leaderboards` and useless dispatch that sets it

docs/docs/home.md
We are missing a step when running the example project on the docs homepage
=> Update example script

admin/admin.go, admin/deployments.go, admin/provisioner/provisioner.go, admin/server/server.go, admin/worker/check_slots.go, admin/worker/worker.go, cli/cmd/admin/start.go
- Implements support for a background worker process in `admin`
- The worker runs by default when running `rill admin start`. You can override it as follows:
- Run `rill admin start server` to only run the admin server
- Run `rill admin start worker` to only run the worker
- (Running multiple workers is harmless, but redundant)
- Adds the first background job: `check_slots`, which prints info/warning logs for slots capacity (runs every 15 minutes by default)
=> Check slots job

web-local/test/ui/utils/useTestServer.ts
e2e tests randomly hang and fail https://github.com/rilldata/rill-developer/issues/2068
The e2e tests are occasionally hanging on network requests for profiling. After talking to @begelundmuller, he suggested increasing the pool size during testing. That seems to have fixed the problem. He will take a look at the underlying cause so that we can avoid this issue even with a pool size of 1.
```
$ cd ./web-local && npm run test
```
=> fix: e2e test hanging

.gitignore, Makefile, runtime/drivers/duckdb/olap_test.go
It's currently just an ad-hoc output you can get by running `make coverage.go`. We can investigate connecting to a coverage monitoring service in a later PR.
It reports the current coverage at 50.5% of statements.
=> Add Go test coverage

runtime/connectors/https/https.go, runtime/services/catalog/artifacts/yaml/objects.go
E.g. for authorization:
```
headers:
authorization: Bearer abcdef...
```
=> Support `headers` in source YAML for HTTP connector

web-admin/src/components/home/WelcomeMessage.svelte, web-admin/src/routes/[organization]/+page.svelte
Recent docs updates broke a couple links in Rill Cloud.
=> Fix links to quickstart

web-local/test/ui/dashboards.spec.ts
@begelundmuller and @ericpgreen2 have both reported seeing occasional e2e dashboard test failures in Github Actions on the last line of this testing sequence:
```typescript
await page.getByRole("button", { name: "Add dimension" }).click();
await dimensionsTable
.getByRole("row")
.nth(2)
.getByRole("textbox", { name: "Dimension label" })
.fill("Domain Name");
await dimensionsTable
.getByRole("row")
.nth(2)
.getByLabel("Dimension column")
.selectOption("domain");
// Go to dashboard
await page.getByRole("button", { name: "Go to dashboard" }).click();
// Check Avg Bid Price
await playwrightExpect(page.getByText("Avg Bid Price $3.01")).toBeVisible();
```
This script is adding a dimension in the metrics config, configuring the column, and clicking "Go to dashboard".
Occasionally the test is …
=> fix: occasional e2e test failure when adding dashboard dimension

admin/worker/check_slots.go
When there are no deployments at all, `minPctUsed` does not get set to a correct value, so it prints a warning, even though everything is fine.
=> Fix check slots warning when no slots are used

web-common/src/features/welcome/BackgroundImage.svelte, web-common/src/features/welcome/ProjectCards.svelte, web-local/vite.config.ts
Recent PRs (#2450, #2501) added images to the `/welcome` page by referencing static assets in CSS. Background images were added via Tailwind classes like `bg-[url('/img/welcome-bg-art.png')]`
This caused `vite build` to emit warnings because it can't resolve `/img` in the `/static` directory. See warnings:
I followed [this Stack Overflow post](https://stackoverflow.com/questions/75843825/sveltekit-dev-build-and-path-problems-with-static-assets-referenced-in-css) to work around the issue. It suggests using a Vite alias to explicitly state the images' directory, then using the alias in CSS like `bg-[url('$img/welcome-bg-art.png')]`
=> Fix Vite `/img` warnings

web-common/src/features/dashboards/time-controls/CustomTimeRangeInput.svelte, web-common/src/features/dashboards/time-controls/TimeControls.svelte, web-common/src/features/dashboards/time-controls/TimeGrainSelector.svelte, web-common/src/features/metrics-views/workspace/config-parameters/SmallestTimeGrainSelector.svelte, web-common/src/lib/time/grains/index.spec.ts, web-common/src/lib/time/grains/index.ts, web-local/test/ui/dashboards.spec.ts
The dashboard crashes for the Margin cost example dashboard when 24 hours time range is set
https://github.com/rilldata/rill-developer/assets/4402679/f3855f8c-a134-4d5b-abbe-a45d52d091fd
Also related: #2516
We were allowing day as possible time grain for 24 hours which resulted in this error (similar case for 14 days as well)
This PR now also simplifies some part of `TimeControls` and uses `getAllowedTimeGrain` to calculate time selector options.
1. Initate the marigin dashboard from the examples
2. In the time range `Last 24 hours` option should not be present
=> Fix bug when min time grain is set

.gitignore
This would enable us to add multiple projects starting with `dev-project` to the repo. This will help with testing out multiple projects easily.
=> Add all dev-projects* to gitignore

runtime/pkg/observability/middleware.go, runtime/server/catalog.go
Example output:
```
{"level":"info","ts":1685611241.669065,"msg":"grpc finished call","protocol":"grpc","peer.address":"::1","grpc.component":"server","grpc.method_type":"unary","grpc.method":"/rill.runtime.v1.RuntimeService/ListCatalogEntries","instance_id":"default","type":"OBJECT_TYPE_UNSPECIFIED","grpc.code":"OK","duration":0.002065833}
```
=> observability.SetRequestAttributes

runtime/services/catalog/artifacts/artifacts_test.go, runtime/services/catalog/artifacts/yaml/objects.go, web-common/src/features/metrics-views/DimensionColumns.ts, web-common/src/features/metrics-views/metrics-internal-store.spec.ts, web-common/src/features/metrics-views/metrics-internal-store.ts, web-common/src/features/metrics-views/workspace/MetricsExploreMetricsButton.svelte
This PR uses column instead of property to define the source of a dimension in dashboard config yaml. Only edits to the dashboard from the UI will update the yaml to use this new field. Backwards compatibility is also part of this PR for older projects.
N/A Will be in the dev branch
=> property => column in dashboard.yaml

package-lock.json
When running `npm run dev`, I was seeing this warning message:
This PR is the result of following the instructions to run `npx update-browserslist-db@latest` to update the `caniuse-lite` database.
=> Fix `Browserslist` warning

web-common/src/features/dashboards/DashboardAssets.svelte, web-common/src/features/entity-management/AddAssetButton.svelte, web-common/src/features/models/navigation/ModelAssets.svelte, web-common/src/features/sources/navigation/TableAssets.svelte, web-common/src/layout/navigation/NavigationEntry.svelte, web-common/src/layout/navigation/NavigationHeader.svelte
[PRD in Notion](https://www.notion.so/rilldata/Improving-Target-size-for-Add-Source-Models-Dashboard-Nav-c04af12473a642e8b87143b826a12038)
This PR improves the "Add {source, model, dashboard}" buttons. It removes the icon buttons in favor of large horizontal buttons that explicitly say "Add source", "Add model", and "Add dashboard", respectively. 
This PR does not implement the "Suggested Actions" component of the PRD. That will follow in a separate PR.
Verify that the new buttons match the Figma mocks.
=> Improve "Add {source, model, dashboard}" buttons

web-auth/src/components/Auth.svelte
Auth0 is not consistent with it's error fields. 
For example adding a weak password on SignUp gives the below error as `description` is an object
This PR tries for a best effort solution looking for a string error message.
=> Handle different error message fields for Auth

cli/cmd/runtime/start.go, cli/pkg/local/app.go, runtime/server/auth/jwt.go, runtime/server/auth/jwt_test.go, runtime/server/catalog_test.go, runtime/server/queries_columns_test.go, runtime/server/queries_metrics_comparison_toplist_test.go, runtime/server/queries_tables_test.go, runtime/server/queries_timeseries_test.go, runtime/server/server.go, runtime/server/server_test.go
Should fix runtime startup failing if the admin server is restarting at the same time. We have seen this error message previously:
```
{"level":"fatal","ts":1686039113.0174265,"caller":"runtime/start.go:130","msg":"error: could not create server","error":"failed to extract response via extractor function: invalid HTTP status code: 503","stacktrace":"github.com/rilldata/rill/cli/cmd/runtime.StartCmd.func1\n\t/home/runner/work/rill-developer/rill-developer/cli/cmd/runtime/start.go:130\ngithub.com/spf13/cobra.(*Command).execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068\ngithub.com/spf13/cobra.(*Command).Execute\n\t/home/runner/go/pkg/mod/github.com …
```
=> Retry initial JWKS fetch

web-common/src/features/dashboards/big-number/MeasuresContainer.svelte, web-common/src/features/dashboards/dimension-table/DimensionDisplay.svelte, web-common/src/features/dashboards/leaderboard/LeaderboardDisplay.svelte, web-common/src/features/dashboards/time-series/MetricsTimeSeriesCharts.svelte
[Notion page](https://www.notion.so/rilldata/Only-run-queries-once-dashboard-state-is-initialized-451de063dba34117a4cccfdc189e17ae?d=ac03ba48ef4d45ac865bc46068a7164e)
This PR applies TanStack Query's `enabled` flag to each `/totals` request. We ensure that we only submit a request once the dashboard's time range and filters have been set.
Most significantly, if we issue the request without a time range, the backend will assume the query applies to the all time range. Querying the all time range locks up a Druid cluster.
1. Open a dashboard
2. Open your browser devtools
3. Go to the Network tab
4. Filter for `/totals`
5. Refresh the dashboard page and observe 1 request to `/totals` and that request has a specified time range. Previously, there were 4 requests to `/totals`, some of which …
=> Reduce excessive calls to `/totals`

web-common/src/features/models/workspace/Editor.svelte
This PR adds `else` to our DuckDB SQL Dialect. Practically, this includes `else` in CodeMirror's syntax highlighting and autocomplete.
=> Add `else` to DuckDB SQL dialect

cli/pkg/telemetry/telemetry.go
When we added the user id telemetry we didnt add send it with the actual event.
=> Adding user_id to cli telemetry

web-common/src/features/models/workspace/ModelBody.svelte, web-common/src/runtime-client/invalidation.ts
Do not refetch profiling queries while modelling if the model fails.
We unnecessarily refetch profiling queries even if the model has failed. This will lead to a lot of unnecessary calls while actively typing a sql query.
Note that there is still a failed request for catalog entry. Non presence of a catalog entry means there is an error in the entity. So once we have refactored our app to the new architecture we need to revisit this logic.
1. Create a model by typing down the query char by char.
2. While typing any failed sql should not output any 400s for profiling queries.
=> Do not refetch profiling for failed model

runtime/drivers/duckdb/duckdb.go
Currently we do not explicitly support timezones. 
Until we figure out timezone support on applications side, use UTC as the timezone on runtime.
=> Put timezone to UTC

web-common/src/features/dashboards/big-number/MeasuresContainer.svelte, web-common/src/features/dashboards/leaderboard/LeaderboardDisplay.svelte
This PR fixes the 400 error that flashes when refreshing a filtered dashboard in the Cloud UI.
=> Wait for `selectedMeasures` before querying `/totals` API

web-local/src/app.html
We do not use calendly anymore. Removing the redundant download of its javascript.
=> Removing calendly download

web-common/src/features/dashboards/big-number/MeasuresContainer.svelte, web-common/src/features/dashboards/leaderboard/LeaderboardDisplay.svelte
This PR addresses [Himadri's bug report in Slack](https://rilldata.slack.com/archives/CTZ8XBQ85/p1686975790118379).
This bug is motivation for instantiating our Svelte stores higher in the component tree.
=> Fix "Cannot read properties of undefined" error

web-common/src/lib/formatters.ts
The timestamps returned from the runtime were not being displayed properly. 
https://rilldata.slack.com/archives/CTZ8XBQ85/p1686876647920379
We were using a 12 hour clock while formatting the timestamps. This PR switches it to a 24 hour clock. 
[D3 Locale format types](https://github.com/d3/d3-time-format#locale_format)
1. Create a model
2. `SELECT cast('2022-01-01 00:00:00' as timestamp) as ts, cast('2022-01-01' as timestamptz) tsz`
3. The resulted rows should display `2022-01-01 00:00:00`
=> Use 24 hour format for hours

web-common/src/components/data-graphic/compositions/timestamp-profile/TimestampProfileSummary.svelte, web-common/src/features/dashboards/proto-state/fromProto.ts, web-common/src/features/dashboards/proto-state/toProto.ts, web-common/src/features/dashboards/time-controls/time-range-utils.spec.disabled.ts, web-common/src/features/metrics-views/workspace/config-parameters/SmallestTimeGrainSelector.svelte, web-common/src/lib/time/config.ts, web-common/src/lib/time/grains/index.spec.ts, web-common/src/lib/time/grains/index.ts, web-common/src/lib/time/types.ts
1. Add `quarter` time grain
2. Deprecate `getTimeRangeOptions` method
3. Reconfig allowed time grains as per - https://www.notion.so/rilldata/Relationships-between-points-in-time-durations-time-ranges-offsets-and-natural-comparisons-a45146205f4e425fa5f3b325518ae12a?pvs=4#64319a0aa8de40df87d28fb4b613570c
Related:  #2613
=> Time Grain enhancements

runtime/drivers/sqlite/sqlite.go
Sqlite doesn't natively support `TIMESTAMP`s. The Go sqlite driver adds support for timestamps by serializing/deserializing timestamps to text.
For compatibility reasons, it uses Go's built-in time serialization by default, which for Kathmandu (and maybe other timezones) outputs a rare format that it cannot parse back:
```
2023-06-21T13:16:34.92806+02:00
2023-06-21 17:02:06.347726 +0545 +0545 m=+0.014533293
```
Setting `_time_format=sqlite` forces the sqlite driver to serialize in a predictable format.
=> Fix sqlite TIMESTAMP type in rare timezones

web-admin/src/app.html
https://www.notion.so/rilldata/Add-an-Open-Graph-image-to-Rill-Cloud-70e43a27c54a4cdaa4eac6cf9aa81cc9
Adds a meta tag which links to the image stored in Prod CDN
Can be verified after merging and seeing the Rill admin staging link for a dashboard on Slack
=> Add og image for web admin social previews

web-common/src/components/virtualized-table/sections/ColumnHeaders.svelte, web-common/src/features/dashboards/dimension-table/DimensionTable.svelte, web-common/src/features/dashboards/dimension-table/DimensionValueHeader.svelte
Fixes https://github.com/rilldata/rill/issues/2682, where the background color of the dimension details table headers was transparent so on scroll, you would see overflowed values behind it.
Adds explicit "bg-white" classes to all dimension table headers
1. Run `npm run dev`
2. Open localhost:3000 and navigate to a dashboard
3. Open a dimension details table
4. Minimize the height of the screen until you have to vertically scroll in the dimension details table
5. Observe that the scrolled values are hidden behind the sticky table headers
=> fix: missing background colors in table headers

web-admin/src/components/projects/ProjectDeploymentLogs.svelte
Cloud status page doesn’t render logs that aren’t formatted as JSON #2556 
Parses a string log which is not a JSON as an error item.
=> Parse and dispaly string logs

web-common/src/features/dashboards/rows-viewer/RowsViewerAccordion.svelte, web-local/test/ui/dashboards.spec.ts
Relabeling "Source Data" >> "Model Data" in the dashboard row viewer accordion to avoid confusion with where the data is coming from in our taxonomy of Source > Model > Dashboard
Changed a text label and updated the e2e test so it will click the right button
Open a dashboard and observe that the row viewer accordion says "Model Data"
=> feat: update dashboard row viewer label

web-common/src/features/dashboards/big-number/MeasuresContainer.svelte, web-common/src/features/dashboards/dimension-table/DimensionDisplay.svelte, web-common/src/features/dashboards/leaderboard/Leaderboard.svelte, web-common/src/features/dashboards/leaderboard/LeaderboardDisplay.svelte, web-common/src/features/dashboards/rows-viewer/RowsViewer.svelte, web-common/src/features/dashboards/rows-viewer/RowsViewerAccordion.svelte
https://rilldata.slack.com/archives/C02T907FEUB/p1687945434275359?thread_ts=1687812338.356339&cid=C02T907FEUB
For no time series dashboards, the time keys still had values in them. This PR set those keys to `undefined` if the dashboard has no time series.
=> Set time keys to undefined if no time series

web-common/src/features/dashboards/dimension-table/DimensionDisplay.svelte
closes #2714
Comparisons in dimension table would break if the selected measure was hidden.
1. Go to a dashboard and make sure comparison is enabled.
2. Hide the measure selected for leaderboards.
3. Go to any dimension details page. UI should not break.
4. Show/hide measures when in dimension details page. UI should not break.
=> Handling hidden measure in dimension table

web-common/src/features/dashboards/rows-viewer/RowsViewerAccordion.svelte
Per @jkhwu's design feedback, we are flipping the dash row viewer caret direction and moving it to the left of the label in order to represent it as a Drawer instead of as an Accordion.
=> fix: tweak row viewer design to look like a drawer

web-common/src/features/dashboards/dimension-table/DimensionDisplay.svelte, web-common/src/features/dashboards/dimension-table/dimension-table-utils.ts
https://rilldata.slack.com/archives/C04AGHL77PS/p1688065468472389
Comparison toplist is using `dimensionName` instead of `dimensionColumn` to get values.
Need to update the dimension table to use `dimensionColumn` to get values from the toplist.
1. Make sure to have comparisons enabled on a dashboard.
2. Go to a dimension details table.
3. Comparison data in toplist should be the same as toplist from full dashboard.
=> Fixing comparision toplist in dimension table

web-common/src/features/dashboards/dimension-table/DimensionDisplay.svelte
Refreshing a dashboard dimension display breaks sometimes
Use the AdBids.csv in our repo to create dashboard.
Select Last 4 Weeks and go to a dimension table and hit refresh
=> Wait for store values to be available

web-common/src/features/dashboards/proto-state/dashboard-url-state.spec.ts, web-common/src/features/dashboards/proto-state/dashboard-url-state.ts
When a dashboard is opened, back button has to be pressed twice to go back to the previous page.
We were calling `goto` without any state twice initially when default state was selected.
Adding a safeguard to not call `goto` if the new state and state in url match.
1. Go to a dashboard using the left nav from any other page.
2. Pressing back button once should take you back to the previous page.
3. This should apply when selecting various filters.
=> Call goto once for the same state

web-common/src/features/dashboards/dimension-table/DimensionDisplay.svelte, web-common/src/features/dashboards/dimension-table/dimension-table-utils.spec.ts, web-common/src/features/dashboards/dimension-table/dimension-table-utils.ts
We were using `dimensionName` to show toplist delta values in dimension detail table.
Using `dimensionColumn` to show the delta values. The values should now match the toplist from full dashboard.
1. Go to a dashboard with comparison.
2. Compare delta values for a dimension in full dashboard and detail table. They should now match.
=> Using the correct field to show toplist delta

web-auth/src/components/Auth.svelte
Users are always redirected to Login auth page. For invite links, we want to show Sing Up page.
Uses the extra param sent in the URL to decide which page to show
Related: #2720
=> Show sign up auth page when suggested

web-common/src/components/column-profile/queries.ts
Since we added strict validations to APIs, timeseries profiling is broken.
Passing `measures` to make sure API validation succeeds.
1. Use a data source with time stamp column.
2. Profiling for the time stamp column should show the chart in both sources and model pages.
=> Updating timeseries API to new validations

web-common/src/features/dashboards/DashboardAssets.svelte, web-common/src/features/dashboards/workspace/Dashboard.svelte, web-common/src/features/entity-management/types.ts, web-common/src/features/metrics-views/workspace/MetricsWorkspace.svelte, web-common/src/features/models/navigation/ModelMenuItems.svelte, web-common/src/features/models/workspace/ModelWorkspace.svelte, web-common/src/features/models/workspace/inspector/EmbeddedSourceReference.svelte, web-common/src/features/sources/add-source/LocalSource.svelte, web-common/src/features/sources/add-source/RemoteSource.svelte, web-common/src/features/sources/embedded/EmbeddedSourceMenuItems.svelte, web-common/src/features/sources/navigation/SourceMenuItems.svelte, web-common/src/features/sources/workspace/SourceWorkspace.svelte, web-common/src/layout/app-store.ts, web-common/src/layout/navigation/NavigationEntry.svelte, web-common/src/metrics/service/MetricsTypes.ts
Uses `page` store from sveltekit to derive active entity
Adds missing navigation events
=> Deprecate app store in favor of derived store

web-local/test/ui/utils/useTestServer.ts
Occasionally e2e test failures due to locking
Occasionally we see e2e tests fail because a stage db file is still locked. @AdityaHegde has already put in one PR to fix this by using different stage files for each test run. This PR adds to that by making sure we are waiting for processes to exit properly while running the test serially. While this code is probably unnecessary at this point, I think its important that while we are running our tests in serial, we should make sure that they are exiting properly to avoid any other bugs in the future.
Run the e2e tests
=> fix: add wait for process to exit between e2e tests

runtime/services/catalog/catalog.go
List catalog queries takes lock which is shared with reconcile calls. This leads to the UI being blocked when a reconcile is running in background.
The lock is only needed for modeller to make sure the DAG is up to date to show dependancies. So to get the background reconcile to work in cloud we can use try lock to fill in DAG.
=> Use trylock for catalog queries

web-common/src/features/dashboards/proto-state/DashboardStateProvider.svelte
In cloud url state is cleared and not applied to the dashboard.
The url state was being overriden by default state.
1. Setup cloud locally.
2. Deploy some project.
3. Go to a dashboard, select some filters.
4. Refresh the page, filters should persist.
=> Fix 1st time state being overriden

web-common/src/features/dashboards/time-series/MetricsTimeSeriesCharts.svelte
This PR is a quick fix to prevent charts from unmounting when filtering. Otherwise charts flicker when new data is fetched for the big number.
=> prevent chart unmount when filtering

web-common/src/components/chip/removable-list-chip/RemovableListMenu.spec.ts, web-common/src/components/chip/removable-list-chip/RemovableListMenu.svelte, web-common/src/components/search/Search.svelte, web-common/src/features/dashboards/filters/Filters.svelte
Fixes bugs:
- Filter bar search results were not rendering properly. Showing "undefined" instead
- Filter bar search would flash an empty state on first search
- Search component had a race condition with autofocus that could cause a TypeError to throw
**Filter bar search results were not rendering properly. Showing "undefined" instead**: The Filters component tries to look up search result data based on the dimension id, but the API returns the data keyed by dimension column name. This PR adds a lookup of the column name and uses that to access the search result display value instead of the dimension id.
**Filter bar search would flash an empty state on first search**: By default, we pass an empty array of search results to the RemovableMenuList component. This component has no way of …
=> fix: Filters bar not rendering search results properly

web-admin/src/components/errors/error-utils.ts
This PR fixes the problem [reported in Slack](https://rilldata.slack.com/archives/CTZ8XBQ85/p1689066245860979?thread_ts=1689049013.950719&cid=CTZ8XBQ85) that when a user deletes a project's GitHub repo, the project page is blocked with a full page "repository not found" 400 error.
Now, the project page displays as normal, with an error log that includes the message "repository does not exist".
=> Handle "repository not found" error

proto/rill/ui/v1/dashboard.proto, web-common/src/features/dashboards/proto-state/fromProto.ts, web-common/src/features/dashboards/proto-state/toProto.ts, web-common/src/features/metrics-views/metrics-internal-store.ts, web-common/src/proto/gen/rill/ui/v1/dashboard_pb.ts
Persisting showing of percentage of totals to the url state.
Auto generation of dashboard should add `valid_percent_of_total` to the total records measure.
1. Import a source with time stamp.
2. Autogenerate dashboard from it.
3. The dashboard created should have a measure with percent of totals enabled.
4. Toggling it should update the url state and refreshing should persist the toggle.
=> Percentage totals url state

web-common/src/features/entity-management/sync-file-system.ts, web-common/src/layout/RillDeveloperLayout.svelte
This PR disables bidirectional sync, per [Slack discussion](https://rilldata.slack.com/archives/CTZ8XBQ85/p1689266955444809). The sporadic, blocking reconcile has confused users. 
Previously, the application had polled the filesystem under three scenarios:
1. The user navigates to a new page
2. Every X seconds
3. The user returns focus to the browser tab
Previously, we had disabled scenarios 1 & 3. This PR:
- reverts the work to disable scenarios 1 & 3
- disables the whole feature (scenarios 1-3)
=> Disable bidirectional sync

web-admin/src/components/navigation/BreadcrumbItem.svelte, web-common/src/components/floating-element/FloatingElement.svelte, web-common/src/components/floating-element/WithTogglableFloatingElement.svelte, web-common/src/components/menu/wrappers/WithSelectMenu.svelte, web-common/src/lib/place-element.ts
On short screens, for a project with many dashboards, the dashboard breadcrumb's menu renders off-screen.
This PR adds an `overflowFlipY` boolean to the following components:
- `FloatingElement.svelte`
- `WithTogglableFloatingElement.svelte`
- `WithSelectMenu.svelte`
Previously, it was assumed that, if the content overflowed, we'd want to flip the content's location across the y axis. Now, if  `overflowFlipY` is `false`, the content will not be flipped. Instead, the window will scroll.
1. Go to a project with many dashboards (or mock the `menuOptions` in `Breadcrumbs.svelte`)
2. Open a dashboard
3. Shrink your window vertically
4. Open the dashboard dropdown
5. Ensure you can see all the options
=> Fix breadcrumbs with many menu items

web-common/src/components/button-group/ButtonGroup.svelte, web-common/src/features/dashboards/leaderboard/LeaderboardControls.svelte
a couple tiny follow ups to the pct of total work:
- gray-300 for button group outlines
- hide percent of total if a measure without validPercentOfTotal is selected
=> Percent-of-total follow up tweaks

web-common/src/features/models/workspace/Editor.svelte
1) In adding the YAML editor, we've lost the appearance of highlights in the SQL editor. Somehow, the YAML and SQL themes are conflicting. ([Slack bug report](https://rilldata.slack.com/archives/CTZ8XBQ85/p1689718130861029))
2) We've designed a new editor theme, which we haven't yet applied to the SQL editor
This PR uses the new editor theme for the SQL editor.
Here's what it looks like:
1. Write a SQL model & verify a pleasant, interactive editing experience.
2. Observe the new theme.
=> Use new theme for SQL editor

web-common/src/features/dashboards/leaderboard/DimensionLeaderboardEntrySet.svelte, web-common/src/features/dashboards/leaderboard/Leaderboard.svelte, web-common/src/features/dashboards/leaderboard/LeaderboardDisplay.svelte
use unfiltered total for percent-of-total calculations. addresses comment here: https://www.notion.so/rilldata/Design-Rev-on-Display-percent-of-total-metrics-in-dashboards-2bbf36511ff9452d949286c5a996205e?pvs=4#b7b7e1f53c394cfb9357775336c8731e
=> use unfiltered total for percent-of-total calculations

web-common/src/features/dashboards/leaderboard/LeaderboardContextColumnToggle.svelte
addresses issue here
https://www.notion.so/rilldata/Design-Rev-on-Display-percent-of-total-metrics-in-dashboards-2bbf36511ff9452d949286c5a996205e?pvs=4#0f2d8708a5074fd0858ff875f25d8d38
=> update summable metric tooltip

runtime/drivers/duckdb/migrations/0001.sql
It seems DuckDB can't remove an existing PK constraint, but this will hopefully fix the issue for new projects
See https://github.com/rilldata/rill/issues/2699 and related PRs for details
=> Remove rill.catalog primary key

runtime/queries/column_timeseries.go, runtime/queries/metricsview_rows.go, runtime/queries/sqlutil.go, runtime/server/queries_timeseries_test.go
Performance regression due to `time_bucket`, ie:
```
========= time_bucket
Running tool: /opt/homebrew/opt/go/libexec/bin/go test -benchmem -run=^$ -bench ^BenchmarkMetricsViewsTimeSeries$ github.com/rilldata/rill/runtime/queries -count=1
goos: darwin
goarch: arm64
pkg: github.com/rilldata/rill/runtime/queries
BenchmarkMetricsViewsTimeSeries-10           415     2586518 ns/op     43838 B/op     1240 allocs/op
PASS
ok    github.com/rilldata/rill/runtime/queries  13.004s
====== time_bucket, 30s
/opt/homebrew/opt/go/libexec/bin/go test -benchmem -run=^$ -bench ^BenchmarkMetricsViewsTimeSeries$ github.com/rilldata/rill/runtime/queries -count=1 -benchtime=30s
goos: darwin
goarch: arm64
pkg: github.com/rilldata/rill/runtime/queries
BenchmarkMetricsViewsTimeSeries-10         28398 …
```
=> Replace time_bucket with date_trunc

runtime/compilers/rillv1/parser.go, runtime/compilers/rillv1/parser_test.go
This PR contains some minor improvements to the project parser for async reconcile
- Make sure a resource's `Refs` only contains valid refs
- If a ref does not explicitly provide a kind (like "source" or "model"), we try to infer it
- If no kind can be inferred, the ref is discarded (see comments in PR for details)
- Add check that a source and a model does not use the same name
- The new catalog supports different resource kinds having the same name, but we need this exception to apply for sources/models since they are both mapped to tables)
- Track modifications to `rill.yaml` in `Diff`
=> Compiler: check refs and unique source/model names

runtime/drivers/blob/blobdownloader.go
Post changes in PR #2557 no s3 api calls are done during iterator creation phase for single files. This causes issues for objects with public access since we rely on failures to retry with anonymous credentials. 
We now pre fetch data in cases of single files to check for access.
@ericpgreen2 @nishantmonu51
=> S3 public file access fix

web-admin/src/routes/[organization]/[project]/[dashboard]/+page.svelte, web-common/src/features/dashboards/leaderboard/LeaderboardDisplay.svelte, web-common/src/features/dashboards/proto-state/DashboardStateProvider.svelte, web-common/src/features/dashboards/workspace/Dashboard.svelte, web-local/src/routes/(application)/dashboard/[name]/+page.svelte
Our state navigation is currently broken in many ways. One critical bug is that in Cloud, it will try to render a dashboard before the dashboard store is ready on navigation, causing the entire dashboard to break and the app to freeze.
This PR fixes the critical bug by moving the step to hydrate a dashboard initially OUT of the dashboard component itself. It also for now resets the dashboard state provider using a metricViewName #key. This may or may not be a temporary step; it depends on how we fix the other state navigation bugs.
=> fix: reset dash state provider on metric name

web-common/src/lib/duckdb-data-types.ts
This quick fix adds the duckdb `UUID` type, which was reported as missing
=> add uuid type

web-local/src/lib/svelte-query/globalQueryClient.ts
https://www.notion.so/rilldata/Rill-Developer-doesn-t-work-offline-92cb9b608b5543c59d8eefe8d4159e6c
Rill Developer doesn't work when offline today, even though it should. The reason is that TanStack QueryClients are by default configured to not attempt requests when the network is offline. This PR adds a change where, if running Rill Developer, the QueryClient will use networkMode "always", which will configure TanStack to send requests even if offline.
1. Run `npm run dev`
2. Turn wifi off
3. Open localhost:3000 and navigate between sources, models, and dashboards
=> feat: support offline in local dev

runtime/queries/column_timeseries.go, runtime/server/queries.go, runtime/server/queries_timeseries_test.go
For example:
```
D select time_bucket(interval '1 week', timestamptz '2022-10-25', 'Europe/Copenhagen') as week_start_copenhagen;
┌──────────────────────────┐
│  week_start_copenhagen   │
│ timestamp with time zone │
├──────────────────────────┤
│ 2022-10-23 22:00:00+00   │
└──────────────────────────┘
D select time_bucket(interval '1 week', timestamptz '2022-11-01', 'Europe/Copenhagen') as week_start_copenhagen;
┌──────────────────────────┐
│  week_start_copenhagen   │
│ timestamp with time zone │
├──────────────────────────┤
│ 2022-10-30 23:00:00+00   │
└──────────────────────────┘
D select * from range(time_bucket(interval '1 week', timestamptz '2022-10-25', 'Europe/Copenhagen'), time_bucket(interval '1 week', timestamptz '2022-11-01', 'Europe/Copenhagen'), interval '1 week') ; …
```
=> `range` doesn't take into account time zone DST

web-common/src/features/dashboards/leaderboard/LeaderboardDisplay.svelte, web-common/src/features/dashboards/proto-state/dashboard-url-state.ts
Switching between dashboard is inconsistent with retaining all the selections.
There was a race condition in the url sync component. It would run with state of older dashboard for newer dashboard.
1. Create 2 dashboards.
2. Go to one and select a few filters and change the time settings.
3. Go to the other and do the same.
4. Switching between these should retain the filters and time selections.
=> Adding a name safeguard for url state

cli/cmd/runtime/ping.go, cli/cmd/start/start.go, docs/docs/reference/cli/start.md
It seems some users run into conflicts on the internal gRPC port 9010. This changes it to something higher/rarer.
Based on https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers, 49009 is not officially used, and is outside the range of 49152–65535 from which other services may acquire temporary ports
=> Change internal gRPC port to 49009

web-common/src/features/dashboards/big-number/MeasureBigNumber.svelte, web-common/src/features/dashboards/dimension-table/DimensionDisplay.svelte, web-common/src/features/dashboards/dimension-table/dimension-table-utils.ts, web-common/src/features/dashboards/humanize-numbers.ts, web-common/src/features/dashboards/leaderboard/Leaderboard.svelte, web-common/src/features/dashboards/leaderboard/LeaderboardDisplay.svelte, web-common/src/features/dashboards/leaderboard/__stories__/LeaderboardListItem.stories.svelte, web-common/src/features/dashboards/time-series/MetricsTimeSeriesCharts.svelte, web-local/src/routes/dev/data-graphic/empty-timeseries.svelte
This PR does some minor cleanup, but primarily updates the type name `NicelyFormattedTypes`  to `FormatPreset` to match the string we've ended up adopting in the YAML spec for metrics.
@djbarnwal hoping for a quick review and merge on this since it's just a find a replace. Thanks!
=> Rename format preset type

web-common/src/components/column-profile/column-types/details/NumericPlot.svelte, web-common/src/components/data-graphic/compositions/timestamp-profile/TimestampDetail.svelte, web-common/src/components/data-graphic/compositions/timestamp-profile/TimestampMouseoverAnnotation.svelte, web-common/src/components/data-graphic/compositions/timestamp-profile/TimestampPaths.svelte, web-common/src/components/data-graphic/marks/prevent-vertical-overlap.ts, web-common/src/components/data-graphic/utils.ts, web-common/src/lib/formatters.ts, web-local/src/routes/dev/data-graphic/basic.svelte, web-local/src/routes/dev/data-graphic/metrics.svelte, web-local/src/routes/dev/data-graphic/reactive.svelte
While working on some formatting code, I encounterd this weird `~~` that I had to waste time going to look up. Turns out this is just an obfuscated way of writing `Math.trunc`, so I went through and quickly cleaned that up to de-obfuscate our codebase a bit.
=> replace `~~`  with `Math.trunc`

web-common/src/features/metrics-views/metrics-internal-store.ts, web-common/src/features/metrics-views/workspace/editor/Placeholder.svelte, web-common/src/features/models/navigation/ModelMenuItems.svelte, web-common/src/features/models/workspace/CreateDashboardButton.svelte, web-common/src/features/sources/createDashboard.ts
Some buttons to create a dashboard are adding a duplicate top-line comment to the YAML file. See [this bug report](https://rilldata.slack.com/archives/CTZ8XBQ85/p1691173690275799?thread_ts=1691173650.441909&cid=CTZ8XBQ85) in Slack.
This PR fixes the bug and, in the process, does a small refactor of the code to generate dashboard YAML.
1. Create dashboards in every possible way.
2. Verify that the dashboard YAML is correct.
=> Remove duplicate top-line comment in dashboard YAML

runtime/drivers/file/file_store.go, runtime/pkg/fileutil/fileutil.go, runtime/services/catalog/migrator/sources/sources.go, runtime/services/catalog/migrator/sources/sources_test.go, web-common/src/features/sources/sourceUtils.ts
When we added sql sources we didnt fully support local files. Local files with path relative to repo root is not replaced.
This PR updates the local file code path to rewrite relative paths.
=> Adding local_file sql source support

web-local/test/ui/dashboards.spec.ts
e2e tests are commonly failing because our menus animate closing and sometimes you need to wait for that animation to finish before playwright can interact with the browser.
This PR makes sure the menu is closed before continuing with tests
=> fix: wait for menu to close during test

web-common/src/lib/url-utils.spec.ts, web-common/src/lib/url-utils.ts
Fixes the issue mentioned [here](https://rilldata.slack.com/archives/C02T907FEUB/p1691751534383459)
We were hardcoding http protocol while redirecting dashboard url with state. Updating it to be based on the protocol of the url.
Hard to do this locally.
=> Fixing http used for dashboard redirect

web-local/test/ui/dashboards.spec.ts
Fixing test stability with the following changes:
- turning animations off during testing
- providing helper to make sure time selector menu has closed before continuing a test flow
- increasing allowed test run time
=> fix: e2e test stability

web-common/src/features/dashboards/time-dimension-details/Pivot.svelte, web-common/src/features/dashboards/time-dimension-details/TimeDimensionDetailsTable.svelte, web-common/src/features/dashboards/time-dimension-details/TimeDimensionDetailsTableCell.svelte, web-common/src/features/dashboards/time-dimension-details/data.ts, web-common/src/features/dashboards/time-dimension-details/mock-data.ts, web-common/src/features/dashboards/time-dimension-details/util.ts
Incremental step in adding the [time dimension details table](https://www.notion.so/rilldata/Time-Dimension-Detail-Design-Mocks-and-Specification-2dd22773d6e8479ca8d297f95877c669)
This PR adds async data fetching
Each cell of the table now has the ability to fetch its data via svelte-query. The cells look up which "block" of data they are in, then request that block. In this initial PR, we set the block size to 100, so data will be fetched in pages of 0-99, 100-199, etc. We can play with this number over time to find the best performing result. Svelte-query handles deduping these requests and serving from cache, so when many cells request the same block, they all get the same page.
The data fetching in this PR is just mocking a network call, with a configurable delay set to 1s. Once we …
=> feat: TDT async data 

cli/cmd/runtime/start.go, cli/cmd/start/start.go, cli/pkg/local/app.go, runtime/caches.go, runtime/caches_test.go, runtime/connections.go, runtime/drivers/duckdb/config.go, runtime/drivers/duckdb/config_test.go, runtime/drivers/duckdb/duckdb.go, runtime/drivers/duckdb/duckdb_test.go, runtime/pkg/activity/client.go, runtime/registry.go, runtime/registry_test.go, runtime/runtime.go, runtime/server/server.go, runtime/testruntime/testruntime.go
Closes #2848 
The PR updates a cached DuckDB connection so that it can emit DuckDB stats.
Each cached connection is cached per instance id and dsn and hence can autonomously collect and emit required stats per instance id and dsn.
=> Periodically emit DuckDB database metrics

web-common/src/features/dashboards/DashboardStateProvider.svelte, web-common/src/features/dashboards/dashboard-stores-test-data.ts, web-common/src/features/dashboards/dashboard-stores.spec.ts, web-common/src/features/dashboards/dashboard-stores.ts
Dashboards without timestamp are not rendered at all.
Our dashboard init assumes timestamp is always present. Refactored it a bit to support dashboards that do not have timestamps.
1. Create a dashboard with timestamp.
2. Go to dashboard.
3. Remove the timestamp in the editor.
4. Go back to dashboard. It should render without issues.
5. Add back the timestamp.
6. Go back to dashboard. Time controls should be back and intearactable.
=> Fixing dashboards without timestamp

web-common/src/features/dashboards/time-controls/CustomTimeRangeInput.svelte
Previously if you select July 1- July 30 in PDT, it will show up as Jun 30 - Jul 30 in the picker. This PR fixes the bug in custom date picker when a timezone is selected.
=> Fix zone bug in custom date picker

web-admin/src/components/projects/ProjectDeploymentLogs.svelte, web-admin/src/components/projects/ProjectDeploymentStatus.svelte, web-admin/src/components/projects/ProjectHero.svelte, web-admin/src/components/projects/RedeployProjectCTA.svelte, web-admin/src/routes/[organization]/[project]/+page.svelte
This PR:
- Hides the "View logs" button when a project is hibernating
- Hides the (empty) dashboard list component when a project is hibernating
- Moves the call-to-action to redeploy a hibernated project from the Project Logs page `{org}/{project}/-/logs` to the Project page `{org}/{project}`
- Differentiates the CTA betweeen project Admins and Viewers
=> Cloud UI: handle project hibernation on the new project page

runtime/drivers/duckdb/transporter/objectStore_to_duckDB.go
We expect that the error reported [here](https://rilldata.slack.com/archives/C01190F1R1D/p1692654170064749?thread_ts=1692652651.922889&cid=C01190F1R1D) is due to `checkpoint` that was introduced recently.
=> remove checkpoint during data ingestion

web-common/src/components/data-graphic/utils.ts, web-common/src/features/dashboards/time-series/MeasureChart.svelte, web-common/src/features/dashboards/time-series/MeasureScrub.svelte
Restructure scrub and zoom so that it can be reused at other places such as Time Detailed View.
This PR moves scrub methods from `MeasureChart` to `MeasureScrub` and fixes - 
1. Glitch animation when scrubbing
2. Removes scrub when mouse is released outside the charts
=> Re-structure scrub methods

web-common/src/components/modal/dialog/Dialog.svelte
Issue: A dialog closes when you begin your click (mousedown) inside the modal and end your click (mouseup) outside the modal. [Bug report in Slack.](https://rilldata.slack.com/archives/C0415QK8DK6/p1692285215926799)
This PR changes the `Dialog` behavior to close on mousedown. This is a bit of a hack, but the net result is a better experience. In the future, rather than rolling our own dialog component, we should move to a headless component library like https://svelte-headlessui.goss.io/.
=> Fix `Dialog` component bug

web-common/src/features/dashboards/dashboard-stores-test-data.ts, web-common/src/features/dashboards/dashboard-stores.spec.ts, web-common/src/features/dashboards/dashboard-stores.ts, web-common/src/features/dashboards/leaderboard/LeaderboardContextColumnMenu.svelte
closes #2961
1. Create a dashboard with timestamp
2. Update the default time range to one of the supported ones. https://github.com/rilldata/rill/blob/main/web-common/src/lib/time/ranges/index.ts#L105
3. Go to dashboard. The time range wont change if the dashboard was already opened. (Is a different issue around state initialization)
4. Refresh the dashboard and the default time range should show up.
=> Fixing default time range broken after dashboard init changes

web-common/src/components/floating-element/WithTogglableFloatingElement.svelte, web-common/src/components/menu/wrappers/WithSelectMenu.svelte
https://github.com/rilldata/rill/issues/2979, https://github.com/rilldata/rill/pull/2774
This PR removes the default behavior that menus flip over the Y axis when the content is long.
Run through the app and double-check that no menus are obscured.
=> Change default `flip` behavior of menus

cli/cmd/root.go, cli/cmd/upgrade/upgrade.go, cli/cmd/version/version.go, cli/pkg/update/update.go, docs/docs/install.md
This PR adds a `rill upgrade` command that downloads and runs the installation script. It also supports a `--nightly` flag to install the latest nightly build.
I called the command `rill upgrade` instead of `rill update` to avoid ambiguity with source refreshes.
Closes https://github.com/rilldata/rill/issues/2969
=> CLI: Add "rill upgrade" command

web-common/src/features/dashboards/dashboard-stores.spec.ts, web-common/src/features/dashboards/dashboard-stores.ts
When a default time range is selected in metrics config, comparison should be enabled by default if available.
1. Create a dashboard with timestamp.
2. Set `default_time_range` to `P1D`.
3. Go to dashboard.
4. Time range should be last 24 hrs and comparison should be enabled to last day.
=> Fix default time range adding comparision

web-common/src/features/dashboards/time-series/MeasureChart.svelte, web-common/src/features/dashboards/time-series/MeasureScrub.svelte, web-common/src/features/dashboards/time-series/MetricsTimeSeriesCharts.svelte
1. Zoom was broken on dashboards with high number of charts when keybinding `Z` was used
2. The zoomed in dates were not accurate due to timezone changes
1. Moves `<svelte:window>` to a component single component so to avoid multiple dispatches/state changes for the same keybinding.
2. Handles timezone offset when zoomed in
Play around with zoom on a dashboard with 5 or more charts.
=> Fix zoom bugs

runtime/queries/column_timeseries.go
since https://github.com/rilldata/rill/pull/2925 is not merged yet, we are still using this instead of MV query so cache key will have metricsview policy
=> fix timeseries caching

web-common/src/features/project/selectors.ts
When editing a `rill.yaml` document, there were occasionally not-very-useful warnings popping up in the browser console. 
Here's one: 
This PR hides these warnings.
Docs: https://eemeli.org/yaml/#document-options
=> Hide console warnings when parsing `rill.yaml`

proto/buf.gen.openapi-admin.yaml, proto/buf.gen.openapi-runtime.yaml, proto/gen/rill/admin/v1/admin.swagger.yaml, proto/gen/rill/runtime/v1/runtime.swagger.yaml, web-common/src/runtime-client/gen/index.schemas.ts
We were not pinned to a specific version of the `grpc-ecosystem/openapiv2` plugin, so started running into this issue when 2.17 was released: https://github.com/grpc-ecosystem/grpc-gateway/issues/3557
Fixing by pinning to 2.16.2 for now.
=> Fix broken OpenAPI bindings generator

web-common/src/features/dashboards/granular-access-policies/DevJWTProvider.svelte, web-common/src/features/dashboards/granular-access-policies/ViewAsButton.svelte, web-common/src/features/dashboards/granular-access-policies/resetSelectedMockUserAfterNavigate.ts, web-common/src/features/dashboards/granular-access-policies/stores.ts, web-common/src/features/dashboards/granular-access-policies/updateDevJWT.ts, web-common/src/runtime-client/RuntimeProvider.svelte, web-local/src/routes/(application)/+layout.svelte, web-local/src/routes/(application)/dashboard/[name]/+page.svelte
For errored projects we periodically fetch the status to update the UI if the status changes. This along with a global reactive statement for jwt to refetch the entire dashboard leads to a periodic refresh for errored out projects.
Moving the setting of jwt to the action itself. This way unnecessary refetches are avoided.
1. Start the cloud ui locally using `./scripts/devtool.sh`
2. Create a valid project with atleast 2 dashboard.
3. Update the project to mark one of the dashboard invalid and trigger refresh.
4. Open the valid dashboard.
5. The page should not refresh periodically.
=> Fixing periodic page refresh on errored dashboard

web-admin/src/components/projects/DashboardList.svelte
It's confusing when a dashboard is marked as errored when the project is reconciling. This PR hides any error badges while  the project is reconciling.
[Reported in Slack.](https://rilldata.slack.com/archives/C02T907FEUB/p1693892479745239)
=> Hide dashboard error badge when reconciling

runtime/queries/metricsview_comparison_toplist.go, runtime/server/queries_metrics_comparison_toplist_test.go
As pointed about by @bcolloran, it's also worthwhile revisiting the base/comparison terminology used here since the comparison value is actually used as the base for the comparison. Let's revisit that in a separate PR when we also rename `MetricsViewComparisonToplist` to `MetricsViewToplist` (or maybe it's time we just make it `MetricsToplist`?).
See context in [Slack](https://rilldata.slack.com/archives/C02T907FEUB/p1692996522697639?thread_ts=1692829203.034269&cid=C02T907FEUB).
=> Fix toplist comparison deltas

admin/deployments.go, runtime/drivers/blob/blobdownloader.go, runtime/server/server.go
=> Options to improve ingest performance

runtime/drivers/bigquery/api.go, runtime/drivers/bigquery/bigquery.go, runtime/drivers/bigquery/sql_store.go
1. Need to pass credentials while creating storage client as well.
2. The SDK internally resolves credentials based on env variables and local variables if credentials are not passed so fail if credentials are not resolved.
=> bigquery storage api fix

admin/deployments.go, cli/pkg/local/app.go, runtime/drivers/drivers_test.go, runtime/drivers/duckdb/config.go, runtime/drivers/duckdb/config_test.go, runtime/drivers/duckdb/duckdb.go, runtime/drivers/duckdb/duckdb_test.go, runtime/drivers/duckdb/olap_test.go, runtime/server/queries_test.go
- Adds support for configuring the DuckDB pool size through the config map (instead of the DSN)
- Sets the DuckDB pool size to 4 by default on local (was previously 1)
=> Set DuckDB pool size to 4 on local

web-common/src/features/dashboards/leaderboard/LeaderboardListItem.svelte
#3049 
Disable click action when pressed with shift key
1. Shift click on a leaderboard item
2. Value should be copied but not included.
=> Do not select leaderboard item on shift click

web-admin/src/components/projects/DashboardList.svelte
This PR switches titles in dashboard listings from using a fixed width container + truncation to using a variable width container + overflow scroll. This ensures you can always see the full dashboard title.
=> Cloud UI: don't truncate dashboard titles

web-common/src/features/dashboards/time-controls/TimeControls.svelte
Scrub was not working on some of the charts. On further inspection saw that `setTimeZone` was being called every time the app re-rendered and dispatched a call to set the scrub as `undefined`. 
For dashboards without any time zone we were making repeated state calls. This PR fixes that issue.
1. Scrub on a dashboard without any timezone keys defined
2. The scrub should work
=> Remove repeated time zone calls

runtime/drivers/duckdb/duckdb.go, runtime/drivers/duckdb/olap.go
Introduced 3 DuckDB related metrics: `duckdb_queue_latency_ms`, `duckdb_total_latency_ms`, `duckdb_query_latency_ms`
=> Emit DuckDB query metrics

web-common/src/components/menu/core/MenuItem.svelte
Our `MenuItem` component had a few shortcomings that I had to address in https://github.com/rilldata/rill/pull/3047. To ensure there aren't any side effects to these changes, I've created this PR to test/accept it in isolation.
Specifically:
- The background color on hover didn't fill the full width of some menus
- Focus was applied on hover
- Clicks weren't propagating to parent components
- Content placed in the "right" slot wasn't centered
=> Fix up `MenuItem` component

runtime/drivers/druid/olap.go, runtime/drivers/duckdb/duckdb.go, runtime/drivers/duckdb/duckdb_test.go, runtime/drivers/duckdb/olap.go, runtime/drivers/duckdb/transporter/motherduck_to_duckDB.go, runtime/drivers/olap.go, runtime/queries/column_timeseries.go, runtime/queries/table_columns.go, runtime/reconcilers/util.go, runtime/services/catalog/migrator/sources/sources.go
- We're seeing the DuckDB `.wal` explode in size when using a transaction to drop and replace a table. For a ~25GB dataset, we've observed a `.wal` size grow to ~250GB and freezing for almost an hour.
- This PR replaces the DB-level transaction with a `RWMutex` in the DuckDB driver. Regular queries take a read lock, "transactions" take a write lock.
- This loses the fault tolerance of transactions, but keeps consistency.
=> Use mutex instead of tx for DuckDB drop and replace table

runtime/drivers/duckdb/transporter/duckDB_to_duckDB.go, runtime/drivers/duckdb/transporter/filestore_to_duckDB.go, runtime/drivers/duckdb/transporter/motherduck_to_duckDB.go, runtime/drivers/duckdb/transporter/objectStore_to_duckDB.go, runtime/drivers/duckdb/transporter/utils.go, runtime/drivers/duckdb/transporter/utils_test.go, runtime/drivers/gcs/gcs.go, runtime/drivers/s3/s3.go, runtime/services/catalog/artifacts/artifacts_test.go, runtime/services/catalog/artifacts/yaml/objects.go
- Moves backwards compatibility rules for source properties into the drivers
- Enables the backwards compatibility rules to also work for the new reconcile
Note: The parsing of `fileSourceProperties` in the DuckDB transporters isn't the cleanest, since a) ideally they would be parsed in the source driver, not sink driver, b) some of them are actually sink properties. But that was also an issue before, so we can clean that up later.
=> Move source properties backwards compatibility rules to drivers

runtime/catalog_cache.go, runtime/runtime.go, runtime/server/controller.go
Didn't initially port over access policy checks in the new resource APIs. Doing that here.
The actual `ResolveMetricsViewSecurityV2` is not yet implemented for the `runtimev1.MetricsViewSpec`. To avoid too much duplicate code, will do that in the PR that will replace usage of `runtimev1.MetricsView` with `runtimev1.MetricsViewSpec` everywhere.
=> Add access policy checks for new resource API

web-common/src/lib/number-formatting/strategies/IntTimesPowerOfTen.spec.ts, web-common/src/lib/number-formatting/strategies/IntTimesPowerOfTen.ts, web-common/src/lib/number-formatting/utils/format-with-order-of-magnitude.ts
hey @ericpgreen2, this should clear some of the warnings that may show up in the console re https://github.com/rilldata/rill/issues/3074.
Some of those warnings are actually a result of invalid inputs to a formatting function, but some just represent floating point imprecision that we can round away. This will solve all the cases of FP imprecision, but not the genuine bad inputs.
(Interestingly, it seems like all the examples you show in the issue are actually bad inputs, whereas I was seeing a mix)
=> update IntTimesPowerOfTenFormatter to handle edge cases with floating point errors

web-common/src/features/dashboards/dimension-table/DimensionFilterGutter.svelte
Fix bug when comparison circles were being shown on exclude mode without the dimension being compared.
=> Don't show comparison circles on exclude mode

cli/pkg/local/app.go
- The frontend crashes on source refresh if telemetry tracking errors
- This PR fixes the issue on the backend by never returning errors for telemetry tracking, even when it fails
=> Never return errors for failed telemetry uploads

runtime/pkg/symmetriccrypto/symmetriccrypto.go, runtime/pkg/symmetriccrypto/symmetriccrypto_test.go, runtime/server/downloads.go, runtime/server/queries_metrics.go
- Exports do not work in cloud because they require the JWT to be passed to the download handler.
- Passing the JWT is not trivial when initiating a download from the browser.
- This PR removes auth requirements from the download handler, leveraging a pre-signed (actually encrypted) download token containing the request and user attributes needed to resolve the download.
- It currently uses an ephemerally generated, in-memory encryption key. This will be reset every time the runtime is restarted. We should eventually replace this with an environment-configured key. Until it's replaced, download URLs will break when a runtime is restarted. This is acceptable since download URLs are usually very short-lived (seconds).
=> Implement signed download tokens

web-common/src/features/dashboards/leaderboard/LeaderboardHeader.svelte
Fixes a bug noticed by Mike -- on `main`, only clicking on the text in a leaderboard title opens the dimension table; this PR expands the clickable are to fill the space to the right of that.
=> expands leaderboard clickable area

web-local/src/lib/svelte-query/globalQueryClient.ts
This PR enables Rill Developer to function offline by configuring TanStack Query's [Network Mode](https://tanstack.com/query/v4/docs/react/guides/network-mode).
=> Enable Rill Developer to function offline

web-common/src/features/metrics-views/metrics-internal-store.ts
This PR adjusts the dashboard autogenerate code to generate sum metrics for float column types. 
Integer types are not included yet as we cannot deterministically figure out if they are are ID columns or actual metrics.
=> Autogenerate sum metric definitions for float columns

web-common/src/components/data-types/Interval.svelte
Running `make cli` (or `npm run build`) emits this warning:
This PR fixes that warning.
=> Fix build warning

web-common/src/features/sources/editor/SourceEditor.svelte
This PR allows you to save & refresh a source file by pressing `mod` + `s`, where the modifier key is `cmd` on Mac and `ctrl` on Windows/Linux.
=> Add `mod` + `s` to save and refresh source file

runtime/compilers/rillv1/parse_metrics_view.go, runtime/compilers/rillv1/parse_migration.go, runtime/compilers/rillv1/parse_model.go, runtime/compilers/rillv1/parse_rillyaml.go, runtime/compilers/rillv1/parse_source.go, runtime/compilers/rillv1/parser.go, runtime/compilers/rillv1/parser_test.go
Fixes the nil pointer error introduced in https://github.com/rilldata/rill/pull/3176 (tests failing in https://github.com/rilldata/rill/pull/3092).
Also adds generic support for providing project-wide defaults for any source/model/dashboard property from rill.yaml.
=> Support project-wide defaults in rill.yaml

web-common/src/lib/time/config.ts, web-common/src/lib/time/transforms/index.ts, web-common/src/lib/time/types.ts
Closes #3199 
Fixes the case when anchored time ranges such as Today, Month to Date, Year to Date etc. would use the latest data as reference point instead of the current time in cases when latest data is in the future.
More - https://rilldata.slack.com/archives/CTZ8XBQ85/p1696875814646139
=> For anchored time ranges use the min of latest data and now

web-admin/src/features/projects/ProjectDashboardsListener.svelte, web-admin/src/features/projects/ProjectDeploymentStatusChip.svelte, web-admin/src/features/projects/dashboards.ts, web-admin/src/features/projects/selectors.ts, web-admin/src/routes/[organization]/[project]/+layout.svelte, web-common/src/features/dashboards/time-controls/time-control-store.ts, web-common/src/features/entity-management/resource-invalidations.ts
Adding the watcher client in the cloud would mean that all the users with a dashboard open would have an open connection with the server.
Removing the watcher client and going back to periodic refresh. The list all resources has a periodic refresh and any updated dashboards are invalidated.
=> Removing watcher clients from cloud

web-common/src/features/dashboards/DashboardAssets.svelte, web-common/src/features/dashboards/granular-access-policies/resetSelectedMockUserAfterNavigate.ts, web-common/src/features/entity-management/resource-invalidations.ts, web-common/src/features/entity-management/resource-selectors.ts, web-common/src/features/metrics-views/workspace/editor/update-metrics.ts, web-common/src/features/models/workspace/ModelWorkspaceCTAs.svelte, web-common/src/features/models/workspace/inspector/ModelInspector.svelte
1. Navigating between dashboards refreshes everything. Added safeguards for view-as value.
2. During the async reconcile merge a fix for resetting dashboard time controls got reverted.
3. Modelling errors put the modeller into a weird state. Temporarily disabling profiling on errors. This needs a proper fix from the controller where any update sends an extra event just before scheduling with reconcileStatus != IDLE.
4. Go to dashboard button in model is broken. Updated to use Resource instead of Catalog.
=> Fixing some edge cases with async reconcile in modelling

admin/auth_token.go, admin/database/database.go, admin/database/postgres/migrations/0016.sql, admin/database/postgres/postgres.go, admin/deployments.go, admin/permissions.go, admin/pkg/authtoken/authtoken.go, admin/server/auth/claims.go, admin/used_flusher.go, admin/worker/delete_expired_token.go, admin/worker/worker.go, runtime/drivers/admin/admin.go
Adds an `admin` driver to runtime, and during provisioning, generates a deployment-specific admin access token and sets it on the instance.
This enables the runtime to "phone home" to the control plane to pull config. This will be used to:
- Only send scheduled reports to project members
- Fetch user attributes for each recipient for granular access policies in scheduled reports
- Pulling ad-hoc artifacts (not in Github) from the admin server to the runtime
- Deprecate the `github` driver (which requires our master Github app credentials to be available on each runtime) and instead call the admin server to get Git credentials for the runtime
=> Deployment admin access tokens + stubs for runtime admin driver

web-admin/src/features/projects/DashboardList.svelte, web-admin/src/features/projects/ProjectDashboardsListener.svelte, web-admin/src/features/projects/ProjectDeploymentStatusChip.svelte, web-admin/src/features/projects/dashboards.ts
We were using direct calls to get dashboard list in project page.
Replacing the direct call to instead use tanstack query. This way there shouldnt be any issue with stale jwt.
=> Using tanstack query for all lists in cloud

web-admin/src/features/errors/ErrorPage.svelte, web-admin/src/features/errors/error-utils.ts
Upon navigating to a dashboard with a 502 error (at the time of writing, [this one](https://ui.rilldata.com/demo/rill-app-engagement/moble_app_engagement)), the Error Page is blank with the following message in the browser console:
This PR protects against accessing an undefined `status` field.
=> Avoid a blank error page

.prettierignore
couple tiny updates to prettierignore
=> prettierignore -- ignore .gitkeep and yaml

runtime/queries/column_numeric_histogram.go, runtime/queries/column_rug_histogram.go, runtime/server/queries_columns_test.go, runtime/testruntime/testdata/ad_bids/models/ad_bids_errored.sql, web-common/src/components/column-profile/column-types/NumericProfile.svelte
Histogram queries throw an error when run on duckdb 0.9.
`Error: INTERNAL Error: Failed to bind column reference "SUBQUERY" [476.0] (bindings: [401.0])`
Found a workaround where calculating min, max and range outside of the CTE fixes this.
=> Fixing histogram query on duckdb 0.9

cli/pkg/local/app.go, runtime/catalog_cache.go, runtime/connection_cache.go, runtime/connection_cache_test.go, runtime/controller.go, runtime/controller_test.go, runtime/drivers/sqlite/catalog.go, runtime/queries/metricsview_api_benchmark_test.go, runtime/queries/metricsview_comparison_toplist_benchmark_test.go, runtime/queries/metricsview_comparison_toplist_test.go, runtime/query.go, runtime/registry.go, runtime/registry_test.go, runtime/server/catalog.go, runtime/server/controller.go, runtime/server/queries_metrics.go, runtime/server/queries_metrics_timeseries_test.go, runtime/testruntime/reconcile.go, runtime/testruntime/testruntime.go
Previously, the registry cache would load all existing instances from the metastore on startup, start their controllers, call `WaitUntilReady`, then create the global project parser if it didn't already exist.
Since controller initialization needs to load the catalog, and we embed the catalog in DuckDB, if opening any DuckDB handle is slow (e.g. has a large wal), this would could cause the entire runtime initialization to hang. This means the runtime server isn't started, so health checks fail, and we got a crash loop in Kubernetes.
This PR moves controller initialization into the background. Instead, any call to `runtime.Controller(ctx, instanceID)` will hang until the controller has finished initializing ready or has errored.
=> Run controller initialization in the background

web-common/src/features/dashboards/leaderboard/Leaderboard.svelte, web-common/src/features/dashboards/leaderboard/leaderboard-utils.ts
it's somehow possible for an active value to appear more than once in the set of filters for a leaderboard, which can cause downstream breakage. This is a quick fix to workaround that until I can dig deeper (or someone else can)
=> fix duplicate active values in leaderboard

web-admin/src/features/projects/ProjectCards.svelte
=> Fix project cards not wrapping on Home and Org pages

runtime/compilers/rillv1/template.go, runtime/connections.go, runtime/controller.go, runtime/drivers/duckdb/transporter/utils.go, runtime/queries/queries.go, runtime/registry.go, runtime/runtime.go, runtime/server/controller.go, runtime/server/server.go
- Check ctx cancellation when acquiring a connection (better than returning a cache eviction error)
- Add tracing to `Controller.Get(...)` and `Controller.List(...)` and `Runtime.Controller(...)`
- Increase query execution timeout to 3 minutes
=> Telemetry improvements for ListResources and misc. other fixes

web-admin/src/features/errors/error-utils.ts
This PR improves Cloud error handling to account for more cases. Now we:
- Check for network errors
- Show the error page for errors missing `response.status` or `response.data.message`
=> Fix missing error page

web-admin/src/routes/[organization]/[project]/[dashboard]/+page.svelte, web-common/src/features/dashboards/stores/DashboardStateProvider.svelte
This PR adds a spinner while we wait for the dashboard to first load. Specifically, the initial query to `MetricsViewTimeRange` can take a while when the query queue is full, so we need a loading state under this circumstance.
[Slack report](https://rilldata.slack.com/archives/C02T907FEUB/p1697701218945499)
=> Add spinner while waiting for initial dashboard state

runtime/compilers/rillv1/init.go, runtime/compilers/rillv1beta/project.go
Have seen a few projects that had `.DS_Store` committed by accident
=> Add .DS_Store to .gitignore for new empty projects

cli/cmd/project/describe.go, cli/cmd/project/project.go
Usage:
```
❯ rill project describe -h                                                      
Retrieve detailed state for a specific resource (source, model, dashboard, ...)
Usage:
rill project describe [<project-name>] <kind> <name> [flags]
Flags:
--path string      Project directory (default ".")
--project string   Project name
```
=> CLI: Implement "rill project describe"

runtime/pkg/securetoken/securetoken.go
Seem like the library we're using to create download tokens has a default limit of 4kb
=> Fix error if export token is too long

runtime/drivers/bigquery/sql_store.go, runtime/drivers/blob/blobdownloader.go, runtime/drivers/duckdb/transporter/objectStore_to_duckDB.go, runtime/drivers/duckdb/transporter/transporter_test.go, runtime/drivers/duckdb/transporter/utils.go, runtime/drivers/gcs/gcs.go, runtime/drivers/object_store.go, runtime/drivers/s3/s3.go
1. We ingest in batches when using duckdb sql since runtime is crashing with OOM if ingesting large amount of data in one query. 
2. It may not be possible to always  ingest in batches when using duckDB sql (example having a group by clause) in these cases batch ingestion can be disabled using `batch_size: -1` in source.yaml
3. Also added a dumb(very) retry logic to fix error listed in [issue](https://github.com/rilldata/rill/issues/3323). Seeing this very frequently now both on local and cloud.
=> Runtime: ingest in batches when using duckdb sql

.github/workflows/rill-cloud.yml
its confusing
```
$ docker pull gcr.io/rilldata/rill-headless
Using default tag: latest
Error response from daemon: manifest for gcr.io/rilldata/rill-headless:latest not found: manifest unknown: Failed to fetch "latest" from request "/v2/rilldata/rill-headless/manifests/latest".
```
=> Don't publish latest image

web-common/src/features/dashboards/proto-state/fromProto.ts, web-common/src/features/dashboards/proto-state/toProto.ts, web-common/src/features/dashboards/stores/dashboard-stores.ts
Going back by using back button fails for TDD and DimensionTable.
Making sure absence of TDD measure and DimensionTable dimension marks it as undefined in `fromProto`. In the long run we should enums to denote what is being shown instead of the method we have.
1. Create a dashboard with a timeseries.
2. Go to TDD view.
3. Click back button.
4. TDD view should go away.
=> Fixing url state with value based visuals

runtime/drivers/duckdb/config.go, runtime/drivers/duckdb/config_test.go, runtime/drivers/duckdb/duckdb.go
1. Adds option to set custom duckdb configurations via `rill env set connector.duckdb.boot_queries "SET max_memory='12GB';SET threads=30" --project=rill-examples`
2. `pool_size` can be capped by `rill env set connector.duckdb.pool_size 2 --project=rill-examples`
3. Limits default pool size to a max of 5.
=> Support explicitly overriding DuckDB threads and max_memory configs

web-admin/src/features/projects/ProjectDeploymentStatusChip.svelte
We were using DEPLOYMENT_STATUS_UNSPECIFIED while the dashboard list is loading.
Using DEPLOYMENT_STATUS_PENDING while the dashboard list is loading.
=> Fix Project deployment status to show loading while dashboard list is loading.

web-common/src/features/dashboards/workspace/DashboardCTAs.svelte, web-common/src/features/entity-management/resource-status-utils.ts, web-local/src/routes/(application)/dashboard/[name]/+page.svelte
closes #3388
There was a null check missing due to which dashboard meta query refresh would crash the app.
1. Create a source (preferably a local file) with a refresh.
2. Create a dashboard out of this.
3. While the dashboard is active it should refresh periodically and not crash the app.
=> Fixing dashbaord refresh due to source refresh

runtime/queries/metricsview_aggregation.go, runtime/queries/metricsview_comparison_toplist.go, runtime/queries/metricsview_timeseries.go, runtime/queries/metricsview_timeseries_test.go, runtime/queries/timeutil.go, runtime/queries/timeutil_test.go, runtime/reconcilers/report.go
UI rounds time ranges based on selected time grain. We need the same support for reports.
This PR adds,
=> Adding support for round_to_grain for APIs

cli/pkg/local/app.go
Disabling waiting for initial reconcile to complete on startup. Since we added handling of delayed reconcile in UI we can open the UI ASAP and show the user loading spinners.
=> Disabling wait for reconcile on startup

web-common/src/components/preview-table/PreviewTable.svelte
fixes bugbash issue re timestamp column widths: https://www.notion.so/rilldata/Bug-Bash-Rill-GA-6867ccc289494508ae5f8d966d8902c5?pvs=4#aed6a4ae5dba42a49d2a9ecd7dd92fe1
=> Bugbash: fix timestamp column sizing in preview table

web-common/src/features/sources/modal/FileDrop.svelte, web-common/src/features/sources/modal/LocalSourceUpload.svelte, web-common/src/features/sources/modal/RemoteSourceForm.svelte
On a fresh project local imports take some time after the file upload before redirecting to the source. This feels like nothing happened after an upload.
Adding a redirect to the source page so that the `ingesting` message is shown and there is a feedback after an upload.
1. Start from a fresh project.
2. Upload a large file.
3. After the `importing` overlay is closed the page should redirect to source page where the `ingesting` message is shown.
=> Adding a redirect to source on import

web-local/test/ui/dashboards.spec.ts
Fixes the [error described here](https://learn.microsoft.com/en-us/azure/playwright-testing/troubleshoot-test-run-failures#test-fails-with-path-is-not-available-when-connecting-remotely), which allows e2e tests to be run from the playwright vscode extension.
=> fix error that prevented running e2e tests from vscode extension

web-common/src/features/dashboards/pivot/Pivot.svelte, web-common/src/features/dashboards/pivot/regular-table-style.css, web-common/src/features/dashboards/time-dimension-details/TDDTable.svelte, web-common/src/features/dashboards/time-dimension-details/util.ts
In TDD gray out rows which are not included or excluded.
This PR also moves the `regular-table` styles inside the repo so that they can be managed easily.
=> Gray out unselected rows in table

runtime/compilers/rillv1/parser.go, runtime/compilers/rillv1/parser_test.go
Closes https://github.com/rilldata/rill/issues/3403
=> Runtime: Fix cyclic ref when a metrics view references an underlying table with the same name

web-common/src/features/dashboards/time-series/MetricsTimeSeriesCharts.svelte, web-common/src/features/dashboards/time-series/timeseries-data-store.ts
Bug Bash -  https://www.notion.so/rilldata/Bug-Bash-Rill-GA-6867ccc289494508ae5f8d966d8902c5?pvs=4#c4b33949bb5d4c24b6f2c8c69865798e
Adds fetching status when totals data is not ready. This shows a spinner instead of 0 value.
=> Add fetching status to Big Number

web-admin/src/features/dashboards/listing/DashboardList.svelte, web-admin/src/features/navigation/nav-utils.ts, web-admin/src/features/projects/ProjectBuilding.svelte, web-admin/src/features/projects/ProjectErrored.svelte, web-admin/src/features/projects/ProjectParseErrors.svelte, web-admin/src/features/projects/ProjectTabs.svelte, web-admin/src/routes/[organization]/[project]/-/status/+page.svelte
Changing the copy from "logs" to "status" more accurately reflects the contents of the page. The page does not contain running logs, it only shows one-point-in-time parse errors.
=> Cloud UI: rename "Logs" page to "Status"

web-common/src/features/entity-management/resource-selectors.ts, web-common/src/features/models/createDashboardFromModel.ts, web-common/src/features/models/navigation/ModelMenuItems.svelte, web-common/src/features/models/workspace/CreateDashboardButton.svelte
When model ingestion is slow create dashboard button can trigger for older data.
Adding a safeguard to make sure we wait before getting the schema before creating a dashboard. Note that pressing the button immediately after changing the model will still break this, but a user wont be that quick.
=> Adding safeguard for creation of dashboard while model is being ingested

docs/docs/deploy/credentials/postgres.md, runtime/drivers/postgres/postgres.go, runtime/drivers/postgres/sql_store.go
We moved to `connector.name.var`
=> Runtime: log and docs fix for postgres connector

web-common/src/features/dashboards/big-number/MeasureBigNumber.svelte
`break-words` or `overflow-wrap: break-word` works for firefox but not for chrome. See https://github.com/tailwindlabs/tailwindcss/discussions/10545#discussioncomment-4925891
=> Wrap longer labels for big number

web-common/src/features/entity-management/resource-invalidations.ts
Every now and then creating a dashboard fails and redirects to edit page. But immediately going to the dashboard works without needing a refresh. This happens consistently when adding a column and removing it before autogenerating a dashboard.
Adding a workaround for an event for resource when it is created. Ignoring it when status=IDLE and we have not seen it before.
1. Create a model with a timestamp and one dimension.
2. Create a dashboard and delete it.
3. Add `*` to the model and remove it.
4. Create a dashboard. (Make sure to wait a little, there is another issue not fixed in this PR if done too quickly)
5. Should work without an issue and redirect to the dashboard page.
=> Fixing creating a dashboard after editing a model

cli/cmd/deploy/deploy.go, cli/cmd/env/configure.go, runtime/compilers/rillv1/connectors.go
Note: Only the changes in `deploy.go` were needed, but ended up making a few other minor changes during debugging.
Closes https://github.com/rilldata/rill/issues/3399
=> CLI: Fix sources requiring credentials being printed twice

docs/docs/reference/project-files/dashboards.md
=> docs: add timezone for dashboard.yaml

web-common/src/features/dashboards/dimension-table/ExportDimensionTableDataButton.svelte, web-common/src/features/dashboards/dimension-table/dimension-table-export-utils.ts
Scheduled reports are to be run for the latest time period.
Fill in the isoDuration and isoOffset so that reporting can use it to run for the latest period.
=> Send corring time controls to shceduled exports

web-admin/src/features/scheduled-reports/history/ReportHistoryTable.svelte, web-admin/src/features/scheduled-reports/history/ReportHistoryTableCompositeCell.svelte, web-admin/src/features/scheduled-reports/listing/ReportsTable.svelte, web-admin/src/features/scheduled-reports/listing/ReportsTableCompositeCell.svelte, web-admin/src/features/scheduled-reports/metadata/ReportMetadata.svelte, web-admin/src/features/scheduled-reports/metadata/utils.ts, web-admin/src/features/scheduled-reports/tableUtils.ts, web-common/src/components/menu-v2/MenuItem.svelte, web-common/src/components/menu-v2/MenuItems.svelte, web-common/src/features/dashboards/dimension-table/ExportDimensionTableDataButton.svelte, web-common/src/features/dashboards/scheduled-reports/CreateScheduledReportModal.svelte, web-common/src/lib/time/timezone/index.ts
This PR:
- Adds a "Time zone" element to the scheduled reports form. The included options are:
- The dashboard's current time zone (if time zone enabled)
- The user's local time zone
- UTC
- Accounts for the report's time zone throughout the report management UI (reports table, report metadata display, report recent run history)
=> Make scheduled reports timezone-aware

runtime/drivers/bigquery/sql_store.go
=> 3429: Fallback to a query execution if BQ Storage API cannot be used

web-common/src/components/button/Button.svelte, web-common/src/features/sources/modal/SourceImportedModal.svelte, web-common/src/features/sources/workspace/SourceWorkspaceHeader.svelte, web-common/src/layout/workspace/WorkspaceHeader.svelte
This PR accounts for long file names in two places:
- The new modal that shows after a source is imported ([bug bash](https://www.notion.so/rilldata/Bug-Bash-Rill-GA-6867ccc289494508ae5f8d966d8902c5?pvs=4#86498cb9142440d6bc90cfb52ec4dd6b))
- The workspace header ([bug bash](https://www.notion.so/rilldata/Bug-Bash-Rill-GA-6867ccc289494508ae5f8d966d8902c5?pvs=4#2d56975c436f46499aa60e0c220bdc17))
=> Rill Developer: account for long file names

web-admin/src/features/dashboards/listing/DashboardsTableCompositeCell.svelte
Addresses this [bug bash report ](https://www.notion.so/rilldata/Bug-Bash-Rill-GA-6867ccc289494508ae5f8d966d8902c5?pvs=4#db7cecacc04141ee98b3db1a3735fa45)
See the third entry, which was previously blank:
=> Fix: fallback to dashboard `name` when no `title` in the Cloud UI dashboards table

web-admin/src/features/scheduled-reports/history/ReportHistoryTable.svelte, web-admin/src/features/scheduled-reports/history/ReportHistoryTableHeader.svelte, web-admin/src/features/scheduled-reports/metadata/MetadataLabel.svelte, web-admin/src/features/scheduled-reports/metadata/ReportMetadata.svelte, web-admin/src/features/scheduled-reports/metadata/ReportOwnerBlock.svelte, web-admin/src/routes/[organization]/[project]/-/reports/[report]/+page.svelte, web-common/src/components/menu-v2/MenuItem.svelte
This PR improves the design of the Scheduled Report page at `/{org}/{project}/-/reports/{report}`.
Additionally, because the `ListProjectMembers` API is only accessible to Admins, this PR removes the call to this API for Viewers.
=> Improve design of the Scheduled Report page

web-admin/src/features/scheduled-reports/listing/ReportOwnerBullet.svelte, web-admin/src/features/scheduled-reports/listing/ReportsTable.svelte, web-admin/src/features/scheduled-reports/listing/ReportsTableCompositeCell.svelte
This PR fixes two bugs in the scheduled reports table:
- Project Viewers would see a 403 error because they're not allowed to call `ListProjectMembers`
- The table header's search box threw an error when `reportTime` was undefined
=> Bugfixes in Scheduled Reports table

web-common/src/features/dashboards/time-series/multiple-dimension-queries.ts
Do not call Aggregation API when the measure list is empty.
https://rilldata.slack.com/archives/C04AGHL77PS/p1699904575728479
=> Fix: Do not call API for empty measure list

web-admin/src/features/scheduled-reports/metadata/utils.ts
This PR fixes a bug on the Scheduled Report page where the "Next run" date showed "Invalid DateTime" when the time zone was not specified. When a time zone is not specified, we interpret it as UTC.
=> fix: handle missing time zone as UTC in Scheduled Report's Next run date

web-common/src/features/dashboards/big-number/BigNumberTooltipContent.svelte, web-common/src/features/dashboards/big-number/MeasureBigNumber.svelte
- Don't show anything in the tooltip when value is `undefined`
- Do no show tile/card in TDD view.
=> Fixes to Big number tooltips

web-common/src/features/dashboards/pivot/Pivot.svelte
Replace null strings present in measure column in TDD table to Null cells.
Before: 
After:
=> Fix: Replace null string with null cell

go.mod, go.sum
Currently removing a directory fails the watcher with error : `no such file or directory`
Seems to be already fixed in this issue : https://github.com/fsnotify/fsnotify/pull/537
Don't see error after upgrade.
=> upgrade watcher to v1.7.0

web-admin/src/features/projects/RedeployProjectCTA.svelte, web-admin/src/routes/[organization]/[project]/+layout.svelte, web-admin/src/routes/[organization]/[project]/+page.svelte
Closes #3499 
This PR fixes a bug that prevented the "Your project is hibernating" CTA from showing on the project page.
The PR also touches up the aesthetics, so that the CTA is centered and prominent:
=> Fix "Your project is hibernating" CTA

web-common/src/components/data-types/FormattedDataType.svelte, web-common/src/components/data-types/MeasureChange.svelte, web-common/src/components/data-types/PercentageChange.svelte, web-common/src/components/data-types/type-utils.ts, web-common/src/features/dashboards/dimension-table/dimension-table-types.ts, web-common/src/features/dashboards/dimension-table/dimension-table-utils.ts, web-common/src/features/dashboards/state-managers/selectors/data-formatting.ts, web-common/src/lib/formatters.ts
This should fix the issue described here: https://rilldata.slack.com/archives/CTZ8XBQ85/p1699976127305919
before:
after:
=> Fix "no data", "prev_value", and a tooltip issue

web-common/src/app.css
Contrast on menu item hover was too low. Flicker on click still works.
Before:
After:
=> fix: menu item focus contrast

web-common/src/features/dashboards/pivot/Pivot.svelte, web-common/src/features/dashboards/time-dimension-details/TDDTable.svelte
Columns in Time Detailed Dimension table are now resizable.
This PR also removes custom width based on viewport size. It provides a fixed width for all columns. Users can resize these as per their convenience. 
https://www.notion.so/rilldata/Time-Dimension-Detail-Experience-Pass-1e2951a6d8f74adcaad70db50fc7607a?pvs=4#ae0af399741d4f6b9e76a6b0b13b65e0
=> Enable table columns to be resizable

runtime/drivers/s3/s3.go
Closes #1967 
Relates to #1710 
Adds the endpoint option to the connector dialog within the UI.
=> feat: add s3 endpoint to UI

web-common/src/components/button-group/ButtonGroup.svelte, web-common/src/features/dashboards/big-number/MeasureBigNumber.svelte, web-common/src/features/dashboards/big-number/MeasuresContainer.svelte, web-common/src/features/dashboards/state-managers/selectors/data-formatting.ts, web-common/src/features/dashboards/time-dimension-details/time-dimension-data-store.ts, web-common/src/features/dashboards/time-dimension-details/util.ts, web-common/src/features/dashboards/time-series/MeasureChart.svelte, web-common/src/features/dashboards/time-series/MetricsTimeSeriesCharts.svelte, web-common/src/lib/number-formatting/format-measure-value.ts, web-common/src/lib/number-formatting/strategies/IntTimesPowerOfTen.ts
Fixes #3527. Tagging @djbarnwal, because I made the formatters accept `undefined` as you requested last week, and therefore removed the need for the `safeFormatter` function, so I took that out. Please confirm that this meets your needs! :-)
=> fix formatter warnings

web-admin/src/features/scheduled-reports/history/ReportHistoryTable.svelte, web-admin/src/features/scheduled-reports/history/ReportHistoryTableCompositeCell.svelte, web-admin/src/features/scheduled-reports/metadata/ReportMetadata.svelte, web-admin/src/features/scheduled-reports/metadata/RunNowButton.svelte
This PR adds a "Run now" button to the report page. This button is used to trigger an ad-hoc run of the report.
[Figma mock](https://www.figma.com/file/Qt6EyotCBS3V6O31jVhMQ7/RILL?type=design&node-id=5744%3A592897&mode=design&t=cyloPlXpIACsksrK-1)
=> Add report "Run now" button

web-common/src/components/tooltip/TooltipContent.svelte
Fixes flicker mentioned here https://rilldata.slack.com/archives/C02T907FEUB/p1701116172362659, add adds a default (overridable) max width to all tooltips
=> add default tooltip max width to fix flicker noticed by Nishant

web-common/src/features/dashboards/state-managers/selectors/time-range.ts, web-common/src/features/dashboards/stores/dashboard-stores.ts, web-common/src/features/dashboards/time-controls/TimeComparisonSelector.svelte, web-common/src/features/dashboards/time-controls/TimeControls.svelte, web-common/src/features/dashboards/time-controls/TimeRangeSelector.svelte, web-common/src/features/dashboards/time-controls/time-control-store.ts, web-common/src/features/dashboards/time-controls/time-range-store.ts, web-common/src/lib/time/comparisons/index.ts, web-common/src/lib/time/config.ts, web-common/src/lib/time/ranges/index.ts, web-common/src/lib/time/ranges/iso-ranges.ts, web-local/test/ui/dashboard-flows/dashboard-flow-template.ts, web-local/test/ui/dashboard-flows/dashboard-flow-test-setup.ts, web-local/test/ui/dashboard-flows/dimension-and-measure-selection.spec.ts, web-local/test/ui/dashboard-flows/time-controls-from-config.spec.ts, web-local/test/ui/dashboards.spec.ts, web-local/test/ui/utils/dashboardHelpers.ts
We added backend support for `available_time_ranges` but no UI support.
1. Refactor TimeRangeSelector to use a new selector that provides the list of available time ranges from `available_time_ranges` config.
2. Refactor TimeComparisonSelector to use a new selector that provides the list of available comparison options from `available_time_ranges` or the default.
1. Create a dashboard with timestamp.
2. Add this setting to start testing,
```
available_time_ranges:
- PT6H
- range: P5D
comparison_offsets:
- rill-PP
- rill-PW
- P4W
- rill-WTD
- rill-MTD
```
=> Integrating available_time_ranges in UI

web-common/src/features/dashboards/time-series/timeseries-data-store.ts
rill-private-issues#7 
Cloud dashboard sometimes crashes when changing to no comparison mode.
We were sending an additional request to `timeseries` API when comparison was changed to no comparison. The `timeStart` and `timeEnd` were undefined leading to the error.
=> Disable invalid request when changing to no comparison

web-common/src/features/dashboards/time-controls/ComparisonSelector.svelte
For dimensions not having labels, the the comparison selector would show blank items. Now we fallback to dimension name if no label is present
=> Use name for dimension if label not present

web-admin/src/features/scheduled-reports/metadata/ReportMetadata.svelte, web-admin/src/features/scheduled-reports/metadata/ReportOwnerBlock.svelte, web-admin/src/features/scheduled-reports/selectors.ts
For reports created through code, this PR hides the report page's three-dot menu that includes the "Edit report" and "Delete report" actions. For reports created through code, the admin should edit/delete reports by editing the code files directly.
Contributes to #3427
=> Hide UI controls for scheduled reports created through code

package-lock.json, web-common/package.json
#3552 removed some Storybook dependencies that weren't obviously used. It turns out they're used by the Storybook smoketest, which runs in CI/CD: `npm run storybook:smoketest -w web-common`
While we don't actively have any stories in the smoketest, this PR adds back the dependencies to give us the capability going forward.
=> Add back Storybook smoketest dependencies

runtime/pkg/securetoken/securetoken.go, runtime/server/downloads.go, runtime/server/server_test.go
Makes the following changes to reduce download token size:
- Apply GZIP compression to baked queries and download tokens
- Use gob instead of json for serialization in `pkg/securetoken`
Testing with a filter of 500 website URLs:
- Protobuf size: 26091
- Token length before this PR: 62136
- Token length after this PR: 10088
Other observations:
- Removing encryption does not change the token size
- I identified a further possibility for a ~30% size reduction, but it would require a few more hours of work. Added details in a comment in `pkg/securetoken`.
=> Add compression and use gob encoding for download tokens

web-common/src/features/scheduled-reports/EditScheduledReportDialog.svelte
Before this PR, editing a scheduled report and clicking "Save" sometimes led the user to a 404 page. This happened because:
1. We instantiated the "Edit report" form with the time zone abbreviation, not with the underlying IANA time zone.
2. When the form was submitted with this time zone abbreviation, it resulted in  an "invalid time zone" error in the virtual report file.
3. The presence of this error caused the report resource to be torn down.
4. Because the report resource no longer existed, a 404 page resulted.
This PR fixes this.
=> Fix time zone bug in "Edit report" form

web-admin/src/client/utils.ts, web-admin/src/features/errors/error-utils.ts
Closes #3372 
When adding special handling for 401s from the Runtime server, we broke the auth redirect for 401s from the Admin server (when on the Dashboard page).
This PR:
- Redirects to the login page whenever a request to the admin server returns a 401
- Edits the login page redirect so that, after login, the user is returned to their intended page
Note: In the future we can consider using unique TanStack Query `QueryClients` for the Admin server and for different Runtimes. That isolation would've prevented this issue from happening in the first place.
=> Fix auth redirect on the Dashboard page

runtime/controller.go, runtime/drivers/duckdb/config_test.go, runtime/drivers/duckdb/duckdb.go, runtime/drivers/duckdb/olap.go, runtime/drivers/duckdb/olap_crud_test.go, runtime/drivers/duckdb/transporter_motherduck_to_duckDB.go, runtime/drivers/duckdb/transporter_postgres_to_duckDB_test.go, runtime/drivers/duckdb/transporter_sqlite_to_duckDB_test.go, runtime/drivers/duckdb/transporter_sqlstore_to_duckDB.go, runtime/drivers/duckdb/transporter_test.go, runtime/registry_test.go
- Ensures `LongRunning=true` for all mutation queries
- Stop the reconcile controller and log an error if a cancelled reconcile does not finish within 10 minutes
- Log an error from DuckDB driver if a connection has been held for more than one hour
- Avoid implicit connection creation in `detachAllDBs`
- Correct usage of `reopenDB`
Contributes to https://github.com/rilldata/rill-private-issues/issues/17
=> Runtime: Reduce chance and impact of deadlocked DuckDB calls

web-common/src/app.css, web-common/src/layout/RillDeveloperLayout.svelte
`overscroll-behavior: none` is CSS that prevents trackpad gesture navigation (given it's enabled at your OS level). Previously, this CSS lived in our `app.css` file, which applies to both Rill Cloud and Rill Developer. This PR move the CSS so that it only applies to Rill Developer.
Code editors, or at least vscode.dev, tend to restrict this sort of trackpad navigation so that horizontally scrolling your code file does not accidentally trigger navigation.
Closes #3574
=> Only apply `overscroll-behavior: none` to Rill Developer

.github/workflows/web-test.yml, web-common/src/features/entity-management/resource-status-utils.ts, web-local/src/routes/(application)/dashboard/[name]/+page.svelte
We can declare victory in `web-local`: the `src/routes/dev` folder can stay ignored since it's not user facing. After this pr we won't be ignoring any user facing type errors in that subfolder of the repo.
part of  #3424
=> limit `--ignore` in web-local to only dev route!

docs/docs/deploy/source-refresh.md
Documenting how to configure source refreshes under the Deploy to Cloud section to enable better self-service.
=> Docs: Adding page for source refresh

web-common/src/lib/number-formatting/strategies/intervals.spec.ts, web-common/src/lib/number-formatting/strategies/intervals.ts
This should fix #3655 -- this code is now as systematic as I know how to be in JS. Literally every everything value used in the function is either a literal of a defined type, a predefined constant field access, or a number, and any non-numeric input should be handle as well.
I was not able to reproduce the actual bug locally, so I can't 100% confirm that this will fix it, but it is now impossible to access the `unit` field on a possibly undefined value, because there is no more accessing of fields with runtime values.
=> make formatMsInterval tighter and add tests

web-common/src/features/dashboards/time-series/timeseries-data-store.ts
Refactor `timeseries-store` for svelte 4 upgrade. Removes svelte-check errors.
Closes #3617
=> Refac: Svelte-check and svelte 4 upgrade changes

web-common/src/features/dashboards/proto-state/fromProto.ts
Fixes url state taken from older dashboards where we used different labels for time comparisons.
=> Adding backwards compatibility for older time comparison

docs/docs/deploy/source-refresh.md, docs/docs/reference/project-files/sources.md
Adding examples of cron syntax in source refreshes (and that it should be wrapped in single quotes for the yaml parser)
=> Docs: Adding clarification to using cron syntax for source refreshes

web-local/test/ui/dashboard-flows/leaderboard-and-dim-table-sort.spec.ts
This PR fixes an issue that occurs when running tests locally (and sometimes in CI).
Re: `leaderboard-and-dim-table-sort.spec.ts`
1. Adds a page timeout after selecting the `Percentage change` sorting option to allow for the Leaderboard rankings to update
2. Broadens the subsequent selectors by using RegEx rather than a specific string. The reason for this is that some Playwright runs trigger the hover effect on the element, which means that the "name" selector may sometimes include an additional number (see below)
If similar issues arise in the future, I think the other selectors could be broadened without issue. Also, if these are too broad, for whatever reason, this PR could be updated with a slightly more complex RegEx to capture both hover and not hovered states.
=> update to leaderboard test to account for inconsistent Playwright behavior

web-admin/src/features/projects/ProjectDeploymentStatus.svelte, web-admin/src/features/projects/ProjectGithubConnection.svelte, web-admin/src/features/projects/selectors.ts, web-admin/src/routes/[organization]/[project]/-/status/+page.svelte
[As discussed in Slack](https://rilldata.slack.com/archives/CTZ8XBQ85/p1701888061780859)
With this PR, on the project status page, we now show two timestamps:
1. Data last refreshed – this indicates the most recent time when a source or model has been refreshed
2. Github last synced – this indicates the last time the project files in Github were synced. This was the timestamp we showed previously, but it wasn't very clear what it represented. This PR moves this timestamp into the Github block to help clarify.
=> Cloud UI: Add "data [last] refreshed" timestamp to project status page

web-common/tailwind.config.cjs
This PR updates the Tailwind config file to no longer import the default colors, which in current versions happens automatically.
This removes the warning related to importing colors that have been renamed.
=> update tailwind config to remove outdated color warning

web-common/tailwind.config.cjs
A recent PR broke theme colors where not all classes had the updated colors. This fixes the issue while also getting rid of the warnings.
=> Fix theme colors and remove warning

web-common/src/components/data-graphic/marks/ChunkedLine.svelte
Closes #3524
Lines that do not extend to the right edge of the graph are clipped using a clipPath. Wrapping clipPath in WithTween delays the appearance of the clipping by a fraction of a second, causing unintended flickering when sorting or updating data.
This PR removes the wrapping of the clipPath element with no immediately apparent change in functionality. However, there may be a good reason that I am not yet aware of for why the tweening is necessary on the clipPath.
=> removed WithTween wrapper around clipPath to prevent fickering when charts are updated

docs/README.md, docs/src/css/custom.css
Adds short-hand css classes to hide pages and categories from documentation.
=> docs: hide content class

web-common/src/features/dashboards/time-series/timeseries-data-store.ts, web-common/src/runtime-client/http-request-queue/priorities.ts
Closes #3381 
Note: I did not have access to the dataset being used in the referenced Notion doc, so had to artificially recreate this situation while debugging.
The issue seems to be that TimeSeriesDataStore was artificially holding back data and returning `isFetching` as `true` until both the totals and primary queries were available.
During exploration, I saw no obvious UI issues related to rendering either of those pieces of data independently. As such, my proposed fix is to simply change the boolean logic of the `isFetching` property and remove the stricter "gate". This appears to solve the issue.
This PR also updates the `totals` query to a priority of 30.
=> remove artificial time series chart delay

web-common/src/features/models/selectors.ts, web-common/src/features/models/workspace/Editor.svelte, web-common/src/features/sources/selectors.ts
Closes #3384
Like the idea of coloring sources and models differently, but this PR does not address that feature.
=> suggest models in the code editor

web-common/src/features/dashboards/time-series/TimeSeriesChartContainer.svelte
For some initial renders of the chart, we were seeing negative width value error in the console. 
This was one of those bugs which took hours to figure out but required a one line change. This occurs when `workspaceWidth` is still being computed and has a value of 0.
I tried pulling out the ternary operators out of the HTML block and into the scripts. Somehow that made the charts fixed a single smaller width. Not sure what is exactly going wrong and why reactivity is not working there properly. Nevertheless have made changes which fixes the bug/error.
=> Fix: Negative SVG values in Graphic Context

runtime/drivers/duckdb/duckdb.go, runtime/drivers/duckdb/transporter_duckDB_to_duckDB.go, runtime/drivers/duckdb/transporter_duckDB_to_duckDB_test.go, runtime/drivers/duckdb/transporter_motherduck_to_duckDB.go, web-common/src/features/sources/modal/AddSourceModal.svelte, web-common/src/features/sources/modal/yupSchemas.ts, web-common/src/features/sources/sourceUtils.ts
=> Runtime: unified `duckdb` connector for `motherduck` and external `db` files

runtime/queries/metricsview_comparison_toplist.go
So that only one metric is present in order by and druid can optimize it to native topN instead of group by
=> remove order by true from toplist api

runtime/reconcilers/model.go, runtime/reconcilers/source.go, runtime/reconcilers/util.go
To be removed once debugging is complete
=> Runtim: Debug logs for identifying intermittent query failure

.github/workflows/web-test-code-quality.yml, .github/workflows/web-test-e2e.yml, .github/workflows/web-test-unit-tests.yml
Splits web tests up into:
- code quality (lint and type check)
- unit tests (we apparently only have unit tests in web-common and web-auth, though we have not been running the auth tests in CI, so those are added)
- e2e tests (only web-local and web-admin have this, though web-admin only seems to have a test stub for now)
Note that we have a separate GH action that runs prettier on the entire repo (prettier.yaml) so I thought it was redundant to have the prettier checks for each web folder. Easy to add back in if that is incorrect.
Looking to @himadrisingh for approval from the dev-ops perspective since I'm not super familiar with the ins-and-outs of GH actions. In particular, I don't know what the "dorny/paths-filter@v2" does, so I just copied that over as-is across the board. Please LMK …
=> split web tests

web-common/src/components/data-graphic/guides/Axis.svelte, web-common/src/lib/number-formatting/humanizer-types.ts, web-common/src/lib/number-formatting/humanizer.ts, web-common/src/lib/number-formatting/strategies/SingleDigitTimesPowerOfTen.spec.ts, web-common/src/lib/number-formatting/strategies/SingleDigitTimesPowerOfTen.ts
fixes #3631, updates to more accurate+descriptive name
=> rename "intTimePowerOfTen" to "singleDigitTimesPowerOfTen", silence warnings

web-common/src/components/chip/removable-list-chip/RemovableListChip.svelte, web-common/src/components/menu/core/MenuItem.svelte, web-common/src/components/searchable-filter-menu/SearchableFilterDropdown.svelte, web-common/src/features/dashboards/filters/FilterButton.svelte, web-common/src/features/dashboards/filters/Filters.svelte, web-common/src/features/dashboards/filters/formatFilters.ts, web-common/src/features/dashboards/filters/getDisplayName.ts, web-common/src/features/dashboards/state-managers/actions/dimension-filters.ts
This PR moves temporary/potential/incomplete filters (those that do not have dimension values) outside of the dashboard store.
This addresses a change in the runtime that happened in #3624  that requires the `in` field of a filter be a nonempty array.
=> move incomplete filters out of dashboard store and into a dedicated piece of state

runtime/drivers/druid/olap.go
Prevents the panics observed in these [logs](https://rill.datadoghq.com/logs?query=service%3Arill-cloud%20%40error%3A%2A%20%40msg%3A%22panic%20in%20reconciler%22&agg_m=count&agg_q=kube_namespace%2Chost%2C%40env&agg_t=count&cols=host%2Cservice&index=main&messageDisplay=inline&refresh_mode=sliding&source=monitor_notif&stream_sort=desc&view=spans&viz=stream&from_ts=1703075402000&to_ts=1703075702000&live=false)
=> Runtime: error instead of panic when creating models on Druid

web-admin/src/features/view-as-user/setViewedAsUser.ts
PR #3590 changed the API response of `GetDeploymentCredentials`, renaming `jwt` to `accessToken`.  This PR accounts for this change client-side.
Closes #3739
=> Fix "View As" functionality in Cloud UI 

web-common/src/features/models/workspace/CreateDashboardButton.svelte
Changes `Create Dashboard` to `Autogenerate Dashboard` from user feedback
=> fix: clarify model CTA button copy

runtime/queries/metricsview.go, runtime/queries/metricsview_aggregation.go, runtime/queries/metricsview_comparison_toplist.go, runtime/queries/metricsview_rows.go, runtime/queries/metricsview_timeseries.go, runtime/queries/metricsview_toplist.go, runtime/queries/metricsview_totals.go, runtime/reconcilers/metrics_view.go
Fixes an issue introduced in https://github.com/rilldata/rill/pull/3624 where security policy row filters are not added to `WHERE` clauses. This issue is only in staging and has not been released yet.
Also fixes an unrelated issue where column validation would fail for metrics views if a column used uppercase characters.
=> Runtime: Fix missing security policy row filters for new filter expressions

web-common/src/features/dashboards/rows-viewer/RowsViewer.svelte, web-common/src/features/dashboards/rows-viewer/RowsViewerAccordion.svelte, web-common/src/layout/drag.ts, web-common/src/layout/navigation/Navigation.svelte
Closes https://github.com/rilldata/rill/issues/3744
=> Allow resizing the height of the "Model Data" dashboard module in Rill Developer

web-common/src/features/dashboards/filters/Filters.svelte, web-common/src/features/dashboards/leaderboard/LeaderboardListItem.svelte, web-common/src/features/dashboards/state-managers/actions/dimension-filters.ts
This PR changes the filter clearing behavior so that the "temporary" filter pill is only maintained when interacting with filters through the dropdown menu.
=> tweak filter clearing behavior

web-common/src/features/dashboards/filters/Filters.svelte, web-common/src/features/dashboards/leaderboard/leaderboard-utils.ts, web-common/src/features/dashboards/state-managers/actions/dimension-filters.ts, web-common/src/lib/arrayUtils.ts
Older filter objects stored all non-null filters as strings. This is a temporary fix for this use case. In the new filters we should retain the original type.
=> Fix issues with non string dimension filters

web-common/src/features/dashboards/leaderboard/LeaderboardDisplay.svelte
The `LeaderboardDisplay` component, unlike others rendered in the `Dashboard`'s right pane, was determining its height from a fixed calculation. When viewing model data, this meant that the Leaderboards could not all be scrolled into view. This PR fixes that issue by using `h-full` instead.
=> fixes issue where leaderboard could not be fully scrolled when viewing model data on the dashboard

web-common/src/components/chip/chip-types.ts, web-common/src/components/chip/removable-list-chip/RemovableListChip.svelte
This PR enables the outlines for filter pills via the RemovableListChip component, bringing the UI in line with the design system.
=> enable outlines for filter pills

web-common/src/components/menu/core/MenuItem.svelte, web-common/src/components/menu/core/MenuItemData.ts, web-common/src/components/searchable-filter-menu/SeachableFilterButton.svelte, web-common/src/components/searchable-filter-menu/SearchableFilterChip.svelte, web-common/src/components/searchable-filter-menu/SearchableFilterDropdown.svelte, web-common/src/components/searchable-filter-menu/SearchableFilterSelectableItem.ts, web-common/src/features/dashboards/filters/FilterButton.svelte, web-local/src/routes/dev/grouped-searchable-filter/+page.svelte
In preparation of adding measure filters we need measures and dimensions sections in the add filter drop down.
This PR only adds this grouping feature to our searchable filter component. Visit http://localhost:3000/dev/grouped-searchable-filter to check how it will look.
=> Adding support for sections in searchable filters

package-lock.json, web-common/package.json, web-common/src/components/table-shadcn/Table.svelte, web-common/src/components/table-shadcn/TableBody.svelte, web-common/src/components/table-shadcn/TableCaption.svelte, web-common/src/components/table-shadcn/TableCell.svelte, web-common/src/components/table-shadcn/TableFooter.svelte, web-common/src/components/table-shadcn/TableHead.svelte, web-common/src/components/table-shadcn/TableHeader.svelte, web-common/src/components/table-shadcn/TableRow.svelte, web-common/src/components/table-shadcn/__stories__/Table.stories.svelte, web-common/src/components/table-shadcn/__stories__/data.ts, web-common/src/components/table-shadcn/index.ts
This PR adds [ShadCN Svelte's "Data Table"](https://www.shadcn-svelte.com/docs/components/data-table) component set to `web-common/components/table-shadcn`. The PR includes a basic Storybook story to show it in action.
This PR will be followed by another that uses this component on the Cloud UI project status page.
=> Add ShadCN's Data Table component set

runtime/queries/metricsview.go
In a previous PR (#3779) we handled empty and/or operations by allowing them. This PR adds the check for empty operations and returns an error.
=> Empty filters are now errors

runtime/drivers/file/watcher.go
I saw this error in a project and I hope this will fix it:
```
2023-12-28T13:47:32.266	ERROR	Stopped watching for file changes	{"err": "watch failed: no such file or directory"}
2023-12-28T13:47:32.266	WARN	Reconcile failed	{"name": "parser", "kind": "ProjectParser", "elapsed": "10.016s", "error": "watch failed: no such file or directory"}
```
=> Runtime: Prevent file watcher errors when a file is rapidly created and deleted

runtime/registry.go, runtime/registry_test.go
Fixes the race condition that repeatedly causes race condition tests to fail on merge to main (e.g. [this one](https://github.com/rilldata/rill/actions/runs/7462333741/job/20304396670))
=> Runtime: fix failing race condition test

web-common/src/features/dashboards/dashboard-fetch-mocks.ts, web-common/src/features/dashboards/proto-state/dashboard-url-state.spec.ts, web-common/src/features/dashboards/selectors/index.ts, web-common/src/features/dashboards/state-managers/selectors/index.ts, web-common/src/features/dashboards/state-managers/selectors/types.ts, web-common/src/features/dashboards/state-managers/state-managers.ts, web-common/src/features/dashboards/stores/dashboard-store-defaults.ts, web-common/src/features/dashboards/stores/dashboard-stores.ts, web-common/src/features/dashboards/time-controls/time-control-store.spec.ts, web-common/src/features/dashboards/time-controls/time-control-store.ts, web-common/src/features/dashboards/time-controls/time-range-store.ts
Addresses the first bullet here: https://github.com/rilldata/rill/issues/3803
=> Dashboard: Replace `ColumnTimeRange` request with `MetricsViewTimeRange` request

runtime/compilers/rillv1/parser.go, runtime/reconcilers/project_parser.go
- When the application is started in a new directory, a sqlite file is created immediately in `tmp/meta.db`
- This causes file watch events to be triggered before `rill.yaml` has been initialized
- This PR fixes the issue by not printing warnings about missing/broken `rill.yaml` files for non-YAML and non-SQL file events
Contributes to https://github.com/rilldata/rill/issues/3551
=> Fix meaningless "broken rill.yaml" warnings for empty projects

runtime/queries/metricsview.go
Fixes issue reported by @djbarnwal [here](https://www.notion.so/rilldata/Pivot-Table-implementation-notes-19dac24bafaa4c018c87298523f25898?pvs=4#cd1faaa19dce4df2a66a045d295a8aaa).
The issue is not in the latest release, only in nightly/staging.
=> Fix compatibility discrepancy between metrics filter and new expressions

runtime/security.go, runtime/security_test.go, runtime/server/controller.go
When there are some include clauses and none of them match, we end up including all measures/dimensions.
Adding a boolean `ExcludeAll` that is set when some include conditions are present but non are met.
=> Adding security policy when no include clauses match

web-common/src/features/dashboards/workspace/DashboardCTAs.svelte, web-common/src/features/dashboards/workspace/DashboardTitle.svelte
This PR fixes an issue where longer project title names overlap onto the call to action buttons (which are also pushed off the left edge) in the Dashboard header. See below.
Before:
After:
=> fix header title overlap on smaller screen sizes

web-common/src/layout/navigation/Navigation.svelte
This PR hides the `Navigation` sidebar when the browser width drops below 768px. This only happens when the window is being made smaller.
=> hide navbar when browser width drops below 768

web-common/src/components/data-graphic/marks/MultiMetricMouseoverLabel.svelte
In Safari, the inclusion of `whitespace: pre-wrap` appears to cause an issue where the value is placed incorrectly (see below). Removing this appears to maintain the intended placement in all browsers. However, it may have been added to address another visual issue.
=> remove whitespace pre-wrap in MultiMetricMouseoverLabel

runtime/drivers/duckdb/duckdb.go, runtime/queries/metricsview_aggregation.go, runtime/queries/metricsview_aggregation_test.go
Adding timezone to dimension expression seems to break because it adds a query arg. This seems like a bug where `?` is not expanded properly, since manually using timezone instead of `?` works.
For now using numbered group by to fix the issue.
=> Fix aggregation on dimenison with timezone

package-lock.json, tsconfig.json, web-admin/package.json, web-common/orval.config.ts, web-common/package.json, web-common/src/proto/gen/rill/ui/v1/dashboard_pb.ts, web-common/src/runtime-client/add-signal-argument.ts, web-common/src/runtime-client/gen/query-service/query-service.ts
closes #3710
The queries in dashboard are not being cancelled when changing the filters and other settings. This is apparent while using druid or a large project.
We actually call cancel queries. But the orval generated code is not passing on the abort signal to our client. So cancellations are not honoured for these. The root cause is that these queries are POST requests overridden to be queries instead of mutations. This seems to have an edge case in orval of not adding signal properly.
=> Fix POST queries to honour the abort signal

runtime/server/server.go
Include a hostname, localhost, when connecting to the GRPC endpoint.
Fixes bug in which `rill start` fails to start up when a proxy server is configured because rill sends an invalid request to the proxy.  Using mitmproxy, for example, will log the following error when rill tries to connect to the GRPC endpoint using only the port:
Bad HTTP request line: b'CONNECT :49009 HTTP/1.1'
=> Fix Use With Proxy

web-common/src/features/dashboards/selectors/index.ts, web-common/src/features/dashboards/state-managers/state-managers.ts
When we moved to the metrics view query to fetch time range summary, reactivity on metrics view name was missing. This adds it back.
=> Add back reactivity to the metrics view time range summary calls

docs/docs/develop/import-data.md
Adding short primer / section on how to connect to and read from Google Sheets from Rill directly.
=> Document connecting to Google Sheets as a source

web-common/src/features/dashboards/time-series/multiple-dimension-queries.ts
Selecting compare by dimension in the time dimensional table would result in all dimension values getting the same measure value. This was because the filter was getting sent properly.
=> Fixing all dimension values having the same measure value

web-common/src/components/tooltip/MetaKey.svelte, web-common/src/components/virtualized-table/core/Cell.svelte, web-common/src/features/dashboards/dimension-table/DimensionDisplay.svelte, web-common/src/features/dashboards/leaderboard/LeaderboardListItem.svelte, web-common/src/features/dashboards/leaderboard/LeaderboardTooltipContent.svelte, web-common/src/features/dashboards/state-managers/actions/dimension-filters.ts
closes #3848
This adds a simple cmd/ctrl + click handler to leaderboard and dimension table. Doing this on an unselected value will select just that value and deselect everything else. Doing this on a selected value will just deselect it similar to a normal click.
=> Support toggle click in leaderboards to exclusively select a dimension value

runtime/drivers/druid/olap.go
Although `rowsToSchema(rows)` should not return any error in current case but can lead to leaks in future.
=> Runtime: druid close fix

web-common/src/features/dashboards/pivot/PivotSidebar.svelte, web-common/src/features/dashboards/workspace/Dashboard.svelte
This PR removes the bottom margin from the dashboard header to allow the pivot view to display full height. It also changes the sidebar background and border colors to match the latest designs.
=> update dashboard layout to match design system

web-admin/src/routes/-/embed/+page.svelte, web-admin/src/routes/[organization]/[project]/[dashboard]/+page.svelte, web-local/src/routes/(application)/dashboard/[name]/+page.svelte
We are seeing issues with stale data from a previously selected dashbaord. This happens when we switch between 2 dashboards that are already opened (this caches data and updates are immediate). Since `StateManagersProvider` is outside the key the `stateManagers.setMetricsViewName` is run before the update in `metricsViewName` propagates to the key and the underlying dashboard components are swapped. There is a brief moment when components will have newer data in state managers but local data is stale. This can be seen in `Filters.svelte` where we have `activeDimensionName`.
One quick fix is to add the state managers under the key. Another way is to add safeguard everywhere queries are made using data inside a component, but this is not scalable. We should come up with a good fix in the …
=> Add state managers under the key by dash name

web-common/src/features/dashboards/tab-bar/Tab.svelte, web-common/src/features/dashboards/tab-bar/TabBar.svelte
This PR puts the pivot table functionality behind a feature flag, initially controllable via a URL Search Param.
To set this flag, add `?features=pivot` to the URL. The `features` key expects a comma separated list of values.
=> place pivot feature behind flag

web-common/src/features/dashboards/dimension-table/dimension-table-utils.ts
In the previous cleanup PR, dimension table got missed for QA and had incorrect filter applied to it.
=> Fix filter not applying in dimension table

web-common/src/components/button/Button.svelte, web-common/src/components/forms/InputArray.svelte
This PR fixes two issues with the "Add email" button for scheduled reports:
1. The color was dark blue (primary) not white (secondary)
2. The button was squished vertically when its container overflowed
Before:
After:
=> Fix 'Add email' button

web-admin/src/features/navigation/nav-utils.ts, web-admin/src/routes/+layout.svelte, web-common/src/components/calls-to-action/CTALayoutContainer.svelte
A [previous PR](https://github.com/rilldata/rill/pull/3843) caused us to lose the top margin on CTA pages. This PR further cleans up the Cloud layout to ensure aesthetic CTA pages.
Before:
After:
=> Fix CTA layout bug

web-admin/src/features/navigation/nav-utils.ts
The scroll logic in `web-admin/src/routes/+layout.svelte` checks to see if the user is on a dashboard page. Previously, we only checked dashboards at the route `/{org}/{project}/{dashboard}`. With this PR, we additionally check embedded dashboards served from `/-/embed`.
=> Fix scroll on embedded dashboards

web-common/src/features/dashboards/selectors/index.ts, web-common/src/features/dashboards/state-managers/state-managers.ts
Time range summary calls are missing no time dimension safeguard. This leads to a 400 call crashing the app in cloud.
Adding `enabled` field to the time range summary query.
1. Create a dashboard without a `timestamp` defined.
2. On dev there shouldnt be any 400 calls when navigating to the dashboard.
3. On cloud the dashbaord shouldnt crash.
=> Add safeguard to time range summary calls to support dashboards without timestamp columns

cli/cmd/start/start.go
Found this issue while debugging main for margin_metering project. The check for "too many files" uses project path argument as is. No argument should instead use `.` to denote current directory.
=> Fixing rill start without project path argument

web-admin/src/features/projects/ProjectBuilding.svelte, web-common/src/app.css, web-common/src/components/column-profile/ColumnProfileIcon.svelte, web-common/src/features/entity-management/Spinner.svelte, web-common/src/layout/BlockingOverlayContainer.svelte
fixes #3913 
default brand theme:
custom user theme from orange to green
=> fix spinner gradient

web-common/src/features/dashboards/leaderboard/ContextColumnValue.svelte, web-common/src/features/dashboards/leaderboard/LeaderboardHeader.svelte, web-common/src/features/dashboards/state-managers/actions/context-columns.ts, web-common/src/features/dashboards/state-managers/state-managers.ts
like https://github.com/rilldata/rill/pull/3946/files, I think this fixes https://github.com/rilldata/rill-private-issues/issues/112, though I don't have an objective measure.
This PR uses an additional store in `getStateManagers`, but what actually seems to be the thing that does the trick is wrapping the update to that store in a conditional.
=> fix slow leaderboard loads

web-admin/src/features/errors/error-utils.ts, web-common/src/runtime-client/is-runtime-query.ts
[Requested on Slack.](https://rilldata.slack.com/archives/CTZ8XBQ85/p1704812898068369?thread_ts=1704760656.823219&cid=CTZ8XBQ85)
When a dashboard query returns a 400 error:
- Before this PR, we showed a full-screen error page.
- After this PR, the Dashboard component is responsible for handling the error. Specific components, like a Time Series Chart or a Leaderboard, should now display a localized error.
In the future, we can apply the same behavior to more error cases, like 500-level errors. This PR does not include 500-level errors because that'd require more UX thought. When a 500-level error occurs, it's perhaps likely that all queries will fail. When all queries fail, we _should_ show a full-screen error page.
=> Let the Dashboard handle 400 errors

web-common/src/features/dashboards/time-series/MetricsTimeSeriesCharts.svelte
Closes https://github.com/rilldata/rill-private-issues/issues/120
The workflow cited in the issue above triggered the `MeasureChart.svelte` component to render with an `undefined` time grain. That crashed the application.
This PR prevents the time series charts from rendering until the `timeControlsStore` has resolved with a defined `interval`.
=> Fix bug in line charts when the time controls are not ready

web-common/src/app.css, web-common/src/features/dashboards/big-number/MeasureBigNumber.svelte, web-common/src/features/dashboards/leaderboard/LeaderboardHeader.svelte
partial fix of #3907, teeny tweak to colors in a couple places
=> use brand colors for bignum and leaderboard names

web-common/src/components/chip/core/Chip.svelte, web-common/src/components/data-graphic/actions/scrub-action-factory.ts, web-common/src/components/data-graphic/elements/SimpleSVGContainer.svelte, web-common/src/components/forms/InputV2.svelte, web-common/src/features/dashboards/filters/measure-filters/MeasureFilter.svelte, web-common/src/features/dashboards/filters/measure-filters/MeasureFilterMenu.svelte, web-common/src/features/dashboards/filters/measure-filters/measure-filter-options.ts
The purpose of this PR is to convert the `MeasureFilterMenu` and `MeasureFilter` components to ShadCN and improve the UX around validation when adjusting measure filter parameters.
It also solves a bug where the `preventDefault` call on the MeasureChart function prevented the measure filter form from submitting when clicking outside.
Regarding validation UX, the new menu now restores the last previously valid state of the form on close.  If you change the threshold, for instance, from "Less Than" to "Between", the new form fields are no longer valid w/r/t the API. If you dismiss the menu in this state, the last valid state is restored, so you'll see "Less Than" when the menu is reopened. This is to bring consistency between what you see in the Chip (which is always valid w/r/t the API) …
=> convert measure filter dropdown to ShadCN components and resolve validation issues

web-common/src/features/dashboards/config.ts
With some references of old `blue-500` gone, TDD table was showing black lines for the the first selected color. This PR fixes it.
=> Add reference for missing tailwind color

admin/server/deployment.go, admin/server/projects.go, runtime/server/auth/interceptors.go
To make JWT expiration errors less frequent and easier to aggregate in the observability dashboard
=> Improve errors for expired JWTs and increase TTL to 24h

admin/deployments.go
This PR sets models to be materialized by default on cloud. This has successfully improved performance in several deployed projects already.
This is a short term change pending separation of ETL and serving (work ongoing), which will enable smart materialization of only those models that are referenced by a metrics view.
Closes https://github.com/rilldata/rill-private-issues/issues/142
=> Materialize models by default in deployed projects

web-common/src/components/chip/chip-types.ts, web-common/src/features/dashboards/pivot/DragList.svelte, web-common/src/features/dashboards/pivot/PivotChip.svelte, web-common/src/features/dashboards/pivot/PivotHeader.svelte, web-common/src/features/dashboards/pivot/PivotSidebar.svelte, web-common/src/features/dashboards/pivot/PivotTable.svelte, web-common/src/features/dashboards/pivot/TimeDropdown.svelte, web-common/src/features/dashboards/pivot/pivot-data-store.ts, web-common/src/features/dashboards/pivot/pivot-utils.ts, web-common/src/features/dashboards/pivot/types.ts, web-common/src/features/dashboards/state-managers/selectors/pivot.ts, web-common/src/features/dashboards/stores/dashboard-store-defaults.ts, web-common/src/features/dashboards/stores/dashboard-stores.ts, web-common/src/features/dashboards/time-dimension-details/TDDHeader.svelte
This PR adds the initial code necessary for supporting time granularity in the pivot table.
- Changes row/column data structure in the pivot store
- Removes related utils from pivot-utils
- Adds selectors for rows and columns
- Changes setPivotRows and setPivotColumns function to match new structure
- Adds a new PivotChip component to wrap Chip
- Displays a dropdown menu (not fully styled) for time pills in the pivot header
- Does not support adding multiple time pills (requires more API work)
=> initial time grain support for pivot table

web-common/src/features/dashboards/pivot/pivot-data-store.ts
Fixes an issue where time pills were not being properly transformed when added as a parameter to the pivot table rows.
=> fix: enable time for pivot rows

web-common/src/features/dashboards/pivot/pivot-data-store.ts, web-common/src/features/dashboards/pivot/pivot-expansion.ts, web-common/src/features/dashboards/pivot/pivot-queries.ts, web-common/src/features/dashboards/pivot/types.ts
Treating aggregation as timeseries and sending in `ResolvedMeasureFilter` to all the queries fired in pivot queries.
=> Pass through measure filters to pivot queries

web-common/src/features/dashboards/pivot/pivot-column-definition.ts
If measure name or dimension name had a dot in it ex - `dimension.property.extensions`, tanstack table would interpret as accessing a nested structure. This PR fixes it so that dot can be present in name.
Example of failed case - 
Reproduction steps -
- Edit yaml spec and add dot in the name of a dimension
- Create pivot using that dimension
=> Fix accessor with dot in name

web-common/src/features/dashboards/pivot/PivotDisplay.svelte, web-common/src/features/dashboards/pivot/PivotEmpty.svelte
Instead of displaying the "lonely" svg, add a placeholder for when pivot table data is being fetched.
https://github.com/rilldata/rill-private-issues/issues/150
=> Placeholder for when pivot is fetching

web-common/src/features/dashboards/pivot/pivot-utils.ts
Updates the cache map key. Included measure filter string in the key. 
Changing measure filter would now re-fetch table data instead of keeping stale data.
=> Update key for pivot table cache

web-common/src/features/dashboards/pivot/pivot-column-definition.ts
The accessor for measures in the pivot table right now are broken. Use `accessorKey` instead of `accessorFn` for measures.
=> Fix: Select correct accessor for measures

web-common/src/components/button/Button.svelte, web-common/src/features/dashboards/pivot/AddField.svelte, web-common/src/features/dashboards/pivot/DragList.svelte, web-common/src/features/dashboards/pivot/PivotDrag.svelte, web-common/src/features/dashboards/pivot/PivotHeader.svelte, web-common/src/features/dashboards/pivot/PivotSidebar.svelte, web-common/src/features/dashboards/state-managers/selectors/pivot.ts, web-common/src/features/dashboards/stores/dashboard-stores.ts
This PR adds a button to the pivot columns and rows drag lists that allows the user to select pivot fields via dropdown. To support this, the dimension and measure aggregators have been moved to the pivot selectors.
=> Add button for selecting pivot fields via dropdown

tsconfig.json
Upon upgrading some dependencies in #3999, I started to get these errors:
This PR updates the root `.tsconfig`'s `lib`, `module`, and `target` to use `esnext`. FWIW, this is the same configuration as in SvelteKit's `.tsconfig`, and it'd be nice to converge.
=> Use `esnext` (as does SvelteKit's `tsconfig.json`)

.github/workflows/web-test-code-quality.yml
will make it easier to remove individual files when cleaning them up
related to https://github.com/rilldata/rill/issues/3424
=> ignore single in svelte-check files rather than folders

cli/cmd/root.go, cli/pkg/printer/printer.go, go.mod, go.sum
**Usage** 
use `--format [csv,json,tsv]` with any command and output will be in required format, Better usecase would be to use this flag for **list** commands where we expected couple of rows
=> Added output format flag for CSV, TSV or JSON output for all commands

web-common/src/features/dashboards/pivot/PivotToolbar.svelte
Hide expand visible button until we have a way to get `lowestVisibleRow` value.
Post styling and virtualization we can use [rangeExtractor](https://tanstack.com/virtual/v3/docs/api/virtualizer#rangeextractor) from `tanstack-virtual` to get render indices and derive `lowestVisibleRow`.
=> Hide expand visible button in Pivot view

web-common/src/features/dashboards/stores/DashboardStateProvider.svelte
Just after opening a dashboard with a url state that has non-default time range selected, changing the time grain for the 1st time will reset the time range to the default time range.
This is because there is a delay in url state applying to the dashboard store. This PR makes sure that the url state is loaded as soon as the store is created.
1. Go to a dashboard.
2. Select a different time range.
3. Refresh the page.
4. Change the time grain.
5. Time range should not be reset.
=> Fix delayed dashboard url state load

web-common/src/features/dashboards/filters/measure-filters/measure-filter-utils.ts
partially addresses #3980
Since measure filters make a frontend query instead of a subquery in the backend we can face issues with not all values being included since there is a limit on the query result.
This PR makes this consistent by adding a sort to the toplist query used to fetch the results. The correct solution would be a backend sub query.
=> Fix measure filter being inconsistent with certain data sets.

web-admin/src/features/authentication/AuthRedirect.svelte, web-admin/src/features/authentication/AvatarButton.svelte, web-admin/src/features/navigation/Breadcrumbs.svelte, web-admin/src/features/organizations/active-org/OrganizationRedirect.svelte, web-admin/src/features/organizations/active-org/local-storage.ts, web-admin/src/features/organizations/activeOrg.ts, web-admin/src/routes/+page.svelte
PR https://github.com/rilldata/rill/pull/3787 introduced the concept of an "active" org to the Cloud UI. Navigation to the homepage will redirect to the active `/{org}` page. The active org is stored in local storage.
This PR stores the "active org" on a per-user basis: `activeOrg_{userID}`. This accounts for a bug  where `rill sudo user open` navigated to the wrong organization.
Closes https://github.com/rilldata/rill-private-issues/issues/133
=> Cloud UI: fix `rill sudo user open`

web-admin/src/routes/-/auth/device/+page.svelte
This page wasn't correctly wrapped in our "CTA" components.
Before:
After:
=> Fix layout on `/-/auth/device` page

runtime/queries/metricsview_aggregation.go
- Application sends `Etc/UTC` instead of `UTC`
- Remove extra parentheses in `time_floor` function which causes query to fail
=> Fix issues with mv agg query

web-common/src/components/button/Button.svelte, web-common/src/components/tag/Tag.svelte, web-common/src/features/dashboards/filters/Filters.svelte, web-common/src/features/dashboards/tab-bar/Tab.svelte, web-common/src/features/dashboards/tab-bar/TabBar.svelte, web-common/src/features/dashboards/workspace/Dashboard.svelte
The purpose of this PR was to simply add a `Beta` tag to the Pivot tab on the dashboard, but turned into one that refactors the Dashboard tab component with native functionality instead of extending headless-ui, whose limited functionality was presenting some issues. Additionally, this PR solves some layout oversights in the header component.
=> Update dashboard header layout and tab component

web-common/src/features/dashboards/pivot/PivotExpandableCell.svelte, web-common/src/features/dashboards/pivot/pivot-column-definition.ts
If one of the values of a dimension is "" (empty string), the app would crash. This PR adds a label `<empty string>` for such cases.
=> Fix: Add label for empty string in column header

web-common/src/features/dashboards/pivot/pivot-data-store.ts
For dashboards of larger size, it might be a few seconds until we have data from `metricsView` query. `getPivotConfig` returns an empty config until then.
For those cases, we want to show a spinner as well.
=> Enable fetching state for larger dashboards

web-common/src/features/dashboards/state-managers/selectors/dashboard-queries.ts
Not a 100% sure when this broke, but if we have a measure hidden but it is selected as the leaderboard measure dimension display breaks. This is because we call sort on the selected leaderboard measure without actually selecting it in the query.
Sending all relevant measures to the query so that the app doesnt crash.
=> Send all relevant measures to dimension display query

web-common/src/features/dashboards/state-managers/selectors/pivot.ts
This PR removes the filtering of the measures and dimensions based on the visibility in the dashboard.
=> Remove pivot field filtering based on dashboard visibility

web-common/src/features/dashboards/pivot/DragList.svelte, web-common/src/features/dashboards/pivot/PivotDrag.svelte, web-common/src/features/dashboards/pivot/PivotSidebar.svelte
This PR filters out available time grain options from the pivot sidebar as they are added to the table. It also adds some placeholder text when no fields are available and resolves a layout issue when there are more pills in the column/row component than can fit in the browser width.
=> Filter time grain options in pivot sidebar based on table state

runtime/drivers/snowflake/sql_store.go
This should work correctly for most cases except timestamps with very high precision that cannot fit into `arrow.Timestamp`
Closes #4079
=> No need in additional context for timestamps of Snowflake

proto/rill/ui/v1/dashboard.proto, web-common/src/features/dashboards/proto-state/fromProto.ts, web-common/src/features/dashboards/proto-state/toProto.ts, web-common/src/proto/gen/rill/ui/v1/dashboard_pb.ts
Row time dimensions was missing from url state.
Adding a new field to the proto and code to serialise/deserialise row time dimensions.
=> Persist row time dimensions in url state

web-common/src/features/dashboards/pivot/PivotTable.svelte
This PR adds row based virtualization to the pivot table. Column virtualization will be added separately.
TanStack's virtualization library and flexRenderer are not performant enough for our use case and will need to be replaced.
=> Add row based virtualization to pivot table

web-common/src/features/welcome/WelcomePageRedirect.svelte
PR https://github.com/rilldata/rill/pull/4027 introduced a bug that resulted in a blank Welcome page for new DuckDB-backed projects. This PR fixes that bug.
=> Fix blank welcome screen

web-common/src/features/dashboards/pivot/pivot-data-store.ts
For cases where we have column dimensions and row dimension without any measures, the table view shows a fetching spinner. We should instead show the empty state for now
=> Fix invalid fetching state

docs/docs/install.md
We should also call out how the install script can be used to install a specific version of Rill
=> Adding steps for specific version install

web-common/src/features/entity-management/resource-invalidations.ts, web-common/src/features/tables/TableAssets.svelte
Closes #4085
Additionally, fixes a bug where deleting a source or model would reveal its old underlying table in the sidebar.
=> Fix two bugs in Tables list

web-common/src/features/welcome/ProjectCards.svelte, web-common/src/layout/BasicLayout.svelte
A recent PR caused navigation to `/welcome/` rather than `/welcome`. It's unclear why navigation to this route now includes the trailing slash (especially given [SvelteKit's default](https://kit.svelte.dev/docs/page-options#trailingslash) is to never include trailing slashes). However, this PR protects against the trailing slash in two places:
- Logic to show/hide the left-hand sidebar
- Links to example project dashboards
=> Fix Welcome page navigation bugs

web-common/src/features/dashboards/pivot/pivot-column-definition.ts
Headers with value `false` were crashing the app. This PR enables use of any non string header values for the pivot table.
=> Fix: Support all non string headers

web-common/src/components/chip/core/Chip.svelte, web-common/src/components/chip/core/RemoveChipButton.svelte, web-common/src/features/dashboards/pivot/PivotChip.svelte
Removes tooltip from Pivot chips and adds a prop to suppress tooltips in chip component.
=> Fix: Remove tooltip from Pivot chips

web-common/src/features/dashboards/pivot/PivotTable.svelte
The table scroll position would reset to 0 when expanding a row item after scrolling a bit further down the table. This PR adds `scrollOffset` to the `virtualizer` to avoid such cases during a state change.
=> Fix: Scroll to previous position in the table on expansion

admin/server/deployment.go
This is not used by UI, that uses correct kind as it knows that its a dashboard but better to have correct string.
=> fix kind string

.github/workflows/web-test-code-quality.yml
svelte-check was updated recently and a lot more files that havent changed recently are failing. This disabled it for now to unblock other devs.
=> Disable svelte check for a few files

web-common/src/features/dashboards/pivot/PivotTable.svelte
This PR updates the styling of the leftmost column when a table without row dimensions are being displayed. Previously, in this scenario, non-total columns were being pinned and styled to look like "header" columns, which this PR now fixes.
=> Update styling for tables without row dimensions

web-admin/src/features/projects/selectors.ts, web-admin/src/features/view-as-user/clearViewedAsUser.ts, web-admin/src/features/view-as-user/setViewedAsUser.ts, web-common/src/features/dashboards/granular-access-policies/updateDevJWT.ts, web-common/src/features/dashboards/stores/dashboard-stores.spec.ts, web-common/src/runtime-client/RuntimeProvider.svelte, web-common/src/runtime-client/constants.ts, web-common/src/runtime-client/http-client.ts, web-common/src/runtime-client/runtime-store.ts, web-common/src/runtime-client/watch-request-client.ts
Closes #3876
This PR ensures a fresh JWT before firing requests to a Runtime server. This helps avoid the race condition mentioned in the above issue.
This PR assumes a runtime access token TTL of 30 minutes. So when this PR is merged, we'll be ready to merge https://github.com/rilldata/rill/pull/4058.
=> Fix race condition for expired JWTs

web-common/src/features/alerts/CreateAlertDialog.svelte, web-common/src/features/alerts/criteria-tab/CriteriaForm.svelte
Options like selected measure and dimension can be pre-filled from the dashboard settings.
=> Prefil alert options from the underlying dashboard

docs/docs/integration/embedding.md
Changes the embedding docs page to:
- Mention the new end-to-end embedding example on https://github.com/rilldata/rill-embedding-example 
- Incorporate learnings/bugfixes from building the embedding example
=> Incorporate embedding example in docs; other embedding fixes

web-common/src/components/forms/Select.svelte, web-common/src/features/alerts/data-tab/AlertDialogDataTab.svelte
This PR:
- Adds an `optional` prop to our `Select` form element
- Uses this `optional` prop for two elements in the Alert form: "Split by dimension" and "Split by time grain"
=> Make a couple items in the Alert form optional

web-admin/src/routes/-/embed/+page.svelte
This PR makes it possible to add a custom theme to an embedded dashboard. Now, adding the `theme` query parameter to to an iframe URL will correctly propagate the custom theme to your embed.
Example iframe URL: `https://ui.rilldata.com/-/embed?access_token=<access_token>&instance_id=<instance_id>&kind=rill.runtime.v1.MetricsView&resource=<dashboard_name>&runtime_host=<runtime_host>&theme=<my_theme>`
=> Enable custom themes for embedded dashboards

web-common/src/app.css, web-common/src/features/dashboards/big-number/MeasureBigNumber.svelte, web-common/src/features/dashboards/leaderboard/LeaderboardHeader.svelte
This PR reverts the default header color of the BigNumber and Leaderboard components to `slate-600`, displaying the UI primary color only on hover.
=> Revert Leaderboard/BigNumber header color to slate-600

web-common/src/features/dashboards/workspace/Dashboard.svelte, web-common/src/features/feature-flags.ts
This PR enables the Data Viewer in Rill Cloud when a user appends their URL with `?features=data-viewer`.
=> Add feature flag to enable the Data Viewer in Rill Cloud

web-common/src/features/dashboards/pivot/PivotExpandableCell.svelte, web-common/src/features/dashboards/pivot/PivotTable.svelte
Restricts the width of the first column in the pivot table. Previously, long strings would cover the whole screen. This PR adds a max width of `500px` for the first column.
Before
After
=> Restrict width of the first column

web-common/src/features/dashboards/pivot/pivot-data-store.ts
The top level pivot config was depending on dashboard store 3 times. One directly, another through time controls and last one through measure filter resolutions.
This PR updates it to be just once. Time controls and measure filter resolutions are computed directly from the resolved dashboard state.
=> Fix multiple updates of pivot state leading to cancelled requests

web-common/src/components/data-graphic/elements/SimpleSVGContainer.svelte, web-common/src/features/dashboards/time-series/MeasureScrub.svelte
Fixes #3936
The `role=button` was overriding the cursor class passed to the SVG element.
=> Fix cursor when hovering over scurb area

scripts/tsc-with-whitelist.sh, web-common/src/features/dashboards/state-managers/memoize-metrics-store.ts
Updating the whitelist script to check by file _and_ TS code. This will prevent newTS errors from entering the codebase unless there is already an error with the same error code in the updated file. The whitelist can be gradually tightened as the codebase improves.
=> update tsc checks to filter by file and TS error code

.github/workflows/web-test-code-quality.yml
A recent PR regenerated our `package-lock` and led to `svelte-check` picking up new Typescript errors. This PR temporarily adds those files to the `svelte-check` `--ignore` list, so our lint checks will pass.
We should follow this PR with another that fixes the offending files and removes them from the `--ignore` list.
=> Temporarily ignore files in `svelte-check`

runtime/queries/metricsview.go, web-admin/src/features/alerts/history/AlertHistoryStatusChip.svelte, web-admin/src/features/alerts/history/AlertHistoryTable.svelte, web-admin/src/features/alerts/history/AlertHistoryTableCompositeCell.svelte, web-common/src/components/tag/Tag.svelte
Improvements:
- Updated chip copy to match mocks
- Added error text in case of a Failed execution
- Refactored the `AlertHistoryStatusChip` to use our `Tag` component
Some examples:
=> Improve Alert History table

web-common/src/features/dashboards/big-number/MeasureBigNumber.svelte
This PR prevents the measure number from overflowing its container, regardless of the output of measureValueFormatter.
=> Prevent measure number from overflowing container

package-lock.json, web-admin/package.json, web-auth/package.json, web-local/package.json
Visiting either dev or cloud UIs would add an additional forward slash. This lead to issues in dashboard where state url was not getting applied. Also caused in certain redirects like alerts.
This was caused by a bug in sveltekit. We should ideally upgrade to 2.0.1 to get this fixed. But for now pinning to the last version where this is not broken, 1.30.0.
1. After starting either dev or cloud UIs, visit the page from `http://localhost:3000`
2. Navigating to different page shouldnt add the forward slash.
3. In dashboard the stateful url should get populated.
=> Pin sveltekit to 1.30.0 temporarily

admin/server/auth/middleware.go, admin/server/runtime_proxy.go, admin/server/server.go, runtime/pkg/observability/middleware.go
- Adds a runtime proxy endpoint on the admin service
- Requests made to `{admin host}/v1/orgs/{org}/projects/{project}/runtime/{path...}` are proxied to `{runtime host}/v1/instances/{instanceID}/{path...}`
- Authentication logic:
- If the request is made using an authentication mechanism recognized by the admin service (i.e. browser cookie or service bearer token), the admin service checks permissions and issues an ephemeral JWT similar to the one that could be obtained by calling `GetDeploymentCredentials`.
- If the request is made using an `Authorization` header that the admin service doesn't recognize (e.g. a previously issued runtime JWT), the contents are directly proxied in the runtime request
- If no authentication mechanism is used, the request is proxied without any …
=> Runtime proxy on the admin service

admin/server/server.go
Looks like having `SameSite=Strict` breaks the redirect flow from Auth0 because the `state` nonce that we set in a cookie becomes unavailable.
Setting `SameSite=Lax` should be fine since it still disallows passing cookies on cross-site requests.
=> Admin: Set cookies to Lax

.github/workflows/go-cover.yml, Makefile
The coverage test has been failing for some time with the following errors:
```
github.com/rilldata/rill/proto/gen/rill/admin/v1: open /tmp/go-build1717652986/b205/covmeta.efd544d54abd57024320e5b09e7fbb7333ec3c9e2c058a3d351094eaca3dd4d6: no such file or directory
github.com/rilldata/rill/proto/gen/rill/runtime/v1: open /tmp/go-build1717652986/b324/covmeta.067b3bf4a6ecbbbcd442d5d3dfcb816dbf6bc1aee18591e902bf98c6b115f2e7: no such file or directory
```
This appears to be a bug in Go that can be resolved by setting `GOEXPERIMENT=nocoverageredesign`.
This issue may provide guidance on when the change can be reverted: https://github.com/golang/go/issues/55953.
=> Fix Go coverage

admin/server/auth/handlers.go, admin/server/deployment.go, admin/server/github.go, admin/server/runtime_proxy.go, admin/server/server.go, runtime/pkg/httputil/httputil.go, runtime/pkg/middleware/request.go, runtime/pkg/observability/httpmux.go, runtime/server/server.go
Example:
```go
// Can do this:
return httputil.Errorf(http.StatusBadRequest, "runtime proxy not available for owner type %q", claims.OwnerType())
// Instead of this:	
http.Error(w, fmt.Sprintf("runtime proxy not available for owner type %q", claims.OwnerType()), http.StatusBadRequest)
return
```
Also includes a few other minor cleanups.
=> Util for better HTTP error handling

web-common/src/features/dashboards/time-dimension-details/TimeDimensionDisplay.svelte, web-common/src/features/dashboards/time-dimension-details/time-dimension-data-store.ts, web-common/src/features/dashboards/time-series/timeseries-data-store.ts
Partially fixes #4188
This checks for error in the timeseries data store and propagates that to the TDD table. 
We do not currently check for error on the individual timeseries API which is called for each row of the TDD table. Since we are planning to move away from individual timeseries API to a batch aggregation API, will add the error handling directly there.
=> Handle API error for timeseries

web-common/src/features/dashboards/pivot/PivotTable.svelte
https://rilldata.slack.com/archives/C02T907FEUB/p1709162281494139
Fixes the direction of the arrow in the pivot table. Descending order should have a downward facing arrow.
=> Fix: Pivot arrow direction

web-common/src/features/dashboards/rows-viewer/RowsViewerAccordion.svelte
We enabled the data viewer via feature flags via https://github.com/rilldata/rill/pull/4158
However the export option still checked for local, removed that so the entire component is toggled via feature flags.
=> fix: export dialog visible with feature flag

cli/pkg/local/app.go
When rill-dev is run in offline mode, we get lot of failure info logs.
```
{"level":"info","ts":1708516890.8632698,"msg":"failed to send telemetry{error 26 0  Post \"https://intake.rilldata.io/events/data-modeler-metrics\": d
ial tcp: lookup intake.rilldata.io: no such host}"}
```
=> Move telemetry failure logs to debug

runtime/compilers/rillv1/parse_node.go, runtime/compilers/rillv1/parser.go
Closes issue reported [here](https://rilldata.slack.com/archives/CTZ8XBQ85/p1709530154230399?thread_ts=1708474022.726509&cid=CTZ8XBQ85)
=> Runtime: Support dots in YAML/SQL filenames

web-common/src/components/button/Button.svelte
This PR updates the Button component with a new `href` prop. When passed, the element will be rendered as an `<a>` tag rather than a `<button>`.
=> Render Button component as a tag when passed an href prop

web-admin/src/features/errors/error-utils.ts
In testing https://github.com/rilldata/rill/pull/4227, I found that the rows viewer can trigger a 429 error. We should not block Cloud dashboards with this error.
=> Cloud UI: Don't block dashboards on 429 errors

runtime/drivers/clickhouse/information_schema.go, runtime/drivers/clickhouse/olap.go
1. Although not clear from the clickhouse docs but underlying type in `LowCardinality` type can also nullable. 
2. We actually don't need `is_nullable` from `information_schema.columns` since any nullable type in clickhouse is expected to be of form `Nullable(x)` so removed its usage.
=> Runtime: Handle clickhouse LowCardinality nullable types

runtime/drivers/file/watcher.go
Ran into an error where the watcher stopped because `Rel` received an empty target path:
```
{"level":"error","ts":1709713441.4184802,"msg":"Stopped watching for file changes","instance_id":"default","error":"watch failed: Rel: can't make  relative to /Users/benjamin/Documents/foo"}
```
Can't think of anything else that could have caused it than `fsnotify` emitting an empty event.
=> Runtime: gracefully handle weird watcher issue

web-common/src/features/dashboards/proto-state/toProto.ts
Removes expanded state from proto. A number of bugs were coming up because we don't yet support recursive, asynchronous, derived store based API calls yet. Once we have that it, we can revert this back.
=> Remove Pivot expanded state from proto

web-common/src/features/metrics-views/workspace/editor/MetricsEditor.svelte
Removes redundant statement. Reconcile errors are already present in line errors.
=> Remove redudant reconcile error in editor

web-admin/src/features/projects/status/ResourceErrorMessage.svelte
Error messages on the status page are truncated after two lines:
This PR adds a tooltip that contains the full error message:
=> Cloud UI: add a tooltip to show full error messages on the Status page

runtime/drivers/duckdb/olap.go, runtime/drivers/duckdb/olap_crud_test.go
The issue is that at lot of places we look at `information_schema` `lookup` on main db to determine whether tbl is a view or table. For external table storage, it will always resolve to view so in cases when external table storage is enabled we need to check if its a true view or a view on top of externally stored table.
=> Runtime: drop table fix for external table storage

web-common/src/features/onboarding/OnboardingWorkspace.svelte, web-common/src/layout/workspace/Inspector.svelte, web-common/src/layout/workspace/WorkspaceContainer.svelte, web-local/src/routes/(application)/dashboard/[name]/+page.svelte
This PR is an intermediary step on the way to removing the manual tween and layout calculations used across the application, but also solves some UI issues along the way.
In essence, this changes the WorkspaceContainer so that elements/components passed via the "body" slot behave as expected w/r/t flex layout and scroll behavior without needing to accommodate for the header height. It also alters some type annotations and properly connects the `inspector` prop to element rendering by removing the `hasInspector` variable.
=> Update workspace container

package.json, web-local/package.json
The declaration of the `PLAYWRIGHT_TEST` environment variable was not being captured during the test-invoked CLI build process, preventing AI features from being disabled during local testing.
=> Fix: Placement of environment variable declaration

package.json, web-common/src/components/searchable-filter-menu/SeachableFilterButton.svelte, web-common/src/features/dashboards/leaderboard/LeaderboardControls.svelte, web-local/package.json, web-local/tests/dashboards/dashboards.spec.ts, web-local/tests/dashboards/dimension-and-measure-selection.spec.ts, web-local/tests/dashboards/leaderboard-and-dim-table-sort.spec.ts, web-local/tests/dashboards/leaderboard-context-column.spec.ts, web-local/tests/dashboards/number-formatting.spec.ts
See #4286 first
This PR makes a variety of related changes and improvements to our end-to-end dashboard tests.
- Adds more descriptive aria-labels to the dropdown menus and uses those to locate the elements
- Adds assertions that the text value of those elements has changed rather than attempting to locate them by the text value, which `getByRole` is not intended for
- Adds appropriate locator actions to wait for menu visibility to change (should improve test stability on different platforms)
- Adds wrapper helper functions for selecting menu items
- Closes menus explicitly via the escape key when necessary
Finally, the `leaderboard-context-column` test was repeatedly closing a menu that closed automatically, meaning it was actually re-opening the menu. Somehow, the test was still …
=> Tests: locator and clarity tweaks

runtime/compilers/rillv1/parse_node.go, runtime/compilers/rillv1/parse_rillyaml.go
- This PR adds shorthands for configuring environment-specific overrides for the `dev` and `prod` environments.
- This saves one level of nesting for configuring our two primary environments.
- The shorthands work in both individual YAML files and for `rill.yaml`.
- We still support the current `env:environment_name:` syntax. This keeps environment-specific overrides available for custom environments.
Examples:
```yaml
connector: s3
path: s3://bucket/**/*.parquet
dev:
path: s3://bucket/year=2024/month=01/**/*.parquet
prod:
models:
materialize: true
```
=> Runtime: shorthands for configuring "dev" and "prod" envs

web-common/src/features/dashboards/time-series/TimeSeriesChartContainer.svelte
TimeSeries chart container was taking up the available space rather than limiting itself to the width of its children.
=> Fix: timeseries chart container spacing

web-common/src/features/dashboards/time-series/ChartInteractions.svelte
Pressing left or right arrow while in an input field such as measure threshold, dimension search in comparison would pan the charts. We want to disable key event actions when on an input field.
1. Add a measure filter
2. Use the left and right arrows while in the input field
3. The charts should not pan
=> Fix: Disable chart keydown ops on input fields

web-common/src/features/generic-yaml-editor/YamlWorkspace.svelte, web-common/src/features/generic-yaml-editor/YamlWorkspaceHeader.svelte, web-common/src/features/metrics-views/workspace/MetricsWorkspace.svelte, web-common/src/features/models/workspace/ModelBody.svelte, web-common/src/features/models/workspace/ModelWorkspace.svelte, web-common/src/features/models/workspace/ModelWorkspaceHeader.svelte, web-common/src/features/onboarding/OnboardingWorkspace.svelte, web-common/src/features/sources/workspace/SourceWorkspace.svelte, web-common/src/features/sources/workspace/SourceWorkspaceBody.svelte, web-common/src/features/tables/TableWorkspaceHeader.svelte, web-common/src/layout/Resizer.svelte, web-common/src/layout/workspace/HorizontalSplitter.svelte, web-common/src/layout/workspace/Inspector.svelte, web-common/src/layout/workspace/WorkspaceContainer.svelte, web-common/src/layout/workspace/WorkspaceEditorContainer.svelte, web-common/src/layout/workspace/WorkspaceHeader.svelte, web-common/src/layout/workspace/WorkspaceTableContainer.svelte, web-common/src/layout/workspace/workspace-stores.ts, web-local/src/routes/(application)/chart/[name]/+page.svelte, web-local/src/routes/(application)/dashboard/[name]/+page.svelte, web-local/src/routes/(application)/table/[name]/+page.svelte
This PR refactors the process by which we store, update and render the various layout parameters associated with a workspace to improve rendering performance and, hopefully, simplify the DX around how all of this works.
To that end, the following changes were made:
-Remove the use of context to pass around layout parameters
-Create new `WorkspaceLayout` and `Workspaces` stores using our new state management model
-Rely on CSS/Svelte transitions to animate in/out panel sliding rather than manual tween calculations
-Add a new `Resizer` component
-Collect the table and inspector state into a single localStorage item
-Debounce updating localStorage when state changes
This should solve a variety of UI responsiveness issues when interacting with these surfaces (e.g. toggling the panels should …
=> Refactor workspace layout

cli/pkg/cmdutil/helper.go, runtime/pkg/activity/event.go, runtime/pkg/middleware/activity.go, runtime/server/generate_metrics_view.go
Closes https://github.com/rilldata/rill-private-issues/issues/186
=> Telemetry for success/failure of AI-based metrics view generation

web-common/src/features/onboarding/OnboardingWorkspace.svelte, web-common/src/features/sources/modal/AddSourceModal.svelte, web-common/src/features/sources/modal/DuplicateSource.svelte, web-common/src/features/sources/modal/add-source-visibility.ts, web-common/src/features/sources/navigation/SourceAssets.svelte, web-common/src/features/welcome/TitleContent.svelte, web-common/src/layout/RillDeveloperLayout.svelte
This PR moves the duplicate source modal flow from its own dedicated component into the `AddSourceModal` component.
Previously, these concerns were separated in a way that caused UI issues, as seen below.
Blocker for #4216 
Before:
After:
=> Rework duplicate source modal

web-common/src/features/dashboards/stores/dashboard-stores.ts, web-common/src/features/dashboards/time-series/ChartInteractions.svelte
Pressing cmd/alt + left/right keys for navigation also updates time range because of chart panning. This interferes with history navigation of the browser and url state restoring.
This PR disables chart pan when cmd/alt key is pressed.
=> Disable chart pan on cmd/alt + arrow key

web-common/src/features/dashboards/stores/dashboard-store-defaults.ts
`default_comparison => dimension` , `default_dimensions` and `default_measures` were doing an exact check. But dimension and measure names are case insensitive.
Making sure we do a case insensitive check when we load the default dashboard config.
=> Make dimension/measure in dashboard config insensitive

runtime/pkg/duckdbsql/ast_rewrite.go, runtime/pkg/duckdbsql/ast_test.go, runtime/pkg/duckdbsql/ast_traversal.go, runtime/pkg/duckdbsql/ast_values.go, runtime/pkg/duckdbsql/corrections.go, web-common/src/layout/RillDeveloperLayout.svelte
A query like this was erroring out,
```
select * from read_parquet('data/sales_data_more_variability_aggregated.parquet') USING SAMPLE 10%
```
This is because json format wont retain `.0`. This leads to a json like this,
```
"sample": {
"sample_size": {
"type": {
"id": "DOUBLE",
"type_info": null
},
"is_null": false,
"value": 10 // Since this doesnt have a `.0` duckdb seem to assume it is uint
},
"is_percentage": true,
"method": "System",
"seed": -1
},
```
We need to change the `type.id` and match the type.
=> Fix format of ducksql sample select query

web-common/src/components/icons/connectors/AmazonRedshift.svelte
=> Redshift logo color fix

web-admin/src/features/navigation/BreadcrumbItem.svelte, web-admin/src/features/navigation/Breadcrumbs.svelte
In the Org Breadcrumb's call to `ListOrganizations`, we have not yet set a specific page size. The page size defaults to 20. This PR explicitly sets a page size of 100.
Further, to accommodate many results, this PR adds a maximum height and scrollbar to the Breadcrumb dropdown menus.
This is a quick fix. In the future, we can add a search box and/or lazy loading for large lists (including in the project and dashboard breadcrumbs).
=> Cloud UI: handle more than 20 orgs in the Org Breadcrumb's dropdown menu

web-common/src/components/editor/theme.ts
Increase the code editor font-weight from default(400) to 500
More - https://rilldata.slack.com/archives/C04JP568RR6/p1710153070240849
=> Style: Increase code editor font weight

runtime/reconcilers/util.go, runtime/resolvers/metrics_sql.go, runtime/resolvers/metrics_sql_test.go, runtime/testruntime/testdata/ad_bids/apis/mv_sql_policy_api.yaml, runtime/testruntime/testdata/ad_bids/apis/simple_mv_sql_api.yaml, runtime/testruntime/testdata/ad_bids/apis/templated_mv_sql_api.yaml, runtime/testruntime/testdata/ad_bids/dashboards/ad_bids_mini_metrics_with_policy.yaml
1. Adds support for dimension expressions in metrics_sql
2. Joins are not supported
3. User defined aliases or shorthand notations are not supported. The rewritten sql will have the alias same as the dimension and measure.
4. Alias for dimension and measure is not supported but can be added if required.
=> Runtime: Add support for dimension expressions in metrics_sql

runtime/drivers/duckdb/config.go, runtime/drivers/duckdb/olap.go, runtime/drivers/duckdb/olap_crud_test.go
Usage:
```bash
rill start dev-project --var connector.duckdb.log_queries=true
```
Note that it will only log queries passed to the OLAP interface. Internal queries (such as migrations and information schema queries) will not be logged.
=> Runtime: Add log_queries config key to DuckDB driver

web-common/src/features/tables/TableAssets.svelte, web-common/src/features/tables/selectors.ts
We've had a race condition: sometimes deleting a source or model triggers the underlying table to show up in the sidebar's Tables list. This PR fixes this race condition.
[Bug report in Slack](https://rilldata.slack.com/archives/CTCJ58H3M/p1709759539842889)
=> Fix race condition in Tables list

web-common/src/features/dashboards/pivot/pivot-data-store.ts, web-common/src/features/dashboards/pivot/pivot-queries.ts, web-common/src/features/dashboards/pivot/pivot-table-transformations.ts, web-common/src/features/dashboards/pivot/pivot-utils.ts
Fixes #4338
The initial row query (rowDimensionAxisQuery) when called with measure filters would only return measure totals with the applied filter.
To fix this, we have another query through which we get the totals for all measures and place them in the order defined by the first row query.
=> Fix: Pivot row totals data inconsistency

web-common/src/features/tables/TableAssets.svelte
Bugfix follow-up to #4337 
We need to actually call the debounced function.
=> Bugfix follow-up to #4337

docs/docs/reference/templating.md
Closes https://github.com/rilldata/rill-private-issues/issues/215
=> Docs: Document when `{{ ref ... }}` tags are needed when using templating

runtime/queries/resource_watermark.go, runtime/queries/resource_watermark_test.go, runtime/reconcilers/alert.go
Also includes some minor comment and logging improvements in the alerts reconciler.
Closes https://github.com/rilldata/rill-private-issues/issues/198.
=> Alerts: Fix data at watermark boundary is excluded

web-common/src/features/dashboards/proto-state/dashboard-url-state.ts, web-common/src/features/entity-management/resource-invalidations.ts
closes #3955
Using `URL::searchParams` and `URL::toString` does the encoding for us. So an additional encoding is not necessary.
=> Encode dashboard url state only once

runtime/drivers/file/file.go, runtime/drivers/file/repo.go, runtime/drivers/file/watcher.go
It seems like my last fix here did not make this issue go away: https://github.com/rilldata/rill/pull/4254.
I'm not able to reproduce the issue, but saw it again.
Adding a warning log for it to get more contextual information for next time I see it...
=> Add debug log for weird file watcher error

docs/docusaurus.config.js
Adding a link to the Rill blog in the top navigation header
=> docs: adding blog to header

docs/docs/build/connect/source-refresh.md
Refactoring the intro as configuring the sources does not have to be done after deploying a project to Rill Cloud (and to generalize it a bit so it belongs under the `sources` section). Furthermore, making some clear distinctions about when to configure source refresh in Rill Developer vs Rill Cloud, plus some other minor cleanup.
=> Update source refresh page to align with new docs structure

admin/admin.go, admin/metrics.go, admin/metrics/client.go, admin/worker/run_autoscaler.go, admin/worker/worker.go, cli/cmd/admin/start.go
This is a prototype PR that makes the admin service capable of querying custom APIs on the https://github.com/rilldata/rill-cloud-metrics project.
This enables dogfooding Rill for various analytics use cases, such as autoscaling, health checks, quota enforcement, usage-based billing, etc.
Setting a metrics project is optional. If not set, the admin service will still work (to avoid circular dependencies!).
You can provide a metrics project by setting the following environment variable:
```
RILL_ADMIN_METRICS_PROJECT=rilldata/internal-rill-cloud-metrics
```
The PR includes an initial integration with a prototype `autoscaler-slots-recommendations` custom API and adds scaffolding for an autoscaling job that leverages those recommendations (not actually implemented).
Todo for a complete …
=> Admin: Scaffolding for metrics project integration for autoscaling

web-common/src/features/dashboards/dimension-table/DimensionHeader.svelte, web-common/src/features/dashboards/dimension-table/DimensionTable.svelte, web-common/src/features/dashboards/dimension-table/dimension-table-utils.ts
This PR features critical short term fixes for the `DimensionTable` component while the complete refactor (#4374) is in progress.
- Reverts incorrect width and height assignment
- Removes the forced expansion of the first column
=> Fix: Dimension Table critical short term fixes

web-common/src/components/dropdown-menu/DropdownMenuItem.svelte, web-common/src/layout/navigation/NavigationMenuItem.svelte
This PR addresses an apparent bug with the ShadCN menu component where it is not responsive to changes in the disabled prop. This PR adds a `#key` block to force the component to re-render.
=> Fix: Key ShadCN MenuItem on disabled prop

web-common/src/features/dashboards/time-controls/TimeControls.svelte
A recent change broke the way we set `baseTimeRange`. `dashboardStore.selectedTimeRange` is not guaranteed to have start and end just when a url state is loaded. But `timeControlsStore.selectedTimeRange` is sure to be filled in.
=> Fix base time range not getting set from url state

web-common/src/features/charts/createChart.ts, web-common/src/features/charts/render/VegaLiteRenderer.svelte, web-common/src/features/charts/render/vega-config.ts
First pass at adding Rill theme to custom charts. This might change soon with design input
=> Add rill theme to custom charts

web-admin/src/features/bookmarks/selectors.ts, web-admin/src/features/dashboards/DashboardAdminStateProvider.svelte, web-common/src/features/dashboards/selectors/index.ts, web-common/src/features/dashboards/stores/DashboardStateProvider.svelte, web-common/src/features/dashboards/stores/syncDashboardState.ts
During bookmark changes we added a layer to add loading of home bookmark. This PR refactors the code to streamline the sync code and generalise for local and cloud.
=> Refactor dashboard state sync with metrics view spec

web-admin/src/features/dashboards/listing/selectors.ts, web-admin/src/features/embeds/TopNavigationBarEmbed.svelte, web-admin/src/features/navigation/Breadcrumbs.svelte, web-common/src/features/dashboards/DashboardAssets.svelte, web-common/src/features/dashboards/selectors.ts
Quick fix for [this bug reported in Slack](https://rilldata.slack.com/archives/CTZ8XBQ85/p1710963629492489).
Not all dashboards have an underlying Model. Some dashboards are built directly on top of a Source or Table resource. This PR hides the "Edit model" menu item when there is no Model to edit.
=> Rill Developer: Fix dashboard's "Edit model" button

docs/docs/reference/olap-engines/clickhouse.md, docs/docs/reference/olap-engines/druid.md, docs/docs/reference/olap-engines/multiple-olap.md
Correcting all instances of `connection.<olap>.dsn` with `connector.<olap>.dsn` in the OLAP engine section of our docs based on typos / corrections in #4399
=> Updating OLAP engine docs with correct param

web-common/src/features/charts/render/vega-config.ts
Updates the default theme for custom charts based on - 
https://www.notion.so/rilldata/Apply-default-Rill-theme-and-support-custom-themes-to-the-Chart-a8acc657ebce45cbb6baea563000be83
=> Update default theme for charts

.github/workflows/web-test-e2e.yml
Currently, CI's `npm run test -w web-admin` errors out because it's taking >1 minute to build the application in advance of the test suite. `web-admin/playwright.config.ts` uses a default 60s timeout for starting up the Playwright `webServer`.
Rather than increase the timeout, this PR removes the `npm run test -w web-admin` command from CI. We currently only have one dummy `web-admin` e2e test.
We can revert this when we have 1) material e2e tests to run for `web-admin` and 2) a sustainable solution to the build timeout (such as re-using the output from `npm run build -w web-admin`).
=> Remove dummy `web-admin` e2e test from CI

cli/cmd/devtool/seed.go
FIxes `Error: create project failed with error rpc error: code = InvalidArgument desc = Malformed version:  (InvalidArgument)` post provisioner changes for `devtool seed`
=> fix: add productversion to devtool seed

web-common/src/features/metrics-views/workspace/MetricsWorkspace.svelte, web-common/src/features/metrics-views/workspace/MetricsWorkspaceHeader.svelte
Closes https://github.com/rilldata/rill-private-issues/issues/234
The Metrics Inspector is enabled for DuckDB-backed projects:
The Metrics Inspector is hidden for ClickHouse & Druid projects:
=> Hide the Metrics Inspector for OLAP engines that don't support modeling

web-common/src/features/charts/prompt/ChartPromptStatusDisplay.svelte, web-common/src/features/charts/prompt/GenerateVegaSpecPrompt.svelte, web-common/src/features/dashboards/DashboardAssets.svelte, web-common/src/features/models/navigation/ModelMenuItems.svelte, web-common/src/features/sources/navigation/SourceMenuItems.svelte
- Update to use the spinner for loading state of chart generation.
- Close the prompt modals immediately.
- Fix menu items showing up even when custom dashboards is not enabled.
=> Chart generation using AI follow ups fixes and tweaks

web-admin/src/features/alerts/CreateAlert.svelte, web-admin/src/features/alerts/listing/AlertsTableCompositeCell.svelte, web-admin/src/features/alerts/listing/NoAlertsCTA.svelte, web-admin/src/features/alerts/metadata/AlertMetadata.svelte, web-admin/src/features/navigation/TopNavigationBar.svelte, web-common/src/features/alerts/CreateAlertDialog.svelte, web-common/src/features/dashboards/dimension-table/DimensionHeader.svelte
This PR:
- Moves Create Alert entrypoint to the top bar
- Removes the entry point from leaderboard
- Dynamic defaults in the Alerts form depending on UI state
- Updates icons in listings
=> feat: move alerts to top bar

runtime/server/generate_resolver.go, web-common/src/features/charts/chartYaml.ts, web-common/src/features/charts/prompt/generateChart.ts
There were some slight changes to the metrics sql syntax. This leads to some issues where chatgpt tries to add aggregations to columns that are already aggregates like measures.
Also updates the button in charts page to work on errored charts.
=> Update chart generation prompt for new metrics sql syntax

web-common/src/features/project/ProjectTitle.svelte, web-common/src/layout/navigation/Navigation.svelte
This PR fixes an issue where the sidebar scrollbars would appear when the container was not overflowing. It also gives the project title a few more characters worth of space.
=> Fix: Sidebar scroll and title cutoff

web-common/src/features/dashboards/granular-access-policies/resetSelectedMockUserAfterNavigate.ts, web-common/src/features/dashboards/granular-access-policies/updateDevJWT.ts, web-common/src/features/dashboards/selectors/index.ts, web-common/src/runtime-client/http-client.ts
This PR solves an issue where JWTs were being invalidated incorrectly according to the expectation of the HTTP Client. Additionally, it solves a bug where `createMetricsViewSchema` was accessing the queryClient incorrectly.
=> Fix: Mock user JWT invalidation and queryClient access

admin/database/postgres/migrations/0023.sql, docs/docs/manage/roles-permissions.md
This was missing from the initial alerts PR. It fails silently by not letting viewer roles create alerts.
Closes https://github.com/rilldata/rill-private-issues/issues/251
=> Admin: Add DB migration and docs for create_alerts and manage_alerts permissions

web-common/src/features/dashboards/selectors/index.ts, web-common/src/features/dashboards/stores/DashboardStateProvider.svelte, web-common/src/features/dashboards/stores/syncDashboardState.ts, web-common/src/features/dashboards/workspace/DashboardCTAs.svelte, web-common/src/runtime-client/invalidation.ts
This PR is a fix for an issue where dashboards would fall into a perpetual "loading" state when viewing as a mock user with a limited security policy.
This was solved by altering the `createDashboardStateSync` function to return a greater specificity of state than a simple ready/not ready boolean.
As such, even when the dashboard store has failed to load data properly (which would be the case when a user does not have appropriate access), the Dashboard component will still render and handle the `mockUserHasNoAccess` conditional. This is somewhat of a stopgap solution for what should eventually be a more substantial reorganization of how this works.
Because the conditional rendering block doesn't exist in `DashboardStateProvider` in the same way, a conditional had to be added to the …
=> Fix: Perpetual loading state and infinite loop query

runtime/validate.go
Improves reconcilation time on druid based dashboard having 45 dims and 30 measures from 50 sec to 4 sec.
=> Improve reconcilation performance for external dashboards

web-common/src/features/dashboards/pivot/PivotTable.svelte, web-common/src/features/dashboards/pivot/pivot-data-store.ts, web-common/src/features/dashboards/pivot/pivot-table-transformations.ts, web-common/src/features/dashboards/pivot/types.ts
Separate the totals data row rather than clubbing it with the overall pivot data. 
Also makes sure that totals data row is always present when needed ensuring fixed array size while making changes to pivot/scrolling.
=> Refac: Move totals row out of data

runtime/server/controller.go
Makes sure only admins and alert owners/recipients can fetch alert details.
Closes https://github.com/rilldata/rill-private-issues/issues/250
=> Runtime: Apply access policies to alerts returned in ListResources

runtime/drivers/clickhouse/clickhouse.go, runtime/drivers/clickhouse/olap.go, runtime/drivers/druid/druid.go, runtime/drivers/druid/olap.go
We already support `--var connector.duckdb.log_queries=true` to enable query logging for Druid. This PR adds support for:
- Passing `--var connector.druid.log_queries=true` for Druid query logging
- Passing `--var connector.clickhouse.log_queries=true` for ClickHouse query logging
=> Runtime: Add query logging flags for Druid and ClickHouse

web-common/src/features/dashboards/pivot/PivotDrag.svelte, web-common/src/features/dashboards/pivot/PivotPortalItem.svelte, web-common/src/features/dashboards/pivot/PivotTable.svelte, web-common/src/features/dashboards/pivot/pivot-data-store.ts
To support the new infinite scrolling feature, this PR updates the `PivotTable` component to calculate an initial column width that remains fixed until changed manually via resizing or new pill state necessitates that it be recalculated.
Closes: #4432
=> Feat: Resize Pivot header column

tsconfig.json, web-admin/src/components/table/Table.svelte, web-admin/src/features/alerts/history/AlertHistoryStatusChip.svelte, web-admin/src/features/alerts/history/AlertHistoryTable.svelte, web-admin/src/features/alerts/history/AlertHistoryTableHeader.svelte, web-admin/src/features/alerts/listing/AlertsTable.svelte, web-admin/src/features/dashboards/listing/DashboardsTable.svelte, web-admin/src/features/dashboards/listing/DashboardsTableHeader.svelte, web-admin/src/features/organizations/OrganizationAccessControls.svelte, web-admin/src/features/projects/ProjectAccessControls.svelte, web-admin/src/features/scheduled-reports/history/ReportHistoryTable.svelte, web-admin/src/features/scheduled-reports/history/ReportHistoryTableHeader.svelte, web-admin/src/features/scheduled-reports/listing/ReportsTable.svelte, web-admin/src/features/scheduled-reports/listing/ReportsTableHeader.svelte, web-admin/src/features/view-as-user/ViewAsUserPopover.svelte, web-admin/tsconfig.json, web-auth/tsconfig.json, web-common/src/features/dashboards/pivot/pivot-data-store.ts, web-common/src/features/dashboards/proto-state/filter-converter.ts, web-local/tsconfig.json
This PR fixes an issue with the `tsconfig` files across our projects by properly extending the svelte-kit base configuration.
This is a critical fix required to support the use of ambient types.
=> Fix: SvelteKit configuration and lack of ambient types

web-common/src/features/dashboards/pivot/pivot-data-store.ts, web-common/src/features/dashboards/pivot/pivot-expansion.ts, web-common/src/features/dashboards/pivot/pivot-table-transformations.ts
1. Create a row nested pivot table with more than 100 rows
2. Scroll to the end of the table
3. Expand a row 
The expand doesn't work in this case
The table was being returned early which skipped expansion queries.
Same as mentioned in the Issue
=> Fix: Pivot expansion on infinite scroll

.github/workflows/rill-ui.yml
Bump nodejs version to build UI in ci.
Try resolving `Netlify credentials not provided, not deployable` issue.
=> fix: bump node version to resolve ui build failure

proto/rill/ui/v1/dashboard.proto, web-common/src/features/alerts/CreateAlertDialog.svelte, web-common/src/features/dashboards/proto-state/fromProto.ts, web-common/src/features/dashboards/proto-state/toProto.ts, web-common/src/features/dashboards/state-managers/actions/dimension-filters.ts, web-common/src/features/dashboards/state-managers/actions/filters.ts, web-common/src/features/dashboards/stores/dashboard-store-defaults.ts, web-common/src/features/dashboards/stores/dashboard-stores.ts, web-common/src/features/dashboards/stores/metrics-explorer-entity.ts, web-common/src/features/dashboards/time-dimension-details/TDDHeader.svelte, web-common/src/features/dashboards/time-dimension-details/TimeDimensionDisplay.svelte, web-common/src/features/dashboards/time-dimension-details/export-tdd.ts, web-common/src/features/dashboards/time-dimension-details/time-dimension-data-store.ts, web-common/src/features/dashboards/time-dimension-details/types.ts, web-common/src/features/dashboards/time-series/MetricsTimeSeriesCharts.svelte, web-common/src/features/dashboards/time-series/multiple-dimension-queries.ts, web-common/src/features/dashboards/time-series/timeseries-data-store.ts, web-common/src/features/dashboards/workspace/Dashboard.svelte, web-common/src/proto/gen/rill/ui/v1/dashboard_pb.ts
This PR refactors the TDD state by consolidating `expandedMeasureName` and `pinIndex` inside `tdd`. It also introduces `chartType` state for tdd.
Todo
=> Consolidate TDD state and include chart type

web-common/src/features/dashboards/tab-bar/TabBar.svelte, web-common/src/features/entity-management/file-artifacts.ts, web-common/src/features/entity-management/resource-invalidations.ts, web-common/src/features/tables/TableAssets.svelte, web-common/src/features/tables/selectors.ts
Fixes a couple of things,
1. Behaviour telemetry is not present on cloud. This PR disables it when the global is not present. We should look into enabling in the future.
2. Source rename doesnt invalidate the olap table list properly. This PR tracks a rename and invalidates it. We use `renamedFrom` in the resource meta to check if it was set and then unset. Reconciler uses it internally to tracks renames, but unsets it once reconciler is done renaming.
=> Telemetry and source rename fixes

admin/server/alerts.go, web-admin/src/features/alerts/metadata/AlertMetadata.svelte, web-admin/src/features/scheduled-reports/metadata/ReportMetadata.svelte, web-common/src/features/alerts/EditAlertDialog.svelte, web-common/src/features/scheduled-reports/EditScheduledReportDialog.svelte
Pulling fixes from #4509 so that it is independent.
1. Fixes the create alert endpoint to populate the correct field.
2. Fixes the usage of email recipients in alerts and reports
=> Udpate usage of notifiers to fix alert and report

web-common/src/features/dashboards/filters/measure-filters/MeasureFilter.svelte, web-common/src/features/dashboards/filters/measure-filters/MeasureFilterBody.svelte, web-common/src/features/dashboards/filters/measure-filters/MeasureFilterMenu.svelte, web-common/src/features/dashboards/filters/measure-filters/MeasureFilterReadOnlyChip.svelte, web-common/src/features/dashboards/filters/measure-filters/measure-filter-entry.spec.ts, web-common/src/features/dashboards/filters/measure-filters/measure-filter-entry.ts, web-common/src/features/dashboards/filters/measure-filters/measure-filter-options.ts
For ease of use mapping to and from proto type `V1Expression` should be separate from the measure filter forms and pills.
This PR is a 1st step towards this. It refactors all components dealing with measure filter editing and the pills to use a new format that can be mapped directly to the form.
Note: this makes things easier for comparison in alerts.
A follow up PR will refactor our dashboard state to store this directly.
=> Refactor measure filter components to be agnostic of proto types

web-common/src/components/chip/removable-list-chip/RemovableListChip.svelte, web-common/src/components/chip/removable-list-chip/RemovableListMenu.svelte, web-common/src/features/dashboards/dimension-table/DimensionDisplay.svelte, web-common/src/features/dashboards/dimension-table/DimensionHeader.svelte, web-common/src/features/dashboards/filters/FilterChips.svelte, web-common/src/features/dashboards/filters/Filters.svelte, web-common/src/features/dashboards/filters/dimension-filters/DimensionFilter.svelte, web-common/src/features/dashboards/filters/dimension-filters/getDimensionType.ts, web-common/src/features/dashboards/selectors/index.ts
This PR disables search for non-string dimensions in,
Also removes a usage of old filters in getting the filter list in pills. Also updates to use MetricsViewComparison instead of MetricsViewToplist (deprecated)
=> Disable search for non-string dimensions

runtime/resolvers/metrics_sql.go, runtime/resolvers/metrics_sql_test.go, runtime/resolvers/sql.go, runtime/testruntime/testdata/ad_bids/apis/templated_mv_sql_api.yaml, runtime/testruntime/testdata/ad_bids/apis/templated_mv_sql_api_2.yaml
The metrics SQL parser should resolve template first before parsing the SQL with template functions. This is required since the underlying parser can't always parse SQL with templates. Example below:
```
SELECT publisher, domain, measure_2 
FROM ad_bids_mini_metrics
WHERE
-- can access user attributes with templating
{{ if (ne .user.domain "") }} domain = '{{ .user.domain }}' {{ end }}
-- can use Sprig functions, e.g. to easily set defaults
{{ if (not .export) }} LIMIT {{ default 1 .args.pageSize }} {{ end }}
```
=> Runtime: metrics sql template fix

runtime/drivers/registry.go
Updates the default limits to:
- 200k rows for direct downloads (override with: `rill env set rill.download_row_limit <number>`)
- 2m cells for a single pivot query (override with: `rill env set rill.pivot_cell_limit <number>`)
=> Update default row and cell limits for exports

web-common/src/features/charts/ChartDisplay.svelte, web-common/src/features/entity-management/resource-invalidations.ts, web-common/src/runtime-client/invalidation.ts, web-common/src/runtime-client/manual-clients.ts
We had hardcoded to make a call to localhost:9009 initially. Adding a svelte query hook that uses our httpClient.
=> Add svelte-query hook for chart data

web-common/src/components/forms/FormSection.svelte, web-common/src/features/alerts/delivery-tab/AlertDialogDeliveryTab.svelte
When slack is not enabled we show a message directing users to the docs. This PR adjusts the spacing to match other sections.
=> Adjusting the spacing in slack notification section to match other sections

admin/admin.go, admin/worker/worker.go, cli/cmd/admin/start.go
Allow configuration of the slot autoscaler cron job frequency.
Previously, the run_autoscaler cron job frequency was hardcoded to _00:00 Monday PT_.
The new `RILL_ADMIN_AUTOSCALER_CRON` variable enables flexible scheduling, facilitating more frequent runs in test or debug modes.
Set `RILL_ADMIN_AUTOSCALER_CRON` to the desired cron schedule, based on the [robfig-cron syntax](https://pkg.go.dev/github.com/robfig/cron/v3#hdr-Usage). e.g., `CRON_TZ=Asia/Tokyo 30 04 * * *` for _04:30 Tokyo time every day_.
=> Introducing `RILL_ADMIN_AUTOSCALER_CRON` Environment Variable

runtime/drivers/duckdb/duckdb.go
seems like this is a consequence of a [breaking change](https://duckdb.org/2024/02/13/announcing-duckdb-0100.html#breaking-sql-changes)
=> old_implicit_casting to cast numbers to strings while table union by name

runtime/drivers/duckdb/olap.go, runtime/drivers/duckdb/transporter_duckDB_to_duckDB.go, runtime/reconcilers/model.go, runtime/reconcilers/source.go, runtime/reconcilers/util.go
Details here : 
https://github.com/duckdb/duckdb/issues/9342
https://github.com/duckdb/duckdb/pull/11297 
Even though we don't run any `ATTACH` & `DETACH` in parallel but I think that duckDB is also getting into this condition when running any information_schema call in parallel to DETACH operation.
We ensure all `DETACH` happen in isolation and sequentially using internal drivers `tx` lock.
=> Runtime : Detach duckdb files with `tx` lock

web-common/src/features/sources/modal/AddSourceModal.svelte, web-common/src/features/sources/modal/LocalSourceUpload.svelte, web-common/src/features/sources/modal/add-source-visibility.ts, web-common/src/layout/RillDeveloperLayout.svelte
This PR adds history entries associated with the state of the Add Source modal. This is something that is trivial and has a pretty clean API in SvelteKit 2.0, but is kind of cumbersome using native browser APIs. As such, this is kind of a patchy approach and another reason to move to 2.0 as soon as possible.
Closes: #4541
=> Associate history entries with AddSourceModal state

admin/deployments.go, admin/server/projects.go
This PR makes `CreateProject.ProdVersion` default to `latest` on the server-side. This is necessary since older versions of Rill do not pass a `ProdVersion`.
Without this change, I'm getting this error during `rill deploy` from `v0.42.3`:
```
Error: create project failed with error rpc error: code = InvalidArgument desc = Malformed version:  (InvalidArgument)
```
=> Admin: Fix version missing error for "rill deploy" from old versions

web-common/src/features/metrics-views/workspace/editor/metrics-schema.json
Updates the required fields based on - 
The only required fields in a metrics def are:
1. Exactly one of:
`model`
`table`
2. Exactly one of:
`dimensions[*].column`
`dimensions[*].property`
`dimensions[*].expression`
3. `measures[*].expression`
Everything else is optional
https://rilldata.slack.com/archives/C02T907FEUB/p1713182860271179
=> Update required fields in metrics schema

runtime/drivers/duckdb/olap.go
Here is my hypothesis around how detach can fail even in happy scenarios:
1. The db file is created and we start ingesting data. 
2. The ingestion fails due to n number of reasons like duckdb memory limit exhausted, cancellation etc.
3. In the cleanup we `reopen` db which re-attaches all files and removes directory with a db file but no version.txt file.
4. Now the detach in cleanup will complain that db file does not exist.
=> Runtime: change error log to debug

web-common/src/features/feature-flags.ts
This PR changes the scope of the AI feature flag from `user` to `system`, meaning it can't be set/overwritten via localStorage, URL or the YAML file.
Looking forward, the feature flags store should probably be broken up into three components: a `config` store that is project/organization specific and depends on data only available via the API, a `preferences` store for things that can be toggled on and off and are not intended to be hidden, and a `feature flags` store for things disabled by default and enabled manually. Also, there are certain things, like `adminServer` that don't need to be reactive or controlled during runtime that should be constants determined by environment variables.
=> Update AI feature flag scope

admin/server/admin_rbac_test.go, admin/server/organizations.go, admin/server/projects.go
Closes issue reported in [Slack](https://rilldata.slack.com/archives/CTZ8XBQ85/p1713218977194649).
=> Let non-admin users remove themselves from orgs and projects

web-local/src/routes/(application)/custom-dashboard/[name]/+page.svelte
=> Fix: Custom Dashboard component assignment name

web-common/src/features/models/workspace/ModelWorkspaceCTAs.svelte
- Changed the button text from "Preview" to "Go to dashboard"
- Changed the button color from dark gray to our brand color (to align with the other CTA buttons)
=> Tweak model's "Go to dashboard" button

web-admin/src/features/alerts/CreateAlert.svelte, web-common/src/features/dashboards/dimension-table/ExportDimensionTableDataButton.svelte
We currently do not gracefully handle when timestamp column is not present for reports and alerts.
Temporarily disabling creating them when timestamp column is not present in the dashboard.
=> Disable reports and alerts for dashboards with no timestamp column

web-common/src/features/dashboards/pivot/PivotTable.svelte, web-common/src/layout/Resizer.svelte
This PR sets a minimum width for measure columns and adds the ability to resize them across the table.
In the examples below, the first image shows the initial layout (measures are given more space without having to reference the associated dimension name) and the other two show resizing the measure up or down.
Seeing some rendering artifacts in Safari, but is stable in Chrome.
=> Fix/Feat: Resizable Pivot measure columns

web-common/src/components/navigation/breadcrumbs/Breadcrumbs.svelte, web-local/src/routes/(application)/+layout.svelte, web-local/src/routes/+layout.svelte, web-local/src/routes/welcome/+page.svelte, web-local/src/routes/welcome/+page.ts
- Moves the global `body` div to the top level `+layout` file
- Eliminates page flashing by moving the redirect and `isProjectInitialized` conditional check that was originally part of the `/welcome` route (different from the `WelcomePageRedirect`) to a load function
- Moves the call to `initializeNodeStoreContexts` above the `getContext` call
=> Fix: Post reorg tweaks

web-common/src/features/entity-management/watch-files-client.ts
This PR changes the `resetQueries` call to `refetchQueries`, ensuring that file blobs are not reset to undefined as queries are fetching. There may have been a reason for this which I am not aware of, but this change is necessary for adding optimistic updates to our file mutations.
It also adds a leading slash to the `rill.yaml` conditional check as `FILE_EVENT_WRITE` sends paths in that format.
=> Fix: Adjust file invalidation type and rill.yaml file path

web-common/src/features/charts/prompt/GenerateChartYAMLPrompt.svelte, web-common/src/features/entity-management/AddAssetButton.svelte, web-common/src/features/entity-management/file-selectors.ts, web-common/src/features/file-explorer/FileExplorer.svelte, web-common/src/features/file-explorer/NavEntryPortal.svelte, web-common/src/features/file-explorer/NavFile.svelte, web-common/src/features/file-explorer/nav-entry-drag-drop-store.ts
- Add a small distance before triggering the drag
- Add icons to the dragged element.
- Disable drag-drop for rill.yaml
=> Improve drag drop UX in file explorer and other fixes

web-common/src/features/dashboards/tab-bar/TabBar.svelte
Removing the beta tag from the Pivot tab.
Keeping the beta logic around in case we add more tabs/feature surface areas in the future.
=> fix: remove beta tag for pivot

web-admin/src/features/navigation/TopNavigationBar.svelte
Addresses this [bug report in Slack](https://rilldata.slack.com/archives/CTZ8XBQ85/p1713229199298049).
=> Fix: prevent the `ListProjectsForOrganization` request from firing before the `organization` is defined

web-common/src/features/entity-management/actions.ts, web-common/src/features/entity-management/file-selectors.ts
In the new file explorer we use name+kind to decide what type of editor we use. When renaming it switching from undefined to a valid one. This causes a flicker from entity's editor to fallback editor back to entity's editor. By proactively adding name+kind to the target path we can avoid this.
=> fix: flicker during rename in the new file explorer

runtime/server/generate_metrics_view.go, web-common/src/lib/time/config.ts, web-common/src/lib/time/types.ts
This PR populates the `available_time_ranges` field in a dashboard config with our standard defaults. It also solves a bug where `rill-QTD` would not populate because it did not have a corresponding entry in the `PERIOD_TO_DATE` dictionary.
=> Populate available_time_ranges with defaults

runtime/queries/metricsview_comparison_toplist.go
For druid if there are more than 5 measures in the toplist or if toplist returns results equal to the limit rows then we do a second query by adding those top values as a filter. It has been observed in past for kargo and now for automatad as well that if we remove the limit clause from this query then this is run as a groupby query (instead of topN) and it is much faster than topN. More details in an internal notion doc.
=> remove limit for druid exactify toplist query

runtime/compilers/rillv1/parser.go, runtime/drivers/admin/repo.go, runtime/drivers/file/repo.go, runtime/drivers/github/repo.go, runtime/drivers/repo.go, runtime/reconcilers/project_parser.go
When a folder is renamed files within the new folder is considered as new files rather than renames. This is an attempt at fixing it by going through all files in the cache that have the prefix of a deleted folder.
=> Fix rename of a folder not correctly identifying inner entities are renamed

web-admin/src/components/layout/ContentContainer.svelte, web-admin/src/routes/+layout.svelte, web-admin/src/routes/[organization]/[project]/-/dashboards/[dashboard]/+page.svelte, web-common/src/features/custom-dashboards/Chart.svelte, web-common/src/features/custom-dashboards/CustomDashboardEmbed.svelte
Adds structure to the custom dashboard page for `web-admin`. It is expected that this route may throw errors depending on your chart/custom-dashboard spec as Chart data fetching, which is currently using a manual client, throws uncaught errors.
This also removes a conditional check that was being used to apply `h-screen` on the root component for `web-admin`. I didn't see any obvious issues caused by removing this, though we should probably rework the layout for `web-admin` to allow for a sticky `TopNavigationBar` and scrollable tables.
=> Add preliminary components to cloud custom dashboard page

web-common/src/features/dashboards/time-controls/new-time-controls.ts
This PR adds the structure of the new time control store without actually implementing it anywhere. This is to make sure that that as the UI elements are updated with our new menus, pickers and Super Pill, the new store can easily be tested without having to keep branches in sync.
=> Add new time control state structure

web-common/src/features/tables/TableAssets.svelte, web-common/src/layout/navigation/Navigation.svelte
- The Tables section is now initially positioned at the midpoint of the sidebar
- The section can be moved up/down by the user
Contributes to https://github.com/rilldata/rill-private-issues/issues/309
=> File Explorer: make the Tables section position user-controlled

web-common/src/features/dashboards/filters/measure-filters/measure-filter-utils.ts
When there is no data for a measure filter instead of showing an empty dashboard it shows a full dashboard.
This fixes that use case and makes sure we apply empty response filters properly.
=> Fix measure filter returning no data

web-common/src/components/WorkspaceError.svelte, web-common/src/components/preview-table/ConnectedPreviewTable.svelte, web-local/src/routes/(application)/[type=workspace]/[name]/+page.svelte, web-local/src/routes/(application)/dashboard/[name]/edit/+page.svelte, web-local/src/routes/(application)/files/[...file]/+page.svelte
Previously, we weren't handling errors when rendering a Preview Table. This became apparent when a ClickHouse table contained some invalid UTF-8 strings. This PR shows an error message in these circumstances.
Closes #4542 
Before:
After:
=> Handle errors when rendering the `PreviewTable`

web-common/src/features/entity-management/file-selectors.spec.ts, web-common/src/features/entity-management/file-selectors.ts, web-common/src/features/entity-management/resource-selectors.ts, web-common/src/features/file-explorer/FileExplorer.svelte, web-common/src/features/file-explorer/new-files.ts, web-local/src/routes/(application)/custom-dashboards/[name]/+page.svelte
This PR fixes cases where new files were not properly incrementing their names to e.g. `untitled_file_1`. There are a few permutations to handle:
- New blank files in the root directory
- New blank files in subdirectories
- New directories in the root directory
- New directories in subdirectories
- New resource files in their resource-specific directories
The PR also fixes some other CRUD-related errors:
- Removes a no-longer-needed constraint on renaming custom dashboards
- Fixes a console error when deleting files from the root page
=> File Explorer: Fix new file names

web-local/src/routes/(application)/[type=workspace]/[name]/+page.svelte
Fixes a regression where the Source/Model workspace's preview table was not showing its loading state when the Source/Model was reconciling.
Now:
=> Fix loading state of Source/Model preview table

web-common/src/features/entity-management/AddAssetButton.svelte
- Sources & Models are not currently supported for ClickHouse- and Druid-backed projects
- This PR hides the Sources & Models options in the "Add [resource]" button when the application is started with either of these OLAP engines.
=> Rill Developer: Hide Sources & Models for ClickHouse & Druid

web-common/src/features/entity-management/ReconcilingSpinner.svelte
Previously in Rill Developer, we were using the term "Ingesting" whenever a resource was reconciling. This PR uses the term "Building" for all resources except for Sources.
Closes [#4543](https://github.com/rilldata/rill/issues/4543)
=> Use resource-specific reconcile terminology

web-common/src/features/custom-dashboards/Component.svelte, web-common/src/features/custom-dashboards/CustomDashboardEmbed.svelte
The `chartView` override was not being passed down correctly.
Also adds a key to the ResizeHandle each block and uses `svelte:component` to silence a warning.
=> Fix: Chart height override

web-common/src/features/project/ProjectTitle.svelte, web-common/src/features/project/selectors.ts
I noticed the project title icon was sometimes missing. I'm not sure what changed recently, but this PR touches up this code to avoid a missing icon.
=> Fix missing project title icon

web-local/src/routes/(application)/[type=workspace]/[name]/+page.svelte
The `isLocalFileConnector()` function was being called for Models, triggering this YAML parse error in the console:
In this case, the `enabled` flag of the `isLocalFileConnector` TanStack Query call _is_ set to `false`, so it seems like a separate call to `GetFile` has been triggering the `select` function.
=> Fix common console error in the Model Workspace

web-admin/src/features/errors/ErrorBoundary.svelte, web-admin/src/routes/+error.svelte, web-common/src/components/ErrorPage.svelte, web-local/src/routes/(viz)/dashboard/[name]/+page.svelte, web-local/src/routes/+error.svelte
This PR:
- Moves the Rill Cloud error page to `web-common`, so it can be re-used for Rill Developer
- Adds a fallback error page for Rill Developer at `web-local/src/routes/+error.svelte` 
- Handles parse errors triggered from an external IDE on the Rill Dev Preview Dashboard page
Addresses [a couple comments here](https://github.com/rilldata/rill/pull/4713#issuecomment-2076182153).
A couple things I noticed, but will keep out of this PR:
- We should rework the `CTAButton` to accept an `href`.
- One file write triggers multiple refetches of the Project Parser resource. Our resource invalidation really needs an audit.
=> Re-use the Cloud error page in Rill Developer

web-local/src/routes/(application)/files/[...file]/+page.svelte
Default editor had an additional border making it slightly out of line with the head. Removing it to make align. (https://www.notion.so/rilldata/Code-window-strokes-are-doubled-01a981c5903a48da9ba41f88fdc0da18)
=> Imrpove default editor styles accoridng to feedback

web-common/src/features/entity-management/file-artifacts.ts, web-common/src/features/entity-management/resource-invalidations.ts
List of OLAP tables is not being invalidated when a new source/model is added. Since we could get multiple events when a new entity is added we need a state in fileArtifacts for new entities.
=> Invalidate olap table list when a new source/model is added

runtime/drivers/file/watcher.go, web-common/src/features/entity-management/resource-invalidations.ts, web-common/src/features/models/selectors.ts
=> Fix edge cases around rename

web-common/src/features/entity-management/RenameAssetModal.svelte
Addresses this [bug report](https://rilldata.slack.com/archives/C02T907FEUB/p1714418500302589) in Slack. A 404 resulted from renaming a file at the top-level of the root directory via the `RenameAssetModal`.
=> File Explorer: Fix 404 error from renaming a file in the root directory

web-common/src/features/entity-management/file-artifacts.ts
While editing a custom dashboard with inline components there is a flicker. This is due to inline component mapping to the same file. In this PR we are not setting the `name` for any sub resource.
=> Fix flicker for inline custom dashboard sub components

web-common/src/features/custom-dashboards/Chart.svelte, web-common/src/features/custom-dashboards/Component.svelte, web-common/src/features/custom-dashboards/CustomDashboardEmbed.svelte, web-common/src/features/custom-dashboards/CustomDashboardPreview.svelte, web-common/src/features/custom-dashboards/DashboardWrapper.svelte, web-common/src/features/custom-dashboards/PreviewElement.svelte, web-local/src/routes/(application)/chart/[name]/+page.svelte, web-local/src/routes/(application)/custom-dashboards/[name]/+page.svelte, web-local/src/routes/(viz)/custom/[name]/+page.svelte
This PR tackles the most critical updates required to bring the Custom Dashboard up to date with the new spec.
=> Update custom dashboard integration to new spec

web-admin/postcss.config.cjs, web-admin/src/routes/[organization]/[project]/-/dashboards/[dashboard]/+page.svelte, web-auth/postcss.config.cjs, web-common/postcss.config.cjs, web-local/postcss.config.cjs
This PR adds `tailwind/nesting` to our postcss config and ensures that all repo configs are based off the one in `web-common`
=> Configure CSS nesting and unify postcss configs

web-common/src/features/entity-management/actions.ts, web-common/src/features/entity-management/file-artifacts.ts, web-common/src/features/entity-management/resource-invalidations.ts, web-common/src/features/welcome/ProjectCards.svelte, web-local/src/routes/(application)/custom-dashboards/[name]/+page.svelte, web-local/src/routes/(application)/dashboard/[name]/edit/+page.svelte
=> Fix OLAP Table list not invalidating in certain cases

admin/server/alerts.go, admin/server/reports.go, cli/cmd/project/describe.go, cli/cmd/project/status.go, runtime/compilers/rillv1/connectors_test.go, runtime/compilers/rillv1/parse_node.go, runtime/compilers/rillv1/parse_source.go, runtime/compilers/rillv1/parser.go, runtime/compilers/rillv1/parser_test.go, runtime/controller.go, runtime/controller_test.go, runtime/reconcilers/alert_test.go, runtime/server/generate_metrics_view.go, runtime/testruntime/testdata/ad_bids/dashboards/ad_bids_metrics_view.yaml, runtime/testruntime/testdata/ad_bids/sources/ad_bids_mini_source.yaml, runtime/testruntime/testdata/ad_bids/sources/ad_bids_source.yaml, runtime/testruntime/testdata/ad_bids_2rows/sources/ad_bids_source.yaml
This PR only changes user-facing usage of `kind`, such as in YAML files and log/error messages. Changing the terminology internally can be done separately.
Example usage:
```yaml
type: api
sql: SELECT 3.141
```
This PR is backwards compatible with older files that use `kind:` and also with older source files that use `type:` to specify the source connector (though only for sources defined in the `sources/` directory).
=> Use `type:` instead of `kind:` for resource types
