rilldata/rill

src/routes/_surfaces/assets/index.svelte

@magorlick let me know what you think. I know it's kind of small. Don't want to detract too much from the rest of the UI

DM-182 adds the CTA in the UI

---

.prettierignore
.prettierrc

I propose that we remove the existing `.prettierrc` and just use prettier defaults across the board. Please chime in if there were strong reasons for choosing any of the settings in that file (IMHO, tabs instead of spaces is a definite no, and none of the others seem important enough to deviate from the community norm).
Also added some folders for .prettierignore, please feel free to suggest additions or removals

proposed configs for prettier

---

src/lib/layout-store.ts
src/routes/index.svelte

Perhaps some of these "should" be bools, but I think nums are fine; can change if desired, but this follows the pattern used in the existing files, and nums appear to be required for tweening in some cases

fix TS lint type error in index.svelte by changing bool -> num.

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/epic.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/nit.md
.github/ISSUE_TEMPLATE/task.md

Open issues

---

jest.config.json

fix file ref in jest.config.json

---

src/lib/components/column-profile/CollapsibleTableSummary.svelte
src/lib/util/file-upload.ts
src/routes/_surfaces/assets/ModelAssets.svelte
src/routes/_surfaces/assets/TableAssets.svelte
src/routes/_surfaces/assets/index.svelte
src/routes/dev/source-gallery.svelte

follow on from #251, removes a prop from CollapsibleTableSummary that is not used in that component and was causing linting errors

Simplify-assets-sidebar-2

---

src/common/data-modeler-service/TableActions.ts
src/routes/_surfaces/assets/TableAssets.svelte

Fixes #230
Adding a check in table sync to not run when it is profiling.

Stopping table sync if it is profiling already

---

README.md
src/cli/InitCommand.ts

Adding a section for connecting to existing duckdb

---

src/common/data-modeler-service/ModelActions.ts
src/common/data-modeler-service/TableActions.ts
src/common/data-modeler-service/response/ActionResponseFactory.ts
src/common/data-modeler-service/response/ActionResponseMessage.ts
src/common/errors/EntityError.ts
src/common/errors/ExistingEntityError.ts
test/functional/DataLoader.spec.ts
test/functional/ModelQuery.spec.ts

Fixes #234
Adding table name check for model name and table names when we are,
- Adding or renaming model name
- Importing a table

Adding deduping table and model names

---

.prettierignore
README.md
package.json
src/cli/DataModelerCliCommand.ts
src/cli/ExampleProjectCommand.ts
src/cli/InitCommand.ts
src/cli/data-modeler-cli.ts
src/common/database-service/DuckDBClient.ts
src/server/serverFactory.ts
test/utils/modify-db.ts

things to get into this PR / verify before merging:

update README.md for 0.2.0

---

src/app.css
src/lib/components/Editor.svelte

This addresses #273, #274, and does a couple minor code cleanups.

Quick wins to improve editor aesthetics

---

src/lib/components/column-profile/ColumnSummaryMiniPlots.svelte

@ericpgreen2, thanks for letting me know about that bug. I think this should fix it, though to be honest I really have no idea why. I've looked over the code a dozen times, I could swear these changes are equivalent to the pre change version. Oh well...
In any case, would you mind pull this branch locally and doing a bit of quick QA to make sure I didn't miss anything during my QA pass? If it looks good to you and these code changes are ok, I think we should merge.
@magorlick  this should fix the bug i mentioned earlier

fixes bug in svelte-ctx

---

.eslintrc.cjs
src/lib/util/formatters.ts
src/lib/util/guid.ts
src/lib/util/model-structure.test.ts
src/lib/util/model-structure.ts
src/lib/util/place-element.ts
src/lib/util/sanitize-query.ts
test/functional/CLI.spec.ts

Fixes #332 
Verified using `npm run lint`

Fix prefer-const errors

---

src/app.css
src/lib/components/Editor.svelte

Disable code folding

---

src/app.css
src/lib/components/table/PreviewTable.svelte
src/lib/components/table/TableCell.svelte

Remove redundancies in results table

---

src/lib/components/column-profile/CollapsibleTableHeader.svelte
src/lib/components/column-profile/CollapsibleTableSummary.svelte

Refactor CollapsibleTableSummary component

---

src/lib/components/column-profile/CollapsibleTableSummary.svelte

Bubble up event for refactored component

Fix select on model names

---

DEVELOPER-GUIDE.md
README.md
scripts/druid-import.sh
scripts/example-project.sh
src/cli/DropTableCommand.ts
src/cli/ImportTableCommand.ts
src/cli/InitCommand.ts
src/lib/components/overlay/ImportingTable.svelte
src/routes/_surfaces/assets/TableAssets.svelte
src/routes/_surfaces/inspector/Model.svelte
src/routes/_surfaces/workspace/WorkspaceHeaderStatusSpinner.svelte
src/routes/index.svelte
test/functional/CLI.spec.ts
test/functional/DuckDbConnection.spec.ts
test/ui/DataModeler.spec.ts

An intermediate step before merging all of #403

Rename `table` to `source` superficially

---

.prettierignore
src/common/database-service/DatabaseColumnActions.ts
src/lib/components/column-profile/CollapsibleTableHeader.svelte
src/lib/components/column-profile/CollapsibleTableSummary.svelte
src/lib/components/column-profile/ColumnProfileDetails.svelte
src/lib/components/viz/histogram/OutlierHistogram.svelte
test/ui/DataModeler.spec.ts

Adding docs to prettierignore.
Updating UI tests to assert on the latest changes.

Fixing prettier and UI tests

---

package-lock.json
package.json
src/lib/components/metrics-definition/CollapsibleMetricsDefinitionSummary.svelte
src/lib/components/metrics-definition/CollapsibleMetricsDefinitionSummaryNavEntry.svelte
src/lib/redux-store/store-root.ts
src/routes/_surfaces/assets/MetricsDefinitionAssets.svelte
src/routes/_surfaces/workspace/metrics-def/MetricsDefModelSelector.svelte
src/routes/_surfaces/workspace/metrics-def/MetricsDefTimeColumnSelector.svelte
src/routes/_surfaces/workspace/metrics-def/MetricsDefWorkspace.svelte
src/routes/_surfaces/workspace/metrics-def/MetricsDefWorkspaceHeader.svelte

Aditya, thanks so much for your work on the suggestions I made the other day. I was able to jump back in and get productive again today -- I didn't make a ton of changes, but I can see a path forward. :thumbsup:

Http-streaming-bc

---

src/lib/application-state-stores/layout-store.ts
src/lib/components/overlay/PreparingImport.svelte
src/lib/util/file-upload.ts
src/routes/index.svelte

Local branch of #429 to enable PR job
Fix for #409

Add overlay for large import

---

src/lib/components/column-profile/CollapsibleTableHeader.svelte
src/lib/components/column-profile/CollapsibleTableSummary.svelte
src/lib/components/column-profile/ColumnProfileNavEntry.svelte
src/lib/components/metrics-definition/MetricsDefinitionSummary.svelte
src/routes/_surfaces/assets/MetricsDefinitionAssets.svelte
src/routes/_surfaces/assets/ModelAssets.svelte
src/routes/_surfaces/assets/TableAssets.svelte
test/utils/ServerSetup.ts

Refactoring collapsible summary components so that we can reuse most of the parts in metrics definition.

Refactoring collapsible summary for better reuse

---

docs/contributors/development.md

`npm build` --> `npm run build`

Fix command in the Developer Guide

---

src/lib/components/table/PreviewTable.svelte
src/lib/components/table/TableHeader.svelte
src/lib/components/table/TableRow.svelte

Add row numbers

---

src/lib/components/column-profile/CollapsibleTableHeader.svelte
src/lib/components/column-profile/CollapsibleTableSummary.svelte

Fixes bug where you can't expand profile when you click on `ExpanderButton`

Fix expand bug

---

package-lock.json
package.json

Update release version

---

src/lib/components/column-profile/ContextButton.svelte
src/lib/components/metrics-definition/MetricsDefinitionGenerateButton.svelte
src/lib/components/table-editable/TableRowWithMenu.svelte
src/routes/_surfaces/workspace/metrics-def/MetricsDefEntityTable.svelte
src/routes/_surfaces/workspace/metrics-def/MetricsDefModelSelector.svelte
src/routes/_surfaces/workspace/metrics-def/MetricsDefTimeColumnSelector.svelte
src/routes/_surfaces/workspace/metrics-def/MetricsDefWorkspace.svelte

@AdityaHegde this PR has a relatively small set of refinements in the metrics def workspace (including making the row menu button bigger, that was a good suggestion :-) ). Feel free to merge if you approve, thanks Aditya!

Metrics explore bc 4

---

src/routes/_surfaces/assets/MetricsDefinitionAssets.svelte

Fix metrics config code icon

---

src/lib/components/data-graphic/elements/GraphicContext.svelte
src/lib/components/data-graphic/guides/Axis.svelte
src/lib/components/data-graphic/guides/Grid.svelte
src/lib/components/data-graphic/utils.ts
src/lib/util/convertTimestampPreview.ts
src/routes/_surfaces/workspace/explore/MetricsTimeSeriesCharts.svelte
src/routes/_surfaces/workspace/explore/time-series-charts/TimeSeriesBody.svelte
src/routes/_surfaces/workspace/explore/time-series-charts/TimeSeriesChartContainer.svelte

Fix metrics chart axes; fix timezone offset issues

---

src/routes/_surfaces/assets/MetricsDefinitionAssets.svelte
src/routes/_surfaces/workspace/WorkspaceHeader.svelte
src/routes/_surfaces/workspace/metrics-def/MetricsDefWorkspaceHeader.svelte

adds explore and metrics icons into the branch

Add explore icons

---

src/routes/_surfaces/workspace/explore/ExploreHeader.svelte

Add edit metrics button

---

src/lib/components/table-editable/EditableTableHeader.svelte
src/lib/components/table-editable/TableCellSelector.svelte

@magorlick simple fixed column width approach (at least maybe cleaner for tomorrow's demo?).  i can put more time into this tomorrow, you can decide whether you like this option or the status quo ante for the demo.

set columns to fixed width for demo, more discussion needed

---

src/routes/_surfaces/inspector/ModelInspectorHeader.svelte

Fix timestamp detection CTA

---

src/common/data-modeler-service/ApplicationActions.ts
src/lib/redux-store/application/application-apis.ts
src/lib/redux-store/application/application-selectors.ts
src/lib/redux-store/application/application-slice.ts
src/lib/redux-store/big-number/big-number-selectors.ts
src/lib/redux-store/dimension-definition/dimension-definition-selectors.ts
src/lib/redux-store/explore/explore-selectors.ts
src/lib/redux-store/measure-definition/measure-definition-selectors.ts
src/lib/redux-store/metrics-definition/metrics-definition-apis.ts
src/lib/redux-store/metrics-definition/metrics-definition-selectors.ts
src/lib/redux-store/store-root.ts
src/lib/redux-store/timeseries/timeseries-selectors.ts
src/lib/redux-store/utils/api-utils.ts
src/lib/redux-store/utils/selector-utils.ts
src/routes/__layout.svelte
src/server/server.ts

Closes #543
Had to add a copy of ApplicationState to redux store to get this working.
Basically check if active entity is the current metrics definition then set it to next available or set to one of the models.

Adding a redux store for application state

---

src/lib/components/metrics-definition/MeasuresColumns.ts
src/lib/components/table-editable/ColumnConfig.ts
src/lib/components/table-editable/TableCellInput.svelte

Adding reactive measure expression validation

---

src/routes/_surfaces/workspace/explore/TimeRangeSelector.svelte

Fix initial time range bug

---

src/lib/components/table-editable/TableCellInput.svelte

update icons and tooltips for metrics designer

---

src/lib/components/table-editable/PinnableTable.svelte
src/lib/components/table-editable/TableCellInput.svelte
src/lib/components/table-editable/TableHeader.svelte
src/lib/components/table-editable/TableRowWithMenu.svelte

@magorlick  for design review and @AdityaHegde  for code review. @AdityaHegde  please note that I messed up the branching on this PR, so you should review this after https://github.com/rilldata/rill-developer/pull/590

Metrics designer row menu

---

src/common/data-modeler-state-service/entity-state-service/MeasureDefinitionStateService.ts
src/common/database-service/DatabaseMetricsExploreActions.ts
src/common/expression-parser/getMessageFromParseError.ts
src/common/expression-parser/parseExpression.ts
src/common/expression-parser/validateAggregate.ts
src/common/rill-developer-service/MeasuresActions.ts
src/common/rill-developer-service/MetricsDefinitionActions.ts
src/common/utils/Debounce.ts
src/lib/components/metrics-definition/MeasuresColumns.ts
src/lib/components/table-editable/ColumnConfig.ts
src/lib/components/table-editable/TableCellInput.svelte
src/lib/duckdb-data-types.ts
src/lib/redux-store/measure-definition/measure-definition-apis.ts
src/lib/redux-store/measure-definition/measure-definition-slice.ts
src/routes/_surfaces/workspace/metrics-def/MetricsDefWorkspace.svelte
test/unit/parseExpression.spec.ts

closes #591 #589 #585
Adding human readable errors for measure expression parse failures.
Adding argument validation to some extent. Will fallback to validating by running the expression through duckdb.

Adding detailed parse validation

---

src/common/database-service/DatabaseMetricsExplorerActions.ts
src/lib/util/humanize-numbers.ts
src/routes/_surfaces/workspace/explore/leaderboards/DimensionLeaderboardEntrySet.svelte

Closes #603 
After fix - 
https://user-images.githubusercontent.com/4402679/179972604-941d8958-ed36-49fe-b2f7-5e338bf0857e.mp4

Handle nulls on leaderboard

---

docs/docs/install/binary.md

Made some updates to explain how to get around Windows binary issues noted by this user:
https://twitter.com/mim_djo/status/1550692817608982529

Update binary.md notes to explain Windows install workaround

---

src/lib/redux-store/explore/explore-slice.ts
src/lib/util/humanize-numbers.ts
src/routes/_surfaces/workspace/explore/leaderboards/Leaderboard.svelte
src/routes/_surfaces/workspace/explore/leaderboards/LeaderboardDisplay.svelte

Grouped Leaderboard formatting

---

src/routes/_surfaces/workspace/explore/time-series-charts/MetricsTimeSeriesCharts.svelte

Humanize Big Number by default

---

docs/src/components/Video.js

just an update to the vimeo url params to autoplay vimeo videos on docs.rilldata.com

Godzig patch 1

---

src/lib/components/table-editable/PinnableTable.svelte
src/lib/components/table-editable/TableCellInput.svelte
src/lib/components/table-editable/TableHeader.svelte

fix problem noticed by @magorlick here: https://rilldata.slack.com/archives/C034S4572LU/p1658858134560019?thread_ts=1658856949.744329&cid=C034S4572LU

fix validation icon z-index problem

---

src/routes/_surfaces/workspace/explore/time-series-charts/MetricsTimeSeriesCharts.svelte

Humanize should be default for chart numbers as well

Humanize axis labels by default

---

src/lib/components/metrics-definition/MetricsDefinitionGenerateButton.svelte
src/lib/components/modeler/ModelerToMetricsButton.svelte
src/lib/redux-store/metrics-definition/metrics-definition-apis.ts
src/lib/redux-store/source/source-apis.ts
src/lib/redux-store/source/source-selectors.ts
src/routes/_surfaces/assets/MetricsDefinitionAssets.svelte
src/routes/_surfaces/assets/TableAssets.svelte
src/routes/_surfaces/inspector/ModelInspectorHeader.svelte
src/routes/_surfaces/workspace/metrics-def/MetricsDefTimeColumnSelector.svelte
test/functional/create-timestamp-rollup-reduction.spec.ts
test/functional/estimate-ideal-rollup-interval.spec.ts

Direct to dashboard button in the modeler

---

src/lib/components/data-graphic/guides/Axis.svelte
src/lib/components/data-graphic/guides/Grid.svelte
src/lib/components/data-graphic/state/types.d.ts
src/lib/components/data-graphic/utils.ts
src/routes/dev/data-graphic/reactive.svelte

Show more than 1 tick in axis where possible

---

src/common/database-service/DatabaseMetricsExplorerActions.ts
src/common/database-service/utils.ts

Add null labels to leaderboard

---

test/data/HistogramSummary.data.ts

Add test case for FD estimator

---

docs/blog/0.6.md

Replacing broken link. Also we should probably pick an asset hosting provider.

Fixing og:image

---

src/lib/components/modeler/ModelerToMetricsButton.svelte
src/lib/redux-store/source/source-selectors.ts
src/routes/_surfaces/assets/MetricsDefinitionAssets.svelte
src/routes/_surfaces/assets/ModelAssets.svelte
src/routes/_surfaces/assets/TableAssets.svelte

standardizes asset menus

---

package.json
src/common/database-service/DatabaseMetricsExplorerActions.ts
test/data/MetricsExplorer.data.ts

closes #690
Fixing leaderboard tests and re-enabling backend CI tests so that this gets caught in the PR itself.

Fixing tests and enabling CI tests

---

src/lib/util/humanize-numbers.ts

Add higher order shorthand symbols

---

src/routes/_surfaces/workspace/explore/ExploreContainer.svelte
src/routes/_surfaces/workspace/explore/time-series-charts/MeasureBigNumber.svelte

Show leaderboard on narrow screens

---

src/lib/components/metrics-definition/DimensionColumns.ts
src/lib/components/table-editable/ColumnConfig.ts
src/lib/components/table-editable/TableCellSelector.svelte

add validation for dimensions

---

src/routes/_surfaces/workspace/explore/ExploreContainer.svelte
src/routes/_surfaces/workspace/explore/ExploreHeader.svelte
src/routes/_surfaces/workspace/explore/leaderboards/LeaderboardDisplay.svelte

fixes dashboard right button alignment issue

---

src/common/database-service/DatabaseTimeSeriesActions.ts
src/routes/_surfaces/workspace/explore/time-controls/time-range-utils.ts

These are the minimal fixes needed to land the weekly timegrain into Eric's timegrain selector PR.

adds weekly timegrain

---

src/lib/components/menu/MenuItem.svelte

uses cursor-not-allowed when menu item is disabled

---

src/routes/_surfaces/workspace/explore/leaderboards/LeaderboardDisplay.svelte

removes leaderboards that are not valid

---

src/lib/components/column-profile/CollapsibleTableHeader.svelte
src/lib/util/command-click-action.ts
src/lib/util/os-detection.ts
src/routes/_surfaces/assets/TableAssets.svelte

fixes command click & standardizes the tooltip styling

---

src/lib/components/column-profile/CollapsibleTableHeader.svelte
src/routes/_surfaces/workspace/ModelWorkspaceHeader.svelte

removes the .sql part of the asset entry

---

docs/docs/defining-metrics.md
docs/sidebars.js

@godzig and @magorlick could you guys take a look at these docs? I'm sure there's a typo or two buried in here, but I also haven't worked with our documentation tools so I don't know how the formatting and stuff like that works—let me know if I'm on the wrong track here or if there are style guides or something that should be followed for documentation like this.
Marissa, also looking to you for any thoughts about the actual content regarding measures in specific.

Documentation about metrics definition

---

Duckdb-Dockerfile
scripts/entrypoint.sh

closes #738
Moving to ubuntu:focal image to make sure latest g++ version is available.

Fixing docker image

---

src/common/database-service/DatabaseMetricsExplorerActions.ts
src/common/database-service/utils.ts
src/common/rill-developer-service/MetricViewActions.ts
src/common/rill-developer-service/MetricsExplorerActions.ts
src/lib/redux-store/explore/explore-apis.ts
src/lib/svelte-query/queries/metric-view.ts
src/routes/_surfaces/workspace/explore/ExploreHeader.svelte
src/routes/_surfaces/workspace/explore/leaderboards/LeaderboardDisplay.svelte
src/routes/_surfaces/workspace/explore/time-controls/TimeControls.svelte
src/routes/_surfaces/workspace/explore/time-series-charts/MetricsTimeSeriesCharts.svelte
src/server/controllers/MetricViewController.ts

Moving big number to svelte-query

---

scripts/example-project.sh
src/cli/ExampleProjectCommand.ts

Fixing the example project command failing when run again.

Fixing docker compose example project

---

src/common/rill-developer-service/MeasuresActions.ts

Making expression column match case insensitive.

---

src/lib/components/leaderboard/LeaderboardListItem.svelte
src/routes/_surfaces/workspace/explore/leaderboards/DimensionLeaderboardEntry.svelte
src/routes/_surfaces/workspace/explore/leaderboards/DimensionLeaderboardEntrySet.svelte
src/routes/_surfaces/workspace/explore/leaderboards/Leaderboard.svelte

refines the loading animation a bit so it's less jarring
https://user-images.githubusercontent.com/95735/187312036-53b521f4-06e1-45e4-95d1-b45596dc050b.mp4

refines the loading animation for leaderboards

---

src/lib/components/icons/Calendar.svelte
src/routes/_surfaces/workspace/explore/ExploreHeader.svelte
src/routes/_surfaces/workspace/explore/filters/Filters.svelte
src/routes/_surfaces/workspace/explore/time-controls/TimeControls.svelte
src/routes/_surfaces/workspace/explore/time-controls/TimeRangeNameSelector.svelte

adds calendar icon; fixes spacing in dashboard header

---

.travis.yml
scripts/check_nightly.sh
scripts/upload.sh

Nightly releases

---

sql/pom.xml
sql/src/main/java/com/rilldata/calcite/CalciteToolbox.java
sql/src/main/java/com/rilldata/calcite/operators/RillOperatorTable.java
sql/src/main/java/com/rilldata/calcite/utility/CalciteUtils.java
sql/src/test/java/com/rilldata/CalciteTests.java
sql/src/test/java/com/rilldata/StaticSchemaTest.java

initial support for duckdb numeric operators

---

src/lib/util/humanize-numbers.ts

Fix humanize for negative numbers

---

src/lib/components/data-types/Base.svelte
src/lib/components/virtualized-table/core/Cell.svelte

Consistent handling of null strings

---

web-local/tailwind.config.cjs

Fix path for column profile colors

Fix tailwind config

---

web-local/src/lib/components/workspace/Model.svelte

Display last correct query results

---

sql/src/main/codegen/config.fmpp
sql/src/main/codegen/includes/create-metric.ftl
sql/src/main/codegen/includes/create-source.ftl
sql/src/main/java/com/rilldata/SqlConverter.java
sql/src/main/java/com/rilldata/SqlConverterEntrypoint.java
sql/src/main/java/com/rilldata/SqlConverterMain.java
sql/src/main/java/com/rilldata/calcite/CalciteToolbox.java
sql/src/main/java/com/rilldata/calcite/extensions/SqlCreateSource.java
sql/src/main/java/com/rilldata/calcite/models/ArtifactType.java
sql/src/main/java/com/rilldata/calcite/models/SqlCreateMetricsView.java
sql/src/main/java/com/rilldata/calcite/models/SqlCreateSource.java
sql/src/main/java/com/rilldata/calcite/validators/CreateMetricsViewValidator.java
sql/src/main/java/com/rilldata/calcite/validators/CreateSourceValidator.java
sql/src/main/java/com/rilldata/calcite/validators/S3ConnectorValidator.java
sql/src/main/java/com/rilldata/calcite/visitors/ExtractArtifact.java
sql/src/main/java/com/rilldata/calcite/visitors/MetricsViewExpander.java
sql/src/main/java/com/rilldata/protobuf/SqlNodeProto.proto
sql/src/main/java/com/rilldata/protobuf/SqlNodeProtoBuilder.java
sql/src/test/java/com/rilldata/CalciteTests.java

follow up on https://github.com/rilldata/rill-developer/pull/896 
This supports syntax parsing and protobuf serialization.

Create source syntax

---

web-local/src/common/data-modeler-service/ApplicationActions.ts
web-local/src/common/utils/getNextEntityId.ts
web-local/src/lib/components/assets/MetricsDefinitionAssets.svelte
web-local/src/lib/components/assets/ModelAssets.svelte
web-local/src/lib/components/assets/TableAssets.svelte

closes #973
Reusing existing code to handle deletion of an active entity.

Fixing deletion on 1st asset

---

web-local/build-tools/postinstall_runtime.sh
web-local/src/cli/ExampleProjectCommand.ts
web-local/src/common/database-service/getBinaryRuntimePath.ts

Handling spaces in project folder

---

web-local/src/common/database-service/DatabaseTableActions.ts

Removing the caught error logging

---

web-local/src/lib/components/dimension/DimensionTableConfig.ts
web-local/src/lib/components/virtualized-table/core/Cell.svelte
web-local/src/lib/components/virtualized-table/core/ColumnHeader.svelte
web-local/src/lib/components/virtualized-table/core/StickyHeader.svelte

Polish dimension table

---

web-local/src/lib/components/data-graphic/actions/scrub-action-factory.ts
web-local/src/lib/components/data-graphic/compositions/timestamp-profile/TimestampDetail.svelte

closes #990 
@willeppy let me know if this fixes the bug.

adds reactive functionality to scrub action; fixes TimestampDetail resize bug

---

docs/docs/install/binary.md

This PR cleans up a code snippet that was wrongly formatted in the docs.

Fix code example for nightly builds

---

package.json
runtime/package.json
web-local/src/common/config/DatabaseConfig.ts
web-local/src/common/connection/DuckDbConnection.ts
web-local/src/common/database-service/DuckDBClient.ts

- Adding a npm command for running runtime
- Ignoring all tables under rill schema

Adding better support for external go runtime

---

web-local/src/common/connection/DuckDbConnection.ts
web-local/src/common/constants.ts

Re-enabling periodic tables sync

---

web-local/src/common/database-service/DatabaseTableActions.ts
web-local/src/common/database-service/DuckDBClient.ts

Escaping columns in min max query

---

web-local/src/lib/components/leaderboard/LeaderboardHeader.svelte
web-local/src/lib/components/leaderboard/LeaderboardOptionsMenu.svelte
web-local/src/lib/components/virtualized-table/core/Cell.svelte
web-local/src/lib/components/virtualized-table/sections/TableCells.svelte
web-local/src/lib/components/viz/BarAndLabel.svelte

Fix dimension table nits

---

go.mod
go.sum
runtime/cmd/main.go
runtime/connectors/connectors.go
runtime/connectors/file/file.go
runtime/connectors/gcs/gcs.go
runtime/connectors/s3/s3.go
runtime/drivers/duckdb/connectors.go
web-local/src/server/adhoc-runtime.ts

There is some issue with our integration with duckdb where successive imports directly from s3/gcs leads to an invalid state. No plugins work in this state, hence successive imports do not work.
For now downloading the files locally and importing them as files into duckdb. No issues here.

Downloading s3 and gcs files for now

---

web-local/src/lib/components/button/Switch.svelte
web-local/src/lib/components/button/index.ts
web-local/src/routes/dev/switch/+page.svelte

This component is mean to be used in a few places:
- @djbarnwal we'd like to replace the include / exclude toggle in the filter pill menu with this + the word "Exclude". Off means include, on means exclude
- this component will be useful in many other places within the UI, and specifically for the upcoming period of period comparison functionality.

add switch component

---

web-common/src/runtime-client/gen/index.schemas.ts
web-local/src/lib/util/file-upload.ts

Using the correct field for file path

---

runtime/server/queries.go

At least partially fixes https://github.com/rilldata/rill-developer/issues/1044
No tests, verified manually. But we should really add that for these endpoints when we get bandwidth.

Fix NaN and Inf serialization

---

runtime/connectors/s3/s3.go
web-local/build-tools/postinstall_runtime.sh

Adding support for default aws region

---

web-local/src/common/utils/duplicateNameUtils.spec.ts
web-local/src/lib/redux-store/metrics-definition/metrics-definition-selectors.ts
web-local/src/lib/redux-store/source/source-apis.ts

Using getName to generate metrics definition names

---

web-local/src/lib/components/assets/sources/AddSourceModal.svelte
web-local/src/lib/components/tab/Tab.svelte

fixes refresh issue on already selected tab

---

web-local/src/lib/components/chip/removable-list-chip/RemovableListChip.svelte
web-local/src/lib/components/chip/removable-list-chip/RemovableListMenu.svelte
web-local/src/lib/components/dimension/DimensionHeader.svelte
web-local/src/lib/components/workspace/explore/filters/Filters.svelte

Make filter toggle include/exclude mode

---

web-local/src/common/rill-developer-service/MetricsDefinitionActions.ts

closes #554
@bcolloran this is where the changes will have to be made to auto generate with label and description. Lemme know if this is what you wanted. Feel free to change the exact text.
@magorlick FYI

Auto generating label and description for measure

---

web-local/src/common/database-service/DatabaseTimeSeriesActions.ts
web-local/src/common/rill-developer-service/MetricsViewActions.ts
web-local/src/lib/components/assets/dashboards/MetricsDefinitionAssets.svelte
web-local/src/lib/components/assets/models/ModelAssets.svelte
web-local/src/lib/components/assets/sources/TableAssets.svelte
web-local/src/lib/components/assets/sources/refreshSource.ts

closes #1117
Fixing reactivity of remote sources around delete and refresh.

Fixing reactivity of new remote sources

---

.travis.yml
build-tools/replace_package_type.cjs
package.json
tsconfig.json
web-local/jest.config.json
web-local/package.json
web-local/src/cli/build-vercel-pkg.ts
web-local/src/common/connection/DuckDbConnection.ts
web-local/src/common/data-modeler-service/TableActions.ts
web-local/src/common/database-service/getBinaryRuntimePath.ts
web-local/src/lib/components/assets/RenameAssetModal.svelte
web-local/src/lib/components/assets/sources/AddSourceModal.svelte
web-local/src/lib/components/assets/sources/LocalSource.svelte
web-local/src/lib/components/assets/sources/RemoteSource.svelte
web-local/src/lib/components/assets/sources/TableAssets.svelte
web-local/src/lib/components/inspector/SourceInspector.svelte
web-local/src/lib/components/overlay/FileDrop.svelte
web-local/src/lib/components/workspace/source/SourceWorkspaceHeader.svelte
web-local/src/lib/connectors/schemas.ts
web-local/src/lib/util/file-upload.ts
web-local/src/moduleAlias.ts
web-local/src/server/ExpressServer.ts
web-local/src/server/RillDeveloper.ts
web-local/vite.config.ts

Fixing binary build

---

runtime/server/migrations.go
runtime/server/migrations_test.go
web-local/build-tools/postinstall_runtime.sh

Updating refresh on during a source overwrite

---

web-local/src/lib/util/extract-table-name.ts
web-local/test/unit/ExtractTableName.spec.ts

Fix ingestion of files with number and hypen

---

web-local/src/lib/components/assets/sources/TableAssets.svelte
web-local/src/lib/components/icons/Import.svelte
web-local/src/lib/components/workspace/source/SourceWorkspaceHeader.svelte

Addresses https://github.com/rilldata/rill-developer/issues/1103

Add icon & copy for local file uploads

---

web-local/src/lib/components/dimension/DimensionTable.svelte
web-local/src/lib/components/search/Search.svelte

Fixes #1137 
Also fixes the case when no dimension column header is show if search results is 0.

Catch return on search

---

web-local/src/common/utils/cliConfirmation.ts

fixes case insensitivity in CLI

---

web-local/src/lib/application-config.ts
web-local/src/lib/components/virtualized-table/core/Cell.svelte
web-local/src/lib/components/workspace/explore/leaderboards/DimensionLeaderboardEntrySet.svelte

fixes the long description issue

---

package-lock.json
web-local/src/common/database-service/DatabaseMetricsExplorerActions.ts
web-local/src/common/database-service/DatabaseTableActions.ts
web-local/src/common/database-service/DatabaseTimeSeriesActions.ts
web-local/src/common/database-service/columnUtils.ts
web-local/src/common/database-service/utils.ts
web-local/test/data/MetricsExplorer.data.ts
web-local/test/functional/metrics-view-edge-cases.spec.ts

closes #1133
Adding column escaping to all queries that reference column in metrics view.

Adding column escaping to metrics view

---

web-local/src/lib/redux-store/utils/api-utils.ts

Moving measure validation to fix message issue

---

web-local/src/common/data-modeler-service/ModelActions.ts
web-local/src/common/rill-developer-service/MetricsDefinitionActions.ts
web-local/src/common/stateInstancesFactory.ts
web-local/src/common/utils/duplicateNameUtils.spec.ts

Using getName for new model and metrics view

---

web-local/src/lib/components/dimension/DimensionTable.svelte
web-local/src/lib/components/virtualized-table/core/Cell.svelte

Fix exclude colors

---

web-local/src/common/rill-developer-service/MetricsViewActions.ts

Adding better error handling in metrics views

---

web-local/src/common/data-modeler-service/ProfileColumnActions.ts
web-local/src/lib/util/formatters.ts

Handling decimal data types

---

web-local/src/lib/application-state-stores/explorer-stores.ts
web-local/src/lib/components/button/Switch.svelte
web-local/src/lib/components/chip/removable-list-chip/RemovableListMenu.svelte
web-local/src/lib/components/dimension/DimensionHeader.svelte
web-local/src/lib/components/leaderboard/LeaderboardHeader.svelte
web-local/src/lib/components/leaderboard/LeaderboardOptionsMenu.svelte
web-local/src/lib/components/menu/core/Menu.svelte
web-local/src/lib/components/workspace/explore/filters/Filters.svelte
web-local/src/lib/components/workspace/explore/leaderboards/Leaderboard.svelte
web-local/src/routes/dev/switch/+page.svelte

Closes #1186 Also addresses # #1159

Enhance switch and fix toggle

---

web-local/src/lib/components/workspace/explore/time-series-charts/MetricsTimeSeriesCharts.svelte

Make axis and point sticky when overflow

---

web-local/build-tools/postinstall_runtime.sh

This increases the runtime version, so we can see the updated connector tooltips in the frontend.

Bump runtime version

---

web-local/src/common/database-service/DatabaseTimeSeriesActions.ts

Fixing timeseries alias clashes with model columns

---

web-local/src/common/data-modeler-service/ModelActions.ts
web-local/src/common/database-service/DatabaseTableActions.ts
web-local/test/functional/ModelQuery.spec.ts

Renaming the temporary view on model rename

---

web-local/src/common/database-service/utils.spec.ts
web-local/src/common/database-service/utils.ts

Handling empty filters entry for a dimension in dashboard queries

---

runtime/server/repos.go
web-common/src/runtime-client/gen/index.schemas.ts
web-local/build-tools/postinstall_runtime.sh
web-local/src/lib/util/file-upload.ts

Permanently fixes temporary solution in https://github.com/rilldata/rill-developer/commit/2795e74c61bf4b32cd4d03ebc73965ee39579c90

Align file upload response object with generated type

---

runtime/drivers/duckdb/migrate.go
web-local/build-tools/postinstall_runtime.sh

Fixes https://github.com/rilldata/rill-developer/issues/1224

Merge WAL into .db after each DuckDB migration

---

runtime/services/catalog/artifacts/artifacts.go
runtime/services/catalog/artifacts/artifacts_test.go
runtime/services/catalog/artifacts/sql/sql.go
runtime/services/catalog/artifacts/yaml/objects.go
runtime/services/catalog/artifacts/yaml/yaml.go
runtime/services/catalog/migrations_test.go
runtime/services/catalog/migrator/migrator.go

Editable artifacts enhancement

---

web-common/orval.config.ts
web-common/src/runtime-client/gen/index.schemas.ts
web-common/src/runtime-client/gen/runtime-service/runtime-service.ts

Note that it also re-generates queries/mutations other new runtime endpoints.
Closes https://github.com/rilldata/rill-developer/issues/1233

Generate MetricsViewMeta as a query. 

---

runtime/services/catalog/migrations.go
runtime/services/catalog/migrations_test.go
runtime/services/catalog/testutils/testutils.go

Errored out items were not being picked up for migration.

Handling errored items

---

runtime/drivers/file/repo.go
runtime/server/catalog_test.go
runtime/services/catalog/catalog_to_protobuf.go
runtime/services/catalog/migrations.go
runtime/services/catalog/migrations_test.go
runtime/services/catalog/migrator/models/models.go
runtime/services/catalog/testutils/testutils.go

Removed objects not appearing in affected paths

---

web-local/src/lib/components/navigation/NavigationEntry.svelte

fixes  #1248

---

web-local/src/cli/StartCommand.ts

Safeguard open on rill start

---

runtime/cmd/main.go
runtime/server/column_api.go
web-common/orval.config.ts
web-common/src/runtime-client/gen/runtime-service/runtime-service.ts
web-local/src/lib/application-state-stores/explorer-stores.ts
web-local/src/lib/components/dimension/DimensionHeader.svelte
web-local/src/lib/components/leaderboard/LeaderboardMeasureSelector.svelte
web-local/src/lib/components/navigation/dashboards/MetricsDefinitionAssets.svelte
web-local/src/lib/components/workspace/explore/Explore.svelte
web-local/src/lib/components/workspace/explore/ExploreHeader.svelte
web-local/src/lib/components/workspace/explore/leaderboards/DimensionDisplay.svelte
web-local/src/lib/components/workspace/explore/leaderboards/Leaderboard.svelte
web-local/src/lib/components/workspace/explore/leaderboards/LeaderboardDisplay.svelte
web-local/src/lib/components/workspace/explore/time-controls/TimeControls.svelte
web-local/src/lib/components/workspace/explore/time-series-charts/MetricsTimeSeriesCharts.svelte
web-local/src/lib/components/workspace/metrics-def/MetricsDefWorkspace.svelte
web-local/src/lib/components/workspace/model/inspector/header/CreateDashboardButton.svelte
web-local/src/lib/svelte-query/queries/metrics-views/metadata.ts
web-local/src/lib/util/convertTimestampPreview.ts
web-local/src/routes/(application)/dashboard/[name]/+page.svelte
web-local/src/routes/(application)/dashboard/[name]/+page.ts

Migrate dashboards to use new APIs

Migrate dashboards

---

web-local/src/common/database-service/DatabaseTimeSeriesActions.ts
web-local/src/lib/application-state-stores/metrics-internal-store.ts
web-local/src/lib/components/workspace/explore/ExploreHeader.svelte
web-local/src/lib/components/workspace/explore/time-controls/TimeControls.svelte
web-local/src/lib/components/workspace/explore/time-controls/TimeRangeNameSelector.svelte
web-local/src/lib/components/workspace/explore/time-controls/time-range-utils.spec.ts
web-local/src/lib/components/workspace/explore/time-controls/time-range-utils.ts
web-local/src/lib/components/workspace/explore/time-series-charts/MetricsTimeSeriesCharts.svelte
web-local/src/lib/util/convertTimestampPreview.ts
web-local/test/data/estimate-ideal-rollup-interval.data.ts

Migrate time controls to runtime API

---

web-local/src/lib/components/workspace/explore/ExploreHeader.svelte
web-local/src/lib/components/workspace/explore/time-controls/TimeRangeNameSelector.svelte

Show label for dashboard and fix lint error

Show label for dashboard

---

web-local/src/lib/components/button/IconButton.svelte
web-local/src/lib/components/column-profile/ColumnProfile.svelte
web-local/src/lib/components/column-profile/data-graphics/details/NumericPlot.svelte
web-local/src/lib/components/column-profile/data-graphics/details/TopK.svelte
web-local/src/lib/components/column-profile/data-graphics/sparks/TimestampSpark.svelte
web-local/src/lib/components/data-graphic/compositions/timestamp-profile/TimestampSpark.svelte
web-local/src/lib/components/data-graphic/guides/DynamicallyPlacedLabel.svelte
web-local/src/lib/components/data-graphic/guides/Rug.svelte
web-local/src/lib/components/data-graphic/marks/HistogramPrimitive.svelte
web-local/src/lib/components/workspace/model/ModelBody.svelte
web-local/src/lib/components/workspace/model/inspector/ModelInspectorModelProfile.svelte

fixes existing eslint errors

---

web-local/src/lib/components/column-profile/queries.ts
web-local/src/lib/util/convertTimestampPreview.ts

fixes timestamp key deletion issue in convertTimestampPreview

---

cli/cmd/source/add.go
runtime/artifacts/artifactsv0/project.go
runtime/services/catalog/artifacts/artifacts.go
runtime/services/catalog/artifacts/artifacts_test.go

Fixing issues around source add from cli

---

runtime/services/catalog/migrations.go
runtime/services/catalog/migrations_test.go
web-local/src/lib/components/navigation/RenameAssetModal.svelte
web-local/src/lib/components/workspace/model/ModelBody.svelte
web-local/src/lib/components/workspace/source/SourceWorkspaceHeader.svelte
web-local/src/lib/svelte-query/actions.ts

Adding error for rename to other types

---

web-local/src/lib/components/workspace/explore/leaderboards/LeaderboardDisplay.svelte
web-local/src/lib/components/workspace/explore/time-series-charts/MeasureBigNumber.svelte
web-local/src/lib/components/workspace/explore/time-series-charts/MetricsTimeSeriesCharts.svelte

Before this PR: the big number & leaderboards were not picking up the number formatting set in the dashboard config.
After this PR: number formatting works as expected.

Fix number formatting

---

web-local/src/lib/components/forms/SubmissionError.svelte
web-local/src/lib/components/navigation/sources/LocalSource.svelte
web-local/src/lib/components/navigation/sources/RemoteSource.svelte
web-local/src/lib/components/navigation/sources/createSource.ts
web-local/src/lib/components/navigation/sources/errors.ts
web-local/src/lib/components/navigation/sources/refreshSource.ts
web-local/src/lib/components/workspace/source/SourceWorkspace.svelte
web-local/src/lib/svelte-query/actions.ts
web-local/src/lib/util/file-upload.ts

This PR:
- adds some good-enough error messaging if a source artifact exists but isn't in the catalog
- adds in error hnadling for ingestion of local source file through UI, which doesn't look like ever made it into this feature

good-enough error messaging for invalid sources

---

web-local/src/lib/components/navigation/Navigation.svelte
web-local/src/lib/components/navigation/dashboards/MetricsDefinitionAssets.svelte
web-local/src/lib/components/navigation/models/ModelMenuItems.svelte
web-local/src/lib/components/navigation/models/createModel.ts
web-local/src/lib/components/navigation/sources/SourceMenuItems.svelte
web-local/src/lib/components/navigation/sources/createSource.ts
web-local/src/lib/components/navigation/sources/refreshSource.ts
web-local/src/lib/components/workspace/metrics-def/MetricsDefWorkspace.svelte
web-local/src/lib/components/workspace/model/ModelBody.svelte
web-local/src/lib/components/workspace/model/inspector/header/CreateDashboardButton.svelte
web-local/src/lib/components/workspace/model/inspector/header/ModelInspectorHeader.svelte
web-local/src/lib/svelte-query/actions.ts
web-local/src/lib/util/entity-mappers.ts
web-local/src/routes/(application)/dashboard/[name]/+page.ts
web-local/src/routes/(application)/dashboard/[name]/edit/+page.svelte
web-local/src/routes/(application)/dashboard/[name]/edit/+page.ts

Making sure the file name is consistent across actions by using a method all other components use.

Using the common method for mapping to file name

---

web-local/src/lib/svelte-query/dashboards.ts
web-local/src/lib/svelte-query/models.ts
web-local/src/lib/svelte-query/sources.ts

This PR alphabetically sorts files in the sidebar in a case-insensitive way.

Sort files case-insensitive

---

runtime/services/catalog/migrations_test.go
runtime/services/catalog/migrator/metrics_views/metrics_views.go

If a dashboard is missing dimension or measure it is an error in the UI. Making it an error in backend to keep things consistent.

Missing dimension or measure is an error

---

runtime/drivers/duckdb/connectors.go
runtime/drivers/duckdb/connectors_test.go
web-local/src/lib/types.ts
web-local/src/lib/util/file-upload.ts

Treating .txt files as csv and consuming as local file in connectors.

Adding support for txt files

---

web-local/src/lib/components/column-profile/column-types/NumericProfile.svelte
web-local/src/lib/components/column-profile/queries.ts
web-local/src/lib/components/workspace/explore/filters/Filters.svelte
web-local/src/lib/components/workspace/explore/leaderboards/DimensionDisplay.svelte
web-local/src/lib/components/workspace/explore/leaderboards/Leaderboard.svelte
web-local/src/lib/components/workspace/explore/time-controls/TimeControls.svelte

Introduced in https://github.com/rilldata/rill-developer/pull/1424

Fix column names bug

---

web-local/src/lib/svelte-query/invalidation.ts

Fixing dashboard invalidations when model column is changed.

Model to dashboard invalidations

---

web-local/src/lib/components/navigation/NavigationEntry.svelte
web-local/src/lib/components/navigation/dashboards/MetricsDefinitionAssets.svelte

This PR cleans up some warnings in the browser console.

Cleanup browser console

---

cli/pkg/local/app.go
runtime/caches.go
runtime/services/catalog/catalog.go
runtime/services/catalog/migrations.go
runtime/services/catalog/migrations_test.go

Temporary: Adding logs around reconciliation.
End goal should be adding an async job support.

Adding logs around reconciliation

---

web-local/src/lib/components/Editor.svelte

Add SQL keywords

---

web-local/src/lib/components/navigation/NavigationHeader.svelte
web-local/src/lib/components/navigation/dashboards/MetricsDefinitionAssets.svelte
web-local/src/lib/components/navigation/sources/TableAssets.svelte
web-local/src/lib/components/tooltip/SlidingWords.svelte
web-local/src/lib/components/workspace/model/inspector/ModelInspectorModelProfile.svelte

This animation has been broken since July, so I've retooled it given the switch to Inter.

fixes slide animation; updates toggle tooltip text for sections

---

web-common/src/runtime-client/http-client.ts
web-local/src/lib/components/column-profile/ColumnProfile.svelte
web-local/src/lib/components/column-profile/column-types/NumericProfile.svelte
web-local/src/lib/components/column-profile/column-types/TimestampProfile.svelte
web-local/src/lib/components/column-profile/column-types/VarcharProfile.svelte
web-local/src/lib/components/column-profile/column-types/details/NumericPlot.svelte
web-local/src/lib/components/column-profile/column-types/details/TopK.svelte
web-local/src/lib/components/column-profile/queries.ts
web-local/src/lib/components/data-graphic/marks/Rug.svelte
web-local/src/lib/http-request-queue/HttpRequestQueue.spec.ts
web-local/src/lib/http-request-queue/HttpRequestQueue.ts
web-local/src/lib/http-request-queue/HttpRequestQueueTypes.ts
web-local/src/lib/http-request-queue/priorities.ts
web-local/src/lib/util/fetchWrapper.ts
web-local/test/ui/utils/helpers.ts

Adding column priority for open profiles

---

web-local/src/lib/components/workspace/model/ModelBody.svelte

Removing model path filter

---

runtime/connectors/gcs/gcs.go

Adding support for reading public buckets when logged out

---

web-local/src/lib/components/column-profile/ColumnProfileIcon.svelte
web-local/src/lib/components/column-profile/ProfileContainer.svelte
web-local/src/lib/components/column-profile/column-types/NumericProfile.svelte
web-local/src/lib/components/column-profile/column-types/TimestampProfile.svelte
web-local/src/lib/components/column-profile/column-types/VarcharProfile.svelte
web-local/src/lib/components/column-profile/queries.ts

adds a spinner to indicate that a profile is fetching

---

web-local/src/lib/components/CollapsibleSectionTitle.svelte
web-local/src/lib/components/navigation/dashboards/MetricsDefinitionAssets.svelte
web-local/src/lib/components/navigation/models/ModelAssets.svelte
web-local/src/lib/components/navigation/sources/TableAssets.svelte

Emphasize nav headers

---

web-local/src/lib/components/navigation/Footer.svelte

Change footer's info icon back to gray

---

web-local/src/lib/components/navigation/RenameAssetModal.svelte
web-local/src/lib/components/workspace/metrics-def/MetricsDefDisplayNameInput.svelte
web-local/src/lib/components/workspace/metrics-def/MetricsDefModelSelector.svelte
web-local/src/lib/components/workspace/metrics-def/MetricsDefTimeColumnSelector.svelte
web-local/src/lib/components/workspace/metrics-def/MetricsDefWorkspace.svelte
web-local/src/lib/components/workspace/metrics-def/MetricsDefWorkspaceHeader.svelte
web-local/src/lib/components/workspace/model/ModelWorkspaceHeader.svelte
web-local/src/lib/components/workspace/source/SourceWorkspaceHeader.svelte
web-local/src/lib/svelte-query/actions.ts

Add editable display name field to Metrics Config UI

---

runtime/services/catalog/migrations.go
runtime/services/catalog/migrations_test.go
runtime/services/catalog/testutils/testutils.go

closes #1515
Turned out to be a bug in reconcile.

Fixing refresh with valid data

---

web-common/src/components/data-graphic/compositions/timestamp-profile/TimestampDetail.svelte
web-common/src/components/data-graphic/compositions/timestamp-profile/TimestampProfileSummary.svelte
web-common/src/lib/formatters.ts
web-local/src/lib/components/column-profile/column-types/TimestampProfile.svelte

adds back in nicer estimated timegrain labels

---

web-local/src/lib/http-request-queue/HttpRequestQueue.ts

Fixing navigation blocked during profiling

---

docs/blog/0.18.md

@himadrisingh , can we merge the release notes and cut the release tomorrow at 9am PST?

Release notes 0.18

---

web-common/src/features/models/workspace/Editor.svelte

maintains focus when user clicks editor multiple times

---

web-common/src/features/models/createModel.ts
web-common/src/features/models/workspace/Editor.svelte
web-common/src/features/models/workspace/ModelBody.svelte
web-common/src/features/models/workspace/ModelWorkspace.svelte
web-local/src/routes/(application)/model/[name]/+page.svelte
web-local/src/routes/(application)/model/[name]/+page.ts

brought up in #1574 ~ this will focus the editor on model creation.

focuses editor on model creation

---

web-local/src/lib/svelte-query/actions.ts
web-local/src/lib/svelte-query/invalidation.ts

Remove old model queries

---

scripts/install.sh

need to provide the version with format `v0.XX.0`, same as the tag

To install specific version

---

web-common/src/features/models/workspace/ModelWorkspaceHeader.svelte
web-common/src/features/sources/workspace/SourceWorkspaceHeader.svelte
web-local/src/lib/application-state-stores/application-store.ts
web-local/src/lib/components/column-profile/ColumnProfileIcon.svelte
web-local/src/lib/components/workspace/core/WorkspaceHeader.svelte
web-local/src/lib/components/workspace/core/WorkspaceHeaderStatusSpinner.svelte
web-local/src/lib/components/workspace/metrics-def/MetricsDefWorkspaceHeader.svelte
web-local/src/lib/http-request-queue/HttpRequestQueue.ts

Add running status spinner to app

---

web-local/src/lib/components/workspace/explore/metrics-container/MetricsTimeSeriesCharts.svelte
web-local/src/lib/components/workspace/explore/metrics-container/TimeSeriesBody.svelte

Fix non humanize shorthand in chart axis

---

web-local/src/lib/components/column-profile/column-types/index.ts

Show profiles for decimals

---

web-common/src/components/forms/SubmissionError.svelte

Set max width for submission error

---

web-common/src/components/overlay/Overlay.svelte

Block all keydown when overlay

---

runtime/connectors/s3/s3.go

Infer s3 bucket's region if not provided

---

web-local/src/lib/components/column-profile/column-types/NumericProfile.svelte
web-local/src/lib/components/column-profile/column-types/TimestampProfile.svelte
web-local/src/lib/components/column-profile/column-types/VarcharProfile.svelte
web-local/src/lib/components/column-profile/column-types/sparks/NullPercentageSpark.svelte

Show fetching status for null profile

---

runtime/drivers/duckdb/olap.go

For context, see the Slack [conversation](https://rilldata.slack.com/archives/C01A9DYP013/p1674642310701869?thread_ts=1674608903.071089&cid=C01A9DYP013) and DuckDB Discord [conversation](https://discord.com/channels/909674491309850675/921100573732909107/1067854703012102304).
This reduced reconcile runtime for the use case from 220ms to 60ms on my machine.
A flaw of using temporary views instead of prepared statements is that it won't validate other statements than `SELECT` (like `INSERT`, etc.). I don't think we'll ever need that, and if we do, I think this performance improvement is worth it in the meantime.

Validate dry run queries using temp views

---

web-local/src/lib/components/preview-table/PreviewTable.svelte

Fix resize of columns for Preview Table

---

web-local/src/routes/(application)/source/[name]/+page.svelte

uses path instead of table hash for embedded source view

---

web-common/src/features/models/workspace/ModelBody.svelte

Fixing invaliding model file

---

runtime/queries/column_topk.go
runtime/queries/column_topk_test.go
runtime/server/queries_columns_test.go

Closes https://github.com/rilldata/rill-developer/issues/1708

Support complex top K values

---

web-local/src/lib/components/column-profile/column-types/details/TopK.svelte
web-local/src/lib/components/virtualized-table/core/Cell.svelte

missed this the first time around w/ the nested types PR.

adds JSON stringified copy values for nested types

---

web-common/src/layout/navigation/NavigationEntry.svelte

Application was crashing without this import.

Fix missing import

---

web-common/src/components/data-graphic/actions/outline.ts
web-common/src/components/data-graphic/guides/DynamicallyPlacedLabel.svelte

fixes dynamically placed label bug with a `MutationObserver`

---

web-common/src/features/dashboards/DashboardAssets.svelte
web-common/src/layout/navigation/NavigationEntry.svelte

removes context menu from readonly dashboard nav entries

---

go.mod
go.sum
runtime/drivers/catalog_test.go
runtime/drivers/duckdb/connectors.go
runtime/drivers/duckdb/duckdb.go
runtime/drivers/duckdb/information_schema.go
runtime/queries/table_columns.go
web-common/src/features/sources/add-source/LocalSource.svelte
web-common/src/features/sources/add-source/file-upload.ts
web-common/src/features/sources/workspace/SourceInspector.svelte
web-local/src/lib/types.ts

Closes https://github.com/rilldata/rill-developer/issues/1768

Upgrade to DuckDB 0.7

---

runtime/connectors/s3/s3.go

s3 public bucket fix

---

cli/cmd/auth/auth.go
cli/cmd/auth/login.go
cli/cmd/auth/logout.go
cli/cmd/org/close.go
cli/cmd/org/create.go
cli/cmd/org/edit.go
cli/cmd/org/invite.go
cli/cmd/org/members.go
cli/cmd/org/org.go
cli/cmd/org/show.go
cli/cmd/org/switch.go
cli/cmd/project/connect.go
cli/cmd/project/delete.go
cli/cmd/project/edit.go
cli/cmd/project/project.go
cli/cmd/project/show.go
cli/cmd/project/status.go
cli/cmd/root.go

see https://github.com/rilldata/rill-developer/issues/1783

Admin CLI: auth, org, project

---

web-common/src/features/dashboards/time-controls/time-range-utils.ts

Set defaults as per - https://www.notion.so/rilldata/Refine-default-time-grain-choices-for-each-time-range-0edfb80f4be1495885be16465afb3dec

Fix time defaults and use constants

---

web-local/src/lib/metrics/ActiveEventHandler.ts

Fire active event only if page was active within a minute

---

web-common/src/components/column-profile/sort-utils.ts
web-common/src/components/data-types/DataTypeIcon.svelte
web-common/src/lib/duckdb-data-types.ts
web-common/src/lib/formatters.ts

fixes UI issues with nested structs

---

web-common/src/features/dashboards/time-controls/NoTimeDimensionCTA.svelte

Disable CTA for read only dashboard

---

web-common/src/features/dashboards/time-controls/NoTimeDimensionCTA.svelte

`main` has a bug due to PRs not having main merged into them.

replaces old runtimeStore with featureFlags store

---

runtime/drivers/git/git.go

Closes https://github.com/rilldata/rill-developer/issues/1837

Git driver: branch name support, DSN object

---

web-local/src/routes/(application)/dashboard/+page.ts
web-local/src/routes/(application)/model/+page.ts
web-local/src/routes/(application)/source/+page.ts

adds redirect to mid-level routes to the root

---

web-common/src/features/dashboards/time-series/MeasureChart.svelte

fixes y extent inflation value to 5/6 in measure chart for now

---

admin/database/database.go
admin/database/postgres/migrate.go
admin/database/postgres/postgres.go
admin/database/postgres/tx.go
admin/pkg/nameseeds/nameseeds.go
admin/user.go

This PR also adds transactions support to `admin/database`

Create initial org when creating user

---

runtime/drivers/duckdb/connectors.go

cc @k-anshul 
```
Ingestion failed for "" : Invalid Input Error: Maximum line size of 2097152 bytes exceeded on line 1!
```

Increase duckdb json size limit

---

runtime/drivers/duckdb/connectors.go

Reverts rilldata/rill-developer#1966

Revert "Increase duckdb json size limit"

---

web-common/src/components/data-graphic/marks/MultiMetricMouseoverLabel.svelte
web-common/src/components/data-types/Base.svelte
web-common/src/components/data-types/FormattedDataType.svelte
web-common/src/components/data-types/Interval.svelte
web-common/src/components/data-types/Number.svelte
web-common/src/components/data-types/PercentageChange.svelte
web-common/src/components/data-types/Timestamp.svelte
web-common/src/components/data-types/Varchar.svelte
web-common/src/components/data-types/type-utils.ts
web-common/src/components/virtualized-table/core/Cell.svelte
web-common/src/components/virtualized-table/core/ColumnHeader.svelte
web-common/src/components/virtualized-table/core/StickyHeader.svelte
web-common/src/components/virtualized-table/sections/ColumnHeaders.svelte
web-common/src/components/virtualized-table/sections/TableCells.svelte
web-common/src/components/virtualized-table/types.d.ts
web-common/src/features/dashboards/dimension-table/DimensionDisplay.svelte
web-common/src/features/dashboards/dimension-table/DimensionTable.svelte
web-common/src/features/dashboards/dimension-table/DimensionTableConfig.ts
web-common/src/features/dashboards/dimension-table/dimension-table-utils.ts
web-common/src/features/dashboards/humanize-numbers.ts
web-common/src/features/dashboards/leaderboard/DimensionLeaderboardEntrySet.svelte
web-common/src/lib/formatters.ts

Add comparison values to Dimension table

---

web-common/src/components/column-profile/column-types/details/TopK.svelte

Fix nested object copy

---

web-common/src/components/VirtualizedGrid.svelte
web-common/src/features/dashboards/proto-state/fromProto.ts

Removes errors and stale log statement.

Cleanup console messages

---

web-common/src/features/dashboards/proto-state/toProto.ts

Url Encoding dashboard url state

---

web-common/src/components/data-types/FormattedDataType.svelte
web-common/src/components/data-types/MeasureChange.svelte
web-common/src/components/tooltip/TooltipDescription.svelte
web-common/src/components/tooltip/TooltipTitle.svelte
web-common/src/components/virtualized-table/core/ColumnHeader.svelte
web-common/src/components/virtualized-table/sections/ColumnHeaders.svelte
web-common/src/features/dashboards/big-number/MeasureBigNumber.svelte
web-common/src/features/dashboards/dimension-table/DimensionDisplay.svelte
web-common/src/features/dashboards/dimension-table/dimension-table-utils.ts
web-local/src/lib/types.ts

- Removes delta percentage column if the selected measure has percentage formatting
- In dimension table column header tooltip add description and the shortcut to sort column

Comparison table fixes

---

admin/github.go
admin/server/organizations.go
admin/user.go

The github push event is still missing. Adding some more logs to debug.

Adding more temporary logs

---

admin/database/database.go
admin/database/postgres/migrations/0009.sql
admin/database/postgres/migrations/0010.sql
cli/cmd/org/members.go
cli/cmd/project/members.go

viewer role

---

admin/database/database.go
admin/database/postgres/postgres.go
admin/server/organizations.go

remove user from all usergroup as well upon removal

proper user cleanup

---

web-admin/src/components/navigation/BreadcrumbItem.svelte
web-admin/src/components/navigation/Breadcrumbs.svelte
web-admin/src/routes/[organization]/+page.svelte
web-admin/src/routes/[organization]/[project]/+layout.svelte
web-admin/src/routes/[organization]/[project]/+page.svelte
web-common/src/components/icons/CaretDownIcon.svelte

This PR:
- Adds dropdown menus to the breadcrumbs
- Edits the organization page to only show when the user has 0 projects
- Edits the project page to only show when the user has 0 dashboards

Add navigation via breadcrumb dropdown menus

---

web-admin/src/components/deployments/DeploymentStatusChip.svelte
web-admin/src/routes/[organization]/[project]/[dashboard]/+page.svelte

This PR fixes reactivity in a couple places. Especially noticeable is when changing dashboards via the new breadcrumb dropdown.

Fix dashboard dropdown reactivity

---

runtime/queries/metricsview_toplist.go

To enhance Druid query performance, refrain from using "ORDER BY true"

---

cli/cmd/deploy/deploy.go
cli/cmd/org/create.go
cli/cmd/org/switch.go

- Check for valid Rill project and Github remote before auth
- Create org based on Github account name after verifying Github access
- Minor language and formatting changes

Review rill deploy

---

admin/server/server.go

Addresses quick fix from https://github.com/rilldata/rill-developer/commit/246fa63d28b9870383c13860ce52e513698166c4

Admin: Restore CLI version check

---

web-admin/src/components/navigation/Breadcrumbs.svelte

This PR improves the dashboard breadcrumb:
- Gets the list of valid dashboards by querying the catalog
- Uses a dashboard's display name (if it exists), rather than the file name
Contributes to #2109

Improve dashboard breadcrumb

---

cli/cmd/deploy/deploy.go
cli/pkg/gitutil/gitutil.go

closes #2098 
Prompts a user for confirmation in case there are changes in local repository.

confirm prompt on local changes

---

web-admin/src/components/navigation/TopNavigationBar.svelte

adds Ask for help link in nav, per design

---

web-admin/src/components/home/ProjectList.svelte

removes tooltip from project link on homepage

---

cli/cmd/deploy/deploy.go
runtime/compilers/rillv1beta/connector.go
runtime/connectors/connectors.go
runtime/connectors/gcs/gcs.go
runtime/connectors/https/https.go
runtime/connectors/localfile/file.go
runtime/connectors/s3/s3.go

closes #2069 
Additionally removed asking s3 region in credentials prompt since region can also be configured in sources

infer if sources are public

---

web-admin/src/components/navigation/Breadcrumbs.svelte

Remove project status from breadcrumb

---

web-common/src/components/data-types/Base.svelte
web-common/src/components/data-types/Varchar.svelte
web-common/src/features/dashboards/leaderboard/DimensionLeaderboardEntrySet.svelte

Closes #2123
based on https://www.notion.so/rilldata/Handling-nulls-across-the-dashboard-fe48846240604b07b273db24ef35926b

Null fixes in the dashboard

---

web-common/src/features/dashboards/time-series/MeasureValueMouseover.svelte

Remove NaN label from above cases

Remove NaN% from hover label

---

docs/docs/references/project-files.md
examples/ad_bids/rill.yaml
examples/default/rill.yaml
examples/sf_props/rill.yaml
runtime/compilers/rillv1beta/project.go
runtime/services/catalog/artifacts/artifacts_test.go
runtime/services/catalog/artifacts/yaml/objects.go
web-common/src/features/metrics-views/metrics-internal-store.ts
web-common/src/features/metrics-views/workspace/config-parameters/DisplayNameInput.svelte
web-common/src/layout/navigation/Navigation.svelte
web-common/src/layout/navigation/ProjectTitle.svelte
web-local/src/routes/(application)/dashboard/[name]/edit/+page.svelte

Update all configs to use `title`

---

web-admin/src/components/errors/error-utils.ts

Handle 401 errors by redirecting to the login page

---

runtime/compilers/rillv1beta/connector.go
runtime/compilers/rillv1beta/connector_test.go

Adding support for checking anonymous access to embedded sources during deploy.

Check embedded sources for anonymous access

---

web-common/src/features/models/workspace/Editor.svelte

Fixes  #2074 
Don't see any commits which change the existing Editor CSS. Also codemirror packages haven't been updated recently. Not sure what was going wrong. Have added new styles which fixes the gutter background. Also increased font size to 13px.

Fix editor gutter and fontSize

---

web-common/src/features/dashboards/time-series/MeasureChart.svelte

Show line chart when no prev data

---

web-admin/src/components/home/WelcomeMessage.svelte
web-admin/src/routes/+page.svelte

This handles the case on the home page where a user hasn't yet joined an organization.

Add a welcome message

---

web-admin/src/routes/-/auth/device/+page.svelte

Change color for rejected auth code message

---

web-admin/src/components/errors/error-utils.ts

Add specific copy for 403 errors

---

admin/database/database.go
admin/database/postgres/migrations/0005.sql
admin/database/postgres/postgres.go
admin/server/organizations.go
admin/server/projects.go
admin/user.go

Resolves https://github.com/rilldata/rill-developer/issues/2207

enforce basic quotas on admin apis

---

web-common/src/features/dashboards/humanize-numbers.ts

@djbarnwal this PR just removes some dead code following from the number formatting work a couple months ago. This is the low hanging fruit from some refactors around that code that @hamilton and I discussed when those changes landed, just getting back to it now. I should have some more stuff on this topic forthcoming.

Cleanup number formatting phase 1

---

web-common/src/features/dashboards/time-series/MeasureChart.svelte

quick pr while working on other stuff -- fixes all this console noise

removes unused component props that were causing console noise

---

runtime/services/catalog/migration_item.go
runtime/services/catalog/migrations_test.go

Tested manually. Sadly we need gcs/aws authentication in github workflow for automated tests.

Fixing reconcile after fixing credentials

---

docs/docs/home.md

Add `rill start` to example project instructions

Update documentation for example project

---

admin/admin.go
admin/email/email.go
admin/email/sender.go
admin/server/organizations.go
admin/server/projects.go
admin/user.go
cli/cmd/org/org.go

Send notification email upon addition of an exiting user to an org or project.

user addition notification email

---

web-admin/src/components/projects/ProjectDashboards.svelte
web-admin/src/components/projects/ProjectGithubConnection.svelte
web-admin/src/routes/[organization]/[project]/+page.svelte

Add dashboard list to project and change layout according to mocks

Project layout changes

---

web-common/src/features/metrics-views/MeasuresColumns.ts

@AdityaHegde this removes a 9 month old FIXME comment that is obsolete given all the changes since then.

delete an ancient fixme

---

admin/database/database.go
admin/database/postgres/postgres.go
admin/server/organizations.go
admin/server/projects.go

Change role of invited user using `rill user set-role`

change role of invited user

---

web-common/src/features/dashboards/workspace/Dashboard.svelte

Fixing dimension table not navigatable

---

admin/database/database.go
admin/deployments.go
admin/projects.go
admin/server/projects.go
cli/cmd/env/configure.go

Reconcile deployment on project update and env changes

---

web-common/src/features/entity-management/Spinner.svelte

Use the new spinner gradient as per the mock.

Change spinner color across the application

---

web-admin/src/components/calls-to-action/CTAButton.svelte
web-admin/src/components/calls-to-action/CTAContentContainer.svelte
web-admin/src/components/calls-to-action/CTAHeader.svelte
web-admin/src/components/calls-to-action/CTAMessage.svelte
web-admin/src/components/calls-to-action/CTANeedHelp.svelte
web-admin/src/components/projects/ProjectBuilding.svelte

Use CTA components for ProjectBuilding

Use CTA components for ProjectBuilding

---

cli/cmd/env/configure.go
runtime/compilers/rillv1beta/connector.go
runtime/compilers/rillv1beta/connector_test.go

CLI: In `rill deploy` and `rill env configure`, list sources requiring credentials as shown [here] (https://www.figma.com/file/ADt3OivNV54xeoXkUpPxP2/RILL?node-id=684-9642&t=13XSlT5Sjk40qHrM-0)

listing source while asking for credentials

---

web-admin/src/routes/[organization]/[project]/[dashboard]/+page.svelte

Fix error flicker on dashboard page

---

web-admin/src/routes/[organization]/[project]/[dashboard]/+page.svelte

Show a 404 page for unknown dashboards

---

web-common/src/components/BarAndLabel.svelte
web-common/src/components/button/IconButton.svelte
web-common/src/components/column-profile/ContextButton.svelte
web-common/src/components/column-profile/ExpanderButton.svelte
web-common/src/components/column-profile/ProfileContainer.svelte
web-common/src/components/data-graphic/marks/MultiMetricMouseoverLabel.svelte
web-common/src/components/menu/core/Menu.svelte
web-common/src/components/menu/core/MenuItem.svelte
web-common/src/components/menu/triggers/SelectButton.svelte
web-common/src/components/search/Search.svelte
web-common/src/components/table-editable/EditableTableHeader.svelte
web-common/src/components/virtualized-table/core/Cell.svelte
web-common/src/features/dashboards/big-number/MeasureBigNumber.svelte
web-common/src/features/dashboards/filters/Filter.svelte
web-common/src/features/dashboards/filters/Filters.svelte
web-common/src/features/dashboards/humanize-numbers.ts
web-common/src/features/dashboards/leaderboard/LeaderboardHeader.svelte
web-common/src/features/dashboards/time-series/MetricsTimeSeriesCharts.svelte
web-common/src/features/metrics-views/workspace/config-parameters/DisplayNameInput.svelte
web-common/src/features/models/workspace/Editor.svelte
web-common/src/features/models/workspace/ModelBody.svelte
web-common/src/features/models/workspace/inspector/References.svelte
web-common/src/features/sources/embedded/ConnectorLabel.svelte
web-common/src/layout/CollapsibleSectionTitle.svelte
web-common/src/layout/navigation/Footer.svelte
web-common/src/layout/navigation/Navigation.svelte
web-common/src/layout/navigation/SurfaceControlButton.svelte
web-common/src/layout/workspace/Inspector.svelte
web-common/src/layout/workspace/WorkspaceHeader.svelte
web-common/src/runtime-client/gen/index.schemas.ts

Prettier fixes for web common

---

web-admin/src/components/navigation/Breadcrumbs.svelte
web-admin/src/routes/[organization]/[project]/-/redirect/+page.svelte

Redirect project breadcrumb selection to project's first dashboard

---

web-admin/src/components/home/WelcomeMessage.svelte
web-common/src/features/dashboards/workspace/DeployDashboardOverlay.svelte

Link to new docs pages

---

web-admin/src/components/authentication/UserButton.svelte

Add docs to the User menu

---

cli/cmd/deploy/deploy.go
cli/cmd/start/start.go
cli/pkg/cmdutil/cmdutil.go
cli/pkg/local/app.go
cli/pkg/telemetry/telemetry.go
web-common/src/metrics/service/MetricsService.ts
web-common/src/runtime-client/manual-clients.ts

We want to track user id in telemetry if the user has logged in.
- Adding user_id to deploy command
- Adding user_id to rill developer if user has logged in

Adding user id to telemetry if logged in

---

web-admin/src/components/home/DeploymentStatusChip.svelte
web-admin/src/components/projects/ProjectBuilding.svelte
web-common/src/features/entity-management/Spinner.svelte

The dashboard has the original color we were using and the cloud components have the new deep purple color

Change spinner color for dashboard

---

web-local/test/setup.sh
web-local/test/ui/dashboards.spec.ts
web-local/test/ui/models.spec.ts

Re-enables the models and dashboards e2e tests

test: re-enable e2e tests

---

runtime/connectors/gcs/gcs.go

Fixes issues accessing public buckets when user didn't login into gcloud

public bucket access fix for gcs

---

cli/cmd/docs/generate.go
docs/docs/deploy/existing-project.md
docs/docs/deploy/share.md
docs/docs/reference/cli/cli.md
docs/docs/reference/cloud/_category_.yml
docs/docs/reference/cloud/quotas.md
docs/docs/reference/cloud/roles-permissions.md

Contributes to https://github.com/rilldata/rill-developer/issues/2371

Docs for permissions, quotas, monorepos, domain whitelisting

---

docs/docusaurus.config.js
docs/package.json
package-lock.json

Also upgrades Docusaurus to latest minor version

Add Mermaid to Docusaurus

---

admin/database/postgres/postgres_test.go
admin/pkg/pgtestcontainer/pgtestcontainer.go
admin/provisioner/provisioner_test.go
admin/server/admin_rbac_test.go
runtime/drivers/drivers_test.go

Hopefully fixes some sporadic testcontainer failures I've seen in CI.

Add correct WaitFor check for Postgres testcontainers

---

docs/blog/0.10.md
docs/blog/0.11.md
docs/blog/0.12.md
docs/blog/0.13.md
docs/blog/0.14.md
docs/blog/0.15.md
docs/blog/0.16.md
docs/blog/0.17.md
docs/blog/0.18.md
docs/blog/0.19.md
docs/blog/0.2.md
docs/blog/0.20.md
docs/blog/0.21.md
docs/blog/0.22.md
docs/blog/0.23.md
docs/blog/0.24.md
docs/blog/0.25.md
docs/blog/0.26.md
docs/blog/0.3.md
docs/blog/0.4.md
docs/blog/0.5.md
docs/blog/0.6.md
docs/blog/0.7.md
docs/blog/0.8.md
docs/blog/0.9.md
docs/docs/develop/import-data.md

updating install link

---

web-common/src/features/welcome/TitleContent.svelte

This PR edits the Welcome page copy so the application is consistent with the marketing site.
Relevant Slack thread here: https://rilldata.slack.com/archives/C04JP568RR6/p1685130634516689

Edit copy on Welcome page

---

runtime/connectors/blob/blobdownloader.go
runtime/connectors/blob/blobdownloader_test.go

Adds support for non-glob ingestion without list permission in S3/GCS

single fix permissions fix

---

docs/blog/0.26.md
docs/blog/0.27.md

release notes 0.27

---

runtime/queries/column_time_range.go

This enables Druid SQL planner use optimized timeboundary query for time range. Its a limitation with Druid currently that the query will be converted to timeBoundary only if only one of the agg either min or max is set, see [here](https://github.com/apache/druid/blob/master/sql/src/main/java/org/apache/druid/sql/calcite/rel/DruidQuery.java#L972).

druid timeboundary query for time range

---

web-common/src/features/sources/sourceUtils.ts
web-common/src/features/welcome/EmptyProject.svelte
web-common/src/features/welcome/ProjectCards.svelte
web-common/src/features/welcome/TitleContent.svelte

UI hangs on source ingestion
UI failure was possibly because of it being called before telemetry object is initialized in an edge case.

add safeguards to telemetry object

---

.golangci.yml
admin/email/README.md
admin/email/email.go
admin/email/email_test.go
admin/email/templates/call_to_action.mjml
admin/email/templates/gen/call_to_action.html
admin/email/templates/generate.sh
admin/server/organizations.go
admin/server/projects.go
admin/user.go

Template for transactional email

---

web-common/src/lib/time/comparisons/index.ts

Addresses the 4th P0 listed in https://github.com/rilldata/rill/issues/2556

Fix dimension table refresh bug

---

runtime/queries/column_numeric_histogram.go
runtime/server/queries_columns_test.go

Closes https://github.com/rilldata/rill/issues/2644

Historgram all-nulls column support

---

runtime/drivers/github/github.go

This might also close https://github.com/rilldata/rill/issues/2655

Fix error in git pull of non-default branches

---

runtime/queries/metricsview.go
runtime/queries/metricsview_test.go

Closes https://github.com/rilldata/rill/issues/2665

XLSX unexpected columns fix

---

web-common/src/features/dashboards/workspace/Dashboard.svelte

Disables dashboard row viewer in cloud

fix: disable rows viewer in cloud

---

docs/blog/0.28.md

release notes 0.28

---

web-common/src/features/dashboards/time-series/MetricsTimeSeriesCharts.svelte
web-common/src/lib/time/ranges/index.ts

For All time range, the charts looked off and the latest point was not being displayed
Shows the last data point for all time on the charts
**Before:**
**After:**

Show all data points for All time range

---

runtime/drivers/druid/olap.go
runtime/pkg/pbutil/pbutil.go
runtime/pkg/pbutil/pbutil_test.go
runtime/queries/column_timeseries.go
runtime/queries/column_topk.go
runtime/queries/metricsview.go
runtime/queries/metricsview_comparison_toplist.go
runtime/queries/metricsview_timeseries.go
runtime/queries/protoutil.go
runtime/server/queries.go

date formatting fix for query results

---

runtime/services/catalog/migrations_test.go
runtime/services/catalog/migrator/models/models.go

Based on bug [reported in Slack](https://rilldata.slack.com/archives/CTZ8XBQ85/p1687891229945899)

Runtime: Fix model not re-materialized on source update

---

runtime/drivers/catalog_test.go
runtime/drivers/duckdb/catalog.go
runtime/drivers/duckdb/migrations/0005.sql
runtime/registry_test.go

removing unique index

---

runtime/queries/metricsview.go
runtime/server/downloads.go

Closes https://github.com/rilldata/rill/issues/2666

Export filename

---

.golangci.yml
admin/admin.go

Auto fix removed for linters

---

cli/cmd/deploy/deploy.go

Proposed updated experience – please give feedback:

CLI: Print suggestions when trying to deploy an existing project

---

docs/docs/develop/import-data.md

Importing sources from cli is no longer supported.

docs: update import-data

---

docs/blog/0.29.md

release notes 0.29

---

runtime/drivers/duckdb/connectors.go
runtime/server/connectors.go

Shows MotherDuck connector always on the UI

MotherDuck connector changes 

---

runtime/server/batch_query_test.go

The code that collects the responses in query batch test was not thread safe. Adding a mutex to make sure when responses are returned at the same doesnt result in a panic.

Fix race condition in query batch test

---

docs/blog/0.30.md

release notes 0.30

---

docs/docs/reference/_category_.yml
docs/docs/reference/project-files/_category_.yml
docs/docs/reference/project-files/dashboards.md

Updates the dashboard YAML reference docs to reflect the YAML properties currently supported by the backend
Closes https://github.com/rilldata/rill/issues/2750

Update dashboard YAML reference docs

---

admin/server/auth/device_code.go
cli/cmd/deploy/deploy.go
cli/pkg/cmdutil/cmdutil.go
web-admin/src/routes/-/auth/cli/success/+page.svelte
web-admin/src/routes/-/auth/success/+page.svelte

change in login flow during rill deploy

---

runtime/drivers/druid/druid_test.go
runtime/queries/metricsview_timeseries.go

see https://druid.apache.org/docs/latest/querying/sql.html#dynamic-parameters

`time_floor` usage cannot inference timezone type

---

docs/docs/reference/project-files/sources.md

The feature was introduced in https://github.com/rilldata/rill/pull/2194

Document "duckdb" YAML property

---

web-common/src/features/dashboards/leaderboard/LeaderboardDisplay.svelte
web-common/src/features/dashboards/workspace/DashboardContainer.svelte

Fixes issue described here: https://www.notion.so/Server-Side-Insights-Gap-Analysis-4353dad918214b2880041551ff14de42?d=d9d9771d8eba4c158b4f7774108667f4&pvs=4#4ccc69aa000b4354b1d2d476a3f21845

fix leaderboard scroll issue

---

docs/blog/0.31.md

release notes

---

runtime/services/catalog/migrations_test.go
runtime/services/catalog/migrator/metricsviews/metrics_views.go

See [this bug report](https://rilldata.slack.com/archives/CTZ8XBQ85/p1691166232980139) in Slack for context

Runtime: Validate dimension and measure columns are unique

---

runtime/queries/metricsview_timeseries.go
runtime/server/queries_metrics_rows_test.go
runtime/server/queries_metrics_timeseries_test.go

https://github.com/rilldata/rill/issues/2841

Exporting for metrics view timeseries

---

web-common/src/features/dashboards/rows-viewer/ExportModelDataButton.svelte
web-local/test/ui/dashboards.spec.ts

- [ x ] Manual verification
- [ x ] Unit test coverage
1. Run `npm run dev`
2. Open localhost:3000 and navigate to a dashboard
3. Click the download icon in the bottom right corner
4. Check the file is downloaded.

Parquet exporting option in the download context menu

---

admin/server/service.go
cli/cmd/service/create.go
cli/cmd/service/service.go
cli/cmd/service/token/token.go

Issue token when creating a service

---

web-common/src/features/sources/modal/errors.ts
web-common/src/layout/workspace/HorizontalSplitter.svelte

This PR makes a few small improvements to the source error messages that we surface in the UI. Specifically, the PR:
- Removes the function `niceDuckdbUnicodeError`, which was buggy. Now we fall back to the raw error that comes from DuckDB.
- Removes an application error message "We had trouble ingesting your data..." which hid the true server error from the user. Now we show the server error, which helps the user debug.
- Centers the handle of the horizontal splitter. Now it is center-aligned with the error message in the console.

Improve source error messages

---

web-common/src/features/dashboards/rows-viewer/ExportModelDataButton.svelte

Menu item ordering for exporting

---

runtime/drivers/file/repo_test.go

Addresses test failure seen here: https://github.com/rilldata/rill/actions/runs/5834172239/job/15823138582#step:5:604

Runtime: fix non-deterministic file watcher test

---

cli/cmd/org/list.go
cli/cmd/project/list.go
cli/cmd/user/list.go

Kept the default limit for user/org and project listing as `50` and can be listed by adding flag `--page-size`

added pagination for listing user/orgs/projects

---

web-common/src/features/dashboards/time-controls/TimeZoneSelector.svelte

Close timezone menu on click outside

Close timezone menu on click outside

---

web-common/src/features/dashboards/time-series/MeasureChart.svelte

There was no visual cue when the user hovered over the edges of the scrub or inside it. Also the heuristic to determine edge/inside was not very robust
Change cursor on hover over edges and inside scrub. Improve interactions
1. Create scrub
2. Hover over the edges and inside the scrub
3. The cursor should change accordingly.

Add cursors on scrub hover, improve interactions

---

docs/docs/deploy/_category_.yml
docs/docs/deploy/credentials/_category_.yml
docs/docs/deploy/credentials/credentials.md
docs/docs/deploy/existing-project.md
docs/docs/develop/_category_.yml
docs/docs/develop/import-data.md
docs/docs/develop/metrics-dashboard.md
docs/docs/develop/sql-models.md
docs/docs/get-started.md
docs/docs/install.md
docs/docs/reference/_category_.yml
docs/docs/reference/cli/cli.md
docs/docs/reference/glob-patterns.md
docs/docs/reference/project-files/_category_.yml
docs/docs/share/_category_.yml
docs/docs/share/roles-permissions.md
docs/docs/share/user-management.md

Changes to docs - clean, callouts, new features

Variety of clean up and callouts

---

web-common/src/features/dashboards/dashboard-stores.ts
web-common/src/features/dashboards/proto-state/toProto.ts
web-common/src/features/dashboards/time-series/MeasureChart.svelte
web-common/src/features/dashboards/time-series/MeasureScrub.svelte

Minor improvements to scrub-zoom

Scrub zoom improvements

---

docs/docs/reference/cli/cli.md
docs/docs/reference/cli/project/edit.md
docs/docs/reference/cli/project/list.md
docs/docs/reference/cli/user/list.md
docs/docs/reference/cli/user/user.md
docs/docs/reference/cli/user/whitelist/list.md
docs/docs/reference/cli/user/whitelist/remove.md
docs/docs/reference/cli/user/whitelist/setup.md
docs/docs/reference/cli/user/whitelist/whitelist.md
docs/docs/reference/cli/whoami.md

Used command - `make docs.generate`

Regenerate CLI docs

---

web-common/src/components/data-graphic/actions/scrub-action-factory.ts
web-common/src/components/data-graphic/elements/SimpleDataGraphic.svelte
web-common/src/components/data-graphic/elements/SimpleSVGContainer.svelte
web-common/src/components/floating-element/FloatingElement.svelte
web-common/src/components/floating-element/WithTogglableFloatingElement.svelte
web-common/src/features/dashboards/time-series/MeasureChart.svelte
web-common/src/features/dashboards/time-series/MeasureScrub.svelte

Adds menu on right click to scrubbed chart

Add scrub menu

---

web-common/src/components/button-group/ButtonGroup.spec.ts
web-common/src/features/dashboards/dimension-table/dimension-table-utils.ts
web-common/src/features/dashboards/leaderboard/Leaderboard.svelte
web-common/src/features/dashboards/leaderboard/LeaderboardContextColumnMenu.svelte
web-local/src/routes/dev/menu/searchable-filter-menu-demo.svelte

fixes the (expand table) button in the leaderboards

Fix (expand table) button

---

runtime/policies.go

silly mistake. Thanks @AdityaHegde for catching this.

use correct attribute for email

---

web-common/src/features/sources/sourceUtils.ts

closes #2999
1. Try to create a source with unsupported file extension.
2. Should be redirected to the created source with an error. (The user should provide the exact read function for the file)

Adding a fallback for file extension detection

---

docs/blog/0.33.md

Release notes initial draft

---

runtime/compilers/rillv1/init.go
runtime/compilers/rillv1beta/project.go
web-common/src/runtime-client/RuntimeProvider.svelte

Follow-up PR to address some suggestions in https://github.com/rilldata/rill/pull/2965

Edit copy in `rill.yaml`

---

web-admin/src/components/projects/RedeployProjectCTA.svelte

Addresses this [bug report in Slack](https://rilldata.slack.com/archives/C02T907FEUB/p1693892079918089).

Fix instruction to redeploy a hibernated project

---

admin/server/server.go

Introduced in https://github.com/rilldata/rill/pull/2986

Fix JWT attributes bug

---

admin/permissions.go
admin/server/auth/claims.go
admin/server/deployment.go
admin/server/projects.go
admin/server/server.go

Fixes reported issue:
> The invited viewer has admin: true  (and I double-checked the user is a viewer in the users_projects_roles table)

Fix permissions attribute in GetDeploymentCredentials

---

web-common/src/features/dashboards/time-controls/TimeControls.svelte

Fixing baseTimeRange on cloud for time grain changes

---

runtime/drivers/blob/blobdownloader.go
runtime/drivers/duckdb/config.go
runtime/drivers/duckdb/duckdb.go

Also reduces the concurrent blob download limit – see comment for details

Configure preserve_insertion_order

---

docs/blog/0.34.md

Release 0.34 notes

---

runtime/pkg/activity/client.go

Fixes issue reported here: https://rilldata.slack.com/archives/C01190F1R1D/p1695043348046779

Fix nil logger in activity.BufferedClient

---

runtime/queries/metricsview.go

Introduced in https://github.com/rilldata/rill/pull/2870

Add header to DuckDB CSV exports

---

runtime/drivers/athena/athena.go
runtime/drivers/azure/azure.go

Fix merge conflict for TertiarySourceConnectors

---

web-common/src/features/welcome/ProjectCards.svelte
web-common/src/features/welcome/UserTestCTA.svelte
web-common/src/features/welcome/Welcome.svelte

This PR adds to the `/welcome` page a CTA to sign up for a user test. [Notion PRD](https://www.notion.so/rilldata/Participant-Payments-200-AMZ-gift-cardt-ecf64f6d06524321b472a654ba63ac6b?d=22a2e42909844192993652638afb7eba)

Add CTA to sign up for a user test

---

web-common/src/features/dashboards/big-number/MeasureBigNumber.svelte

Fixes https://github.com/rilldata/rill/issues/2518
BEFORE
AFTER

removes +- on bignums

---

runtime/pkg/activity/kafka.go
runtime/pkg/activity/kafka_test.go

Kafka producer batching, compression and retry logic to fix 'Local: Queue full'

---

web-common/src/features/dashboards/DashboardStateProvider.svelte
web-common/src/features/dashboards/dashboard-stores.ts

Addresses https://github.com/rilldata/rill/issues/3156
Note: This does not yet fix the problem that arbitrary ISO 8601 durations don't work.

Set the default time range after dashboard YAML edits

---

runtime/compilers/rillv1/parse_metrics_view.go
runtime/compilers/rillv1/parse_migration.go
runtime/compilers/rillv1/parse_model.go
runtime/compilers/rillv1/parse_rillyaml.go
runtime/compilers/rillv1/parse_source.go
runtime/compilers/rillv1/parser.go
runtime/compilers/rillv1/parser_test.go
runtime/reconcilers/project_parser.go
runtime/server/examples.go

Closes https://github.com/rilldata/rill/issues/3187

Support keystroke-by-keystroke editing of rill.yaml

---

CONTRIBUTING.md

fix: correct path to devtool.sh

---

runtime/controller_test.go
runtime/query.go
web-admin/src/features/projects/dashboards.ts
web-common/src/features/dashboards/workspace/DashboardCTAs.svelte
web-common/src/features/entity-management/resource-invalidations.ts
web-common/src/features/entity-management/resource-selectors.ts
web-common/src/features/models/navigation/ModelMenuItems.svelte
web-common/src/features/sources/createDashboard.ts
web-common/src/features/sources/navigation/SourceMenuItems.svelte
web-local/test/ui/dashboards.spec.ts
web-local/test/ui/utils/commonHelpers.ts

1. Removing a leftover println.
2. Updating the ListResource api call to use new schema.
3. Disabling the create dashboard button when source/model is reconciling.
4. Improving test stability.

Async reconcile misc fixes

---

web-common/src/components/preview-table/PreviewTable.svelte
web-common/src/components/preview-table/config.ts
web-common/src/components/virtualized-table/core/ColumnHeader.svelte
web-common/src/components/virtualized-table/drag-table-cell.ts
web-common/src/components/virtualized-table/sections/ColumnHeaders.svelte
web-common/src/components/virtualized-table/types.d.ts
web-common/src/features/dashboards/dimension-table/DimensionDisplay.svelte
web-common/src/features/dashboards/dimension-table/DimensionTable.svelte
web-common/src/features/dashboards/dimension-table/DimensionTableConfig.ts
web-common/src/features/dashboards/dimension-table/DimensionValueHeader.svelte

add the ability to resize the dimension value column in the dimension table

Resize handle dim table

---

web-common/src/components/preview-table/ConnectedPreviewTable.svelte
web-common/src/features/entity-management/ReconcilingSpinner.svelte
web-common/src/features/entity-management/resource-selectors.ts
web-common/src/features/models/workspace/ModelBody.svelte
web-common/src/features/models/workspace/inspector/ModelInspector.svelte
web-common/src/features/models/workspace/inspector/ModelInspectorModelProfile.svelte
web-common/src/features/sources/inspector/SourceInspector.svelte
web-common/src/features/sources/workspace/SourceWorkspaceBody.svelte
web-common/src/features/sources/workspace/SourceWorkspaceHeader.svelte
web-common/src/layout/workspace/WorkspaceHeader.svelte

Improves the look and feel of the spinners along with fixing a few issues with the spinner.

Making improvements to the reconcile spinner

---

docs/docs/reference/project-files/dashboards.md

remove "comma-separated" add "interval_ms" fix typo

---

cli/pkg/local/app.go

Pending support for skipping it on the initial hydration

Disable delayed model materialization 

---

runtime/registry.go

Closes https://github.com/rilldata/rill/issues/3300

Fix local sources failing if triggered before Git clone

---

web-common/src/features/dashboards/dimension-table/DimensionTable.svelte

Closes #3238
Scroll position was not being saved during project refresh.
1. Follow the steps in the slack thread mentioned in the issue

Fix dimension table scroll pos on project refresh

---

runtime/drivers/duckdb/duckdb.go

See this Slack [thread](https://rilldata.slack.com/archives/CTZ8XBQ85/p1698092603383519) for context

Retry DuckDB extension installation with different mirror

---

web-common/src/lib/time/grains/index.spec.ts
web-common/src/lib/time/grains/index.ts

Allow minute granularity for a day and other minor cleanups

Relax constraints to allow minute granularity for a day

---

web-common/src/components/Portal.svelte
web-common/src/components/VirtualizedGrid.svelte
web-common/src/components/button-group/SubButton.svelte
web-common/src/components/dialog-v2/Dialog.svelte
web-common/src/components/editor/YAMLEditor.svelte
web-common/src/components/editor/__stories__/YAMLEditor.stories.svelte
web-common/src/components/editor/line-status/LineNumberGutterMarker.svelte
web-common/src/components/editor/line-status/StatusGutterMarker.svelte
web-common/src/components/grid/GridCell.svelte
web-common/src/components/preview-table/PreviewTable.svelte
web-common/src/components/tab/TabGroup.svelte
web-common/src/components/tooltip/SlidingWords.svelte
web-common/src/components/tooltip/TooltipContent.svelte
web-common/src/components/tsconfig.json
web-common/src/components/virtualized-table/sections/ColumnHeaders.svelte
web-common/src/features/entity-management/Spinner.svelte
web-common/src/tsconfig.json

incremental adoption of `strictNullChecks`

enable strictNullChecks in web-common/src/components, and fix all errors

---

runtime/drivers/duckdb/config.go
runtime/drivers/duckdb/config_test.go

Revert "Runtime: 1GB memory per thread for duckDB"

---

web-common/src/features/dashboards/dimension-table/DimensionDisplay.svelte
web-common/src/features/dashboards/dimension-table/DimensionHeader.svelte
web-common/src/features/dashboards/pivot/Pivot.svelte
web-common/src/features/dashboards/stores/dashboard-stores.ts
web-common/src/features/dashboards/time-dimension-details/TDDHeader.svelte
web-common/src/features/dashboards/time-dimension-details/TDDTable.svelte
web-common/src/features/dashboards/time-dimension-details/TimeDimensionDisplay.svelte

#3248
Adds a button for selecting/deselecting all values from a search.
1. Open TDD or Dimension table
2. Search for a dimension value
3. Select all, deselect all
4. Already selected values should be preserved.

Add select all button to tables on search

---

web-common/src/features/dashboards/time-dimension-details/time-dimension-data-store.ts

Sums previous and current measure data for totals row if comparing Time dimension.

Sum comparison and current for time TDD

---

runtime/drivers/bigquery/sql_store.go

3409: Fixes BigQuery error message

---

tsconfig.json
web-admin/src/features/tsconfig.json
web-admin/src/routes/tsconfig.json
web-common/src/components/tsconfig.json
web-common/src/features/dashboards/tsconfig.json
web-common/src/features/entity-management/ReconcilingSpinner.svelte
web-common/src/features/entity-management/RenameAssetModal.svelte
web-common/src/features/entity-management/name-utils.ts
web-common/src/features/generic-yaml-editor/YamlWorkspaceBody.svelte
web-common/src/features/models/tsconfig.json
web-common/src/features/sources/tsconfig.json
web-common/src/features/tsconfig.json
web-common/src/layout/RillDeveloperLayout.svelte
web-common/src/runtime-client/RuntimeProvider.svelte
web-common/src/tsconfig.json
web-local/src/routes/(application)/+error.svelte

Expands strict null checks in the repo and limits exemptions to certain folders.
This PR only cleans up a few additional files, but will prevent future null check violations outside of the specified folders

enable strictNullChecks at root of repo, exempting targeted folders

---

.github/workflows/cloud-admin.yml

#3445: Manually push to Netlify

---

.github/workflows/cloud-admin.yml

Specific deploy control

---

web-common/src/features/models/workspace/ModelWorkspaceCTAs.svelte

Closes [#3389](https://github.com/rilldata/rill/issues/3389)

Fix model's "Go to dashboard" menu

---

runtime/registry.go
runtime/registry_test.go
runtime/testruntime/testruntime.go

More details around issue in this comment : https://github.com/rilldata/rill/pull/3319#discussion_r1388794254

Runtime: Use saved instance to populate cache 

---

web-common/src/features/dashboards/time-dimension-details/TimeDimensionDisplay.svelte
web-common/src/features/dashboards/time-dimension-details/time-dimension-data-store.ts

Fix flash on table header when filtering values in dimension comparison mode.

Fix flash on table when filtering

---

web-common/src/components/virtualized-table/core/Cell.svelte
web-common/src/features/dashboards/dimension-table/dimension-table-utils.ts

fixes bugbash item here: https://www.notion.so/rilldata/Bug-Bash-Rill-GA-6867ccc289494508ae5f8d966d8902c5?pvs=4#b67e3c98591249679788a9b275588780

 Bugbash: make shift+click alert the same in dimension table and leaderboard

---

web-common/src/features/dashboards/dimension-table/dimension-table-utils.ts
web-common/src/features/dashboards/leaderboard/Leaderboard.svelte
web-common/src/features/dashboards/leaderboard/LeaderboardDisplay.svelte
web-common/src/features/dashboards/leaderboard/LeaderboardListItem.svelte
web-common/src/features/dashboards/leaderboard/leaderboard-utils.ts
web-common/src/features/dashboards/state-managers/selectors/dimension-table.ts

fixes bug bash issue reported here: https://www.notion.so/rilldata/Bug-Bash-Rill-GA-6867ccc289494508ae5f8d966d8902c5?pvs=4#aa4ae826186944489e6aaf21d6fe108a

Bugbash: bar sizing

---

web-admin/src/routes/[organization]/[project]/-/reports/[report]/export/+page.svelte

The export page is empty right now. Adding some text to avoid a blank page.

Updating the export page

---

web-common/app.d.ts
web-common/src/app.css
web-common/src/features/dashboards/big-number/BigNumberTooltipContent.svelte
web-common/src/features/dashboards/big-number/MeasureBigNumber.svelte
web-common/src/features/dashboards/time-series/MetricsTimeSeriesCharts.svelte
web-local/test/ui/dashboards.spec.ts

- Updates tooltips for Big Number
- Update hover UI for Big Number
https://www.notion.so/rilldata/UXQA-Time-Dimension-Detail-9bf47e7f5486411bb22815060864ab2e?pvs=4#7e13cc8d50974bcdb577fd9222cb9aab

Update tooltips for Big number

---

web-common/src/features/dashboards/dimension-table/DimensionFilterGutter.svelte
web-common/src/features/dashboards/dimension-table/DimensionTable.svelte
web-common/src/features/dashboards/leaderboard/Leaderboard.svelte
web-common/src/features/dashboards/leaderboard/LeaderboardItemFilterIcon.svelte
web-common/src/features/dashboards/leaderboard/LeaderboardListItem.svelte
web-common/src/features/dashboards/leaderboard/__stories__/LeaderboardListItem.stories.svelte
web-common/src/features/dashboards/leaderboard/leaderboard-utils.ts
web-common/src/features/dashboards/time-dimension-details/TDDTable.svelte
web-common/src/features/dashboards/time-series/MetricsTimeSeriesCharts.svelte
web-common/src/features/dashboards/time-series/multiple-dimension-queries.ts
web-common/src/features/dashboards/time-series/utils.spec.ts
web-common/src/features/dashboards/time-series/utils.ts

This removes the defaults 3 values selected for comparison.
https://www.notion.so/rilldata/UXQA-Time-Dimension-Detail-9bf47e7f5486411bb22815060864ab2e?pvs=4#b2e2b200df5e4c6697fe8657d00666cc

Refactor: Remove defaults for dimension comparison

---

web-common/src/features/sources/modal/AddSourceModal.svelte
web-common/src/features/sources/modal/LocalSourceUpload.svelte
web-common/src/features/sources/modal/RemoteSourceForm.svelte
web-common/src/features/sources/modal/RequestConnectorForm.svelte

Add explicit "Back" button to the Add Source modal

---

runtime/queries/metricsview_comparison_toplist.go

Rolling back https://github.com/rilldata/rill/pull/3471

DuckDb redundant approximation fix

---

web-admin/src/features/scheduled-reports/listing/NoReportsCTA.svelte

[Per Scheduled Reports UXQA](https://www.notion.so/rilldata/UXQA-Scheduled-Reports-43d79b9b0403477d8cc596506bc13073?p=66c8c4d14d11433c96c168afa8d11f94&pm=s)

Edit copy for CTA when 0 reports in a project

---

web-local/test/ui/dashboards.spec.ts

Add e2e tests for TDD view

---

go.mod
go.sum

Reverting to upgraded original driver

duckdb upgrade to v0.9.2

---

runtime/queries/metricsview_comparison_toplist.go
runtime/queries/metricsview_comparison_toplist_test.go
runtime/testruntime/testdata/ad_bids_2rows/dashboards/ad_bids_metrics.yaml

A smoke test for different combinations:

Dimension label exporting fix

---

web-common/src/features/dashboards/dimension-table/DimensionDisplay.svelte
web-common/src/features/dashboards/dimension-table/DimensionTable.svelte
web-local/test/ui/dashboards.spec.ts

Use correct column property in dimension table. 
Fixes 
- Duplicate columns
- Filtering

Use correct column property in table

---

web-common/src/app.css
web-common/src/components/menu/core/MenuItem.svelte

fix: menu bg hover (again)

---

docs/blog/0.37.md
docs/docs/share/scheduled-reports.md

Release notes for Release 0.37

Release notes for 0.37

---

web-common/src/app.css
web-common/src/features/dashboards/big-number/MeasureBigNumber.svelte

`@apply` can break dev server when making changes to css files. 
More at https://tailwindcss.com/docs/functions-and-directives#using-apply-with-per-component-css
Use the styles directly instead of using `@apply`

Fix: No apply in style tags

---

web-local/test/ui/dashboard-flows/leaderboard-and-dim-table-sort.spec.ts

adds e2e tests for dimension table and leaderboard sorting

add e2e flow for leaderboard and dim table sorting

---

docs/docs/reference/project-files/dashboards.md

add d3 format examples

---

.github/workflows/web-test.yml
web-common/src/components/BarAndLabel.svelte
web-common/src/components/button/Button.svelte
web-common/src/components/button/Switch.svelte
web-common/src/components/button/__stories__/Button.stories.svelte
web-common/src/components/chip/core/RemoveChipButton.svelte
web-common/src/components/floating-element/WithTogglableFloatingElement.svelte
web-common/src/components/modal/Overlay.svelte
web-common/src/components/overlay/Overlay.svelte
web-common/src/features/dashboards/leaderboard/LeaderboardContextColumnMenu.svelte
web-common/src/features/dashboards/leaderboard/LeaderboardControls.svelte

Svelte check ignore cleanup

---

docs/docs/reference/project-files/rill-yaml.md

Closes #3544 
Docs for project wide defaults, example derived from tests.

doc: add project wide default docs

---

web-common/src/components/dialog-v2/Dialog.svelte
web-common/src/components/forms/InformationalField.svelte
web-common/src/components/forms/Input.svelte
web-common/src/features/sources/modal/AddSourceModal.svelte
web-common/src/features/sources/modal/RemoteSourceForm.svelte
web-common/src/features/sources/modal/RequestConnectorForm.svelte

Implements new connector dialog re-designs. Other uses of Dialog looks fine and Input in rename asset dialog looks fine

feat: new connector dialog designs

---

web-common/src/components/button/IconSpaceFixer.svelte
web-common/src/components/chip/chip-types.ts
web-common/src/components/chip/core/Chip.svelte
web-common/src/components/chip/removable-list-chip/RemovableListBody.svelte
web-common/src/components/chip/removable-list-chip/RemovableListChip.svelte
web-common/src/components/searchable-filter-menu/SearchableFilterChip.svelte
web-common/src/features/dashboards/filters/Filters.svelte
web-common/src/features/dashboards/time-controls/ComparisonSelector.svelte

Implements https://www.notion.so/rilldata/Add-filter-button-cc49b174280c4dd6accb17731679e6a7?pvs=4
See notes at the end of page for outstanding implementation details.

feat: updated Chip designs

---

docs/package.json
package-lock.json

Build is failing with the current versions. Updating deps to the latest minor release.

Update docusaurus minor deps

---

runtime/drivers/duckdb/olap.go
runtime/drivers/duckdb/olap_crud_test.go
runtime/drivers/duckdb/transporter_motherduck_to_duckDB.go

Runtime: Fix failures in models if sql has comment at the end

---

go.mod
go.sum

see https://github.com/rilldata/rill/issues/2680

Druid fetch fix

---

runtime/drivers/duckdb/duckdb.go

Closes https://github.com/rilldata/rill/issues/3576

Runtime: Run custom DuckDB boot queries first

---

web-common/src/components/menu/triggers/SelectButton.svelte
web-common/src/components/searchable-filter-menu/SeachableFilterButton.svelte

Fix `SelectButton` console warnigns

Fix: console warnings for Select Button

---

docs/docs/reference/project-files/dashboards.md

Adding the unnest option for dimensions into our dashboard yaml documentation

Document unnest property for dimensions

---

web-common/src/features/dashboards/time-dimension-details/TimeDimensionDisplay.svelte
web-common/src/lib/time/config.ts
web-common/src/lib/time/types.ts

rill-private-issues/issues/20
Instead of estimating the format, we now specify a format for each grain.
Listed in the issue.

Refactor: Format time using grain definition

---

runtime/compilers/rillv1/parse_metrics_view.go

closes #3448
Note: This only restricts duration in metrics view config. Other places like reports and schedules are not affected.

Restrict metrics view duration settings to minute grain and above

---

web-common/src/features/entity-management/resource-invalidations.ts

Model's table is not being update after fixing the query
1. Start typing the query,
```
select 1 as n
union
select 2 as n
```
2. While the 1st part is complete the table should display the value `1`
3. While typing the rest the model goes to error state.
4. After finishing typing the final part, the table should display both `1` and `2`

Fixing model table not updating after fixing the model sql

---

runtime/drivers/snowflake/sql_store.go

User-friendly error instead of "Out of buffer" on ingesting TIME column from Snowflake

---

.github/workflows/web-test.yml
web-common/src/components/column-profile/column-types/NumericProfile.svelte
web-common/src/components/column-profile/column-types/VarcharProfile.svelte
web-common/src/components/column-profile/column-types/details/NumericPlot.svelte
web-common/src/components/column-profile/column-types/details/SummaryNumberPlot.svelte
web-common/src/components/column-profile/column-types/details/TopK.svelte
web-common/src/components/column-profile/column-types/sparks/ColumnCardinalitySpark.svelte
web-common/src/components/column-profile/column-types/sparks/TimestampSpark.svelte
web-common/src/components/column-profile/queries.ts
web-common/src/components/data-graphic/compositions/timestamp-profile/TimestampDetail.svelte
web-common/src/components/data-graphic/compositions/timestamp-profile/TimestampProfileSummary.svelte
web-common/src/components/data-graphic/elements/GraphicContext.svelte
web-common/src/components/data-graphic/elements/SimpleDataGraphic.svelte
web-common/src/components/data-graphic/elements/SimpleSVGContainer.svelte
web-common/src/components/data-graphic/functional-components/WithBisector.svelte
web-common/src/components/data-graphic/functional-components/types.ts
web-common/src/components/data-graphic/state/cascading-context-store.ts
web-common/src/features/models/workspace/ModelWorkspaceHeader.svelte
web-common/src/features/sources/workspace/SourceWorkspaceHeader.svelte

more svelte check --ignore cleanups
part of  #3424

Svelte check ignore cleanup 3

---

docs/docs/reference/project-files/dashboards.md
docs/docs/reference/project-files/themes.md

Add documentation for themes in dashboards

---

go.mod
go.sum

Patch for deadlock fix in duckDB

Runtime: deadlock duckDB patch

---

runtime/drivers/duckdb/olap.go
runtime/drivers/duckdb/olap_crud_test.go
runtime/drivers/duckdb/transporter_objectStore_to_duckDB.go

closes #3619 
Some performance numbers captured here : https://github.com/rilldata/rill/issues/3349#issuecomment-1824417814

Runtime: cast to enum writes to new db

---

docs/docs/reference/rill-iso-extensions.md

Update rill-iso-extensions.md to remove duplicate entry

---

web-common/tailwind.config.cjs

properly extend tailwind colors

---

docs/blog/0.38.md
docs/docs/example-projects.md
docs/docs/integration/_category_.yml
docs/docs/reference/_category_.yml

docs: 38 release notes and fixes

---

web-common/src/features/dashboards/proto-state/fromProto.ts

Adding CONTINUOUS to comparison backwards compatibility code in url state loader

---

runtime/queries/metricsview.go

Druid lower argument fix

---

web-common/src/features/entity-management/file-selectors.ts
web-common/src/features/models/navigation/ModelAssets.svelte
web-common/src/features/models/navigation/ModelMenuItems.svelte
web-common/src/features/models/tsconfig.json
web-common/src/features/models/workspace/Editor.svelte
web-common/src/features/models/workspace/ModelBody.svelte
web-common/src/features/models/workspace/ModelWorkspaceCTAs.svelte
web-common/src/features/models/workspace/ModelWorkspaceHeader.svelte
web-common/src/features/models/workspace/inspector/ModelInspectorHeader.svelte
web-common/src/features/models/workspace/inspector/References.svelte

add strict null checks for web-common/src/features/models/

---

.github/workflows/cloud-admin.yml

Test environment for UI

---

web-common/src/features/dashboards/big-number/MeasuresContainer.svelte
web-common/src/features/dashboards/dimension-table/dimension-table-export-utils.ts
web-common/src/features/dashboards/dimension-table/export-toplist.ts
web-common/src/features/dashboards/proto-state/dashboard-url-state.spec.ts
web-common/src/features/dashboards/state-managers/selectors/active-measure.ts
web-common/src/features/dashboards/stores/dashboard-store-defaults.ts
web-common/src/features/dashboards/stores/dashboard-stores-test-data.ts
web-common/src/features/dashboards/stores/dashboard-stores.ts
web-common/src/features/dashboards/stores/metrics-explorer-entity.ts
web-common/src/features/dashboards/time-series/timeseries-data-store.ts

Use visible measures for timeseries request

---

runtime/drivers/blob/blobdownloader.go
runtime/drivers/s3/s3.go
runtime/reconcilers/model.go
runtime/reconcilers/source.go
runtime/reconcilers/util.go

Revert "Runtime: retain files flag for s3"

---

web-common/src/components/column-profile/column-types/details/TopK.svelte
web-common/src/components/data-graphic/compositions/timestamp-profile/TimestampBound.svelte
web-common/src/components/data-graphic/compositions/timestamp-profile/TimestampTooltipContent.svelte
web-common/src/components/data-types/DataTypeIcon.svelte
web-common/src/components/virtualized-table/core/Cell.svelte
web-common/src/components/virtualized-table/core/ColumnHeader.svelte
web-common/src/features/dashboards/big-number/BigNumberTooltipContent.svelte
web-common/src/features/dashboards/leaderboard/LeaderboardTooltipContent.svelte
web-common/src/features/models/navigation/ModelTooltip.svelte
web-common/src/features/sources/navigation/SourceTooltip.svelte
web-common/src/lib/actions/shift-click-action.ts

Closes https://github.com/rilldata/rill/issues/3740

Hide "Copy to clipboard" tooltip when Clipboard API not available

---

.github/workflows/rill-ui.yml

Test env CD

---

scripts/install.sh

Update install script to use sh instead of bash

---

.github/workflows/rill-ui.yml

Fix the netlify domain

---

.eslintrc.cjs

disable rule that's giving false positives all over the place

---

.github/workflows/rill-ui.yml

tested in stage release branch

Rill UI CI domain fix

---

web-common/src/features/dashboards/time-controls/TimeZoneSelector.svelte
web-common/src/lib/time/timezone/index.ts

#3832
Checks if IANA is valid. If not returns UTC.

Fix: Unknown local IANA

---

web-common/src/features/dashboards/time-series/DimensionValueMouseover.svelte

Handle mouseover tooltip for non string dimension values

---

docs/blog/0.39.md

WIP: 0.39 release notes

---

web-admin/src/features/dashboards/share/ShareDashboardButton.svelte
web-common/src/components/button/Button.svelte
web-common/src/components/dropdown-menu/__stories__/DropdownMenu.stories.svelte
web-common/src/components/forms/InputArray.svelte

- Updates styles to better match design system
- Adds the ability to customize via the class prop
- Removes usage of `buttonClasses` function and co-locates styles within component

rework button component and match design system

---

web-common/src/features/dashboards/filters/FilterButton.svelte
web-common/src/features/dashboards/workspace/Dashboard.svelte

Updates header color and filter button to match design system.

update header color to match design system

---

web-common/src/components/icons/Chart.svelte
web-common/src/components/icons/Pivot.svelte
web-common/src/features/dashboards/state-managers/selectors/index.ts
web-common/src/features/dashboards/state-managers/selectors/pivot.ts
web-common/src/features/dashboards/tab-bar/TabBar.svelte

Adds tab icons and resolves bug related to tab state when navigating between dashboards.

add icons to explore/pivot tabs and resolve navigation bug

---

web-admin/src/routes/+layout.svelte
web-common/src/features/dashboards/DashboardAssets.svelte
web-common/src/features/dashboards/dimension-table/DimensionHeader.svelte
web-common/src/features/dashboards/time-controls/NoTimeDimensionCTA.svelte
web-common/src/features/dashboards/workspace/Dashboard.svelte
web-common/src/features/feature-flags.ts
web-common/src/layout/RillDeveloperLayout.svelte
web-common/src/layout/navigation/Navigation.svelte
web-local/src/routes/(application)/dashboard/[name]/+page.svelte
web-local/src/routes/(application)/dashboard/[name]/edit/+page.svelte
web-local/src/routes/(application)/model/[name]/+page.svelte
web-local/src/routes/(application)/source/[name]/+page.svelte

This PR updates the feature flag implementation in the following ways:
- Fixes typing issues previously present in the file.
- Supports consumption of feature flags via URL Search Params as a comma separated list.
- Creates a custom feature flag store that:
-  Provides three helper methods (set, update and toggle) to dynamically change an arbitrary selection of flags without impacting existing flags.
- Automatically derives getters for each flag so that they can be individually subscribed to in components that need them (rather than subscribing to the entire store)
- Updates the usage of the features flag store throughout the application

update feature flag implementation

---

web-common/src/features/dashboards/pivot/DragList.svelte
web-common/src/features/dashboards/pivot/PivotDrag.svelte
web-common/src/features/dashboards/pivot/PivotHeader.svelte
web-common/src/features/dashboards/pivot/PivotSidebar.svelte
web-common/src/features/dashboards/pivot/pivot-utils.ts
web-common/src/features/dashboards/pivot/types.ts

- Adds a new PivotDrag component to enable design system specifics around drag areas including collapsibility and styling
- Adds new types to capture the structure of chip data
- Adds helper functions for collecting information about column and row values in the needed format
- Makes chips removable in row/column drag sections

collapsible pivot drag area and persistent chip styling

---

web-common/src/features/dashboards/state-managers/actions/filters.ts

Clear filters are not clearing measure filters.
1. Create a dashboard with measures and dimensions.
2. Create a measure filter.
3. Click on clear filters button.
4. Measure filter should not apply anymore.

Update clearAllFilters for measure filters

---

cli/cmd/deploy/deploy.go

Closes https://github.com/rilldata/rill/issues/3935

CLI: Log errors for failed auth in `rill deploy` error cases

---

runtime/queries/metricsview_aggregation.go
runtime/queries/metricsview_comparison_toplist.go
runtime/queries/metricsview_rows.go
runtime/queries/metricsview_timeseries.go
runtime/queries/metricsview_toplist.go
runtime/queries/metricsview_totals.go

Maybe closes this issue: https://github.com/rilldata/rill-private-issues/issues/93

Runtime: wrap user-defined where expressions in parentheses

---

web-common/src/features/dashboards/dimension-table/DimensionHeader.svelte
web-common/src/features/dashboards/dimension-table/ExportDimensionTableDataButton.svelte
web-common/src/features/dashboards/dimension-table/export-toplist.ts
web-common/src/features/dashboards/filters/measure-filters/measure-filter-utils.ts
web-common/src/features/dashboards/rows-viewer/ExportModelDataButton.svelte
web-common/src/features/dashboards/rows-viewer/RowsViewerAccordion.svelte
web-common/src/features/dashboards/rows-viewer/export-metrics.ts
web-common/src/features/dashboards/time-dimension-details/export-tdd.ts

Measure filters were not properly being applied to the exports.
Making sure measure filters are applied to rows, dimensions and TDD exports.

Update all exports in dashboards to use measure filters

---

web-common/src/features/dashboards/pivot/pivot-data-store.ts
web-common/src/features/dashboards/pivot/pivot-expansion.ts
web-common/src/features/dashboards/pivot/pivot-infinite-scroll.ts
web-common/src/features/dashboards/pivot/pivot-merge-filters.ts
web-common/src/features/dashboards/pivot/pivot-queries.ts
web-common/src/features/dashboards/pivot/pivot-utils.ts
web-common/src/features/dashboards/stores/dashboard-store-defaults.ts

Integrate new filter object into pivot prototype

---

web-common/src/components/chip/chip-types.ts
web-common/src/features/dashboards/pivot/DragList.svelte
web-common/src/features/dashboards/pivot/PivotDisplay.svelte
web-common/src/features/dashboards/pivot/PivotEmpty.svelte
web-common/src/features/dashboards/pivot/PivotExpandableCell.svelte
web-common/src/features/dashboards/pivot/PivotHeader.svelte
web-common/src/features/dashboards/pivot/PivotTable.svelte
web-common/src/features/dashboards/pivot/pivot-utils.ts

Preliminary chunk of table styling for initial merge.

preliminary table styling

---

docs/blog/0.40.md

docs: release notes 0.40

---

web-common/src/features/dashboards/leaderboard/leaderboard-utils.ts

fixes https://github.com/rilldata/rill-private-issues/issues/138

change error to console.warn, and a little bit of DRY cleanup

---

README.md

New tagline and gif for readme.md

doc: update readme with new branding

---

web-common/src/components/virtualized-table/core/Cell.svelte
web-common/src/features/dashboards/dimension-table/DimensionTable.svelte
web-common/src/features/dashboards/dimension-table/DimensionTableConfig.ts
web-common/src/features/dashboards/dimension-table/DimensionValueHeader.svelte
web-common/src/features/dashboards/dimension-table/dimension-table-utils.ts

Fixes #3992, and some related type cleanups on the side

Fix #3992, and other cleanups

---

docs/docs/develop/metrics-dashboard.md
docs/docs/reference/project-files/dashboards.md

Documention for:
- Dimension -> expression
- default_comparison

doc: adding dim expr and comparison

---

web-common/src/features/dashboards/filters/measure-filters/MeasureFilterMenu.svelte
web-common/src/features/dashboards/proto-state/toProto.ts

Clean up stale logs

---

web-common/src/components/button/Button.svelte

Button padding inadvertently removed in https://github.com/rilldata/rill/pull/4020

Add back button padding

---

web-common/src/features/dashboards/pivot/PivotTable.svelte

Update pivot table sorted columns icon.

Update pivot table sorted columns icon

---

web-common/src/features/alerts/CreateAlertDialog.svelte

A small fix to make sure necessary fields are added to queryJson

Update the query json during alert creation

---

web-admin/src/features/alerts/selectors.ts
web-common/src/features/entity-management/resource-selectors.ts

Adding basic methods to
- Get a list of alerts
- Get a single alert
- Get the dashboard name from an alert
- Check if alert is created by the UI

Add basics of alerts resource

---

web-common/src/features/dashboards/pivot/DragList.svelte
web-common/src/features/dashboards/pivot/PivotChip.svelte

This PR removes the dropdown for time pills in the pivot table.

Remove dropdown for pivot time pills

---

web-common/src/features/dashboards/pivot/DragList.svelte
web-common/src/features/dashboards/pivot/PivotHeader.svelte

This PR swaps the row and column components in the PivotHeader and fixes a bug in the styling.

Swap pivot rows and columns in pivot header

---

web-common/src/features/dashboards/pivot/PivotEmpty.svelte

Updates the UI for Empty and Loading pivot states as per mocks.

Update Empty Pivot component to match mocks

---

web-common/src/features/dashboards/pivot/PivotDrag.svelte
web-common/src/features/dashboards/pivot/PivotSidebar.svelte

This PR updates the sidebar layout mechanism to display as many pills as possible while still maintaining the visibility of all three sections.

Update pivot sidebar layout mechanism

---

runtime/queries/table_columns.go
runtime/queries/table_head.go

Closes https://github.com/rilldata/rill-private-issues/issues/155

Druid TableRows request

---

web-common/src/features/dashboards/proto-state/proto.spec.ts
web-common/src/features/dashboards/stores/DashboardStateProvider.svelte

Closes #4112
Fixes an issue where updates to the dashboard is not synced on a page load with preexisting url state.

Make sure initial url state load syncs with metrics view

---

.github/workflows/web-test-code-quality.yml
web-common/src/features/dashboards/time-controls/TimeRangeSelector.svelte
web-common/src/lib/time/ranges/index.ts

fix type errors in time range selector

---

web-common/src/features/dashboards/pivot/pivot-infinite-scroll.ts
web-common/src/features/dashboards/pivot/pivot-queries.ts

Reduce join query limit to 300 and increase page size for col to 50.

Reduce join query fetch limit

---

docs/docs/deploy/credentials/athena.md
docs/docs/reference/project-files/themes.md
docs/docusaurus.config.js
docs/package.json
docs/tsconfig.json
package-lock.json

This reverts commit bbc2e283adaea9094ccd5b43b0579d356b7bdd95.

Revert "Updating to Docusaurus v3 (#4078)"

---

web-common/src/features/dashboards/leaderboard/Leaderboard.svelte

Improve leaderboard error display

---

web-common/src/features/dashboards/pivot/PivotDrag.svelte
web-common/src/features/dashboards/pivot/PivotSidebar.svelte

This PR resolves some edge cases in laying out the pivot table sidebar.

Resolve pivot sidebar layout edge cases

---

docs/blog/0.41.md
docs/docs/reference/project-files/dashboards.md

docs: 0.41 release notes

---

docs/blog/0.41.md
docs/docs/develop/import-data.md

Add docs for live connections and clickhouse

---

docs/docs/deploy/credentials/athena.md
docs/docs/reference/project-files/themes.md
docs/docusaurus.config.js
docs/package.json
docs/tsconfig.json
package-lock.json

After rebasing branch against main. Had to recreate package-lock.json as well to resolve dependency tree issues and avoid conflicting react versions (18.2.0 vs 17.0.2). Also, removed typescript in nested package.json in docs directory in favor of the parent package.json file.

Upgrading to Docusaurus v3

---

web-common/src/features/alerts/extract-alert-form-values.ts
web-common/src/features/alerts/form-utils.ts

[Alert Edit] Fix time range reloading and fix where filter

---

web-common/src/features/dashboards/dimension-table/DimensionTable.svelte

Fixes #4190, though the behavior here needs work and is being addressed in #4198.

Fix: Comparison color discrepancy between chart and table

---

admin/server/server.go

https://rilldata.slack.com/archives/C01190F1R1D/p1709286739213069?thread_ts=1708335972.076789&cid=C01190F1R1D

Admin: temporary endpoint to dump headers

---

web-common/src/components/forms/InputV2.svelte
web-common/src/features/alerts/BaseAlertForm.svelte
web-common/src/features/alerts/CreateAlertDialog.svelte
web-common/src/features/alerts/criteria-tab/CriteriaForm.svelte
web-common/src/features/alerts/criteria-tab/parseCriteriaError.ts
web-common/src/features/alerts/data-tab/AlertDialogDataTab.svelte
web-common/src/features/alerts/form-utils.ts

Improve the validation in alerts create/edit.

[Alert] Add validation message across the alert form

---

web-common/src/components/chip/core/Chip.svelte
web-common/src/components/chip/core/RemoveChipButton.svelte

Updates to the Chip component layout to prepare for #4207

Update Chip component layout

---

web-common/src/features/dashboards/workspace/DashboardCTAs.svelte
web-common/src/metrics/BehaviourEventHandler.ts
web-common/src/metrics/service/BehaviourEventFactory.ts
web-common/src/metrics/service/BehaviourEventTypes.ts

Removed unused events.
Added deploy intent event

chore: add deploy intent event

---

runtime/drivers/duckdb/transporter_duckDB_to_duckDB.go

Issue details here : https://rilldata.slack.com/archives/CTZ8XBQ85/p1709564023475539?thread_ts=1709511278.248719&cid=CTZ8XBQ85
cc: @AndrewRTsao

Runtime: fix for relative duckdb file path for external duckdb connector

---

web-common/src/features/dashboards/filters/measure-filters/measure-filter-utils.ts

closes #3990
More detailed explanation: https://github.com/rilldata/rill/issues/3990#issuecomment-1934834417

Handle out of sync race condition in measure filters

---

web-common/src/features/dashboards/filters/measure-filters/MeasureFilterBody.svelte
web-common/src/features/dashboards/filters/measure-filters/measure-filter-utils.ts

Measure filters were not applying since a condition was incorrect.
Fixed the incorrect condition for keeping `dimensionThresholdFilters` and `toplists` in sync.
1. Create any dashboard.
2. Add measure filter.
3. The data should update as and when the measure filter is changed.

Fix measure filter stopped applying

---

web-common/src/features/dashboards/big-number/MeasureBigNumber.svelte

A fix in #4202 was reverted by #4229.

Fix: Measure overflow reversion
