rilldata/rill

web-common/src/components/data-graphic/utils.ts
web-common/src/features/dashboards/time-series/DimensionValueMouseover.svelte
web-common/src/features/dashboards/time-series/MeasureScrub.svelte
web-common/src/features/dashboards/time-series/MetricsTimeSeriesCharts.svelte
web-common/src/features/dashboards/time-series/round-to-nearest-time-unit.ts
web-common/src/features/dashboards/time-series/utils.ts
web-common/src/lib/number-formatting/format-measure-value.ts
web-common/src/lib/time/types.ts

This PR fixes some typing/ergonomic issues with the `bisectData` function as well as related components.

Fix: typing issues related to bisectData

---

web-common/src/components/searchable-filter-menu/SearchableFilterDropdown.svelte
web-common/src/features/dashboards/filters/FilterButton.svelte
web-common/src/features/dashboards/filters/Filters.svelte

Fixes https://github.com/rilldata/rill-private-issues/issues/210

Fix undefined values in dimension filter menu

---

web-common/src/layout/workspace/WorkspaceContainer.svelte

Remove unintended class declaration.

Remove z-index class on Workspace Header

---

admin/deployments.go

Reverts https://github.com/rilldata/rill/pull/3982.
Closes https://github.com/rilldata/rill-private-issues/issues/208.

Disable materialize models by default in cloud

---

web-admin/src/features/projects/ProjectTabs.svelte
web-admin/src/routes/+layout.svelte
web-common/src/features/dashboards/dimension-table/DimensionHeader.svelte
web-common/src/features/feature-flags.ts

This PR removes the Alerts feature flag to enable the feature for all users.

Remove Alerts feature flag

---

docs/blog/0.42.md
docs/docs/reference/project-files/dashboards.md
docs/package.json
package-lock.json

Adding Custom APIs and cleaning up saas deps

docs: more release notes and deps

---

runtime/queries/metricsview_aggregation.go
runtime/queries/metricsview_aggregation_test.go

Closes https://github.com/rilldata/rill/issues/3878

Pivot exporting with labels

---

cli/pkg/local/app.go

Addresses https://github.com/rilldata/rill-private-issues/issues/224

Add InsecureSkipVerify to TLS client config

---

web-common/src/lib/time/config.ts

Temporarily reverts week formatting to date while we work on making it configurable.

fix: revert week formatting to date

---

docs/src/css/custom.scss

Adding bot padding to nav to prevent url preview overlap

docs: add bot padding to nav

---

web-common/src/features/charts/ChartAssets.svelte
web-common/src/features/tables/TableAssets.svelte
web-common/src/layout/navigation/NavigationEntry.svelte

This PR applies a few small styling fixes to the nav bar.

Nav: styling fixes

---

web-admin/src/features/bookmarks/selectors.ts
web-admin/src/features/dashboards/DashboardBookmarksStateProvider.svelte
web-admin/src/features/navigation/TopNavigationBar.svelte
web-admin/src/routes/[organization]/[project]/[dashboard]/+page.svelte

closes #4401
Disabling fetching of bookmarks for anonymous users on shared dashboards.

fix: disable bookmark for anonymous users

---

docs/docs/integrate/custom-api.md
docs/docs/integrate/custom-apis/sql-api.md

docs: hasKey templating example

---

web-common/src/features/dashboards/time-controls/SelectorButton.svelte
web-common/src/features/dashboards/time-controls/TimeGrainSelector.svelte
web-common/src/features/dashboards/time-controls/TimeZoneSelector.svelte
web-local/tests/dashboards/dashboards.spec.ts

This PR updates the TimeGrain and TimeZone selectors to the new menu system.

Chore: Update TimeGrain and TimeZone menus

---

web-common/src/components/forms/Switch.svelte
web-common/src/features/models/workspace/Editor.svelte
web-common/src/features/models/workspace/ModelBody.svelte
web-common/src/features/sources/editor/UnsavedSourceDialog.svelte
web-common/src/layout/workspace/workspace-stores.ts
web-local/src/routes/(application)/model/[name]/+page.svelte

This PR adds a manual trigger for saving models and persists this preference in local storage via the WorkspaceLayout store.
Closes #4301

Feat: Add auto-save toggle to model workspace

---

admin/worker/run_autoscaler.go
admin/worker/worker.go

Implement `runAutoscaler` to  apply recommended slots for projects

feat: update slot by autoscaler

---

web-common/src/features/dashboards/time-series/MetricsTimeSeriesCharts.svelte
web-common/src/features/dashboards/time-series/TimeSeriesChartContainer.svelte
web-common/src/features/dashboards/workspace/Dashboard.svelte
web-common/src/features/generic-yaml-editor/YamlWorkspaceBody.svelte
web-common/src/features/welcome/BackgroundImage.svelte
web-common/src/features/welcome/ProjectCards.svelte
web-common/src/features/welcome/UserTestCTA.svelte
web-common/src/features/welcome/Welcome.svelte
web-common/src/layout/BasicLayout.svelte
web-common/src/layout/navigation/Navigation.svelte
web-local/src/routes/(application)/welcome/+page.svelte

This PR solves an issue with the layout page that prevented it from taking up the full the width of its container.
It also makes a few small tweaks to dashboard pages to ensure components are not cut off at smaller screen dimensions.

Fix: Welcome page layout

---

runtime/queries/metricsview_aggregation.go
runtime/queries/metricsview_aggregation_test.go
runtime/server/queries_metrics_schema_test.go
runtime/testruntime/testdata/ad_bids/dashboards/ad_bids_metrics.yaml

Closes https://github.com/rilldata/rill/issues/4415

Export labels for PIVOT dimensions

---

web-admin/src/features/authentication/AvatarButton.svelte

Adds a shortcut to reports and alerts from the avatar dropdown. Only visible when looking at a dashboard.

feat: add alert & report shortcuts

---

web-common/src/features/tables/TableAssets.svelte
web-common/src/features/tables/UnsupportedTypesIndicator.svelte
web-common/src/features/tables/selectors.ts
web-common/src/layout/navigation/NavigationEntry.svelte

Closes https://github.com/rilldata/rill-private-issues/issues/245

Show a warning indicator for Tables with unsupported data types

---

web-common/src/features/charts/render/vega-config.ts

Update the colors for categorical charts

Update chart categorical colors

---

web-admin/src/features/errors/error-utils.ts
web-admin/src/features/projects/selectors.ts
web-admin/src/features/view-as-user/clearViewedAsUser.ts

Detailed explanation [here](https://github.com/rilldata/rill-private-issues/issues/253#issuecomment-2028387087) and in the code comment.
Closes https://github.com/rilldata/rill-private-issues/issues/253

Use specific `queryKey` for managing the project runtime

---

web-common/src/features/dashboards/dashboard-utils.ts
web-common/src/features/dashboards/state-managers/selectors/dashboard-queries.ts

Helps with reducing the number of values added as filter in the second phase of topN query

Reduce number of values fetched in topN for leaderboards

---

web-common/src/features/dashboards/time-series/timeseries-data-store.ts
web-common/src/features/dashboards/time-series/totals-data-store.ts

Fix: Use updated percent of total in TDD

---

web-common/src/features/charts/ChartsHeader.svelte

Allow renaming of chart items.

Allow renaming of chart resources

---

web-admin/src/features/errors/error-store.ts
web-admin/src/features/errors/error-utils.ts
web-admin/src/features/view-as-user/setViewedAsUser.ts

Following PR #4485, this PR fixes type imports in the Cloud UI.

Fix type imports in Cloud UI

---

.github/workflows/go-lint.yml
.golangci.yml
admin/metrics/client.go
admin/worker/run_autoscaler.go
admin/worker/worker.go

Fix some issues of slot scaler
Partially resolves: https://github.com/rilldata/rill-private-issues/issues/143

Fix: slot autoscaler

---

runtime/queries/metricsview_aggregation.go
runtime/queries/metricsview_comparison_toplist.go
runtime/queries/metricsview_rows.go
runtime/queries/metricsview_timeseries.go
runtime/queries/metricsview_toplist.go
runtime/queries/metricsview_totals.go

Closes https://github.com/rilldata/rill-private-issues/issues/270

TIMESTAMPTZ Duckdb time comparison fix

---

package-lock.json
web-admin/package.json
web-admin/src/features/view-as-user/ViewAsUserChip.svelte

The `DropdownMenu.Group` in the `ViewAsPopover` component was bugging when it wasn't contained within a `DropdownMenu`.
Closes https://github.com/rilldata/rill-private-issues/issues/269

Cloud UI: Fix bug in "View as" popover

---

web-admin/src/routes/[organization]/[project]/[dashboard]/+page.svelte

Closes https://github.com/rilldata/rill-private-issues/issues/276

Fix bug when clearing the "View as" pill

---

.github/workflows/rill-cloud.yml

Better semantic version for main builds

---

web-common/src/components/editor/YAMLEditor.svelte
web-common/src/components/editor/dispatch-events/index.ts
web-common/src/features/charts/editor/ChartsEditorContainer.svelte
web-common/src/features/custom-dashboards/Chart.svelte
web-common/src/features/custom-dashboards/CustomDashboard.svelte
web-common/src/features/custom-dashboards/CustomDashboardEditor.svelte
web-common/src/features/custom-dashboards/Element.svelte
web-local/src/routes/(application)/custom-dashboard/[name]/+page.svelte

- Parse errors are surfaced in the code editor
- Fixes bug where the click outside target area for deselecting a chart was too small
- Improved instrumentation of chart mutations
- Code reorg

General Custom Dashboard cleanup

---

web-admin/src/features/scheduled-reports/metadata/ReportMetadata.svelte

Fix bug that crashes the Scheduled Report detail page

---

web-common/src/features/dashboards/pivot/pivot-data-store.ts

Fix: Pivot for measures

---

docs/docs/build/models/models.md

Adding clarity about how Pivot statements work within Rill and how to overcome certain DuckDB limitations (that end up causing errors to be thrown within Rill).

Adding section about using pivots while modeling

---

web-common/src/features/dashboards/pivot/DragList.svelte
web-common/src/features/dashboards/pivot/PivotPortalItem.svelte
web-common/src/features/dashboards/pivot/swapListener.ts

Pivot drag state was not properly being reset. Added more explicit naming.

Fix: Reset pivot drag state

---

runtime/drivers/admin/admin.go

Closes https://github.com/rilldata/rill-private-issues/issues/303

Runtime: Fix virtual files being deleted on git pull

---

web-common/src/features/sources/workspace/SourceCTAs.svelte
web-local/src/routes/(application)/[type=workspace]/[name]/+page.svelte

Source: Enable save button while reconciling

---

docs/blog/0.43.md
docs/docs/reference/olap-engines/clickhouse.md
docs/docs/reference/olap-engines/druid.md

docs: 0.43 release notes

---

runtime/drivers/druid/druidsqldriver/druid_api_sql_driver.go

Druid API column types

---

web-local/src/routes/+layout.svelte

Set app wrapper to absolute positioning

---

web-common/src/features/charts/render/VegaLiteRenderer.svelte
web-common/src/features/charts/templates/area.ts
web-common/src/features/charts/templates/build-template.ts
web-common/src/features/charts/templates/grouped-bar.ts
web-common/src/features/charts/templates/line.ts
web-common/src/features/charts/templates/simple-bar.ts
web-common/src/features/charts/templates/stacked-area.ts
web-common/src/features/charts/templates/stacked-bar.ts
web-common/src/features/dashboards/time-dimension-details/charts/ChartTypeSelector.svelte
web-common/src/features/dashboards/time-dimension-details/charts/TDDAlternateChart.svelte
web-common/src/features/dashboards/time-dimension-details/charts/utils.ts
web-common/src/features/dashboards/time-series/MetricsTimeSeriesCharts.svelte

This PR - 
- adds correct tooltip content for the charts 
- enables all chart type by default
- change the style of the tooltip box
- displays proper label for the fields in the tooltip
- Improves default area chart

TDD chart improvements

---

web-common/src/features/editor/FileWorkspaceHeader.svelte
web-common/src/features/file-explorer/FileExplorer.svelte
web-common/src/features/file-explorer/NavDirectoryEntry.svelte
web-common/src/features/file-explorer/NavFile.svelte
web-common/src/features/file-explorer/protected-paths.ts

Contributes to https://github.com/rilldata/rill-private-issues/issues/309

File Explorer: Prevent `rill.yaml` renames and deletes

---

web-common/src/features/file-explorer/FileExplorer.svelte
web-common/src/features/file-explorer/NavFile.svelte

Contributes to https://github.com/rilldata/rill-private-issues/issues/309

File Explorer: Show dotfiles, but gray them out

---

web-auth/src/components/Auth.svelte

Enable SSO Login in Rill cloud as per discussions in [slack](https://rilldata.slack.com/archives/CTZ8XBQ85/p1713496140408249?thread_ts=1713403659.931569&cid=CTZ8XBQ85)

Enable SSO login for rill cloud

---

web-admin/src/features/alerts/metadata/AlertFilters.svelte
web-admin/src/features/alerts/metadata/AlertMetadata.svelte

closes #4351
Pulling changes from #4460 since that might take a while.
Adding a time range pill in filters section if it is present in the alert.

Add time range pill in filters section of alert metadata

---

package-lock.json
web-common/package.json

Update bits-ui version

---

runtime/drivers/olap.go
runtime/queries/metricsview.go
runtime/queries/metricsview_aggregation.go
runtime/queries/metricsview_comparison_toplist.go
runtime/queries/metricsview_schema.go
runtime/queries/metricsview_toplist.go
runtime/validate.go

Fix issues around unnest in dashboard

---

web-common/src/features/file-explorer/FileExplorer.svelte
web-common/src/features/file-explorer/NavDirectory.svelte
web-common/src/features/file-explorer/NavDirectoryEntry.svelte
web-common/src/features/file-explorer/NavFile.svelte
web-common/src/features/file-explorer/directory-store.ts
web-common/src/features/file-explorer/nav-entry-drag-drop-store.ts

File explorer drag-drop UX improvements

---

web-common/src/features/tables/TableEntry.svelte

Addresses https://github.com/rilldata/rill/pull/4687#discussion_r1577987909

Fix undefined variable

---

web-common/src/lib/time/types.ts

Remove last 3 months from default enum list

---

web-common/src/features/dashboards/pivot/pivot-column-definition.ts
web-common/src/features/dashboards/time-dimension-details/TDDHeader.svelte

For dimension label in pivot where name and column are different.
Fixes https://github.com/rilldata/rill-private-issues/issues/248

Fix label for dimensions in pivot

---

package-lock.json
web-common/package.json
web-common/src/features/editor/getExtensionsForFile.ts
web-local/src/routes/(application)/files/[...file]/+page.svelte

Adds a file extension to editor extension map. For now we have mappings for yaml and markdown files.

Add syntax highlighting for markdown files

---

web-common/src/features/dashboards/time-dimension-details/TimeDimensionDisplay.svelte
web-common/src/features/dashboards/time-dimension-details/time-dimension-data-store.ts
web-common/src/features/dashboards/time-series/multiple-dimension-queries.ts

Fixes [#4646](https://github.com/rilldata/rill/issues/4646)

TDD: Return empty array for no data on search

---

web-common/src/features/file-explorer/new-files.ts

This PR replaces the default Chart file with one that works in all projects. (This is a stopgap until the template workflow is in place.)

Custom Dashboards: better default Chart file

---

web-local/tests/dashboards/dashboard-flow-test-setup.ts
web-local/tests/dashboards/dashboards.spec.ts
web-local/tests/dashboards/leaderboard-context-column.spec.ts
web-local/tests/dashboards/metrics-editor.spec.ts
web-local/tests/dashboards/number-formatting.spec.ts
web-local/tests/utils/commonHelpers.ts

This PR solves a variety of issues with test reliability by fixing a few sequencing/selector issues and making the setup of similar tests more consistent.

Fix: Test reliability

---

web-common/src/features/charts/chartYaml.ts
web-common/src/features/charts/prompt/generateChart.spec.ts
web-common/src/features/charts/prompt/generateChart.ts
web-common/src/features/charts/selectors.ts
web-common/src/features/custom-dashboards/Chart.svelte
web-common/src/features/custom-dashboards/CustomDashboardEmbed.svelte
web-common/src/features/custom-dashboards/CustomDashboardPreview.svelte
web-common/src/features/custom-dashboards/Element.svelte
web-common/src/features/entity-management/AddAssetButton.svelte
web-common/src/features/entity-management/ReconcilingSpinner.svelte
web-common/src/features/entity-management/entity-mappers.ts
web-common/src/features/entity-management/file-artifacts.ts
web-common/src/features/entity-management/resource-icon-mapping.ts
web-common/src/features/entity-management/resource-invalidations.ts
web-common/src/features/entity-management/resource-selectors.ts
web-common/src/features/entity-management/watch-resources-client.ts
web-common/src/features/file-explorer/new-files.ts
web-common/src/metrics/service/MetricsTypes.ts
web-common/src/runtime-client/manual-clients.ts
web-local/src/routes/(application)/chart/[name]/+page.svelte
web-local/src/routes/(application)/custom-dashboards/[name]/+page.svelte
web-local/src/routes/(application)/files/[...file]/+page.svelte

Integrates the updated Dashboard component specs in the UI. Note that embedded components breaks in this PR. Should be handled separately.

UI changes for updated Dashboard Component specs

---

runtime/pkg/metricssql/parser.go

This is part of the `time_range` functions work where I missed adding `between` operator part of the ask.

Runtime: Add between operator for metrics_sql

---

web-common/src/features/dashboards/time-dimension-details/charts/ChartTypeSelector.svelte

https://www.notion.so/rilldata/Capitalization-scheme-for-tooltips-e1faab48a5f044b2b3d0ed74335c0e49

Fix copy for alternate chart tooltips

---

web-common/src/features/entity-management/AddAssetButton.svelte

Improve styles on the Add Resource button

---

web-common/src/features/dashboards/time-dimension-details/TDDHeader.svelte
web-common/src/features/dashboards/time-dimension-details/charts/ChartTypeSelector.svelte
web-common/src/features/dashboards/time-series/MetricsTimeSeriesCharts.svelte
web-common/src/features/dashboards/workspace/Dashboard.svelte

Partly revert https://github.com/rilldata/rill/pull/4555 as per https://www.notion.so/rilldata/UXQA-Alt-Viz-fb97d9eb1c5c4fb1bfb3328e83008172?p=c14c24dda8d04920b1f2e73b7cf6b762&pm=s

Revert TDD Header background

---

web-common/src/features/charts/render/VegaLiteRenderer.svelte
web-common/src/features/custom-dashboards/Chart.svelte
web-common/src/features/custom-dashboards/Component.svelte

Chart View: Missing prop

---

web-common/src/features/tables/olap-config.ts

Per https://github.com/rilldata/rill/pull/4684#issuecomment-2085596552

Hide modeling for Pinot projects

---

web-common/src/features/models/workspace/Editor.svelte

Closes [#4745](https://github.com/rilldata/rill/issues/4745)

Model Editor: Remove absolute positioning of footer

---

web-common/src/features/charts/render/VegaLiteRenderer.svelte
web-common/src/features/charts/render/vega-config.ts
web-common/src/features/charts/templates/area.ts
web-common/src/features/charts/templates/grouped-bar.ts
web-common/src/features/charts/templates/simple-bar.ts
web-common/src/features/charts/templates/stacked-area.ts
web-common/src/features/charts/templates/stacked-bar.ts
web-common/src/features/charts/types.ts
web-common/src/features/dashboards/state-managers/selectors/measures.ts
web-common/src/features/dashboards/time-dimension-details/charts/TDDAlternateChart.svelte
web-common/src/features/dashboards/time-dimension-details/charts/utils.ts

Add measure value formatting support for custom charts

Format measure values in custom charts

---

netlify.toml

https://github.com/vega/vega/issues/1106
**Do not push to Prod**

CSP for Vega

---

web-common/src/features/entity-management/RenameAssetModal.svelte
web-common/src/features/models/workspace/ModelWorkspaceCTAs.svelte

Seems like a regression where renaming a folder was not redirecting properly.

Fix redirect on folder rename

---

web-common/src/features/entity-management/resource-invalidations.ts
web-common/src/features/entity-management/watch-files-client.ts

Refetch instead of reset queries to prevent sidebar flashing

---

web-common/src/features/project/selectors.ts

Fix project title for a blank `rill.yaml`

---

web-common/src/features/charts/render/VegaLiteRenderer.svelte

Refac: Increase opacity for custom tooltip to 100%
https://www.notion.so/Alternate-Viz-UX-Pass-3515aafff4f949f18b74a5d15b78bc6a?d=74197268b40e4f54831c00f2fdbae2cc&pvs=4#27f5c5bbe2ff4446916fb3ce69961eec

Refac: Increase opacity for custom tooltip to 100%

---

web-common/src/features/charts/render/VegaLiteRenderer.svelte
web-common/src/features/custom-dashboards/Chart.svelte
web-common/src/features/dashboards/time-dimension-details/TimeDimensionDisplay.svelte
web-common/src/features/dashboards/time-dimension-details/charts/TDDAlternateChart.svelte
web-common/src/features/dashboards/time-dimension-details/charts/patch-vega-spec.ts
web-common/src/features/dashboards/time-dimension-details/charts/utils.ts

Adds highlight/hover interaction to custom TDD charts when TDD table is hovered over.
Also moves some methods out of `utils.ts`

Feat: TDD table hover to chart highlight interaction

---

web-common/src/features/dashboards/time-dimension-details/charts/ChartTypeSelector.svelte
web-common/src/features/dashboards/time-series/MetricsTimeSeriesCharts.svelte

Disabled stacked area and stacked bar chart when there is no active comparison.

Disable stacked charts for no comparison

---

web-common/src/features/sources/modal/AddSourceModal.svelte

Closes https://github.com/rilldata/rill-private-issues/issues/343

Fix bug in conditional for OLAP instructions

---

web-common/src/features/dashboards/time-series/MeasureValueMouseover.svelte

Fixes https://github.com/rilldata/rill-private-issues/issues/258

Fix: Measure tooltip cut off

---

web-admin/src/features/navigation/TopNavigationBar.svelte
web-common/src/components/navigation/breadcrumbs/BreadcrumbItem.svelte
web-local/src/routes/(viz)/+layout.svelte

Closes https://github.com/rilldata/rill-private-issues/issues/336

Fix breadcrumbs case-sensitivity bug

---

docs/blog/0.44.md

With completed bug fixes and misc section

docs: 0.44 release notes

---

web-common/src/features/dashboards/pivot/PivotExpandableCell.svelte

https://www.notion.so/rilldata/Pivot-UI-design-polish-fast-follows-627449790b6c484d8192974535c8b936?pvs=4#3d63b74572c04d8e9f2d4cd01b9712e1

Fix: enlarge target area for nested caret in pivot

---

docs/docs/reference/connectors/motherduck.md
docs/docs/reference/connectors/mysql.md
docs/docs/reference/connectors/postgres.md
docs/docs/reference/connectors/salesforce.md
docs/docs/reference/connectors/sqlite.md

- Include `type: source` in each example snippet
- Change `type: [connector]` to `connector: [connector]`

Docs: update example Source YAML

---

web-common/src/features/dashboards/filters/measure-filters/measure-filter-utils.ts

closes #3980
Toplist query that gets the entries for a measure filter was not getting the correct dimension filters.

fix: Fix measure filters not returning correct results

---

web-common/src/features/entity-management/resource-invalidations.ts
web-common/src/runtime-client/exponential-backoff-tracker.ts
web-common/src/runtime-client/watch-request-client.ts

Simplify streaming reconnection 

---

web-common/src/features/editor/Editor.svelte
web-common/src/features/models/workspace/ModelEditor.svelte
web-common/src/features/sources/editor/SourceEditor.svelte
web-common/src/features/sources/workspace/SourceCTAs.svelte
web-local/src/routes/(application)/[type=workspace]/[name]/+page.svelte
web-local/src/routes/(application)/files/[...file]/+page.svelte

This is a patch fix for an issue related to a race condition when autosaving. It expands upon #4886, but stops short of some more substantial changes that involve removing the use of `createEventDispatcher` and moving the file mutation functionality and localContent cache to the `FileArtifact` class.
Closes: #4878

Fix: Autosave

---

docs/docs/integrate/custom-apis/metrics-sql-api.md
docs/docs/integrate/custom-apis/metrics-sql.md
web-common/src/features/entity-management/AddAssetButton.svelte
web-common/src/features/entity-management/resource-selectors.ts
web-common/src/features/file-explorer/new-files.ts

This PR enables the API file type in the Add -> More File Explorer Menu.
Added some additional documentation and fixes.

feat: enable api file type

---

web-common/src/features/models/workspace/ModelEditor.svelte

This PR patches the current Model editor revert function to dispatch an update to the editor.

Fix: Model editor revert button

---

web-common/src/features/models/workspace/CreateDashboardButton.svelte

Remove Wand icon from generate dashboard button

---

docs/blog/0.44.md
docs/blog/0.45.md

docs: release notes 0.45

---

cli/cmd/user/list.go
cli/pkg/printer/printer.go
cli/pkg/printer/resources.go

Also fixes ugly formatting of the title for the pending invites table.

CLI: Add notice about project-level members to "rill user list"

---

admin/worker/run_autoscaler.go

This pull request refactors the log output for successful slot scaling operations to include the following fields:
- `project_name`
- `updated_slots`
- `prev_slots`
- `org_name`
This update addresses the needs outlined in [Issue #386](https://github.com/rilldata/rill-private-issues/issues/386).

chore: enrich scaling log

---

runtime/drivers/postgres/sql_store.go

Fixes issue raised here : https://discord.com/channels/959796421832343562/1242122283904929913

Runtime : disable prepared statements for postgres connector

---

web-common/src/features/dashboards/pivot/PivotTable.svelte

Pivot: differentiate totals column

---

web-common/src/features/dashboards/pivot/PivotExpandableCell.svelte
web-common/src/features/dashboards/pivot/PivotTable.svelte

pivot: update font weight, chevron color

---

web-common/src/features/dashboards/dashboard-utils.ts
web-common/src/runtime-client/watch-request-client.ts

Fixes an issue where `isSummable` was returning false for functions like APPROX_COUNT_DISTINCT

fix: change summable function check to regex

---

web-common/src/runtime-client/watch-request-client.ts

fix: flip closed connection bool

---

runtime/queries/metricsview_aggregation.go
runtime/queries/metricsview_aggregation_test.go

Comparison aggregation offset fix

---

runtime/drivers/olap.go
runtime/queries/metricsview_aggregation.go
runtime/queries/metricsview_aggregation_test.go

CAMF - Comparison Aggregation Measure Filter

CAMF dups fix

---

web-common/vite.config.ts

fix: vite type issue

---

docs/blog/0.46.md

docs: release notes 0.46

---

runtime/compilers/rillv1/parser.go

Fixes issue reported in Slack: https://rilldata.slack.com/archives/C07710F6932/p1717537677811829

Fix misleading "unknown connector type" error message

---

admin/ai/openai.go
go.mod
go.sum

To be A/B tested against GPT3.5 Turbo before merging!

OpenAI: Upgrade to GPT4o

---

web-admin/src/features/dashboards/query-mappers/getDashboardFromAggregationRequest.ts
web-common/src/features/dashboards/pivot/pivot-data-store.ts
web-common/src/features/dashboards/pivot/pivot-expansion.ts
web-common/src/features/dashboards/pivot/pivot-merge-filters.ts
web-common/src/features/dashboards/pivot/pivot-queries.ts
web-common/src/features/dashboards/pivot/pivot-table-transformations.ts
web-common/src/features/dashboards/pivot/pivot-utils.ts
web-common/src/features/dashboards/stores/dashboard-stores.ts

Add sorting and full filter support for expanded pivot sub tables. Also fixes https://github.com/rilldata/rill-private-issues/issues/407

Add sorting and full filter support for expanded pivot sub tables

---

runtime/metricsview/executor_rewrite_druid_exactify.go

Similar to https://github.com/rilldata/rill/pull/5087

Handle empty result for Druid exactify

---

web-common/src/features/dashboards/dimension-table/DimensionHeader.svelte

feat: start pivot from dimension table

---

web-admin/src/features/navigation/TopNavigationBar.svelte

Uses URL param as fallback for determining organization name.
Closes #4872

fix: enable organization query without user data

---

web-admin/src/features/errors/ErrorBoundary.svelte
web-admin/src/features/errors/error-store.ts
web-admin/src/features/errors/error-utils.ts
web-admin/src/routes/+error.svelte
web-common/src/components/ErrorPage.svelte
web-common/src/components/calls-to-action/CTAContentContainer.svelte

Closes https://github.com/rilldata/rill/issues/3978

Add a "details" section to the error page

---

web-common/src/components/dialog/Dialog.svelte

[Bug report in Slack](https://rilldata.slack.com/archives/C02T907FEUB/p1719319748482559)

Fix missing scrollbar

---

admin/deployments.go
cli/pkg/local/app.go
runtime/drivers/athena/athena.go
runtime/drivers/azure/azure.go
runtime/drivers/bigquery/bigquery.go
runtime/drivers/bigquery/sql_store.go
runtime/drivers/clickhouse/clickhouse.go
runtime/drivers/druid/druid.go
runtime/drivers/duckdb/config.go
runtime/drivers/file/file.go
runtime/drivers/gcs/gcs.go
runtime/drivers/redshift/redshift.go
runtime/drivers/snowflake/snowflake.go
runtime/drivers/snowflake/sql_store.go

Runtime : Fix temp_dir usage for local

---

runtime/drivers/snowflake/sql_store.go

Saw some of these logs appear at microsecond intervals in a prod project – just reducing to something slightly less frequent. (Because debug logs are also buffered and served for the `rill project logs` command.)

Snowflake driver: Reduce chatty debug logs

---

web-common/src/features/dashboards/big-number/MeasureBigNumber.svelte
web-common/src/features/dashboards/time-series/MetricsTimeSeriesCharts.svelte
web-common/src/features/dashboards/time-series/timeseries-data-store.ts
web-common/src/features/dashboards/time-series/totals-data-store.ts

Replace the cross icon with error message received from the API 
Fixes https://github.com/rilldata/rill-private-issues/issues/455
Also addresses #4898

Feat: Display API error for timeseries and totals in the UI

---

.github/workflows/rill-ui.yml

as well as pushes to release branch

Deploy on release branch creation

---

admin/server/projects.go
cli/cmd/shareurl/create.go

- Adds case insensitive checks for the metrics view name in shareable URLs
- Adds validation that the metrics view name and provided fields exist in `rill share-url create`

Fix case sensitivity for shareable URLs

---

web-common/src/features/dashboards/stores/dashboard-stores.ts

fix: Reset sorting when comparison changes

---

cli/cmd/docs/generate.go

docs: subscription subdirectory

---

runtime/compilers/rillv1/data/component-template-v1.json
web-common/src/features/templates/TemplateRenderer.svelte
web-common/src/features/templates/image/Image.svelte
web-common/src/features/templates/types.ts

Adds a image component template
```yaml
type: component
image:
url: https://pbs.twimg.com/profile_images/1753125727107706880/nVQlSOS8_400x400.jpg
css:
object-fit: "contain"
opacity: 1
saturation: 0
blur: 5

feat: add image component

---

web-common/src/features/dashboards/dashboard-utils.ts
web-common/src/features/dashboards/dimension-table/ExportDimensionTableDataButton.svelte
web-common/src/features/dashboards/dimension-table/dimension-table-export-utils.ts
web-common/src/features/dashboards/dimension-table/export-toplist.ts

fix: Order of comparison measures in dimension table export

---

scripts/embed_duckdb_ext/main.go

Skip DuckDB extension download if exists

---

docs/docs/reference/connectors/motherduck.md
docs/docs/reference/olap-engines/duckdb.md
docs/docs/reference/project-files/connectors.md
docs/docs/reference/project-files/dashboards.md

added connector to dashboard and revised the hint in connectors

revised docs

---

admin/billing/biller.go
admin/billing/noop.go
admin/billing/orb.go
admin/worker/trail_end_check.go
admin/worker/worker.go

Checks every midnight for trial period end and logs it

trial end check worker

---

web-common/src/features/dashboards/proto-state/DashboardURLStateProvider.svelte

Closes https://github.com/rilldata/rill-private-issues/issues/326

Fix error handling when loading a dashboard

---

runtime/pkg/observability/observability.go

Similar to https://github.com/DataDog/opentelemetry-examples/blob/main/apps/rest-services/golang/calendar/main.go#L132-L136

Add container id for otel/Datadog

---

web-common/src/features/dashboards/dimension-table/DimensionHeader.svelte
web-common/src/features/dashboards/time-series/MetricsTimeSeriesCharts.svelte
web-common/src/features/dashboards/workspace/Dashboard.svelte

Outstanding:
* Adding divider between timeseries and leaderboards - Done
* Adjust spacing of containers for scrollbars
* The divider invites "draggability", perhaps we should add it?

feat: add pivot for timeseries

---

.github/workflows/docs-check.yml
.github/workflows/prettier.yml
.github/workflows/web-test-code-quality.yml
.github/workflows/web-test-e2e.yml
.github/workflows/web-test-unit-tests.yml
package.json

Added `HUSKY: 0` to the rest of npm install in github actions. Updated prepare script to handle husky install in docs package.json.
ref: https://rilldata.slack.com/archives/CTZ8XBQ85/p1722503514996349

Disable husky run in other github actions

---

cli/cmd/project/status.go

so parser will be nil for viewer role

viewer does not have access to parser

---

CONTRIBUTING.md
Makefile
cli/README.md
web-local/README.md

Also updates the release instructions to match the latest guidelines.

Add rollout sequence and backwards compatibility rules to CONTRIBUTING.md

---

runtime/metricsview/ast.go
runtime/metricsview/executor_rewrite_approx_comparisons.go

disable cte optimization for multi value druid dims

---

web-common/src/components/dropdown-menu/DropdownMenuCheckboxItem.svelte
web-common/src/components/navigation/breadcrumbs/BreadcrumbItem.svelte

Use checkbox menu item on breadcrumb item

---

docs/docs/reference/project-files/dashboards.md

Document `database_schema` in dashboard YAML

Add database_schema

---

web-common/src/features/dashboards/pivot/AddField.svelte

Fix excessive height of Rows and Columns dropdown menu

---

web-admin/src/features/access-request/utils.ts
web-admin/src/features/projects/github/github-errors.ts
web-admin/src/routes/[organization]/[project]/+layout.svelte
web-admin/src/routes/[organization]/[project]/-/invite/+page.svelte
web-common/src/components/preview-table/ConnectedPreviewTable.svelte
web-common/src/features/charts/prompt/generateChart.ts
web-common/src/features/connectors/olap/DatabaseEntry.svelte
web-common/src/features/connectors/olap/DatabaseExplorer.svelte
web-common/src/features/connectors/olap/TableSchema.svelte
web-common/src/features/dashboards/time-series/timeseries-data-store.ts
web-common/src/features/entity-management/RenameAssetModal.svelte
web-local/src/routes/(application)/files/[...file]/+page.ts

Fix for the below typescript error -
```
Cannot read properties of undefined (reading 'message')
```
[Telemetry Dashboard](https://ui.rilldata.com/rilldata/internal-rill-cloud-metrics/rill_ui_telemetry?state=CgYKBFAxNEQYBSIJCgdyaWxsLVBQKg10b3RhbF9yZWNvcmRzMgVzdGFjazgASAFYAWAEag1Bc2lhL0NhbGN1dHRheAKAAQGYAf%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwGiAbAHGq0HCAgSqAcapQcICRIHCgVzdGFjaxKXBxKUBxqRB1R5cGVFcnJvcjogQ2Fubm90IHJlYWQgcHJvcGVydGllcyBvZiB1bmRlZmluZWQgKHJlYWRpbmcgJ21lc3NhZ2UnKQogICAgYXQgQXJyYXkuUHQgKGh0dHBzOi8vdWkucmlsbGRhdGEuY29tL19hcHAvaW1tdXRhYmxlL25vZGVzLzMuNmFiZTEwMzEuanM6MToxMjY5MSkKICAgIGF0IFJ0IChodHRwczovL3VpLnJpbGxkYXRhLmNvbS9fYXBwL2ltbXV0YWJsZS9ub2Rlcy8zLjZhYmUxMDMxLmpzOjE6MTU1OTMpCiAgICBhdCBPdCAoaHR0cHM6Ly91aS5yaWxsZGF0YS5jb20vX2FwcC9pbW11dGFibGUvY2h1bmtzL2luZGV4LmQ1MjcxM2YzLmpzOjQ6Mz …

fix: safe chaining of error response messages

---

docs/blog/0.10.md
docs/blog/0.11.md
docs/blog/0.12.md
docs/blog/0.13.md
docs/blog/0.14.md
docs/blog/0.15.md
docs/blog/0.16.md
docs/blog/0.4.md
docs/blog/0.5.md
docs/blog/0.6.md
docs/blog/0.7.md
docs/blog/0.8.md
docs/blog/0.9.md
package-lock.json

discussed with Marianne, there are broken links in the release notes so we removing this because it doesn't look good.

removed broken videos in old release notes

---

web-admin/src/features/projects/github/ProjectGithubConnection.svelte

Until we figure out a good path for edit we will be disabling it. Users will have to disconnect and reconnect to another repo.

fix: Disabling edit button for github connection.

---

runtime/controller.go
runtime/registry.go

This PR adds a new `reconciled_resource` event of type `log`, which is emitted when a reconcile finishes (except if the reconcile was cancelled and will be retried, which can happen if the YAML changes or the process is terminated).
The event has the following attributes:
- `name` (string): name of the resource
- `type` (string): type of the resource
- `elapsed_ms` (int64): how long the reconcile ran in milliseconds
- `deleted` (bool): indicates if the resource was deleted
- `renamed` (bool): indicates if the resource was renamed
- `error` (string): contains the error returned by the reconcile, if any
Contributes to https://github.com/rilldata/rill/issues/5410

Emit events when a reconcile finishes

---

web-common/src/features/custom-dashboards/Chart.svelte
web-common/src/features/custom-dashboards/Component.svelte
web-common/src/features/entity-management/WatchResourcesClient.ts
web-common/src/features/templates/TemplateRenderer.svelte
web-common/src/features/templates/charts/ChartTemplate.svelte
web-common/src/features/templates/select/Select.svelte
web-common/src/features/workspaces/ChartWorkspace.svelte
web-common/src/runtime-client/invalidation.ts
web-common/src/runtime-client/manual-clients.ts

refac: deprecate chart data query in favor of resolved components query

---

.goreleaser.yaml
runtime/drivers/duckdb/extensions/extensions_linux_arm64.go
scripts/embed_duckdb_ext/main.go
scripts/install.sh

Resolve:
https://rilldata.slack.com/archives/C01190F1R1D/p1724443548781379

feat: add support for linux aarch64

---

runtime/drivers/clickhouse/model_manager.go
runtime/drivers/clickhouse/olap.go
runtime/drivers/clickhouse/olap_test.go

https://github.com/rilldata/rill-private-issues/issues/609

Runtime: fix distributed analytical queries for clickhouse self hosted clusters

---

web-common/src/components/preview-table/ConnectedPreviewTable.svelte

Destructuring the TanStack Query response object seems to fix https://github.com/rilldata/rill/issues/5336.

SQL Editor: Fix stuck loading state

---

web-common/src/features/templates/table/TableRenderer.svelte
web-common/src/features/templates/table/TableTemplate.svelte

Allow scroll on custom table component and expand table to take full width of the container.

fix: scroll on custom table component 

---

proto/gen/rill/admin/v1/admin.swagger.yaml
proto/gen/rill/admin/v1/api.pb.go
proto/gen/rill/runtime/v1/queries.pb.go
proto/gen/rill/runtime/v1/runtime.swagger.yaml
proto/rill/runtime/v1/queries.proto
runtime/queries/metricsview_aggregation.go
runtime/queries/metricsview_aggregation_test.go
web-admin/src/client/gen/index.schemas.ts
web-common/src/proto/gen/rill/admin/v1/api_pb.ts
web-common/src/proto/gen/rill/runtime/v1/queries_pb.ts
web-common/src/runtime-client/gen/index.schemas.ts

closes https://github.com/rilldata/rill/issues/5542

Support passing where and where_sql at the same time in the metrics APIs

---

web-common/src/lib/number-formatting/utils/number-parts-utils.ts

Addresses https://github.com/rilldata/rill/security/code-scanning/3

Fix (Number Formatting): casing mistake in regex

---

web-common/src/features/custom-dashboards/AddChartMenu.svelte
web-common/src/features/entity-management/AddAssetButton.svelte
web-common/src/features/file-explorer/new-files.ts

Changes labels for
- custom dashboard -> canvas dashboard
- chart -> component
Does not change any function names or routes.

fix: label change for canvas dashboards

---

go.mod
runtime/drivers/clickhouse/olap.go
runtime/pkg/jsonval/jsonval.go
runtime/pkg/pbutil/pbutil.go

closes https://github.com/rilldata/rill-private-issues/issues/277

support for tuple and geometric types for clickhouse 

---

web-admin/src/features/projects/user-invite/UserInviteAllowlist.svelte
web-admin/src/features/projects/user-invite/UserInviteForm.svelte
web-admin/src/routes/[organization]/[project]/-/invite/+page.svelte

1. Fix user invite when there is a single entry and it is a pill.
2. Remove domain whitelist message when there are no domains added.
3. In user invite page, `Continue` => `Skip`

fix: User invite not working for a single pill

---

web-common/src/features/charts/prompt/ChartDataDisplay.svelte
web-common/src/features/workspaces/ChartWorkspace.svelte

Fixes
https://github.com/rilldata/rill-private-issues/issues/630
https://github.com/rilldata/rill-private-issues/issues/631
Instead of infinite loading state, we show the error message for the failed request

fix: infinite query glitch on invalid spec

---

web-admin/src/features/alerts/listing/AlertsTable.svelte
web-admin/src/features/alerts/metadata/AlertMetadata.svelte
web-admin/src/features/alerts/selectors.ts

fix: alerts metadata when created through code

---

web-common/src/features/dashboards/pivot/pivot-infinite-scroll.ts
web-common/src/features/dashboards/pivot/pivot-utils.ts

Enables time comparison for time dimensions in the pivot table.

feat: enable time comparison for time dimension in pivot

---

runtime/validate.go

closes https://github.com/rilldata/rill/issues/5618

feat : measure name validation for clickhouse

---

runtime/connections.go
runtime/connections_test.go
runtime/drivers/registry.go
runtime/reconcilers/connector.go
runtime/reconcilers/migration.go
runtime/reconcilers/model.go
runtime/reconcilers/util.go
runtime/resolvers/glob.go
runtime/resolvers/sql.go
runtime/server/components.go
runtime/server/connectors.go

closes https://github.com/rilldata/rill/issues/5590
**NOTE** : template resolution is still case sensitive

fix : allow case insensitive variables

---

runtime/drivers/duckdb/olap.go

- Ensures the temporary table is always created on the same connection as the deletes and inserts
- Changes the `unique_key` comparison to use `IS NOT DISTINCT FROM`

Fixes for incremental_strategy=merge on DuckDB

---

web-common/src/features/charts/chartYaml.ts
web-common/src/features/charts/prompt/GenerateChartYAMLPrompt.svelte
web-common/src/features/charts/prompt/generateChart.spec.ts
web-common/src/features/file-explorer/new-files.ts

Change naming of chart to component in autogenerated yaml and tests

fix: chart to component

---

web-admin/src/features/public-urls/CreatePublicURLForm.svelte

[Bug report in Slack](https://rilldata.slack.com/archives/CTZ8XBQ85/p1726094564274689?thread_ts=1726094052.424129&cid=CTZ8XBQ85)

Public URLs: Prevent user from creating already-expired URLs

---

runtime/compilers/rillv1/data/component-template-v1.json
web-common/src/features/templates/kpi/KPITemplate.svelte
web-common/src/features/templates/table/TableTemplate.svelte
web-common/src/features/templates/table/selector.ts
web-common/src/features/templates/types.ts

Renames the `metric_view` key for table and kpi to `metrics_view`

fix: rename metric_view key

---

web-common/src/features/alerts/form-utils.ts

Closes https://github.com/rilldata/rill-private-issues/issues/682

Fix (Alerts): Remove constraint on percent change

---

web-common/src/features/canvas-dashboards/CanvasDashboardPreview.svelte
web-common/src/features/canvas-dashboards/DashboardWrapper.svelte
web-common/src/features/canvas-dashboards/ResizeHandle.svelte

Solves #5715 as well as two other small display issues.

fix: canvas bounds and sizing issues

---

web-common/src/features/templates/kpi/KPITemplate.svelte
web-common/src/features/templates/table/selector.ts

Temporary fix as we wait for the new time syntax.

fix: upper timeranges

---

web-common/src/components/navigation/breadcrumbs/BreadcrumbItem.svelte

fix: explore flashes on breadcrumb interaction

---

web-common/src/features/dashboards/big-number/MeasureBigNumber.svelte
web-common/src/lib/number-formatting/format-measure-value.ts
web-local/tests/dashboards/number-formatting.spec.ts

Implements https://www.notion.so/rilldata/Formatting-the-display-of-metrics-for-higher-precision-in-tables-and-other-contexts-28371608b0924fd99be243110b12f32c?pvs=4#baef785f6d9d428580db10fdc4862ba0
Part of [#5564](https://github.com/rilldata/rill/issues/5564)

feat: always format big number

---

web-common/src/components/date-picker/Calendar.svelte
web-common/src/components/date-picker/Day.svelte
web-common/src/components/date-picker/Month.svelte
web-common/src/features/dashboards/time-controls/super-pill/components/CalendarPlusDateInput.svelte

Updates the `Calendar` component API to accept a single `selection` prop and provides more flexibility around valid/invalid inputs to support a wider number of use cases.

update calendar component api

---

admin/billing.go

noop biller will return trial end date as zero time

don't raise billing errors if biller is noop

---

docs/docs/reference/olap-engines/clickhouse.md
docs/src/components/LoomVideo.js

adding Eric's CH video to docs!

as requested by Marianne

---

web-common/src/features/dashboards/dashboard-fetch-mocks.ts
web-common/src/runtime-client/fetchWrapper.ts

Naively returns the raw response for non-json responses.

fix: return response for non json

---

web-common/src/features/sources/modal/SourceImportedModal.svelte

fix: not all sources are named hee haw

---

runtime/drivers/bigquery/warehouse.go

Closes https://github.com/rilldata/rill-private-issues/issues/747

BigQuery: Fix temporary files not being cleared immediately after ingestion

---

web-admin/src/features/dashboards/share/ShareDashboardButton.svelte
web-admin/src/features/public-urls/CreatePublicURLForm.svelte

Fix for https://www.notion.so/rilldata/v0-50-0-QA-114ba33c8f5780bd897ecb99547ed623#114ba33c8f5780c29dbedd81e2cf7f8e

Header size and spacing fix

---

web-admin/src/features/alerts/selectors.ts
web-admin/src/features/scheduled-reports/selectors.ts

Addresses [this Notion UXQA item](https://www.notion.so/rilldata/v0-50-0-QA-114ba33c8f5780bd897ecb99547ed623?pvs=4#114ba33c8f5780b3bb5ac38e00165e03)
Bug caused by https://github.com/rilldata/rill-private-issues/issues/719

Fix (Alerts / Reports): ensure queries are refetched after invalidation

---

web-common/src/features/dashboards/pivot/PivotChip.svelte
web-common/src/features/dashboards/pivot/PivotDragItem.svelte
web-common/src/features/dashboards/pivot/types.ts
web-common/src/features/dashboards/state-managers/selectors/pivot.ts

pivot: show pill descriptions when available

---

web-common/src/features/entity-management/AddAssetButton.svelte
web-common/src/features/entity-management/resource-icon-mapping.ts
web-common/src/layout/navigation/Navigation.svelte

- Use the `Database` icon for the "Data" menu item
- Color the `Theme` icon
- Ensure the focus state isn't truncated

Nits: "Add" button

---

web-common/src/features/canvas/CanvasDashboardEmbed.svelte
web-common/src/features/workspaces/ComponentWorkspace.svelte

Scroll bars were showing unnecessarily in the ComponentWorkspace.

fix component workspace display

---

web-common/src/features/metrics-views/ai-generation/generateMetricsView.ts

Patches https://github.com/rilldata/rill/pull/5833

Fix (Autogenerate Explore): Actually use the Metrics View as a base

---

web-common/src/features/explores/ExplorePreviewCTAs.svelte
web-common/src/features/file-explorer/new-files.ts
web-common/src/features/metrics-views/GoToDashboardButton.svelte
web-common/src/features/metrics-views/MetricsViewMenuItems.svelte
web-common/src/features/sources/modal/SourceImportedModal.svelte

Addresses a handful of [UXQA items](https://www.notion.so/rilldata/v0-50-0-QA-114ba33c8f5780bd897ecb99547ed623). See the commit messages for details.

Rill Developer: Various UXQA

---

web-common/src/components/forms/InputWithConfirm.svelte
web-common/src/features/canvas/CanvasDashboardPreview.svelte
web-common/src/features/canvas/ViewSelector.svelte
web-common/src/features/explores/PreviewButton.svelte
web-common/src/features/workspaces/CanvasDashboardWorkspace.svelte
web-common/src/features/workspaces/ExploreWorkspace.svelte
web-common/src/features/workspaces/MetricsWorkspace.svelte
web-common/src/layout/ApplicationHeader.svelte
web-common/src/layout/workspace/WorkspaceContainer.svelte
web-common/src/layout/workspace/WorkspaceHeader.svelte

- Remove "global" preview button
- Add asset level preview buttons in workspaces
- Add preview button tooltip
- Move show grid toggle to canvas overlay
- Change `ViewSelector` corner rounding

0.50 uxqa fixes

---

runtime/metricsview/executor_rewrite_druid_groups.go

Fixes https://github.com/rilldata/rill-private-issues/issues/732

optimize druid query for complex measure

---

web-common/src/features/workspaces/ExploreWorkspace.svelte

shift explore preview button placement

---

web-common/src/features/models/workspace/ModelWorkspaceCTAs.svelte
web-common/src/features/workspaces/ModelWorkspace.svelte

update go to metrics view button styles

---

web-common/src/features/file-explorer/new-files.ts

https://docs.rilldata.com/reference/project-files/metrics_views -> https://docs.rilldata.com/reference/project-files/metrics-views
(Note though that this docs page is yet-to-be created.)

Edit link to Metrics View docs

---

web-admin/src/features/projects/github/GithubRepoSelectionDialog.svelte

Fix CI lint job https://rilldata.slack.com/archives/C02T907FEUB/p1728587092968199

Remove unused prop from button

---

runtime/drivers/olap.go
runtime/metricsview/ast.go

Fixes https://github.com/rilldata/rill-private-issues/issues/748

arrayJoin unnest for clickhouse

---

web-admin/src/features/organizations/users/AvatarCircleList.svelte
web-admin/src/features/organizations/users/OrgUsersTable.svelte
web-admin/src/features/organizations/users/OrgUsersTableUserCompositeCell.svelte
web-admin/src/routes/[organization]/-/users/+page.svelte

Use photo url in users table

---

web-common/src/components/tooltip/TooltipDescription.svelte

https://rilldata.slack.com/archives/C02T907FEUB/p1728999590009859
Increase the line clamp to accommodate larger descriptions.

refac: increase tooltip description lines

---

web-admin/src/features/bookmarks/Bookmarks.svelte
web-admin/src/features/bookmarks/applyBookmark.ts

closes https://github.com/rilldata/rill-private-issues/issues/806

fix: issues with bookmarks selection and deletion

---

web-admin/src/features/projects/status/ProjectResources.svelte

https://rilldata.slack.com/archives/C02T907FEUB/p1729257410994859
https://github.com/user-attachments/assets/5e0469e9-43d3-4dc7-a3f8-32cb9e85db52

Reactive resources when switching projects

---

runtime/drivers/clickhouse/clickhouse.go

Resolve: https://github.com/rilldata/rill/issues/5830

feat: add database spec in clickhouse connector

---

web-admin/src/routes/[organization]/[project]/explore/[dashboard]/+page.svelte

Closes https://github.com/rilldata/rill/issues/5947

Web: Use the Explore's `title` for the page's title

---

admin/billing.go

Moving some bug fixes from #5431

fix: time check during blocking issues

---

web-common/src/features/explores/PreviewButton.svelte
web-common/src/features/workspaces/ExploreWorkspace.svelte

disable preview button when explore resource is reconciling

---

web-common/src/features/dashboards/time-dimension-details/TDDTable.svelte

The TDD is being refactored to use the pivot surface, but this is a quick fix to address #5707.

fix: display null values with italics in TDD

---

admin/billing/biller.go
admin/billing/noop.go
admin/billing/orb.go
admin/jobs/river/org_jobs.go

instead of just cancelling subscriptions, completely remove customer from orb and stripe on org deletion

completely remove org from orb and stripe

---

admin/billing.go
admin/billing/orb.go
admin/jobs/river/org_jobs.go
admin/jobs/river/river.go
admin/server/billing.go
admin/user.go

retry start trial until org billing init is done

check org billing init in start trial job

---

web-common/src/features/explores/ExplorePreviewCTAs.svelte
web-common/src/layout/ApplicationHeader.svelte

Closes https://github.com/rilldata/rill/issues/5873

Fix disappearing "View as" button

---

web-admin/src/features/projects/status/ResourceErrorMessage.svelte
web-common/src/components/table/BasicTable.svelte
web-common/src/lib/actions/copy-to-clipboard.ts

Closes https://github.com/rilldata/rill/issues/5604

Project Status: ability to copy resource error messages to clipboard

---

web-common/src/layout/ApplicationHeader.svelte
web-common/src/layout/navigation/route-utils.ts

closes [#5907](https://github.com/rilldata/rill/issues/5907)

fix: Hide deploy button when on deploy page

---

docs/docs/reference/project-files/rill-yaml.md

Added metrics-views and explores to project YAML

---

web-common/src/features/dashboards/rows-viewer/RowsViewerAccordion.svelte

Small fix for displaying a dashboard "windowed" in another surface.

fix: RowsViewerAccordion fix

---

web-common/src/features/entity-management/actions.ts
web-common/src/features/entity-management/file-path-utils.ts
web-common/src/features/file-explorer/FileExplorer.svelte
web-common/src/features/file-explorer/NavDirectory.svelte
web-common/src/features/file-explorer/NavFile.svelte
web-local/tests/file-explorer.spec.ts

Closes https://github.com/rilldata/rill-private-issues/issues/832, https://github.com/rilldata/rill/issues/4852

File Explorer: Add "Duplicate" menu item

---

web-common/src/features/dashboards/pivot/PivotTable.svelte

For taller screens check if more data row needs to be fetched in pivot table.
https://rilldata.slack.com/archives/C02T907FEUB/p1730398518349819

fix: fetch extra page in pivot for tall screen

---

web-common/src/features/entity-management/WatchResourcesClient.ts

Enables reactivity for the Visual Explore editing surface.

fix: invalidate explore resource

---

web-common/src/components/data-graphic/compositions/timestamp-profile/TimestampBound.svelte
web-common/src/components/data-graphic/compositions/timestamp-profile/TimestampDetail.svelte
web-common/src/components/data-graphic/compositions/timestamp-profile/TimestampMouseoverAnnotation.svelte
web-common/src/features/dashboards/pivot/pivot-column-definition.ts
web-common/src/features/dashboards/time-dimension-details/charts/TDDAlternateChart.svelte
web-common/src/features/dashboards/time-series/MetricsTimeSeriesCharts.svelte
web-common/src/features/dashboards/time-series/utils.ts
web-common/src/lib/convertTimestampPreview.ts
web-common/src/lib/time/grains/index.ts
web-common/src/lib/time/timezone/index.ts

Fixes https://rilldata.slack.com/archives/CTZ8XBQ85/p1730737503655009

fix: account for DST changes while adjusting offsets

---

docs/docs/reference/connectors/motherduck.md

closes https://github.com/rilldata/rill/issues/5935

update docs for motherduck connector

---

web-common/src/features/metrics-views/errors.ts

fix: line error boundaries

---

web-admin/src/features/navigation/TopNavigationBar.svelte
web-admin/src/features/navigation/nav-utils.ts

Fix https://www.notion.so/rilldata/v0-51-0-QA-129ba33c8f5780b68dbff21c0e433094?pvs=4#129ba33c8f5780c2abf0eca5c7765545
https://github.com/user-attachments/assets/7a4f73df-ceee-482d-9135-95eeebf9686c

Revert border b in top nav bar

---

web-common/src/features/dashboards/time-controls/super-pill/components/Zone.svelte
web-common/src/features/dashboards/time-controls/super-pill/components/ZoneDisplay.svelte

This style of DropdownItem will be used in multiple places going forward.

feat: create ZoneDisplay component

---

docs/package.json
package-lock.json
package.json
web-admin/package.json
web-auth/package.json
web-common/package.json
web-local/package.json

https://github.com/rilldata/rill/issues/5592

ops: align versions in monorepo

---

web-admin/src/features/organizations/settings/OrgNameSettings.svelte
web-admin/src/features/organizations/settings/SettingsContainer.svelte

Fix https://www.notion.so/rilldata/v0-51-0-QA-129ba33c8f5780b68dbff21c0e433094#129ba33c8f5780c2abf0eca5c7765545

Address org renames

---

web-common/src/lib/number-formatting/format-measure-value.ts

[Discussed in Slack](https://rilldata.slack.com/archives/C02T907FEUB/p1730913404230269)

Number formatting (Big Number): override user-provided d3 formatter with `percentage` formatter, when appropriate

---

admin/jobs/river/validate_deployments.go

Fixes: https://github.com/rilldata/rill-private-issues/issues/833
Fixes: https://github.com/rilldata/rill-private-issues/issues/893

Remove implicit edit instance invocation from validate deployments job

---

web-common/src/features/dashboards/time-dimension-details/charts/TDDAlternateChart.svelte
web-common/src/features/dashboards/time-dimension-details/charts/patch-vega-spec.ts
web-common/src/features/dashboards/time-series/MetricsTimeSeriesCharts.svelte
web-common/src/features/dashboards/time-series/TimeSeriesChartContainer.svelte

Fixes https://github.com/rilldata/rill-private-issues/issues/891

fix: handle undefined dates in charts

---

web-admin/src/features/projects/status/ProjectResources.svelte

closes https://github.com/rilldata/rill/issues/6077
This PR allows users to refresh all sources and models without having to `rill project refresh` in the CLI every single time.
https://github.com/user-attachments/assets/189153e1-9fa8-4883-bb63-48ada62fb20d

Ability to refresh all sources and models in Project Resources Table

---

web-common/src/features/dashboards/proto-state/DashboardURLStateProvider.svelte

Closes https://github.com/rilldata/rill/issues/5964
Before:
After:

Fix: handle `null` response from `TimeRangeSummary` API

---

cli/cmd/devtool/data/cloud-deps.docker-compose.yml
cli/cmd/devtool/data/otel-collector-config.yaml
cli/cmd/devtool/dotenv.go
cli/cmd/devtool/seed.go
cli/cmd/devtool/start.go

Rill E2E setup

---

web-admin/src/routes/[organization]/[project]/explore/[dashboard]/+page.svelte

Closes https://github.com/rilldata/rill-private-issues/issues/926

fix: key cloud dashboard component on exploreName

---

web-common/src/features/dashboards/pivot/PivotTable.svelte
web-common/src/features/dashboards/pivot/pivot-data-store.ts

Fixed https://github.com/rilldata/rill-private-issues/issues/908

fix: scroll position in pivot

---

admin/server/reports.go

By returning a (wrapped) `err` with a code, we fallback to the default status code annotations added by the error handling middleware.
This problem applies elsewhere in the server, but fixing this gradually as we see issues related to this.

Avoid marking context errors as internal in reports APIs

---

scripts/tsc-with-whitelist.sh
web-admin/src/features/billing/Payment.svelte
web-admin/src/routes/[organization]/-/settings/+layout.svelte
web-admin/src/routes/[organization]/-/settings/+layout.ts
web-admin/src/routes/[organization]/-/settings/billing/+page.svelte
web-admin/src/routes/[organization]/-/settings/usage/+page.svelte
web-admin/src/routes/[organization]/-/settings/usage/+page.ts

1. Hide the Billing tab's Payment module
2. Hide the Usage tab

Billing UI: Hide modules from Orgs on Enterprise plans

---

web-common/src/features/dashboards/pivot/DragList.svelte

Closes https://github.com/rilldata/rill/issues/6108

feat: Add clear button to remove pills from pivot header

---

web-admin/src/features/organizations/users/OrgUsersTable.svelte
web-admin/src/features/organizations/users/create-infinite-query-org-invites.ts
web-admin/src/features/organizations/users/create-infinite-query-org-users.ts
web-admin/src/routes/[organization]/-/users/+page.svelte

closes https://github.com/rilldata/rill/issues/6113
https://github.com/user-attachments/assets/95d880a2-e84b-400c-bce7-9c1d21e63916

Support infinite query when listing org users and invites

---

web-common/src/features/dashboards/pivot/PivotTable.svelte

Users can drag and select multiple values to copy

Allow selection of pivot cell values

---

web-common/src/features/visual-editing/SelectionDropdown.svelte
web-common/src/features/workspaces/VisualExploreEditing.svelte

Fixes an issue in the visual explore editor where the exclude mode was not being respected when toggling items.

fix: exclude mode handling

---

admin/server/projects.go
cli/cmd/env/set.go
runtime/compilers/rillv1/parse_rillyaml.go
runtime/pkg/env/env.go
runtime/pkg/env/env_test.go

closes https://github.com/rilldata/rill/issues/6112

feat : Add validation for env names

---

runtime/drivers/clickhouse/clickhouse.go
runtime/drivers/druid/druid.go
runtime/drivers/pinot/pinot.go
web-common/src/features/sources/modal/yupSchemas.ts

Cloud urls don't have port so one has to add 0 which is confusing and user may not know that 0 works as empty port

mark olap port optional

---

web-admin/src/features/organizations/users/AvatarListItem.svelte
web-admin/src/features/projects/user-management/OrganizationItem.svelte
web-admin/src/features/projects/user-management/ShareProjectPopover.svelte
web-admin/src/features/projects/user-management/UsergroupAvatar.svelte

Address https://www.notion.so/rilldata/Improve-label-copies-to-reduce-confusion-152ba33c8f5780b6b978c34e87ff00e9

Project share copy feedfback

---

web-admin/src/routes/[organization]/-/users/+page.svelte

closes https://github.com/rilldata/rill/issues/6205

Search by name and email in org users

---

runtime/drivers/athena/athena.go
runtime/drivers/athena/warehouse.go

Added support for STS AssumeRole in the Athena connector.

athena-connector: support sts assumerole

---

web-common/src/features/dashboards/dimension-table/DimensionDisplay.svelte
web-common/src/features/dashboards/dimension-table/DimensionHeader.svelte
web-common/src/features/dashboards/time-dimension-details/TDDHeader.svelte
web-common/src/features/dashboards/time-dimension-details/TimeDimensionDisplay.svelte
web-common/src/features/dashboards/time-series/MetricsTimeSeriesCharts.svelte
web-common/src/features/dashboards/workspace/Dashboard.svelte

Closes https://github.com/rilldata/rill-private-issues/issues/983

Hide all "Start pivot" buttons when `embeds.hide_pivot: true`

---

go.mod

Fixed by running `go mod tidy`

Fix AWS STS dependency in `go.mod`

---

web-common/src/features/dashboards/dimension-table/DimensionHeader.svelte
web-common/src/features/dashboards/time-dimension-details/TDDHeader.svelte

Closes https://github.com/rilldata/rill-private-issues/issues/981

Fix "Select all" buttons

---

web-admin/src/features/alerts/metadata/AlertFilters.svelte
web-admin/src/features/billing/plans/CancelledTeamPlan.svelte
web-admin/src/features/billing/plans/TrialPlan.svelte
web-admin/src/features/bookmarks/BookmarkDialog.svelte
web-admin/src/features/navigation/TopNavigationBar.svelte
web-admin/src/routes/[organization]/[project]/-/settings/public-urls/+page.svelte
web-common/src/features/alerts/alert-preview-data.ts
web-common/src/features/alerts/utils.ts
web-common/src/features/dashboards/filters/FilterChipsReadOnly.svelte
web-common/src/features/dashboards/leaderboard/LeaderboardControls.svelte
web-common/src/features/dashboards/state-managers/selectors/measures.ts
web-common/src/features/dashboards/time-dimension-details/TDDHeader.svelte
web-common/src/features/metrics-views/GoToDashboardButton.svelte
web-common/src/features/visual-editing/MeasureDimensionSelector.svelte

Similar to https://github.com/rilldata/rill/pull/6142 remove use of null coalescing for labels.

Fix: Use logical or for labels

---

web-common/src/features/dashboards/time-dimension-details/charts/ChartTypeSelector.svelte

Closes https://github.com/rilldata/rill/issues/6228

Nit: add tooltip for disabled chart

---

web-admin/src/features/projects/status/ProjectGlobalStatusIndicator.svelte
web-admin/src/features/projects/status/ProjectParseErrors.svelte
web-admin/src/features/projects/status/ProjectResources.svelte

This PR better ensures the Project Status page is up-to-date.
Closes https://github.com/rilldata/rill-private-issues/issues/1024

Add `refetchOnWindowFocus` to project status queries

---

web-admin/src/features/projects/status/ProjectResources.svelte
web-admin/src/features/projects/status/RefreshConfirmDialog.svelte

Cherry-picked the confirm dialog changes from https://github.com/rilldata/rill/pull/6175
https://github.com/user-attachments/assets/52d0d1cd-81b1-480d-b0b2-f1f14bef0088

Refresh all resources confirm dialog

---

runtime/controller.go
runtime/pkg/graceful/context.go

- Avoids reporting a graceful controller shutdown as an error if it happens during a catalog flush
- Increases the chance of correctly flushing the catalog changes during shutdown

Gracefully handle controller shutdown during a catalog flush

---

admin/server/alerts.go
admin/server/deployment.go
admin/server/projects.go
admin/server/server.go

Fixes these alerts, which are not internal errors:
- https://rilldata.slack.com/archives/C05TXA7QSTY/p1736872654591969
- https://rilldata.slack.com/archives/C05TXA7QSTY/p1736877813856259

Fix normal errors errorneously marked internal

---

admin/worker/run_autoscaler.go

Closes https://github.com/rilldata/rill-private-issues/issues/1016

Check slots quotas in the autoscaler

---

docs/docs/reference/project-files/advanced-models.md

https://rilldata.slack.com/archives/C088S9KJB17/p1736960544177689

Adding advanced model output parameters from example

---

web-common/src/features/entity-management/AddAssetButton.svelte

Put the Add Canvas dashboard option behind the feature flag.

Add feature flag for Canvas dashboard menu option

---

web-common/src/features/entity-management/AddAssetButton.svelte

Adds beta tag to canvas menu item

Canvas: Add beta tag to canvas menu item

---

web-common/src/features/dashboards/leaderboard/Leaderboard.svelte
web-common/src/features/dashboards/leaderboard/LeaderboardDisplay.svelte
web-common/src/features/dashboards/leaderboard/LeaderboardRow.svelte
web-common/src/features/dashboards/leaderboard/LeaderboardTooltipContent.svelte

Adds the ability to copy individual values in the dimension Leaderboards.
Changes tooltip implementation and copy to reflect this functionality.

feat: leaderboard value copy

---

cli/cmd/env/pull.go

Closes https://github.com/rilldata/rill/issues/6476

Set `rill env pull` to resolve variables for the `dev` environment

---

web-common/src/features/dashboards/pivot/DragList.svelte
web-common/src/features/dashboards/pivot/PivotChip.svelte

Adds quick add actions for pivot pills
https://www.notion.so/rilldata/Quick-add-Dimension-and-Measures-in-Pivot-15aba33c8f5780c482b4ddfd8a35dd52?pvs=4

feat: add quick actions for pivot

---

web-common/src/features/welcome/ProjectCards.svelte
web-common/src/features/welcome/constants.ts
web-local/tests/init.spec.ts
web-local/tests/utils/test.ts

feat: project initialization tests

---

web-admin/src/features/dashboards/share/ShareDashboardPopover.svelte
web-admin/src/features/public-urls/CreatePublicURLForm.svelte
web-common/src/components/date-picker/Calendar.svelte

closes https://github.com/rilldata/rill-private-issues/issues/1149

Set max date for public url form

---

runtime/server/api.go

Fixes issue introduced here: https://github.com/rilldata/rill/commit/7809ad9fa9b98762db8c394a3ed563136e474eac#diff-b3c9902a9c2b52c0b4712c5dac39b0ae396918c0ea3f0b7c3a68bd8430083efdL73

Add API resolver properties back

---

scripts/install.sh

This reverts commit be1bf98299fee3004895b401376480fd9ad141a6.

Revert "disable syftdata (#6523)"

---

web-common/src/components/dropdown-menu/DropdownMenuCheckboxItem.svelte

fix: checkbox indicator lag

---

web-admin/src/features/navigation/TopNavigationBar.svelte

* removed top/bottom padding for custom logos
* matches line height of avatar
* removed bg:hover - checked with janet.

fix: padding and remove hover bg

---

web-admin/src/features/navigation/TopNavigationBar.svelte
web-admin/src/features/organizations/selectors.ts
web-admin/src/routes/+layout.svelte
web-admin/src/routes/+layout.ts

Separates out the "showing" part from #6521 
Add a logo using `rill org upload-logo <org> <path-to-img>`. The logo will show up in the top nav bar.

feat: Show custom logo in UI

---

web-admin/src/components/table/Table.svelte
web-admin/src/features/alerts/history/AlertHistoryTable.svelte
web-admin/src/features/scheduled-reports/history/ReportHistoryTable.svelte

fix: removes search for listings in cloud

---

web-admin/src/features/projects/environment-variables/AddDialog.svelte

Duplicate check for form envs

---

web-common/src/features/dashboards/state-managers/selectors/dimensions.ts
web-common/src/features/dashboards/state-managers/selectors/measures.ts

Closes https://github.com/rilldata/rill/issues/6546

List measures & dimensions by the order specified in the Explore

---

web-common/src/components/forms/Input.svelte

fix: wrap multiline input

---

runtime/pkg/rduckdb/db.go

fix : Release snapshot on all error paths in AcquireReadConnection

---

web-common/src/features/canvas/components/charts/bar-chart/spec.ts
web-common/src/features/canvas/components/charts/builder.ts
web-common/src/features/canvas/components/charts/stacked-bar/spec.ts

- Handle special characters in field
- For bar chart and stacked bar, make legend interactive

Canvas: chart improvements, add legend binding

---

web-admin/src/features/projects/status/ProjectResources.svelte

Address offline feedback https://rilldata.slack.com/archives/D07ED3LUUES/p1738878691539669
https://github.com/user-attachments/assets/a75d2401-1ee5-4c87-bbfe-0a17a6335665

Disable refresh all button when refreshing single resource

---

web-common/src/features/canvas/CanvasComponent.svelte
web-common/src/features/canvas/components/charts/Chart.svelte
web-common/src/features/canvas/components/charts/builder.ts
web-common/src/features/canvas/inspector/AlignmentInput.svelte

Fix low hanging fruits from https://www.notion.so/rilldata/Canvas-Chart-UX-pass-192ba33c8f5780ff92cac5ad387a24d9

Canvas: component nits

---

web-admin/src/routes/[organization]/[project]/explore/[dashboard]/+page.svelte

[Addresses this Slack report](https://rilldata.slack.com/archives/C02T907FEUB/p1738937017202969)
**Checklist:**

fix (Explore): Check both `MetricsView` and `Explore` resources for a `validSpec` and `reconcileError`

---

runtime/drivers/duckdb/information_schema.go

closes https://github.com/rilldata/rill/issues/6460
1. The schema is never used to construct fully qualified table name in case of duckdb : https://github.com/rilldata/rill/blob/baa6274cf3a53ab8c468aeb658819c74ebbba5ab/runtime/drivers/olap.go#L275-L276
2. I also evaluated not setting db/schema at all but that shows up weirdly on UI. We can fix it on frontend if that is expected.

pin duckdb schema to `main`

---

admin/server/assets.go
cli/cmd/org/upload_logo.go

Also unofficially adds support for `.ico`

Support GIF and SVG logo uploads

---

runtime/pkg/rduckdb/db.go

fix : db becomes unusable due to db file not exist error

---

web-admin/src/features/dashboards/listing/utils.ts
web-admin/src/features/projects/environment-variables/ActivityCell.svelte
web-admin/src/features/projects/environment-variables/TimeAgo.svelte

Human readable date time, closes #6416. Added a `TimeAgo` component to exhibit similar datetime behavior used in https://github.com/nmn/react-timeago
https://github.com/user-attachments/assets/94d6839f-cc0d-43c3-9f1c-eb51ac3f7e0e

Human readable relative time

---

web-common/src/components/vega/vega-config.ts
web-common/src/features/canvas/CanvasComponent.svelte
web-common/src/features/canvas/CanvasDashboardEmbed.svelte
web-common/src/features/canvas/CanvasDashboardPreview.svelte
web-common/src/features/canvas/ComponentHeader.svelte
web-common/src/features/canvas/PreviewElement.svelte
web-common/src/features/canvas/components/charts/Chart.svelte
web-common/src/features/canvas/components/charts/bar-chart/spec.ts
web-common/src/features/canvas/components/charts/builder.ts
web-common/src/features/canvas/components/charts/stacked-bar/spec.ts
web-common/src/features/canvas/components/charts/types.ts
web-common/src/features/canvas/components/charts/util.ts
web-common/src/features/canvas/inspector/PositionalFieldConfig.svelte

- Non zero origin for measure by default
- Add a option in dropdown to use 0 based origin
- More descriptive chart title
- Remove interactivity from lenged
- Show auto chart title if description is added

Canvas: Chart improvements

---

web-common/src/components/vega/vega-config.ts
web-common/src/features/canvas/CanvasComponent.svelte
web-common/src/features/canvas/CanvasDashboardEmbed.svelte
web-common/src/features/canvas/CanvasDashboardPreview.svelte
web-common/src/features/canvas/ComponentHeader.svelte
web-common/src/features/canvas/PreviewElement.svelte
web-common/src/features/canvas/components/charts/Chart.svelte
web-common/src/features/canvas/components/charts/bar-chart/spec.ts
web-common/src/features/canvas/components/charts/builder.ts
web-common/src/features/canvas/components/charts/stacked-bar/spec.ts
web-common/src/features/canvas/components/charts/types.ts
web-common/src/features/canvas/components/charts/util.ts
web-common/src/features/canvas/inspector/PositionalFieldConfig.svelte
web-common/src/features/canvas/inspector/VegaConfigInput.svelte

Replace `textArea` with codemirror editor

Add codemirror editor for VL config

---

web-admin/src/features/organizations/users/OrgUsersTableActionsCell.svelte
web-admin/src/features/projects/user-management/OrganizationItem.svelte

Fixes #6652
https://github.com/user-attachments/assets/84fa5401-13ad-45c3-9e20-4c97b8f752d6
**Checklist:**

Invalidate users count in share popover

---

docs/docs/reference/project-files/explore-dashboards.md

Add banner to explore dashboard reference docs
https://github.com/rilldata/rill/pull/6610
**Checklist:**

Add banner to ref docs

---

admin/worker/deployments_health_check.go

Example of logs that were hard to debug due to missing project/deployment/instance IDs: https://rill.datadoghq.com/logs?query=service%3Arill-cloud%20%22deployment%20health%20check%3A%20metrics%20view%20error%22%20container_name%3Acloud-admin-worker&agg_m=count&agg_m_source=base&agg_q=env&agg_q_source=base&agg_t=count&cols=host%2Cservice&event=AwAAAZT6BpXSGCo0IgAAABhBWlQ2QnFRSEFBQlpJUTNZeGNJTjlnQXEAAAAkMDE5NGZhMDYtZDNjNS00OTkxLTllNTUtYWYwMzUxY2Y5NjlhAAABhg&fromUser=true&link_source=monitor_notif&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=desc&top_n=10&top_o=top&viz=stream&x_missing=true&from_ts=1739361257000&to_ts=1739361557000&live=false

More annotations in health check logs

---

web-common/src/features/canvas/AddComponentDropdown.svelte

enable KPI Grid from dropdown menu

Canvas: enable KPI Grid from dropdown menu

---

web-admin/src/features/organizations/OrganizationTabs.svelte
web-admin/tests/homepage.spec.ts

Mike requested this change
**Checklist:**

Change projects tab name from "Overview" to "Projects"

---

web-admin/tests/setup/setup.ts

Updated the login flow in e2e to support the new HRD auth flow.
**Checklist:**

e2e: tweak email and password login flow

---

admin/jobs/river/org_jobs.go

- Was not sure of it but looks like we create new org in e2e test so I think better to delete customers in Orb and Stripe test mode ?
- Deletion will fail in live mode but will work in test mode or if customer was never subscribed in live mode
- Not sure if there is a clean way to detect env (prod or test/dev/stage) to not rely on err for deletion in test mode

delete customer in test mode

---

docs/docs/home/get-started.md
docs/docs/home/home.md

Removing references to 311-ops from docs as the demo has been deleted.

docs: remove 311

---

.github/workflows/codeql.yaml

Filter CodeQL

---

cli/cmd/devtool/dotenv.go

fix: adds e2e to devtool env

---

runtime/drivers/azure/object_store.go
runtime/drivers/bigquery/arrow.go
runtime/drivers/bigquery/warehouse.go
runtime/drivers/blob/blobdownloader.go
runtime/drivers/clickhouse/olap.go
runtime/drivers/druid/native_query.go
runtime/drivers/druid/olap.go
runtime/drivers/duckdb/duckdb.go
runtime/drivers/duckdb/olap.go
runtime/drivers/pinot/olap.go
runtime/drivers/salesforce/bulk.go
runtime/drivers/snowflake/warehouse.go
runtime/pkg/rduckdb/catalog.go
runtime/pkg/rduckdb/db.go
runtime/pkg/rduckdb/db_test.go
runtime/pkg/rduckdb/remote.go
runtime/reconcilers/alert.go
runtime/reconcilers/model.go
runtime/reconcilers/project_parser.go
runtime/reconcilers/refresh_trigger.go
runtime/reconcilers/report.go
runtime/reconcilers/source.go
runtime/server/generate_metrics_view.go
runtime/server/instances.go

subtask for https://github.com/rilldata/rill-private-issues/issues/1257
**Checklist:**

add observability trace ids in several logs

---

runtime/pkg/email/email.go

https://www.notion.so/rilldata/Self-Serve-Prospects-Customers-commercial-workflow-17dba33c8f5780bcb866cf0f7d0090d0?pvs=4#19aba33c8f578071ab30d6566f331a42
**Checklist:**

Updated self-serve emails to match new commercial requests

---

runtime/controller.go
runtime/reconcilers/util.go

https://github.com/rilldata/rill-private-issues/issues/1257
**Checklist:**

Mark `dependency_error: true` for reconcile errors due to a dependency failure

---

web-common/src/features/dashboards/time-series/DimensionValueMouseover.svelte

Fixes https://github.com/rilldata/rill-private-issues/issues/1234
**Checklist:**

fix: use null coalescing for dimension values in chart

---

netlify.toml

HSTS for UI

---

web-common/src/components/dropdown-menu/DropdownMenuCheckboxItem.svelte
web-common/src/features/visual-editing/SelectionDropdown.svelte
web-common/src/features/workspaces/VisualExploreEditing.svelte

This was intended to be fixed here: https://github.com/rilldata/rill/pull/6511. Something either reverted or it was never fixed to begin with. It doesn't happen on every surface, but this change does seem to fix it.
The changes in `SelectionDropdown` and `VisualExploreEditing` are just cleanup.
**Checklist:**

fix: bits ui checkbox display bug

---

web-common/src/components/search/Search.svelte

Clear search text on mount.
**Checklist:**

fix: persistent search text

---

runtime/queries/metricsview.go

Improve error message when passing a subquery filter to MetricsViewRows

---

.github/workflows/web-test-e2e.yml
web-local/package.json
web-local/playwright.config.ts

Closes https://github.com/rilldata/rill/issues/6792
**Checklist:**

e2e (Rill Developer): Add conveniences to test Safari and Firefox

---

web-common/src/features/dashboards/workspace/DeployProjectCTA.svelte
web-common/src/features/project/ProjectRedeployConfirmDialog.svelte

fix: Add confirmation for redeploy

---

web-common/src/features/dashboards/pivot/RegularTable.svelte

https://github.com/rilldata/rill-private-issues/issues/1171
**Checklist:**

fix: inconsistent TDD tooltip and formatted value

---

.github/workflows/web-test-e2e.yml

fix (e2e): Install necessary Playwright dependencies for Safari tests

---

runtime/drivers/olap.go

not documented but pinot seems to support optimized inline select syntax

optimized inline pinot

---

go.mod
go.sum

for the fix - https://github.com/startreedata/pinot-client-go/pull/39

upgrade pinot client

---

web-common/src/features/dashboards/filters/dimension-filters/DimensionFilter.svelte

Searching for null in the dimension filter would crash the application.
**Checklist:**

fix: handle nulls properly in dimension filters

---

runtime/resolvers/testdata/s3_connector.yaml

fix s3 integration test
**Checklist:**

fix s3 integration test

---

runtime/drivers/clickhouse/information_schema.go
runtime/drivers/clickhouse/information_schema_test.go

allow system/information_schema in all if it is the current database

---

docs/docs/home/FAQ.md
docs/docs/home/install.md

Clarifies that we do not support Safari & Firefox at the moment.

docs: Clarify browser support

---

cli/cmd/devtool/data/cloud-deps.docker-compose.yml

```
RILL_ADMIN_EMAIL_SMTP_HOST=localhost
RILL_ADMIN_EMAIL_SMTP_PORT=1025
RILL_ADMIN_EMAIL_SMTP_USERNAME=user
RILL_ADMIN_EMAIL_SMTP_PASSWORD=passwd
RILL_RUNTIME_EMAIL_SMTP_HOST=localhost
RILL_RUNTIME_EMAIL_SMTP_PORT=1025
RILL_RUNTIME_EMAIL_SMTP_USERNAME=user
RILL_RUNTIME_EMAIL_SMTP_PASSWORD=passwd
```
**Checklist:**

Mailpit for test emails

---

web-common/src/features/project/ProjectRedeployConfirmDialog.svelte

Closes https://github.com/rilldata/rill-private-issues/issues/1406
**Checklist:**

fix: redeploy confirm dialog not closing after confirming

---

.golangci.yml
admin/provisioner/clickhousestatic/provisioner_test.go
runtime/drivers/clickhouse/olap.go
runtime/drivers/clickhouse/olap_test.go
runtime/drivers/druid/druid_container_test.go
runtime/drivers/duckdb/model_executor_https_self_test.go
runtime/drivers/duckdb/olap_crud_test.go
runtime/drivers/duckdb/transporter_mysql_to_duckDB_test.go
runtime/drivers/duckdb/transporter_postgres_to_duckDB_test.go
runtime/drivers/duckdb/transporter_test.go
runtime/drivers/olap.go
runtime/drivers/sqlite/registry.go
runtime/metricsview/executor.go
runtime/metricsview/executor_rewrite_druid_exactify.go
runtime/pkg/duckdbsql/duckdbsql.go
runtime/pkg/duckdbsql/expression.go
runtime/pkg/fieldselectorpb/duckdb.go
runtime/queries/column_numeric_histogram.go
runtime/queries/column_timeseries.go
runtime/queries/metricsview_timeseries.go
runtime/queries/resource_watermark.go
runtime/queries/table_columns.go
runtime/server/queries_columns_test.go
runtime/server/queries_tables_test.go
runtime/testruntime/olap.go

closes https://github.com/rilldata/rill/issues/6770
**Checklist:**

fix: query cancellation leads to null results being cached

---

runtime/drivers/duckdb/model_executor_self.go
runtime/resolvers/testdata/gcs_connector.yaml
runtime/resolvers/testdata/s3_connector.yaml

fix: source with duckdb sql that ingests from GCS does not work

---

web-common/src/components/dropdown-menu/DropdownMenuContent.svelte

tweak: larger radius on menu corners

---

runtime/drivers/clickhouse/clickhouse.go
runtime/drivers/clickhouse/olap_test.go
runtime/drivers/druid/druid.go
runtime/drivers/pinot/pinot.go

In my observation, see 10-20% improvement for CH based page loads

reduce connection concurrency

---

web-admin/src/features/projects/status/ProjectResourcesTable.svelte

fix: filter out canvas components from resources table

---

runtime/drivers/azure/azure.go
runtime/drivers/duckdb/model_executor_objectstore_self.go
web-common/src/features/sources/modal/submitAddDataForm.ts
web-common/src/features/sources/modal/yupSchemas.ts

fix: azure account name is different for backend and frontend

---

web-common/src/features/visual-metrics-editing/Sidebar.svelte

fix: use multiline input for advanced dimension expressions

---

web-admin/src/features/alerts/CreateAlert.svelte
web-admin/src/features/navigation/TopNavigationBar.svelte
web-admin/src/features/projects/ProjectTabs.svelte
web-common/src/features/dashboards/dimension-search/GlobalDimensionSearch.svelte
web-common/src/features/exports/ExportMenu.svelte
web-common/src/features/feature-flags.ts

feat: reports and alerts feature flag

---

web-common/src/features/alerts/BaseAlertForm.svelte

Closes https://github.com/rilldata/rill-private-issues/issues/1437
**Checklist:**

fix (Alerts): Button to submit alert edits should read "Update" not "Create"

---

runtime/compilers/rillv1/parse_metrics_view.go
runtime/compilers/rillv1/parser_test.go
runtime/security.go

Resolves: https://github.com/rilldata/rill-private-issues/issues/1253 - Support ref in security policies for mappings

Infer refs from security rules

---

docs/docs/integrate/custom-api.md
docs/docs/integrate/embed-api.md

docs: embed iframe api

---

web-local/src/routes/(viz)/canvas/[name]/+page.svelte

https://rilldata.slack.com/archives/C06M8V1Q5KK/p1743086533053419
Fix navigation for canvas dashboards when using local / Rill developer.
**Checklist:**

fix: navigation for canvas dashboards in rill dev

---

runtime/health.go
runtime/server/health.go

closes https://github.com/rilldata/rill-private-issues/issues/1228
**Checklist:**

throw internal server error if OLAP fails on dynamic runtimes

---

web-common/src/features/canvas/AddComponentDropdown.svelte
web-common/src/features/canvas/CanvasDashboardWrapper.svelte
web-common/src/features/canvas/ElementDivider.svelte
web-common/src/features/canvas/RowDropZone.svelte
web-common/src/features/canvas/RowWrapper.svelte
web-local/tests/canvas/setup.spec.ts

Sets up E2E test scaffolding for Canvas surface.
**Checklist:**

test: setup canvas test scaffolding

---

web-common/src/features/alerts/EditAlertForm.svelte

fix: alert edit crashiing the app

---

web-common/src/features/dashboards/state-managers/actions/measures.ts

Fix https://github.com/rilldata/rill-private-issues/issues/1502 and intend to cherry-pick into `release-0.58` and `release-0.59`
Demo:
https://github.com/user-attachments/assets/f966c670-a27b-46c4-8069-6145aef381a9
**Checklist:**

Update leaderboard measure when hiding measures

---

web-common/src/features/sources/modal/AddDataForm.svelte
web-common/src/features/sources/modal/AddDataModal.svelte

Bugfix after https://github.com/rilldata/rill/pull/6904 and a bad merge.
**Checklist:**

fix (Add Data): OLAP forms were hidden when your default OLAP engine was not DuckDB

---

runtime/drivers/druid/druid_test.go
runtime/drivers/druid/druidsqldriver/druid_api_sql_driver.go

Closes [#6901](https://github.com/rilldata/rill/issues/6901)
**Checklist:**

adding pinger for druid driver

---

runtime/drivers/druid/druidsqldriver/druid_api_sql_driver.go

Fixes https://github.com/rilldata/rill-private-issues/issues/1100
**Checklist:**

return ctx err for druid driver

---

go.mod
go.sum

Fixes https://github.com/rilldata/rill-private-issues/issues/1361
**Checklist:**

update pinot go client

---

docs/docs/reference/olap-engines/druid.md
runtime/drivers/druid/druid.go

Fixes https://github.com/rilldata/rill-private-issues/issues/1166
**Checklist:**

druid version check

---

web-common/src/features/dashboards/pivot/NestedTable.svelte
web-common/src/features/dashboards/pivot/PivotExpandableCell.svelte
web-common/src/features/dashboards/pivot/PivotTable.svelte
web-local/tests/explores/pivot.spec.ts

fix: remove event listeners from expandable cells

---

web-admin/src/features/projects/github/ProjectGithubConnection.svelte

[Feature request in Slack](https://rilldata.slack.com/archives/C02T907FEUB/p1744302687729949)
**Checklist:**

feat (Project status): Show git branch

---

admin/billing/payment/stripe.go

Apparently HK does not have them 
**Checklist:**

remove postal code check since some countries does not have them

---

runtime/drivers/clickhouse/clickhouse.go
runtime/drivers/clickhouse/embed.go
runtime/drivers/druid/druid.go

closes https://github.com/rilldata/rill-private-issues/issues/1482
**Checklist:**

fix embed clickhouse server hanging after sometime

---

web-common/src/features/canvas/components/kpi/KPI.svelte

fix(canvas): kpi title overflow

---

web-admin/tests/setup/setup.ts

This pull request updates the existing e2e when logging in using an admin account. The steps to modify page template for Rill Admin (Staging) are as follows https://www.notion.so/rilldata/Home-Realm-Discovery-HRD-19aba33c8f57809599b0f9f9b22887e8#19aba33c8f578027b9e3e4aca311ccbf
https://www.notion.so/Last-Mile-For-0-60-1d0ba33c8f5780499ebde5c7195040d7?d=1d5ba33c8f57809e94bb001cfb50b2ba&pvs=4#1d0ba33c8f57804899bbc4277b542d6a
**Checklist:**

e2e: Universal Login Flow

---

.github/workflows/go-migrate.yml

fix: Remove NodeJS installation from `go-migrate` GitHub Action

---

cli/cmd/root.go
cli/cmd/sudo/user/assume.go
cli/cmd/sudo/user/unassume.go
cli/pkg/dotrill/dotrill.go
cli/pkg/dotrill/dotrill_test.go

Closes [#1155](https://github.com/rilldata/rill-private-issues/issues/1155)
**Checklist:**

Automactically Unassume user on expiry and reassuming new user

---

runtime/drivers/admin/admin.go
runtime/pkg/archive/archive.go

Closes https://github.com/rilldata/rill-private-issues/issues/1445
**Checklist:**

Fix empty repo error for missing archive

---

docs/docs/manage/project-management/variables-and-credentials.md
web-admin/src/routes/[organization]/[project]/-/settings/environment-variables/+page.svelte

closes https://github.com/rilldata/rill/issues/7150
https://docs.rilldata.com/manage/project-management/variables-and-credentials
**Checklist:**

docs: bump variables link in docs

---

docs/docs/reference/olap-engines/pinot.md

fix pinot docs

---

web-common/src/features/dashboards/stores/dashboard-stores.ts

fix: check for empty dims

---

docs/blog/0.60.md

v60 release notes

---

runtime/resolvers/glob.go

fix: for glob resolver only change the connector

---

runtime/pkg/email/email.go
runtime/pkg/email/email_test.go
runtime/pkg/email/templates/alert_fail.mjml
runtime/pkg/email/templates/alert_status.mjml
runtime/pkg/email/templates/call_to_action.mjml
runtime/pkg/email/templates/gen/alert_fail.html
runtime/pkg/email/templates/gen/alert_status.html
runtime/pkg/email/templates/gen/call_to_action.html
runtime/pkg/email/templates/gen/informational.html
runtime/pkg/email/templates/gen/project_access_request.html
runtime/pkg/email/templates/gen/scheduled_report.html
runtime/pkg/email/templates/gen/welcome_to_team.html
runtime/pkg/email/templates/gen/welcome_to_trial.html
runtime/pkg/email/templates/informational.mjml
runtime/pkg/email/templates/project_access_request.mjml
runtime/pkg/email/templates/scheduled_report.mjml
runtime/pkg/email/templates/welcome_to_team.mjml
runtime/pkg/email/templates/welcome_to_trial.mjml

So we don't have this problem next year as well.
**Checklist:**

Dynamic copyright year in transactional emails

---

.github/workflows/cli-release.yml
.github/workflows/rill-cloud.yml
.github/workflows/rill-ui.yml

Trigger only on tags starting v

---

admin/database/postgres/migrations/0067.sql

Allow editors to create and manage magic auth tokens

---

runtime/metricsview/executor_rewrite_limit_pushdown.go

Fixes https://github.com/rilldata/rill-private-issues/issues/1630
**Checklist:**

only apply limit to inner most query

---

runtime/drivers/bigquery/bigquery.go
runtime/drivers/bigquery/model_executor_self_gcs.go
runtime/drivers/bigquery/warehouse.go

Support configuring the BigQuery `project_id` at the connector level

---

runtime/parser/parse_explore_test.go
runtime/parser/parse_partial_field_selector.go

Support selecting a single field with a scalar in the field selector YAML

---

runtime/pkg/rduckdb/db.go

Setting the status to error instead of setting a dedicated field makes it easy to visualize error traces.
**Checklist:**

set span's status code to error in case of errors

---

docs/docs/reference/connectors/snowflake.md

docs: snowflake update on keys

---

runtime/drivers/bigquery/bigquery.go
runtime/drivers/bigquery/warehouse.go
runtime/parser/parse_source.go

Ran into these when making some changes in the metrics project. 
**Checklist:**

Misc. fixes when using `bigquery` source on non-default OLAP

---

web-admin/src/features/navigation/TopNavigationBar.svelte

Addresses the confusion in [this thread](https://rilldata.slack.com/archives/C05PS7DF508/p1746575211945539)
**Checklist:**

fix (Breadcrumbs): Show org breadcrumb when non-member visits org with public project

---

cli/cmd/billing/subscription/edit.go
cli/cmd/billing/subscription/renew.go
cli/cmd/billing/subscription/subscription.go

remove hardcoded plan names

---

web-common/src/components/vega/util.ts
web-common/src/features/canvas/components/charts/builder.ts
web-common/src/features/canvas/components/charts/cartesian-charts/CartesianChart.ts
web-common/src/features/canvas/components/charts/circular-charts/CircularChart.ts
web-common/src/features/canvas/components/charts/heatmap-charts/HeatmapChart.ts
web-common/src/features/canvas/components/charts/heatmap-charts/spec.ts
web-common/src/features/canvas/components/charts/query-utils.ts
web-common/src/features/canvas/components/charts/types.ts
web-common/src/features/canvas/components/charts/util.ts

https://rilldata.slack.com/archives/C06M8V1Q5KK/p1746629957767839
Fixes heatmap queries
- Do not query topN for temporal dimensions
- Sort by measure for nominal dimensions
- Order values in chart by measure when possible.
**Checklist:**

fix: heatmap aggregation queries

---

admin/github.go
admin/jobs/river/delete_unused_github_repo.go
admin/server/github.go
admin/server/projects.go
admin/testadmin/testadmin.go
cli/cmd/project/connect_github.go
cli/pkg/local/server.go
go.mod
go.sum

feat : Cache github installation tokens and reuse AppsTransport for reusing TCP connections

---

runtime/drivers/clickhouse/crud.go
runtime/drivers/clickhouse/model_executor_self.go
runtime/drivers/clickhouse/olap_test.go

fix: partition overwrite fix for distributed tables

---

docs/docusaurus.config.js
docs/plugins/llms-txt-plugin.ts

Adds a naive plugin to generate llm.txt and a llm-full.txt on building the docs.

docs: adds llm plugin

---

go.mod
go.sum
runtime/parser/parse_model_test.go

Fix failing change mode tests in parser and `go mod tidy`
**Checklist:**

fix: Fix failing change mode tests in parser

---

docs/docs/manage/granting/aws-s3-bucket.md
docs/docs/manage/granting/azure-storage-container.md
docs/docs/manage/granting/gcs-bucket.md
docs/docs/manage/granting/google-bigquery.md

https://rilldata.slack.com/archives/C01190F1R1D/p1746709739274459?thread_ts=1746708931.909149&cid=C01190F1R1D
**Checklist:**

added warning per slack thread below

---

web-common/src/features/sources/sourceUtils.ts

https://linear.app/rilldata/issue/ENG-534/generated-models-should-use-multi-line-yaml-for-easier-editing
**Checklist:**

fix: multi line sql prop in sources

---

docs/blog/0.62.md

docs: 0.62 release notes

---

web-admin/src/features/alerts/listing/AlertsTableCompositeCell.svelte

Addresses [this Slack convo](https://rilldata.slack.com/archives/C01190F1R1D/p1747732276923619?thread_ts=1747661954.199389&cid=C01190F1R1D).
**Checklist:**

chore (Alerts): Change microcopy from "Last triggered" to "Last checked" 

---

docs/docs/reference/project-files/apis.md

docs: add api props

---

web-common/src/features/canvas/inspector/chart/VegaConfigInput.svelte

Update placeholder text for config input editor
**Checklist:**

tweak: update placeholder text for vega config input

---

web-admin/src/features/organizations/users/CreateUserGroupDialog.svelte
web-admin/src/features/organizations/users/EditUserGroupDialog.svelte

This pull request updates the user group message in the name validation.
**Checklist:**

[ENG-760] Update user group name guideline message

---

docs/blog/0.63.md

docs: add release notes 0.63

---

runtime/pkg/graceful/http.go

Change HTTP graceful shutdown for MCP

---

web-admin/src/routes/+layout.ts

[Addresses this Slack report](https://rilldata.slack.com/archives/C02T907FEUB/p1749030024046039)
**Checklist:**

Fix error handling for `GetOrganization` request

---

runtime/health.go
runtime/server/health.go
runtime/server/server.go

Fixes https://linear.app/rilldata/issue/PLAT-53/investigate-and-fix-health-check-failure-on-moloco
**Checklist:**

return error message in http health check

---

.github/workflows/go-cover.yml

Moving go-cover to large-hosted

---

go.mod
go.sum
package-lock.json
web-local/package.json

chore: update critical dependabot alerts
**Checklist:**

chore: Update dependencies

---

cli/cmd/org/org.go
cli/cmd/org/show.go
web-admin/src/app.html
web-admin/src/routes/+layout.svelte
web-admin/src/routes/[organization]/-/settings/+page.svelte

revert: thumbnail

---

web-common/src/app.css
web-common/src/components/editor/theme.ts

fix: editor highlight visibility

---

runtime/drivers/catalog.go
runtime/drivers/sqlite/catalog.go
runtime/server/controller.go

PLAT-46: List project partitions in reverse order of executed_on

---

runtime/drivers/snowflake/snowflake.go

Implementation of Ping PR and individual credential properties PR was separate pr. This issue is created after merging both PR.
Also remove the backward compatible(which i added in ping pr) because it is not required. 
**Checklist:**

Fix Snowflake Ping for individual cred properties

---

.github/workflows/cli-release.yml

Fix typo in the docker creds

---

.github/workflows/rill-cloud.yml

latest release branch deployment to staging
**Checklist:**

latest release branch deployment to staging

---

.github/workflows/cli-release.yml
.goreleaser-darwin_amd64.yaml
.goreleaser-darwin_arm64.yaml
.goreleaser-linux_amd64.yaml
.goreleaser-linux_arm64.yaml

Fix docker publish issue

---

cli/cmd/project/connect_github.go
cli/cmd/project/deploy.go
cli/pkg/cmdutil/githelper.go
cli/pkg/gitutil/gitutil.go
cli/pkg/local/git.go
cli/pkg/local/server.go

feat : Auto commit dotrillcloud folder on project creation

---

docs/blog/0.64.md
docs/docs/contact.md
docs/docs/home/FAQ.md
docs/docs/home/home.md
docs/docs/home/install.md
docs/docs/tutorials/other/Rill Cloud/share-dashboard-publicly.md

Fix typos and broken links using claude code.

Fix typos and broken doc links

---

runtime/drivers/redshift/information_schema.go
runtime/drivers/redshift/redshift.go
runtime/drivers/redshift/warehouse.go

Closes [#PLAT-105](https://linear.app/rilldata/issue/PLAT-105/implement-listdatabaseschemas-listtables-and-gettable-apis-for)
**Checklist:**

PLAT-105 Implement ListDatabaseSchemas, ListTables and GetTable Apis for Redshift

---

runtime/drivers/mysql/information_schema.go
runtime/drivers/mysql/mysql.go

Closes [#PLAT-103](https://linear.app/rilldata/issue/PLAT-103/implement-listdatabaseschemas-listtables-and-gettable-apis-for-mysql)
Implemented all 3 Apis ListDatabaseSchemas ListTables and GetTable Apis
Tested: 
1. All 3 api working 
2. Gettable api for tablename with ' in it.
3. User can only see the schema they have access to. 
**Checklist:**

PLAT-103 Implement ListDatabaseSchemas, ListTables and GetTable Apis for Mysql

---

runtime/drivers/clickhouse/embed.go

Subtask for https://linear.app/rilldata/issue/PLAT-26/qa-of-the-embedded-clickhouse
**Checklist:**

Fix Clickhouse subprocess issues after a force kill

---

cli/cmd/service/create.go

specify roles for service in cli

---

docs/blog/0.66.md

docs: release notes 0.66

---

package-lock.json

Bump package lock

---

package-lock.json

Fixing package-lock.json

---

runtime/drivers/bigquery/bigquery.go
runtime/drivers/bigquery/information_schema.go
runtime/drivers/bigquery/model_executor_self_gcs.go
runtime/drivers/bigquery/warehouse.go

Closes [#PLAT-90](https://linear.app/rilldata/issue/PLAT-90/implement-listdatabaseschemas-listtables-and-gettable-apis-for)
**Checklist:**

PLAT-90: implement listdatabaseschemas listtables and gettable apis for biquery

---

cli/pkg/installscript/installscript.go

fix install script failing for downloading latest

---

runtime/drivers/clickhouse/clickhouse.go
web-common/src/components/forms/SubmissionError.svelte
web-common/src/features/sources/modal/AddClickHouseForm.svelte
web-common/src/features/sources/modal/AddDataForm.svelte
web-common/src/features/sources/modal/AddDataModal.svelte
web-common/src/features/sources/modal/LocalSourceUpload.svelte
web-common/src/features/sources/modal/NeedHelpText.svelte

This pull request enhances the data connector form UI by introducing left and right side panels.
Closes https://linear.app/rilldata/issue/APP-22/improve-the-add-clickhouse-modal-to-account-for-dynamic-field-inputs
https://github.com/user-attachments/assets/51d3cc22-c740-411c-913e-ec9e125acc47
**Checklist:**

Connector form UI

---

docs/docs/reference/olap-engines/clickhouse.md

Remove reference to non-existing images
**Checklist:**

Remove reference to non-existing images

---

runtime/metricsview/executor.go
runtime/metricsview/executor_timestamps.go

Fixes https://linear.app/rilldata/issue/ENG-838/syft-data-ch-based-dashboard-when-no-data-returns-weird-dashboard
**Checklist:**

null value for ch watermark

---

runtime/drivers/athena/athena.go
runtime/drivers/athena/information_schema.go
runtime/drivers/athena/warehouse.go

Closes [#PLAT-104](https://linear.app/rilldata/issue/PLAT-104/implement-listdatabaseschemas-listtables-and-gettable-apis-for-athena)
**Checklist:**

PLAT-104 Implement ListDatabaseSchemas, ListTables and GetTable Apis for Athena

---

runtime/drivers/salesforce/salesforce.go

Closes https://linear.app/rilldata/issue/APP-198/update-salesforce-connector-modal-field-tooltips
**Checklist:**

Bump hints in Salesforce

---

runtime/parser/init.go

fix : Unpack empty should also add a connector file and olap_connector setting

---

runtime/drivers/clickhouse/information_schema.go
runtime/drivers/clickhouse/olap.go
runtime/drivers/druid/olap.go
runtime/drivers/duckdb/olap.go
runtime/drivers/olap.go
runtime/drivers/pinot/olap.go
runtime/metricsview/executor.go
runtime/metricsview/executor_validate.go

Fixes https://linear.app/rilldata/issue/PLAT-129/time-dimension-validation-failing-for-ch-projects-in-067
CH does not return schema if limit is 0,  this fixes it by using describe query
**Checklist:**

use describe query to get schema for clickhouse

---

runtime/drivers/postgres/information_schema.go
runtime/drivers/postgres/postgres.go
runtime/parser/schema/project.schema.yaml

closes [PLAT-117: support individual credential for postgres connector](https://linear.app/rilldata/issue/PLAT-117/support-individual-credential-for-postgres-connector)
**Checklist:**

support individual credential for postgres-connector

---

cli/pkg/gitutil/gitutil.go
cli/pkg/local/git.go

fix : git APIs throw bad request if git repo does not exist

---

admin/provisioner/clickhousestatic/provisioner.go

Support `cluster` property in the Clickhouse provisioner

---

runtime/drivers/mysql/mysql.go
runtime/drivers/mysql/mysql_test.go

Fixing issue mentioned in https://linear.app/rilldata/issue/ENG-853/issue-when-adding-mysql-dsn-in-a-new-file#comment-a9eb2162
**Checklist:**

fix mysql dsn error

---

runtime/drivers/clickhouse/model_manager.go
runtime/drivers/clickhouse/olap.go

fix partitions_overwrite strategy broken by default

---

runtime/reconcilers/model.go
runtime/reconcilers/model_test.go

Fix manual model triggers not working with `change_mode: patch`

---

runtime/queries/resource_watermark.go

use actual column for time dim in watermark query

---

web-admin/tests/canvas.spec.ts
web-common/tests/projects/openrtb/dashboards/bids_canvas.yaml

https://linear.app/rilldata/issue/APP-154/add-e2e-test-for-interacting-with-a-canvas-dashboard-in-cloud
**Checklist:**

chore: canvas e2e cloud sanity test

---

cli/cmd/project/status.go

[PLAT-132: Support `--local` flag in `rill project status`](https://linear.app/rilldata/issue/PLAT-132/support-local-flag-in-rill-project-status)
**Checklist:**

PLAT-132 support local flag in rill project status

---

cli/cmd/deploy/deploy.go
cli/cmd/project/connect_github.go

change default remote from first remote to origin

---

admin/server/auth/middleware.go
admin/server/server.go

[PLAT-120: Pentest: Implement definitive session timeout](https://linear.app/rilldata/issue/PLAT-120/pentest-implement-definitive-session-timeout)
**Checklist:**

Refresh cookie on accessing v1/users/current

---

web-common/src/components/notifications/Notification.svelte
web-common/src/components/notifications/NotificationCenter.svelte

fix: notification color

---

docs/blog/0.69.md

docs: release notes

---

cli/cmd/project/connect_github.go
cli/cmd/project/deploy.go
cli/pkg/cmdutil/githelper.go
cli/pkg/local/server.go

https://linear.app/rilldata/issue/PLAT-154/investigate-deploy-journey-edge-cases
**Checklist:**

ensure gitignore contains necessary entries before deploy

---

go.mod
go.sum
runtime/server/mcp_server.go
runtime/server/mcp_test.go

Remove unused MCP server tools and related test cases until it is fully supported
**Checklist:**

Remove unused MCP server tools and related test cases

---

web-admin/src/features/dashboards/share/ShareDashboardPopover.svelte
web-admin/src/features/navigation/TopNavigationBar.svelte

Closes https://linear.app/rilldata/issue/APP-115/share-button-on-canvas-dashboards
**Checklist:**

feat: add share popover for canvas

---

cli/pkg/gitutil/gitcmdwrapper.go
cli/pkg/gitutil/gitutil.go
cli/pkg/local/server.go

fix: project update for self managed git repos is not implemented

---

runtime/drivers/olap.go

escape identifier in unnest clickhouse

---

docs/blog/0.70.md
web-common/src/features/canvas/explore-link/ExploreLink.svelte

docs: release notes 0.70

---

admin/provisioner/clickhousestatic/provisioner.go
admin/provisioner/clickhousestatic/provisioner_test.go

Edge cases found while testing managed database name generations.
**Checklist:**

Managed database name generation

---

admin/server/cookies/cookies.go

Change logs as discussed in https://rilldata.slack.com/archives/CTZ8XBQ85/p1756207780422029
**Checklist:**

change log to info if cookie expired

---

docs/docs/deploy/deploy-dashboard/deploy-dashboard.md
docs/src/theme/DocSidebar/index.js

request https://www.notion.so/rilldata/Docs-improvements-wishlist-24eba33c8f578012a400e8f6649811e1
**Checklist:**

[DOCS] Hide side bar in Contact Page

---

README.md
docs/README.md

request https://www.notion.so/rilldata/Docs-improvements-wishlist-24eba33c8f578012a400e8f6649811e1
**Checklist:**

[DOCS] New GH readme page

---

web-common/src/features/connectors/code-utils.spec.ts
web-common/src/features/connectors/code-utils.ts
web-common/src/features/sources/sourceUtils.ts
web-common/tests/projects/AdBids/sources/AdBids.yaml
web-common/tests/projects/AdImpressions/sources/AdImpressions.yaml

Fixes APP-322
Updates generated model yaml according to linear.
**Checklist:**

fix: format models yaml

---

runtime/pkg/rduckdb/db.go
runtime/pkg/rduckdb/db_test.go

fix: views gets deleted in rduckdb on db reopen

---

web-common/src/features/canvas/components/charts/builder.ts
web-common/src/features/canvas/components/charts/circular-charts/CircularChart.ts
web-common/src/features/canvas/components/charts/circular-charts/pie.ts
web-common/src/features/canvas/components/charts/types.ts
web-common/src/features/canvas/components/charts/util.ts
web-common/src/features/canvas/inspector/chart/PositionalFieldConfig.svelte
web-common/src/features/canvas/inspector/chart/field-config/SortConfig.svelte

Fixes https://linear.app/rilldata/issue/APP-289/add-total-measure-number-to-center-of-donut-chart-component
- Add color picker for individual dimension values
- Add sort selector for color dimension, position labels according to sort order
- Add total value for the measure inside the donut chart
**Checklist:**

feat: donut chart improvements

---

runtime/drivers/olap.go

Works similar to Druid 
**Checklist:**

[PLAT-157] time spine support for pinot

---

docs/docs/reference/project-files/connectors.md
runtime/parser/schema/project.schema.yaml

Update documentation for snowflake connector

---

.github/workflows/cli-release.yml
.goreleaser.yaml

use Goreleaser v2.11 

---

docs/docs/contact/contact.md

[DOCS] new discord link

---

web-common/src/lib/time/ranges/formatter.ts

Fixes an issue with formatting invalid or malformed intervals.
**Checklist:**

fix: formatting of invalid intervals

---

admin/billing/orb.go
admin/database/postgres/migrations/0079.sql

See the discussion on platform [ticket](https://linear.app/rilldata/issue/PLAT-196).
**Checklist:**

[PLAT-196] increase trial orgs quota

---

web-common/src/features/connectors/explorer/DatabaseSchemaEntry.svelte
web-common/src/features/connectors/selectors.ts

https://rilldata.slack.com/archives/C02T907FEUB/p1758145290842579?thread_ts=1758078767.676079&cid=C02T907FEUB
**Checklist:**

Schemas Requests Hotfix

---

docs/docs/connect/connect.md
docs/docs/connect/data-source/mysql.md
docs/docs/connect/data-source/openai.md
docs/docs/reference/project-files/apis.md
docs/docs/reference/project-files/connectors.md
docs/docs/reference/project-files/rill-yaml.md
runtime/parser/schema/project.schema.yaml
runtime/parser/schema/rillyaml.schema.yaml

[DOCS] ai_connector in rill.yaml

---

web-common/src/lib/time/ranges/formatter.spec.ts

fix: add timezone specific format tests

---

runtime/drivers/duckdb/duckdb.go

Update error message for model execution in DuckDB connector

Update error message for model execution in DuckDB connector

---

.goreleaser.yaml

Publish to cdn/ latest/

---

runtime/drivers/bigquery/model_executor_self_gcs.go
runtime/drivers/snowflake/model_executor_self_objectstore.go

Fixing return path for warehouse unload
**Checklist:**

Fixing return path for warehouse unload

---

cli/cmd/project/deploy.go

fix : Set deploy flags for existing project

---

runtime/metricsview/metricssql/filter_parser.go
runtime/metricsview/metricssql/filter_parser_test.go
runtime/metricsview/metricssql/parser.go
runtime/metricsview/metricssql/parser_test.go
runtime/metricsview/metricssql/time_range_parser.go
runtime/queries/metricsview_aggregation.go
runtime/queries/proto.go
runtime/resolvers/metrics_sql.go
runtime/server/canvases.go

Move package `metricssql` under package `metricsview`

---

web-admin/src/routes/[organization]/-/users/+page.svelte

Total user count from the payload instead of counting rows visible in the table.
**Checklist:**

fix: total user count

---

runtime/completion.go
runtime/server/mcp_server.go

Prompt improvements to pass some tests from https://github.com/rilldata/rill/pull/7936
**Checklist:**

feat (AI): project-level prompt improvements

---

web-common/src/features/sources/modal/AddDataForm.svelte

Fixing some pet peeves of mine, letting @lovincyrus  focus on big items!
**Checklist:**

Adjusting height of Snowflake and Salesforce Add data modal

---

runtime/completion.go

Addresses [this Slack report](https://rilldata.slack.com/archives/C08RDR9Q26P/p1759349083441749)
**Checklist:**

fix (AI): Ease guardrails

---

docs/docs/deploy/deploy-dashboard/deploy-from-cli.md

docs: gitlab notes

---

web-common/src/features/dashboards/time-controls/new-time-controls.ts

chore: left over console.log

---

runtime/drivers/athena/warehouse.go
runtime/drivers/s3/model_manager.go

https://rilldata.slack.com/archives/CTCJ58H3M/p1759751813465949
**Checklist:**

fix panic in athena delete object

---

cli/pkg/gitutil/gitutil.go

We are seeing `Error: reference not found` when trying to do a fresh deploy using rill-managed git. Skipping head check for this error.
**Checklist:**

fix: reference not found error during rill-managed deploy

---

go.mod
go.sum
runtime/pkg/ai/openai.go

Big improvement in response quality!
For example, in response to "Run a bunch of queries and tell me a story", here's the before-and-after for the AI's final takeaways.
**Before**
**After**
Closes [APP-457](https://linear.app/rilldata/issue/APP-457/upgrade-from-gpt-4o)
**Checklist:**

feat (AI): Upgrade to GPT-4.1

---

runtime/drivers/duckdb/model_executor_objectstore_self.go
runtime/drivers/gcs/gcs.go

Fixing gcs hmac connector.
**Checklist:**

fix gcs hmac connector
