web-common/src/components/editor/YAMLEditor.svelte, web-common/src/components/editor/__stories__/YAMLEditor.stories.svelte, web-common/src/features/charts/editor/ChartsEditor.svelte, web-common/src/features/custom-dashboards/CustomDashboardEditor.svelte, web-common/src/features/generic-yaml-editor/YamlWorkspaceBody.svelte, web-common/src/features/metrics-views/workspace/editor/MetricsEditor.svelte, web-common/src/features/sources/editor/SourceEditor.svelte, web-local/src/routes/(application)/[type=workspace]/[name]/+page.svelte, web-local/src/routes/(application)/custom-dashboards/[name]/+page.svelte, web-local/src/routes/(application)/dashboard/[name]/edit/+page.svelte
The Codemirror editor currently ignores updates that happen while the Editor is focused. This is partly a symptom of our invalidation/refetching approach where an update triggered via keystroke from within the editor is eventually received by the editor again via a prop update. Changing that behavior is an ongoing discussion. Because of that conditional, a focused editor would not update its content even when the underlying file being displayed changed.
This PR adds a `key` prop to the `YAMLEditor` that unfocuses the editor whenever the prop changes, allowing the conditional check to pass. Implementing it this way, as opposed to wrapping uses of the component in a `key` block, ensures the logic is documented/captured with the component.
=> Fix: Unfocus YAML Editor on file change

web-common/src/features/tables/TableExplorer.svelte, web-common/src/layout/Resizer.svelte, web-local/src/routes/(application)/chart/[name]/+page.svelte, web-local/src/routes/(application)/custom-dashboards/[name]/+page.svelte
This PR increases the width/height of the Resizer component and properly shifts it to the right (when placed on that side) to allow for overhanging the container boundary (when allowed). It also adds a border to the Custom Dashboard and Chart editors to better signify the handle location.
=> Resizer: Increase target size

.github/workflows/cli-release.yml, .github/workflows/docs-check.yml, .github/workflows/docs-crawler.yml, .github/workflows/druid-test-image.yml, .github/workflows/go-cover.yml, .github/workflows/go-lint.yml, .github/workflows/go-test.yml, .github/workflows/prettier.yml, .github/workflows/proto-check.yml, .github/workflows/rill-cloud.yml, .github/workflows/rill-ui.yml, .github/workflows/web-test-code-quality.yml, .github/workflows/web-test-e2e.yml, .github/workflows/web-test-unit-tests.yml
Update GitHub Actions to the latest versions.
Recent failures in GitHub Actions were linked to outdated versions, leading to unexpected errors. For example:
https://rilldata.slack.com/archives/C01190F1R1D/p1714425925985609
Upgrading to the latest versions will help prevent such issues.
=> chore: bump actions' verions to avoid ci crash

web-common/src/features/dashboards/proto-state/fromProto.ts
closes #4530
The issue was with only `+` being present in the state that would get decoded to a space. Now we are decoding only if there is a`%` in the state.
=> Fix URL decoding already decoded state

web-admin/src/features/projects/status/ProjectResourcesTable.svelte, web-common/src/features/charts/chartYaml.ts, web-common/src/features/charts/prompt/generateChart.spec.ts, web-common/src/features/charts/prompt/generateChart.ts, web-common/src/features/entity-management/actions.ts, web-common/src/features/entity-management/file-content-utils.spec.ts, web-common/src/features/entity-management/file-content-utils.ts, web-common/src/features/file-explorer/new-files.ts, web-common/src/features/metrics-views/metrics-internal-store.ts, web-common/src/features/sources/sourceUtils.ts, web-local/tests/dashboards/dashboards.spec.ts, web-local/tests/dashboards/leaderboard-context-column.spec.ts, web-local/tests/dashboards/time-controls-from-config.spec.disabled.ts, web-local/tests/sources.spec.ts
Follows https://github.com/rilldata/rill/pull/4774 with the relevant UI changes:
- New files are generated with `type` not `kind`
- The toast message that appears when moving a file out of its native folder uses "type" not "kind"
- The project status page uses "type" not "kind"
- Updates the client-side YAML parser in `file-content-utils.ts`
- Updates tests
=> UI: Use `type:` instead of `kind:` for resource types

web-common/src/features/sources/source-imported-utils.ts, web-common/src/runtime-client/watch-request-client.ts
WatchRequestClient no longer had the reconnection feature.
This causes issues during a fresh project when the controller is restarted and all the watch clients are disconnected. This can be seen by starting a fresh project and import a source, the loading spinner would be present forever since the reconciled event is never recieved.
=> Add back reconnection to watch request client

web-common/src/features/dashboards/big-number/MeasureBigNumber.svelte
Stopgap solution for suppressing tooltip when moving from Explore to TDD view.
=> fix: suppress tooltip on navigation to tdd

web-common/src/features/entity-management/file-artifacts.ts, web-common/src/features/entity-management/resource-invalidations.ts, web-common/src/features/sources/modal/file-upload.ts, web-local/src/routes/(application)/[type=workspace]/[name]/+page.svelte
=> File explorer - Invalidation issues when source's table query has errored or is deleted

runtime/compilers/rillv1/parse_rillyaml.go, runtime/compilers/rillv1/parser_test.go
We've had a few requests to allow for disabling certain features and the current feature flag syntax for `rill.yaml` would make this cumbersome. This PR proposes changing the structure to a `string/bool` map (which is how it's treated after parsing now anyway) so that customers can easily set certain features to `false`
#4800 would need to be merged first
=> Change feature flag yaml structure to map

web-common/src/features/charts/templates/stacked-area.ts, web-common/src/features/dashboards/time-dimension-details/charts/utils.ts
https://github.com/rilldata/rill/pull/4778 broke time comparison tooltip for stacked area. The comparison measure variable was being sanitized two times.
=> Fix: time comparison tooltip for stacked area

web-common/src/features/dashboards/time-series/multiple-dimension-queries.ts
On scrubbing the TDD table would become empty. This PR now returns `undefined` instead of returning empty array so that the previous state is preserved.
=> Fix: show TDD table on scrub

web-common/src/features/feature-flags.ts
closes #4763
We cannot use repo APIs in cloud to get rill.yaml. Feature flags was moved to GetInstance. This PR updates to make use of GetInstance.
=> Use GetInstance to load feature flags instead of rill.yaml

web-common/src/features/feature-flags.ts
PR https://github.com/rilldata/rill/pull/4800 introduced a bug where the application would throw a 500 error on startup. The function `createRuntimeServiceGetInstance` was missing a parameter `params`. I've explicitly provided it as `undefined`.
=> Fix 500 error on application startup

web-common/src/features/dashboards/time-dimension-details/charts/ChartTypeSelector.svelte, web-common/src/features/dashboards/time-series/TimeSeriesChartContainer.svelte
=> Fix: chart labels from overflow

runtime/drivers/druid/druidsqldriver/druid_api_sql_driver.go
Druid returns NaN and +/-Infinity results as JSON strings. This PR parses such strings into native Go floats, which can natively represent NaN and infinity. 
The runtime server already returns NaN and Infinity as `null`, so this change ensures strings will never be returned as floating point values from Druid-backed metrics queries.
=> Runtime: Parse inf and NaN results from Druid as floats

.gitignore, Makefile, cli/cmd/root.go, cli/cmd/uninstall/uninstall.go, cli/cmd/upgrade/upgrade.go, cli/pkg/installscript/installscript.go
This PR adds a `rill uninstall` command.
It also makes two other minor changes to improve the CLI's use of the install script:
- Adds support for the `--version` flag on `rill upgrade`
- Embeds the install script directly in the binary
=> CLI: Uninstall command

cli/cmd/env/configure.go, cli/cmd/env/rm.go, cli/cmd/env/set.go, cli/cmd/env/show.go, cli/pkg/cmdutil/helper.go, docs/docs/explore/alerts/slack.md, docs/docs/reference/cli/cli.md, docs/docs/reference/cli/deploy.md, docs/docs/reference/cli/env/configure.md, docs/docs/reference/cli/env/env.md, docs/docs/reference/cli/env/pull.md, docs/docs/reference/cli/env/push.md, docs/docs/reference/cli/env/rm.md, docs/docs/reference/cli/env/show.md, docs/docs/reference/cli/project/edit.md, docs/docs/reference/cli/start.md, docs/docs/reference/cli/uninstall.md, docs/docs/reference/cli/upgrade.md, docs/docs/reference/cli/user/add.md, docs/docs/reference/cli/user/set-role.md, docs/docs/reference/cli/user/whitelist/list.md, docs/docs/reference/cli/user/whitelist/remove.md, docs/docs/reference/cli/user/whitelist/setup.md, docs/docs/reference/cli/user/whitelist/whitelist.md, runtime/compilers/rillv1/connectors.go
Changes:
- In `rill env configure`, prompt for credentials for all connectors specified under `connectors:` in `rill.yaml`
- In `rill env {show,set,rm}`, infer the project name from the current Git repository if available
- Remove redeploy prompt from `rill env configure` (not needed anymore, new variables are automatically used)
- Fix typo in `rill env set` example in the docs
- Regenerate CLI docs
=> CLI: Misc. `rill env` fixes

docs/docs/reference/connectors/athena.md, docs/docs/reference/connectors/azure.md, docs/docs/reference/connectors/bigquery.md, docs/docs/reference/connectors/gcs.md, docs/docs/reference/connectors/motherduck.md, docs/docs/reference/connectors/mysql.md, docs/docs/reference/connectors/postgres.md, docs/docs/reference/connectors/redshift.md, docs/docs/reference/connectors/s3.md, docs/docs/reference/connectors/salesforce.md, docs/docs/reference/connectors/snowflake.md
For some reason, we were making a callout to `.home` instead of `.env` in our reference connector documentation
=> Correcting .home with .env

web-common/src/features/dashboards/time-dimension-details/charts/tdd-tooltip-formatter.ts
For stacked area tooltip, `undefined` was being show when the value had no data.
=> Hide undefined value from tooltip

docs/docs/reference/connectors/athena.md, docs/docs/reference/connectors/azure.md, docs/docs/reference/connectors/bigquery.md, docs/docs/reference/connectors/gcs.md, docs/docs/reference/connectors/motherduck.md, docs/docs/reference/connectors/mysql.md, docs/docs/reference/connectors/postgres.md, docs/docs/reference/connectors/redshift.md, docs/docs/reference/connectors/s3.md, docs/docs/reference/connectors/salesforce.md, docs/docs/reference/connectors/snowflake.md, docs/docs/reference/project-files/sources.md
Clarifying to make the callout less confusing in our docs and clear that we're not referring to a global location
=> Changing <RILL_HOME> to <RILL_PROJECT_DIRECTORY>

web-common/src/features/charts/templates/build-template.ts, web-common/src/features/charts/templates/utils.ts
Support non string dimension values for stacked area vega lite charts
Fixes https://rilldata.slack.com/archives/CTZ8XBQ85/p1715175142246769
=> Fix: stacked area chart for non string dimension values

web-local/src/routes/(application)/custom-dashboards/[name]/+page.svelte
=> Fix: Add chart when no items set

web-common/src/components/virtualized-table/VirtualTable.svelte, web-common/src/components/virtualized-table/columnSizes.spec.ts, web-common/src/components/virtualized-table/columnSizes.ts
While modelling (or editing a source), adding a column was not reflecting in the preview table. Also removing columns would add white empty space. The width was not reactive and was fixed per entity.
Adding some code to make the use set width be saved and also be reactive when column list changes.
=> fix: Make the preview table column width reactive

web-common/src/features/dashboards/time-dimension-details/TimeDimensionDisplay.svelte
Fixes https://github.com/rilldata/rill-private-issues/issues/347
I can't reproduce the issue reliably so haven't tested this out but this should fix the issue. I am resetting the table highlight store once the table parent component is unmounted.
=> Fix: No highlight dimension line on explore

web-common/src/features/alerts/criteria-tab/CriteriaForm.svelte, web-common/src/features/alerts/criteria-tab/operations.ts, web-common/src/features/dashboards/filters/measure-filters/MeasureFilterBody.svelte, web-common/src/features/dashboards/filters/measure-filters/measure-filter-entry.spec.ts, web-common/src/features/dashboards/filters/measure-filters/measure-filter-entry.ts, web-common/src/features/dashboards/filters/measure-filters/measure-filter-options.ts
We are updating the list of options available in alert criteria to be a simpler and smaller list.
- `greater than or equals`
- `less than`
- `equals`
- `does not equals`
Older alerts will still work and will show the correct criteria in alert page. But during edit it wont be available anymore.
=> feat: Update alert criteria options to have a simpler list

runtime/pkg/metricssql/parser.go, runtime/pkg/metricssql/parser_test.go
Added support for `date_add`, `date_sub` and `now`
=> Runtime: handling of other time functions in metrics_sql

runtime/server/generate_metrics_view.go
Closes https://github.com/rilldata/rill/issues/4599
=> Fix: Escape complex column names in generated measure expressions

web-common/src/components/data-types/Base.svelte, web-common/src/components/data-types/PercentageChange.svelte, web-common/src/components/virtualized-table/core/Cell.svelte, web-common/src/features/dashboards/big-number/MeasureBigNumber.svelte, web-common/src/features/dashboards/leaderboard/ContextColumnValue.svelte, web-common/src/features/dashboards/pivot/PivotMeasureCell.svelte, web-common/src/features/dashboards/pivot/RegularTable.svelte
`null` or `undefined` were being formatted as "no data" before which was verbose. This PR replaces it with "-"
=> Replace "no data" with `-` in all tables

web-local/src/routes/(application)/chart/[name]/+page.svelte
=> Chart Editor: Left align table

runtime/drivers/druid/druidsqldriver/druid_api_sql_driver.go
Druid request was created twice so different query ids, the query id used in cancellation was different from id of actual request sent to druid.
=> fix bug with druid sql query id

web-common/src/runtime-client/fetchWrapper.ts, web-local/src/routes/(application)/chart/[name]/+page.svelte
In certain scenarios, the  fetchWrapper tries to parse the json response multiple times, which throws. This PR reorganizes this function to avoid this duplicate call.
=> Fix: fetchWrapper duplicate json parsing

web-common/src/features/charts/templates/grouped-bar.ts, web-common/src/features/charts/templates/simple-bar.ts
Disable vornoi selection of marks on hover for bar charts.
=> Disable vornoi for bar charts

web-common/src/components/date-picker/Litepicker.svelte, web-common/src/components/date-picker/custom-picker.js
This PR adjusts the custom picker implementation so that it properly scrolls to the relevant boundary date when selecting a text input.
This is patch fix for code that will soon be deprecated.
closes: #4899
=> fix: Custom picker focus handling

docs/docs/reference/connectors/motherduck.md
it seems like this might have been a copy/paste error.
=> fix typo in motherduck connector reference

runtime/compilers/rillv1/data/component-template-v1.json, runtime/compilers/rillv1/parse_component.go
- Adds support for a `template:` renderer in resources of `type: component`.
- Resources will have `spec.renderer == "template"` and `spec.rendererProperties` will contain the supplied properties.
- The template properties are validated using the JSON schema in `runtime/compilers/rillv1/data/component-template-v1.json`. It currently has validation stubs for `line_chart` and `bar_chart` templates.
Example:
```yaml
type: component
template:
name: line_chart
x: foo
y: bar
```
=> Runtime: Component renderer for "template:"

web-common/src/features/dashboards/time-series/MetricsTimeSeriesCharts.svelte
Fixes https://github.com/rilldata/rill-private-issues/issues/379
Moved the check from availability of compared dimension data to included values for the compared dimension
=> Preserve alt chart type on refresh

runtime/controller.go, runtime/controller_test.go
Fixes two issues that sometimes occurs when a resource is renamed while it is reconciling:
- The resource would no longer exist when the previous reconcile finished, leading to stopping of the controller
- The rename would start reconciling before the reconciler invocation for the previous name had completed
=> Runtime: Fix renaming a reconciling resource

.gitignore, Makefile, runtime/drivers/duckdb/duckdb.go, runtime/drivers/duckdb/extensions.go, runtime/drivers/duckdb/extensions/extensions.go, runtime/pkg/duckdbsql/duckdbsql.go, scripts/embed_duckdb_ext/main.go
=> Embed DuckDB extensions in the Rill binary

web-common/src/features/entity-management/resource-invalidations.ts
Prereq/Subset of #4901:
- Skips invalidation if the filename is not present
- This was causing a FileArtifact to be created/refetched without a valid pathname
=> Fix: Skip invalidation if no filename present

runtime/pkg/pbutil/pbutil.go, runtime/queries/metricsview_aggregation.go
My understanding is that duckdb's timezone of the returned value is always in `UTC` due to the way it is scanned here : https://github.com/marcboeker/go-duckdb/blob/e1139f74c461fc566a20d2c2c05b7bb851b1415c/rows.go#L174C10-L174C25
In case of clickhouse it depends on the timezone of column : https://github.com/ClickHouse/clickhouse-go/blob/28fd6a4954a5dbf09b7dcc0fcce597beb2dd0b58/lib/column/datetime64.go#L303
Though it is always supposed to be in `session_timezone` which is set to UTC for us but there are edge case as defined here : https://clickhouse.com/docs/en/operations/settings/settings#session_timezone
We handle it explicitly by converting all time values to UTC.
=> Runtime: Clickhouse timezone fixes

web-common/src/features/entity-management/file-artifacts.ts
closes #4943 (potentially #4944 as well?)
This is a patch to make sure reconciling resources are updated and the reconciling spinner is shown. This might have regression where the left nav entry will flicker. We need to have a proper fix with debounce. We can do that after the patch release.
=> fix: Updating errors for reconciling resources

runtime/drivers/duckdb/transporter_postgres_to_duckDB_test.go, runtime/drivers/duckdb/transporter_sqlstore_to_duckDB.go, runtime/drivers/postgres/parser.go
Reported here : https://rilldata.slack.com/archives/CTZ8XBQ85/p1715191773721049
=> Runtime: fix uuid type for postgres connector

web-common/src/features/entity-management/ResourceWatcher.svelte, web-common/src/runtime-client/watch-request-client.ts
During recent refactors the code to stop the watcher when out of focus for 5 seconds was removed. This adds back the code by making sure the retry doesnt reconnect when stopped because of page out of focus.
=> fix: Teardown file & resources watcher when out of focus

web-common/src/components/data-types/PercentageChange.svelte
Percentage change for measure does not inherit the parent font weight because of a fixed style mentioned in `PercentageChange` which is not being used anywhere.  This PR removes that class.
=> Remove font style declaration from `PercentageChange`

web-common/src/features/dashboards/pivot/PivotTable.svelte, web-common/src/features/dashboards/pivot/pivot-data-store.ts
Fixes #4942
Makes two changes -
1. For pivot table with rows less than 50 do not change row page number on scroll
2. When the pivot config changes (ex- time range, comparison range etc.) update `rowPage` to 1.
=> Fix: stale pivot data on config change

runtime/compilers/rillv1/init.go
Previously, new Rill projects were initialized with emtpy `source`, `model`, and `dashboard` directories. This PR removes those empty folders from initialized projects. Particularly, the `source` and `model` directories are not currently applicable to ClickHouse-backed projects.
[Context in Notion](https://www.notion.so/rilldata/Improving-our-Connect-to-ClickHouse-modal-64420494ff514247b2fc60fef2267033?pvs=4#3e4d8f54ad7c4fb1be10b1116cc9484e)
=> Remove empty directories from initialized projects

runtime/drivers/olap.go, runtime/queries/metricsview_timeseries.go
We need to cast result of `date_trunc` to timestamp since `date_trunc('month`, ...) results `date`
=> Runtime : Cast result of `date_trunc` to timestamp

web-admin/src/features/alerts/metadata/AlertFilterCriteria.svelte, web-common/src/features/alerts/criteria-tab/CriteriaForm.svelte
- In alert form there was not enough space for `>=` causing it to be truncated.
- In alert details page the criteria had a max width. Removing this to show the entire text.
=> fix(alert): Some spacing nits for alerts

web-common/src/features/connectors/ConnectorExplorer.svelte, web-common/src/features/connectors/olap/DatabaseSchemaEntry.svelte, web-common/src/features/connectors/olap/TableEntry.svelte, web-common/src/features/connectors/olap/TableMenuItems.svelte, web-common/src/features/connectors/olap/TableWorkspaceHeader.svelte, web-common/src/features/connectors/olap/olap-config.ts, web-local/src/routes/(application)/connector/clickhouse/[name]/[database]/[table]/+page.svelte, web-local/src/routes/(application)/connector/druid/[name]/[schema]/[table]/+page.svelte, web-local/src/routes/(application)/connector/duckdb/[name]/[database]/[schema]/[table]/+page.svelte, web-local/src/routes/(application)/connector/pinot/[name]/[table]/+page.svelte
This PR is a small refactor to handle arbitrary connector names in the UI. This sets us up to allow >1 connector per connector type/driver.
For illustration, here's a connector not named the same as its driver:
=> Connectors: Handle arbitrary names

web-common/src/features/connectors/olap/DatabaseExplorer.svelte, web-common/src/features/connectors/utils.ts, web-common/src/features/entity-management/WatchResourcesClient.ts
This PR invalidates the `AnalyzeConnectors` and `OLAPListTables` APIs when a Connector changes.
One finding –
- When editing a secret in a `.env` file, sometimes the frontend does not see a `RESOURCE_EVENT_WRITE`. This is a problem because the frontend listens for this event to know when to invalidate the above APIs. Discussing with @begelundmuller, we could have the following race condition: edits to the `.env` file trigger the Controller to restart, the frontend's streaming connection is terminated and re-established, and any reconciliation events that occurred while the frontend was not subscribed to the backend are lost.
=> Connectors: query invalidations

web-common/src/features/entity-management/ResourceWatcher.svelte, web-common/src/runtime-client/watch-request-client.ts
This PR displays an error message via the `ResourceWatcher` component when the streaming connections have failed >= 2 times.
Closes: #3633
=> feat: display runtime disconnect message

web-common/src/features/alerts/data-tab/AlertDialogDataTab.svelte, web-common/src/features/dashboards/filters/FilterButton.svelte, web-common/src/features/dashboards/leaderboard/LeaderboardControls.svelte, web-common/src/features/dashboards/state-managers/selectors/measures.spec.ts, web-common/src/features/dashboards/state-managers/selectors/measures.ts, web-common/src/features/dashboards/state-managers/selectors/pivot.ts, web-common/src/features/dashboards/stores/AdvancedMeasureCorrector.spec.ts, web-common/src/features/dashboards/stores/AdvancedMeasureCorrector.ts, web-common/src/features/dashboards/stores/dashboard-stores-test-data.ts, web-common/src/features/dashboards/stores/dashboard-stores.ts, web-common/src/features/dashboards/stores/filter-utils.ts, web-common/src/features/dashboards/time-controls/TimeControls.svelte, web-common/src/features/dashboards/time-controls/time-control-store.spec.ts, web-common/src/features/dashboards/time-series/ChartInteractions.svelte, web-common/src/features/dashboards/time-series/MeasureChart.svelte, web-common/src/features/dashboards/time-series/MetricsTimeSeriesCharts.svelte, web-common/src/features/dashboards/time-series/timeseries-data-store.ts, web-common/src/lib/arrayUtils.ts
Removed certain advanced measures from pivot and alerts. Also updates the dashboard state with any incorrect selections. EG: when in a TDD with a measure depending on a specific time grain and time grain is changed, active measure is cleared.
Sample dashboard,
```
type: metrics_view
title: Adbids Model
model: AdBids_model
timeseries: timestamp
dimensions:
- label: Publisher
column: publisher
- label: Domain
column: domain
measures:
- name: total_records
label: Total records
expression: COUNT(*)
format_preset: humanize
valid_percent_of_total: true
- name: bid_price
label: Sum of Bid Price
expression: SUM(bid_price)
format_preset: humanize
valid_percent_of_total: true
- name: bid_price_lag
label: Bid Price Lag
expression: "bid_price - LAG(bid_price)"
window: true
requires: [bid_price, …
```
=> fix(advanced measures): Exclude advanced measures from pivot and exclude comparison measures

runtime/compilers/rillv1/parse_dashboard.go, web-common/src/features/custom-dashboards/CustomDashboardPreview.svelte, web-local/src/routes/(application)/custom-dashboards/[name]/+page.svelte
This PR adds a keydown listener for `Backspace` and `Delete` to the Custom Dashboards workspace that removes the currently selected component.
=> feat: remove chart on backspace/delete

web-common/src/features/charts/render/VegaLiteRenderer.svelte, web-common/src/features/charts/render/vega-config.ts
The legends for some charts were missing. This updates the config and reduces the X axis padding.
=> Use autosize for vega charts

web-common/src/features/connectors/ConnectorEntry.svelte, web-common/src/features/connectors/olap/DatabaseEntry.svelte, web-common/src/features/connectors/olap/DatabaseSchemaEntry.svelte, web-common/src/features/connectors/olap/TableEntry.svelte, web-common/src/features/connectors/olap/TableMenuItems.svelte, web-common/src/features/connectors/olap/TableSchema.svelte, web-common/src/features/file-explorer/NavDirectoryEntry.svelte
Previously, clicking a Table entry revealed its schema. Now, clicking a Table entry navigates to the Table Preview.
[Context here](https://www.notion.so/rilldata/Improving-our-Connect-to-ClickHouse-modal-64420494ff514247b2fc60fef2267033?pvs=4#34bfe6a65fe947ca84166804fd746490)
=> Connectors: Click a table to preview it

web-common/src/features/entity-management/WatchResourcesClient.ts
WatchResourcesClient was calling `refetchQueries` instead of `invalidateQueries`.
=> tweak: invalidate rather than refetch resources

web-common/src/components/ErrorPage.svelte, web-common/src/features/entity-management/ResourceWatcher.svelte
This PR uses the `ErrorPage` component instead of `WorkspaceError` for handling situations where the connection to the runtime has been lost.
=> Use ErrorPage component when runtime connection fails

web-admin/src/features/dashboards/listing/selectors.ts, web-admin/src/features/errors/error-utils.ts, web-admin/src/features/projects/selectors.ts, web-admin/src/features/projects/status/ProjectDeploymentStatusChip.svelte, web-admin/src/routes/[organization]/[project]/+layout.svelte, web-admin/src/routes/[organization]/[project]/[dashboard]/+page.svelte, web-common/src/runtime-client/RuntimeProvider.svelte, web-common/src/runtime-client/runtime-store.ts
Currently, re-visiting a Project page can trigger a 401 error. In the error case, a stale JWT sits in the `GetProject` Query Cache and is used in a runtime request. The 401 triggers a full-screen error page.
This PR does a few things to mitigate this, notably:
1. Adds `refetchOnMount`, `refetchOnWindowFocus`, and `refetchOnReconnect` to refetch the JWT when the user re-visits the page
2. Explicitly adds `cacheTime` to garbage-collect old JWTs
3. Removes the full-screen error page for runtime 401s on the Project page
[Bug report in Slack](https://rilldata.slack.com/archives/C01190F1R1D/p1718237032223209?thread_ts=1718235808.839709&cid=C01190F1R1D)
=> Cloud UI: Fix 401 error on the Project page due to stale JWT 

web-common/src/features/dashboards/pivot/PivotDisplay.svelte, web-common/src/features/dashboards/pivot/PivotEmpty.svelte, web-common/src/features/dashboards/pivot/pivot-data-store.ts
On adding mutually exclusive filters on a pivot table, the table would crash and be in a perpetual loading state. This PR fixes it and adds a message if there is no result to display.
=> Fix: Empty data on exclusive filters on pivot

runtime/compilers/rillv1/data/component-template-v1.json, runtime/compilers/rillv1/parse_component.go, runtime/compilers/rillv1/parser_test.go
This PR adds fallback support for a generic renderer in the component resource YAML. A map value must be provided to a generic renderer (unlike the built-in/hardcoded renderers which can accept another type, like `markdown` accepts a `string`).
Examples:
```yaml
type: component
line_chart:
x: event_time
y: total_sales
type: component
data:
metrics_sql: SELECT 1
line_chart:
x: event_time
y: total_sales
type: component
line_chart:
x: event_time
y: total_sales
bar_chart:
x: event_time
y: total_sales
```
Closes https://github.com/rilldata/rill/issues/5072
=> Runtime: Untyped component renderer

web-common/src/features/custom-dashboards/CustomDashboardPreview.svelte, web-common/src/features/custom-dashboards/PreviewElement.svelte, web-local/src/routes/(application)/custom-dashboards/[name]/+page.svelte
* Don't try to show external yaml for components inline
* Handle closing and clearing second editor when moving in/out of selected state
* Removed placeholder right-click context options
* Don't render right-click menu for components defined inline
TODO:
* We are still updating and fetching the dashboard.yaml on a component click without changes.
=> fix: handle inlineComponents

web-admin/src/features/projects/ProjectBuilding.svelte, web-admin/src/features/projects/ProjectErrored.svelte, web-admin/src/routes/-/github/connect/+page.svelte, web-admin/src/routes/-/github/connect/retry-auth/+page.svelte, web-admin/src/routes/-/github/connect/retry-install/+page.svelte, web-admin/src/routes/[organization]/[project]/-/alerts/[alert]/open/+page.svelte, web-admin/src/routes/[organization]/[project]/-/reports/[report]/export/+page.svelte, web-admin/src/routes/[organization]/[project]/-/reports/[report]/open/+page.svelte, web-common/src/components/ErrorPage.svelte, web-common/src/components/button/Button.svelte, web-common/src/components/calls-to-action/CTAButton.svelte
This PR refactors our `CTAButton` to build on top of our `Button` component. Importantly, the `CTAButton` now accepts an `href` prop.
=> Refactor: `CTAButton` component

runtime/drivers/clickhouse/clickhouse.go, runtime/drivers/clickhouse/context.go, runtime/drivers/clickhouse/olap.go
Clickhouse http interface requires a `session_id` to be passed to tie queries to a certain session.
=> Runtime: Fix session usage for clickhouse http interface

web-common/src/components/navigation/breadcrumbs/BreadcrumbItem.svelte, web-local/src/routes/(viz)/+layout.svelte
See discussion here: https://github.com/rilldata/rill/issues/4911
=> breadcrumb tweak

package-lock.json, web-common/package.json, web-common/src/runtime-client/local-service.ts
Splitting out tanstack wrapper around LocalService from #5106
=> feat: Adding tanstack query wrapper around LocalService

web-common/src/features/dashboards/pivot/pivot-data-store.ts
We get an empty table on scrolling a pivot table beyond 50 values. This PR fixes it by checking that we are on the first page when we validate for empty axes.
=> fix: empty pivot table on scroll

web-common/src/features/dashboards/pivot/PivotTable.svelte, web-common/src/features/dashboards/pivot/pivot-expansion.ts
The challenge with revealing sub-rows when there are no measures is that we really don't know what should come in those sub-rows. 
Example -
Dimension 1: Country
Values: India, USA, UK
Dimension 2: Cities
Values: Delhi, New York, London
Displaying a "cross-product" to get the sub-rows would give wrong results.
In case we use the first measure as a reference, depending on the measure type avg/sum/etc we can get confusing results.
The best solution probably is to use the inline `count(*)` as a measure when there is no measure. This PR implements this approach.
Closes #4637
=> fix: reveal sub row dimension values in pivot without measures

runtime/resolver.go, runtime/resolvers/metrics.go, runtime/resolvers/sql.go
Fixes issue where `duckdb.Decimal` is serialized as an object instead of a number.
=> Runtime: Use jsonval to serialize resolver results

web-admin/src/features/navigation/TopNavigationBar.svelte
Visiting the root cloud page causes and uncaught error and leads to a crashed app.
=> fix: uncaught error on root cloud page

web-common/src/features/models/workspace/inspector/References.svelte
Fixes broken urls to file paths
=> fix: broken urls to refs in inspector

web-common/src/features/dashboards/pivot/pivot-merge-filters.ts
When there is a measure threshold filter sub tables in pivot with multiple dimensions breaks sub tables. The query doesnt apply the filter of the sub table and shows all the dimension values.
=> fix(pivot): measure filter breaking sub table in pivot

web-common/src/components/editor/presets/yamlWithJsonAndSql.ts, web-common/src/features/metrics-views/workspace/editor/MetricsEditor.svelte, web-local/src/routes/(application)/files/[...file]/+page.svelte
API:
MetricsView (must be unquoted):
Closes: #5056
=> feat: highlight SQL-in-YAML for API and MetricsView asset types

web-admin/src/routes/+layout.svelte, web-common/src/features/entity-management/ResourceWatcher.svelte, web-local/src/routes/+layout.svelte
Moving initialisation of javascript error telemetry to the same place where it is created.
=> fix: javascript error telemetry not firing anymore

web-common/src/lib/event-bus/event-bus.ts
`crypto` will fail for non-https context and for other hosts then localhost. So in scenarios where someone accesses Rill Developer over http on a non-localhost hostname, such as in a virtual machine or in WSL over hostname, the event bus will fail to initialize.
Seeing as we are only using it as a key for the event bus here is a native math.random implementation. I would assume we don't need full cryptography strength on our frontend event bus keys :)
=> fix: math.random for eventbus

admin/admin.go, admin/database/database.go, admin/database/postgres/migrations/0031.sql, admin/database/postgres/postgres.go, admin/server/admin_rbac_test.go, admin/server/assets.go, admin/server/repos.go, admin/server/server.go, admin/worker/delete_unsued_assets.go, admin/worker/worker.go, cli/cmd/admin/start.go, cli/pkg/mock/server.go
=> feat: Asset cleanup

cli/cmd/start/start.go
We use `ignore_paths` with a few [hardcoded paths](https://github.com/rilldata/rill/blob/main/runtime/drivers/repo.go#L52) while reading the project files. But this was missing while we check for large projects during `rill start`
=> fix: use ignore_paths while checking large projects during rill start

web-common/src/features/dashboards/stores/dashboard-stores.ts
Temporary fix for https://rilldata.slack.com/archives/CTZ8XBQ85/p1719374514886679
We don't have support for asynchronous calls in our pivot data store. To fetch the values for a particular nested sub-table, we need to know the values of its parents. This generally works well when a user expands the table one by one. However, if we attempt to call everything at once, we need an asynchronous way to handle data in the Svelte store. This is also why implementing an "Expand All" feature would require a significant refactor. Currently, we are looking at ways to fix it so that we at least don't show incorrect data. One solution could be to collapse all expanded values when measures are changed.
A follow up for this would be to add support for asynchronous sequential calls.
=> Fix: collapse expanded values on measure change

web-common/src/components/forms/MultiInput.svelte, web-common/src/components/forms/__stories__/MultiInput.stories.svelte
For user invite we need a single input that takes multiple items that can be deleted. This can also replace our inputs for user invite, slack users and slack channels in alerts/report forms.
=> feat: Add multiple items in a single input component

web-common/src/features/metrics-views/workspace/PreviewButton.svelte
The spinner shows up when navigating to any url. This is an issue during login flow where we redirect to `/auth`, which can take time.
Fixing the button to only show spinner when navigating to the relevant route.
=> fix: show loading spinner on Preview button only when navigating to the relevant route

web-common/src/features/dashboards/pivot/RegularTable.svelte, web-common/src/features/dashboards/time-dimension-details/TDDTable.svelte, web-common/src/features/dashboards/time-dimension-details/TimeDimensionDisplay.svelte, web-common/src/features/dashboards/time-dimension-details/time-dimension-data-store.ts, web-local/tests/dashboards/dashboards.spec.ts
This PR is a stopgap solution to enable copying of values via the TDD table. A larger refactor is necessary to remove the use of `RegularTable`, but this is a significant lift that is not currently prioritized.
This PR moves the responsibility for formatting from the data preparation utilities to the display components.
Tooltips are displayed using the native HTML `title` attribute rather than our bespoke `Tooltip` component as using the latter is not practical with Regular Table and the tooltip approach throughout the app is in flux.
Closes: #4490
=> feat: add copy/tooltips to TDD table

docs/docs/build/connect/glob-patterns.md, docs/docs/reference/project-files/sources.md, runtime/drivers/blob/blobdownloader.go, runtime/drivers/blob/blobdownloader_test.go
By default no limits on files listed and files matched and 100 GB on total size.
=> Runtime : Modify blob limits

runtime/drivers/duckdb/model_executor_self_file.go, runtime/drivers/duckdb/olap.go, runtime/drivers/file/model_executor.go, runtime/drivers/file/model_executor_olap_self.go, runtime/drivers/registry.go, runtime/metricsview/executor.go, runtime/metricsview/executor_export.go, runtime/metricsview/executor_rewrite_limit.go, runtime/server/downloads.go, runtime/testruntime/testruntime.go
closes https://github.com/rilldata/rill-private-issues/issues/432
The excel export limit is not fully optimised. The entire export data is written into temporary files by the underlying library and the limit is only checked when writing data from these temporary files to output files. I checked and could not find any way to control these temporary files.
=> Runtime : Better export limits

web-admin/src/features/alerts/listing/AlertsTable.svelte
Changes the `Last triggered` timestamp for alerts from `executionTime` to `finishedOn` (with a fallback of `startedOn`)
=> fix: change last trigger reference

web-admin/src/features/alerts/selectors.ts, web-admin/src/features/scheduled-reports/selectors.ts
`TopNavigationBar` makes use of queries that require the project instance ID, but this components exists outside of the `RuntimeProvider` scope. As such, the instanceId may not initially be set when one arrives at an alert or report page directly.
This is a workaround fix, in my opinion, and a real fix would require a reorganization of the routes and load functions.
=> fix: disable alert/report queries when instanceid undefined

runtime/reconcilers/alert.go, runtime/reconcilers/report.go
- Changes all alert/report logs to info-level or higher
- Logs a specific reason for skipping alert/report checks
Closes https://github.com/rilldata/rill-private-issues/issues/469
=> Runtime: More detailed alert/report logs

netlify.toml
=> Add Pylon's new `font-src` to CSP

web-common/src/features/dashboards/leaderboard/LeaderboardListItem.svelte
* appends protocols for urls without them
* trims input of whitespaces to allow {{ columnName }} in yaml
=> fix: add protocols and whitespace trim

runtime/drivers/druid/druidsqldriver/druid_api_sql_driver.go
Without this it will return non meaningful error while decoding response body
=> return actual err status from druid resp

admin/database/postgres/migrations/0033.sql
Overlooked and used `TIMESTAMP` for `expires_on` earlier. This was causing issue with dev env where timezone is behind UTC and auth code would just expire. Won't cause any migration issue on prod as tz is already UTC and anyways we just delete auth codes after use so table should be just empty.
=> use timestamp col with tz for auth code expiration

admin/worker/run_autoscaler.go
Update:
- Prevent downscaling
Should Partially resolve: https://github.com/rilldata/rill-private-issues/issues/475
=> feat: Update scaling policy

cli/cmd/deploy/deploy.go
Note that this PR does not handle the prompts in the deploy flow, which may currently still block even if --interactive is false. This PR only handles the happy path for deploys in CI.
=> Don't open browser after deploy when --interactive=false

web-admin/src/features/bookmarks/Bookmarks.svelte, web-admin/src/features/bookmarks/BookmarksDropdownMenuContent.svelte, web-admin/src/features/navigation/TopNavigationBar.svelte, web-admin/src/features/shareable-urls/CreateShareableURLForm.svelte, web-admin/src/routes/[organization]/[project]/[dashboard]/+page.svelte, web-common/src/features/dashboards/state-managers/StateManagersProvider.svelte, web-common/src/features/dashboards/state-managers/state-managers.ts, web-common/src/features/dashboards/stores/dashboard-stores-test-data.ts, web-common/src/features/dashboards/stores/dashboard-stores.spec.ts, web-local/src/routes/(viz)/+layout.svelte
The purpose of this PR is to make a small step toward disentangling the metricViewName used in various places across the application from the corresponding route parameter in the URL. In practice, this should not be necessary, but this is a quick fix for some upstream issues.
The literal name of a `MetricsView` may be something like `MyDashboard`. The application mostly treats this as case insensitive, so navigating to a dashboard route via `/mydashboard` (or any other variation) will still get you there. However, throughout the FE, the name being passed around sometimes maintains the casing of whatever was typed into the URL rather than the literal name. This can cause issues in places where the case sensitive name is needed (though these should be eliminated).
As such, this makes some …
=> fix: metrics view casing

admin/pkg/authtoken/authtoken.go, admin/pkg/authtoken/authtoken_test.go
Access tokens in Rill follow the format `rill_<type>_<base62(payload)>` where the payload contains the token's ID (16 bytes) and randomly generated secret (24 bytes). 
The `base62` implementation drops leading `0x00` bytes, which means that on average 1 out of every 256 tokens can't be parsed. This PR fixes this issue by left-padding the parsed payload with `0x00`.
It also adds a test that generates 100000 random tokens and tests that they parse correctly to prevent such errors from occurring again.
=> Left pad parsed auth token bytes

go.mod, go.sum, runtime/pkg/duckdbsql/ast_test.go
Closes #5052
The workaround is no longer needed. [The issue](https://github.com/marcboeker/go-duckdb/issues/215) is fixed
=> Upgrade to DuckDB 1.0.0

runtime/drivers/duckdb/transporter_sqlstore_to_duckDB.go, runtime/drivers/postgres/sql_store.go
NOTE : Inserting null UUIDs fails in the latest version of `go-duckdb` but fixed on main. So as of now inserting null UUIDs will fail.
=> Runtime: Fix for inserting NULL UUIDs from SQL Stores

web-common/src/features/dashboards/time-controls/super-pill/components/Comparison.svelte, web-common/src/features/dashboards/time-controls/super-pill/components/RangePicker.svelte
This PR disables the typeahead functionality of the dropdown menu when the custom calendar picker is open. This was previously causing issues with the date input.
=> fix: disable typeahead when calendar picker open

web-common/src/features/dashboards/stores/dashboard-stores.ts
Turning on time comparison was not turning off dimension breakdown.
=> fix: temporary mutual exclusivity of time and dimension comparison

web-common/src/features/dashboards/time-controls/comparison-pill/ComparisonPill.svelte, web-common/src/features/dashboards/time-controls/super-pill/components/Comparison.svelte
The display of the comparison range was not factoring in time zone.
=> fix: comparison range display

admin/worker/run_autoscaler.go, admin/worker/run_autoscaler_test.go
Refactor the slot autoscaler:
1. Avoid scale down
2. Allow scaling when origin slots is small (< 10)
3. Avoid scaling when increase < 10%
4. Avoid scaling when increase < 5 slots
Resolve: https://github.com/rilldata/rill-private-issues/issues/475
=> refactor: update scaling strategies

web-common/src/app.css, web-common/src/features/project/ProjectTitle.svelte, web-common/src/layout/navigation/Navigation.svelte, web-common/src/layout/navigation/SurfaceControlButton.svelte, web-common/src/layout/workspace/WorkspaceHeader.svelte
=> tweak: rill developer header sizing

web-common/src/features/file-explorer/NavDirectory.svelte, web-common/src/features/file-explorer/nav-entry-drag-drop-store.ts
This PR removes the dangling directory/file when the native context menu is opened.
https://github.com/user-attachments/assets/e0df81d0-0036-4a2c-9d77-a784eb0ff67f
closes #5337
=> Cancel drag events of directory/file when the native context menu is opened

admin/server/deployment.go, admin/server/projects.go, admin/server/runtime_proxy.go
FYI, I cannot reproduce any errors relevant to removal of above permissions, did I miss something? I tested running `runtime` and `devtool-cloud`
Closes https://github.com/rilldata/rill-private-issues/issues/484
=> Remove ReadProfiling and ReadRepo permissions from JWTs

docs/docs/reference/olap-engines/pinot.md, docs/docs/reference/project-files/dashboards.md, runtime/compilers/rillv1/parse_metrics_view.go
Closes https://github.com/rilldata/rill/issues/5268
=> Deprecate the `ignore:` setting for dimensions and measures

.github/workflows/prettier.yml, .husky/pre-commit, .prettierignore, package-lock.json, package.json
This PR introduces a pre-commit script that runs against staged git files using [`lint-staged`](https://www.npmjs.com/package/lint-staged). A tiny DX improvement that prettier checks our staged files locally before they run in the prettier checks github action.
closes #5353
=> Add husky pre-commit git hooks to lint staged files

web-common/src/metrics/ErrorEventHandler.ts, web-common/src/metrics/service/ErrorEventFactory.ts
closes https://github.com/rilldata/rill-private-issues/issues/511
=> feat: Add dashboard state to error telemetry to better debug errors

web-common/src/features/authentication/LocalAvatarButton.svelte
Move from `isFetching` to `isLoading` to avoid showing a spinner every time we refetch user state.
=> fix: Avoid showing the spinner on the avatar every time the page is focused.

web-common/src/components/dialog-v2/dialog-overlay.svelte, web-common/src/features/dashboards/leaderboard/LeaderboardRow.svelte
When opening the Alert Dialog, parts of leaderboards are visible over the alert backdrop.
This PR removed the z-index from the leaderboard rows
Before
After
=> fix: remove z-index for leaderboard rows

web-common/src/features/dashboards/filters/Filters.svelte
On the dashboard, adding a filter adds height to the filter section. It’s clear when you add & remove 1 filter. The page is jumpy.
=> fix: update row height for filter bar

web-common/src/features/dashboards/big-number/MeasureBigNumber.svelte, web-common/src/features/dashboards/time-series/MetricsTimeSeriesCharts.svelte
Disable the big number tooltip when switching between Overview and Measure views. Fixes #5352
See before: https://github.com/rilldata/rill/issues/5352#issue-2438372614
After
https://github.com/user-attachments/assets/725aa77e-46bf-4f9c-80d5-dc889e52e40e
=> Disable big number tooltip in expanded time series metrics

runtime/pkg/email/templates/alert_fail.mjml, runtime/pkg/email/templates/alert_status.mjml, runtime/pkg/email/templates/call_to_action.mjml, runtime/pkg/email/templates/gen/alert_fail.html, runtime/pkg/email/templates/gen/alert_status.html, runtime/pkg/email/templates/gen/call_to_action.html, runtime/pkg/email/templates/gen/informational.html, runtime/pkg/email/templates/gen/project_access_request.html, runtime/pkg/email/templates/gen/scheduled_report.html, runtime/pkg/email/templates/informational.mjml, runtime/pkg/email/templates/project_access_request.mjml, runtime/pkg/email/templates/scheduled_report.mjml, web-admin/src/features/projects/github/GithubRepoSelectionDialog.svelte, web-admin/src/features/projects/github/ProjectGithubConnection.svelte, web-admin/src/features/projects/user-invite/CopyInviteLinkButton.svelte, web-admin/src/features/projects/user-invite/UserInviteButton.svelte, web-common/src/components/icons/CaretDownFilledIcon.svelte, web-common/src/components/icons/CaretRightFilledIcon.svelte
1. Update the icons used for `Advanced Options` to match the mocks.
2. Github connection dialog should be fixed and not move around when `Advanced Options` is opened/closed.
3. Update Copyright in all emails from 2023 to 2024
4. Github edit icon should only appear when hover over the github section.
5. Adjust `Share this project` font size.
6. `Copy link` => `Copy URL` and `Link copied` => `URL copied`
Reference: https://www.notion.so/rilldata/v0-48-0-QA-26b6988933094ad1a24626ff412b66ad?pvs=4#ce94c84d67fe4630ae1f07f9cfd506bd
=> fix: Misc design changes for the new deploy flow

web-admin/src/features/projects/github/ConnectToGithubButton.svelte, web-admin/src/features/projects/github/GithubRepoSelectionDialog.svelte, web-admin/src/features/projects/github/ProjectGithubConnection.svelte, web-admin/src/routes/-/github/connect/+page.svelte, web-admin/src/routes/-/github/connect/request/+page.svelte, web-admin/src/routes/-/github/connect/retry-auth/+page.svelte, web-admin/src/routes/-/github/connect/retry-install/+page.svelte, web-admin/src/routes/-/github/connect/success/+page.svelte, web-common/src/features/dashboards/workspace/DeployDashboardCTA.svelte
1. Update all instances of `Github` to `GitHub`.
2. Update github repo selection dialog to state that the project contents will replace target repo.
3. Show repo installation dialog during initial repo connection.
4. Clicking `Redploy` opens the deploy page twice.
=> fix: copy around github to better match our intent

docs/docs/explore/alerts/slack.md, runtime/security.go
Fixes https://github.com/rilldata/rill-private-issues/issues/505 
A hack to allow slack channel users to access the alert. This also means that any alert configured with a slack channel will be viewable by any user part of the project and will appear in their alert list.
=> slack alert viewable by all project users

cli/cmd/sudo/clone.go
otherwise shell interprets it throwing random errors
=> single quote the download url

cli/cmd/start/start.go, cli/pkg/local/app.go
1. Replace `cors allowed-origins` with default localHttpUrl
2. Add a flag `--allowed-origins` to input additional `allowed-origins`
Resolve https://github.com/rilldata/rill/issues/5039
=> refactor: apply cors

web-admin/src/features/alerts/listing/AlertsTableCompositeCell.svelte
=> Humanize last trigger in alerts

runtime/drivers/clickhouse/clickhouse.go, runtime/drivers/druid/druid.go, runtime/drivers/duckdb/duckdb.go, runtime/drivers/duckdb/olap.go, runtime/drivers/duckdb/utils.go, runtime/drivers/olap.go, runtime/drivers/pinot/olap.go
closes https://github.com/rilldata/rill-private-issues/issues/540
1. For emitting events it only uses the size of .db files and excludes temporary tables.
2. For other checks like size limit it calculates size of all.
3. Cleaned up OLAP interface since `EstimateSize` is not relevant for other OLAP engines and only used internally in duckDB driver.
TODO : The background goroutine in `execWithLimits` does not work since `estimateSize` does not take into account the size of new file being written into. This is already an issue and should be fixed separately.
=> change duckdb estimated size calculations

web-common/src/components/forms/Switch.svelte, web-common/src/features/dashboards/time-controls/comparison-pill/ComparisonPill.svelte
=> adjust comparison pill disabled styles

runtime/drivers/olap.go, runtime/metricsview/astexpr.go, runtime/metricsview/astsql.go, runtime/pkg/metricssql/parser_test.go
DuckDB and Druid automatically cast operands to `LIKE` to a text type, but ClickHouse does not. This PR explicitly casts the operands for `LIKE` to a text type for ClickHouse queries.
This should enable dashboards to support search against non-text dimension data types such as dates, ints, etc.
=> Cast operands in `LIKE` and `ILIKE` filters to `TEXT` on ClickHouse

web-common/src/features/dashboards/dimension-table/DimensionDisplay.svelte, web-common/src/features/dashboards/dimension-table/DimensionHeader.svelte, web-common/src/features/dashboards/filters/dimension-filters/DimensionFilter.svelte, web-common/src/features/dashboards/selectors/index.ts
We disabled search for non-string like dimensions as we were using `LIKE %<search>%`. But it seems like it is not needed anymore. Reverting to allowing search for all dimension types.
=> fix: Enable search for all dimension column types

web-common/src/features/dashboards/time-dimension-details/TDDTable.svelte
There was regression in a previous PR where the dimension column values in TDD were formatted as measures if they were numbers. This PR adds a check to avoid that column.
=> fix: do not format numbers in the dimension column

web-admin/src/features/projects/status/ProjectParseErrors.svelte
When a reconciliation yields parse errors, the project parser's reconcile error is `encountered parse errors`. Rather than show this message in the UI, we show the parse errors. 
However, the project parser can report other important reconcile errors. This PR surfaces these reconcile errors in the UI.  
For example:
[Reported in Slack](https://rilldata.slack.com/archives/C02T907FEUB/p1723479548440139)
=> Project Status: show the project parser's reconcile error, if applicable

runtime/metricsview/executor_rewrite_approx_comparisons.go
`dimExpr` contains alias as well so it may refer to the other query dimension instead of the current query. For example if base query is a CTE then in the comparison query where clause it may use `t1.dim IN (select ... from base)`
Its strange when I tested I did not encounter this case.
=> use correctly aliased dim expr in comparison query

web-common/src/features/dashboards/pivot/pivot-export.ts
closes [5295](https://github.com/rilldata/rill/issues/5295)
https://github.com/user-attachments/assets/b9a12cfb-17d0-4e85-9a81-c6d34153c89c
=> Include comparison delta and percent for export data if enableComparison

cli/cmd/devtool/README.md, cli/cmd/devtool/start.go, package.json, web-local/package.json
Previously, both Rill Developer's UI and Rill Cloud's UI were developed on port 3000. This wasn't an issue when they were independent projects. However, now that Rill Developer is integrated with Rill Cloud, particularly for the UI-based deploy flow, it's beneficial to run development versions of both UIs simultaneously.
To resolve the port conflict, this PR:
- Moves Rill Developer UI to port 3001
- Maintains Rill Cloud UI on port 3000
This change allows for easier concurrent development and testing of both UIs.
=> Move Rill Developer's UI dev server to port 3001

web-common/src/features/project/ProjectDeployer.ts
Org name generated can be invalid if it contains invalid chars like `.` `+`. This mirrors the org name generation from cli by replacing invalid chars with `-`
=> fix: Invalid org name generation by mirroring org name generation from cli

admin/server/auth/handlers.go, cli/cmd/start/start.go, runtime/drivers/admin/repo.go, runtime/drivers/file/repo.go, runtime/drivers/repo.go
This PR refactors the project file listings limit checks to ensure consistent limits and skipping of ignored paths.
The refactor also fixes an issue where the project size check in `rill start` did not skip ignored paths due to a bug (missing `/` at the start of the checked path).
=> Refactor project size limit checks

cli/cmd/admin/ping.go, cli/cmd/auth/login.go, cli/cmd/auth/logout.go, cli/cmd/deploy/deploy.go, cli/cmd/devtool/switch-env.go, cli/cmd/org/org_test.go, cli/cmd/project/delete.go, cli/cmd/root.go, cli/cmd/service/service_test.go, cli/cmd/start/start.go, cli/cmd/sudo/user/assume.go, cli/cmd/sudo/user/open.go, cli/cmd/sudo/user/unassume.go, cli/cmd/user/user_test.go, cli/pkg/cmdutil/helper.go, cli/pkg/local/app.go, cli/pkg/local/server.go, cli/pkg/pkce/authenticator.go
This PR refactors the way the various admin service config (such as the access token, admin URL, current cloud project) is loaded throughout the local app and CLI.
Among other things, it fixes an issue where the access token used by the local APIs was not updated when the user ran `rill login`.
=> Refactor admin service config in local app and CLI

web-common/src/features/connectors/ConnectorEntry.svelte, web-common/src/features/connectors/ConnectorExplorer.svelte, web-common/src/features/connectors/connector-explorer-store.ts, web-common/src/features/connectors/olap/DatabaseEntry.svelte, web-common/src/features/connectors/olap/DatabaseSchemaEntry.svelte, web-common/src/features/entity-management/WatchResourcesClient.ts
This PR saves the state of the Connector Explorer in local storage under the key `connector-explorer-state`. Closes https://github.com/rilldata/rill/issues/5327.
For example, the state of this explorer...
... is persisted like:
```json
{
"showConnectors": true,
"expandedItems": {
"clickhouse": true,
"clickhouse|default": false,
"clickhouse|other": true,
"clickhouse|test_database": false
"duckdb": true,
"duckdb|main_db": true,
"duckdb|main_db|main": true,
}
}
```
=> Connectors: persist the state of the Connector Explorer to local storage

web-common/src/features/dashboards/config.ts, web-common/src/features/dashboards/leaderboard/Leaderboard.svelte, web-common/src/features/dashboards/time-series/MetricsTimeSeriesCharts.svelte
The gap between the big number and the measure charts was 28px contrary to 16px suggested in the mocks
=> fix: gap between big number and metrics chart

package.json, web-common/src/features/templates/kpi/KPITemplate.svelte
Use full container width and expand KPI charts to fill whitespace.
=> Expand KPI charts to fill container

web-common/src/features/dashboards/time-controls/super-pill/components/Comparison.svelte, web-common/src/features/dashboards/time-controls/time-control-store.ts
This PR updates the initial assignment of `selectedComparisonRange` so that a valid comparison, if one is available, is assigned by default
=> fix: assign default comparison

web-admin/src/components/table/ResourceHeader.svelte, web-admin/src/components/table/ResourceTableEmpty.svelte, web-admin/src/components/table/Table.svelte, web-admin/src/components/table/Toolbar.svelte, web-admin/src/features/alerts/listing/AlertsTable.svelte, web-admin/src/features/alerts/listing/AlertsTableCompositeCell.svelte, web-admin/src/features/alerts/listing/AlertsTableEmpty.svelte, web-admin/src/features/alerts/listing/AlertsTableHeader.svelte, web-admin/src/features/dashboards/listing/DashboardsTable.svelte, web-admin/src/features/dashboards/listing/DashboardsTableCompositeCell.svelte, web-admin/src/features/dashboards/listing/DashboardsTableHeader.svelte, web-admin/src/features/dashboards/listing/DashboardsTableToolbar.svelte, web-admin/src/features/scheduled-reports/listing/ReportsTable.svelte, web-admin/src/features/scheduled-reports/listing/ReportsTableCompositeCell.svelte, web-admin/src/features/scheduled-reports/listing/ReportsTableEmpty.svelte, web-admin/src/features/scheduled-reports/listing/ReportsTableHeader.svelte, web-admin/src/routes/[organization]/[project]/-/alerts/+page.svelte, web-admin/src/routes/[organization]/[project]/-/reports/+page.svelte
This PR makes the resource tables a little more readable by moving the search bar out of the header and by adding padding.
The PR also factors out `ResourceHeader` and `ResourceTableEmpty` components to remove redundant code.
Before:
After:
=> Nit: Make resource tables more readable

runtime/drivers/clickhouse/model_manager.go, runtime/drivers/clickhouse/olap.go, runtime/drivers/clickhouse/olap_test.go
Fixed `CreateTableAsSelect` on clickhouse cloud.
**NOTE** : Creating a view based on external systems can fail sometimes but the workaround will be to specify columns manually which is also expected to be set in most cases.
=> feat: create table and then insert while creating model in clickhouse

cli/cmd/devtool/start.go, package-lock.json, web-common/src/features/authentication/LocalAvatarButton.svelte, web-common/src/features/dashboards/workspace/DeployDashboardCTA.svelte, web-common/src/features/project/ProjectDeployer.ts
1. Fix `rill devtool start local` not adding `--allowed-origins`. Note that a new binary will be needed for this to work.
2. Fix login/logout not working when running in dev mode using `npm run dev`
3. During a deploy, redirect the user directly to auto0 page instead of `deploy page => GetUser, GetMetadata => auto0 page`
=> fix: Local developer experience improvements

web-common/src/lib/duckdb-data-types.ts, web-common/src/lib/formatters.ts
Fix for the below typescript error -
```
Cannot read properties of undefined (reading 'startsWith')
```
[Telemetry Dashboard](https://ui.rilldata.com/rilldata/internal-rill-cloud-metrics/rill_ui_telemetry?state=CgUKA1A0VxgFKg10b3RhbF9yZWNvcmRzMgVzdGFjazgASAFYAWAEag1Bc2lhL0NhbGN1dHRheAKAAQGYAf%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwGiAYEHGv4GCAgS%2BQYa9gYICRIHCgVzdGFjaxLoBhLlBhriBlR5cGVFcnJvcjogQ2Fubm90IHJlYWQgcHJvcGVydGllcyBvZiB1bmRlZmluZWQgKHJlYWRpbmcgJ3N0YXJ0c1dpdGgnKQogICAgYXQgUGUgKGh0dHBzOi8vdWkucmlsbGRhdGEuY29tL19hcHAvaW1tdXRhYmxlL2NodW5rcy9pbmRleC45ZDY4MWMxMi5qczoxOjQ4NTQzKQogICAgYXQgT2JqZWN0LnAgKGh0dHBzOi8vdWkucmlsbGRhdGEuY29tL19hcHAvaW1tdXRhYmxlL2NodW5rcy9pbmRleC45ZDY4MWMxMi5qczoxOjU3MTEwKQogICAgYXQgT2JqZWN0LnAgKGh0dHBzOi8vdWkucmlsbGRhdGEuY29tL19hcHAvaW1tdXRhYmxlL2NodW5rcy9pbmRleC45ZDY4M …
=> fix: safe guard variable to prevent typescript errors

web-common/src/features/dashboards/pivot/pivot-merge-filters.ts, web-common/src/features/dashboards/time-dimension-details/TimeDimensionDisplay.svelte
Fix
`Cannot read properties of undefined (reading 'rowCount')`
`Cannot read properties of undefined (reading 'subquery')`
[Dashboard Telemetry](https://ui.rilldata.com/rilldata/internal-rill-cloud-metrics/rill_ui_telemetry?state=CgYKBFAxNEQYBSIJCgdyaWxsLVBQKg10b3RhbF9yZWNvcmRzMgdtZXNzYWdlOABIAVgBYARqDUFzaWEvQ2FsY3V0dGF4AYABAZgB%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FAaIBlAEakQEICBKMARqJAQgJEgkKB21lc3NhZ2USPBI6GjhDYW5ub3QgcmVhZCBwcm9wZXJ0aWVzIG9mIHVuZGVmaW5lZCAocmVhZGluZyAnc3VicXVlcnknKRI8EjoaOENhbm5vdCByZWFkIHByb3BlcnRpZXMgb2YgdW5kZWZpbmVkIChyZWFkaW5nICdyb3dDb3VudCcpsAEA%2BAEAgAICigIHZGVmYXVsdA%3D%3D)
=> fix: type errors for unsafe access

cli/cmd/start/start.go, docs/docs/home/get-started.md, docs/docs/reference/cli/org/edit.md, docs/docs/reference/cli/project/edit.md, docs/docs/reference/cli/project/project.md, docs/docs/reference/cli/project/splits.md, docs/docs/reference/cli/start.md, docs/docs/reference/cli/usergroup/remove.md, docs/docs/reference/cli/usergroup/usergroup.md
Added under get-started where we mention start a new rill project as a note,
added the flag to references/cli/start.md
Based on Issue: https://github.com/rilldata/rill/pull/5365
and Slack: https://rilldata.slack.com/archives/C01UFNH4W3B/p1723481208803969?thread_ts=1723461905.169519&cid=C01UFNH4W3B
=> Added note on --allowed-origins flag

runtime/pkg/jsonval/jsonval.go, runtime/pkg/pbutil/pbutil.go
In Go, ClickHouse returns `DECIMAL` types as `string`s instead of `big`s when not explicitly scanned into a different data type. This PR casts those strings to `float64`s before returning them in the metrics APIs.
Note that this is a bad practice, but something we have done historically for DuckDB numbers because the frontend can't yet handle non-float numbers.
=> Runtime: Cast Clickhouse DECIMALs to floats in metrics APIs

web-admin/src/client/http-client.ts, web-admin/src/features/authentication/AuthRedirect.svelte, web-admin/src/features/authentication/AvatarButton.svelte, web-admin/src/features/authentication/SignIn.svelte, web-admin/src/features/authentication/checkUserAccess.ts, web-admin/src/features/errors/error-utils.ts, web-admin/src/features/organizations/active-org/OrganizationRedirect.svelte, web-admin/src/routes/-/auth/device/+page.svelte, web-admin/src/routes/-/github/connect/+page.svelte, web-admin/src/routes/-/github/connect/request/+page.svelte, web-admin/src/routes/-/github/connect/retry-auth/+page.svelte, web-admin/src/routes/-/github/connect/retry-install/+page.svelte
This PR implements the necessary frontend changes to support custom domains.
Namely, if it detects that it runs on a custom domain, it will use `/api` on the current host to contact the `admin` service instead of using the canonical `admin` service endpoint. The only exception to this rule is for the `/auth/login` and `/github/*` endpoints, which must always be called on the canonical `admin` service endpoint.
See further details in the backend PR: https://github.com/rilldata/rill/pull/5498.
Contributes to https://github.com/rilldata/rill/issues/5476.
=> Support custom domains in `web-admin`

admin/server/assets.go, web-admin/src/features/projects/github/ProjectGithubConnection.svelte
During github disconnect, we use user's token to currently github repo to push to archive. This is not necessary and we can instead use the installation token.
This PR also fixes an issue with incorrectly ignored paths.
=> fix: Do not mandate github login/installation for github disconnect for a project

web-common/src/components/navigation/breadcrumbs/BreadcrumbItem.svelte, web-common/src/components/navigation/breadcrumbs/utils.ts
When switching org/project using breadcrumbs it does not retain the sub route. We should retain the sub route if it does not contain a variable part.
=> feat: Retain non-variable sub route on breadcrumbs

web-admin/src/client/redirect-utils.ts, web-admin/src/features/authentication/AuthRedirect.svelte, web-admin/src/features/authentication/AvatarButton.svelte, web-admin/src/features/authentication/SignIn.svelte, web-admin/src/features/authentication/checkUserAccess.ts, web-admin/src/features/errors/error-utils.ts, web-admin/src/routes/-/auth/device/+page.svelte, web-admin/src/routes/-/github/connect/+page.svelte, web-admin/src/routes/-/github/connect/request/+page.svelte, web-admin/src/routes/-/github/connect/retry-auth/+page.svelte, web-admin/src/routes/-/github/connect/retry-install/+page.svelte, web-common/src/components/button/Button.svelte, web-common/src/components/calls-to-action/CTAButton.svelte, web-common/src/features/authentication/LocalAvatarButton.svelte
This is necessary to prevent Svelte from doing SPA routing when navigating to the /api/auth and /api/github paths on orgs with a custom domain configured. (When a custom domain is configured, the admin service is hosted on /api of the same domain, not a different host.)
=> Web: Use window.location or rel=external to navigate to /auth and /github

web-common/src/features/project/ProjectDeployer.ts
Deploy success event is fired asynchronously after a deploy succeeds. Since the page is redirected to project page on cloud the telemetry might not always fire. This adds an await to make sure the telemetry gets fired.
=> fix: deploy success possibly not firing in UI based deploy flow

web-common/src/components/date-picker/Month.svelte, web-common/src/features/dashboards/time-controls/super-pill/components/CalendarPlusDateInput.svelte
When in end date selection mode, selecting a date prior to the current start date will re-assign the start date instead of clearing the range (updating both dates). Days prior to the start date are now a lighter shade of gray and the "potential range" hover state has been updated.
When in start date selection, selecting a date after the end date has a new visual cue, though the behavior is unchanged.
=> tweak: invalid end date ux

web-common/src/features/custom-dashboards/Component.svelte
Fixes #5517
This PR removes local z-index from custom components and adds an explicit z-index for select.
=> fix: force z-index for select component 

runtime/drivers/olap.go, runtime/queries/metricsview_aggregation_test.go
`date_trunc('month', toTimeZone(now(), 'Asia/Kolkata'))` returns date (2024-08-30)
`date_trunc('month', toTimeZone(now(), 'Asia/Kolkata'))::TIMESTAMP` converts it into datetime with timezone set to server timezone (2024-08-30T00:00:00Z) which is not what was expected.
=> fix: DateTruncExpr with timezone gave wrong results for clickchouse

proto/rill/ui/v1/dashboard.proto, web-common/src/features/dashboards/proto-state/dashboard-url-state.spec.ts, web-common/src/features/dashboards/proto-state/fromProto.ts, web-common/src/features/dashboards/proto-state/proto.spec.ts, web-common/src/features/dashboards/proto-state/sparse-proto.spec.ts, web-common/src/features/dashboards/proto-state/toProto.ts, web-common/src/features/dashboards/show-hide-selectors.spec.ts, web-common/src/features/dashboards/stores/AdvancedMeasureCorrector.spec.ts, web-common/src/features/dashboards/stores/dashboard-store-defaults.ts, web-common/src/features/dashboards/stores/dashboard-stores.spec.ts, web-common/src/features/dashboards/stores/test-data/dashboard-stores-test-data.ts, web-common/src/features/dashboards/stores/test-data/dashboard-stores-test-mutations.ts, web-common/src/features/dashboards/time-controls/time-control-store.spec.ts
Currently in certain cases restoring the dashboard back to the default state doesnt match if the store was in default state.
This makes sure dashboard state has the correct fields after restoring. Also adds a bunch of tests around this to avoid regressions.
=> fix: inconsistencies with metrics view state when restored to a proto state

web-admin/src/features/alerts/metadata/AlertMetadata.svelte, web-admin/src/features/errors/error-utils.ts, web-common/src/runtime-client/is-runtime-query.ts, web-common/src/runtime-client/query-matcher.ts
For an Alert that has had its underlying Metrics View deleted, the Alert page now shows this icon & tooltip:
Closes https://github.com/rilldata/rill-private-issues/issues/626
=> Fix (Alerts): Handle a missing Metrics View on the Alert page

docs/docs/deploy/project-errors.md
This PR adds docs for the project error alerting feature introduced in https://github.com/rilldata/rill/pull/5525.
=> Docs for alerts on project errors

admin/admin.go, admin/database/database.go, admin/database/postgres/migrations/0043.sql, admin/database/postgres/postgres.go, admin/database/postgres/postgres_test.go, admin/provisioner/static_test.go, admin/server/admin_rbac_test.go, cli/cmd/admin/start.go, cli/pkg/mock/server.go, scripts/generate_enc_keyring/main.go
Fixes https://github.com/rilldata/rill-private-issues/issues/590
Before merging this, we will need to set following admin property in helm with secret in vault, also dev .env file should be updated, otherwise admin service will fail to start  -
```
RILL_ADMIN_DATABASE_ENCRYPTION_KEYRING='[{"key_id":"<id(can use numerical order for id starting from 1)>","key":"<32-bytes-base64-encoded-secret>"}]'
```
For key rotation, new key should be prepended to the array as the first key is used for encryption. New secret can be generated using `openssl rand -base64 32`
Included a utility to generate keyring - `go run scripts/generate_enc_keyring/main.go`. It accepts prepending to existing keyring with `go run scripts/generate_enc_keyring/main.go …
=> postgres column encryption for sensitive data

web-common/src/features/connectors/olap/TableMenuItems.svelte, web-common/src/features/connectors/olap/selectors.ts, web-common/src/features/entity-management/AddAssetButton.svelte, web-common/src/features/metrics-views/MetricsInspector.svelte, web-common/src/features/metrics-views/workspace/editor/Placeholder.svelte, web-common/src/features/workspaces/MetricsWorkspace.svelte
We only support modeling for certain OLAP engines. Previously, we determined whether or not to show a modeling feature by checking the project's _default_ OLAP engine. This check didn't work in projects with multiple OLAP engines – some might support modeling, some might not.
This PR now takes into account both the default OLAP engine and, if applicable, the particular asset's OLAP engine.
[Context in Slack](https://rilldata.slack.com/archives/C02T907FEUB/p1724943962557839)
=> Fix: Account for multi-OLAP paradigm when checking for OLAP modeling support

runtime/drivers/duckdb/transporter_sqlstore_to_duckDB.go
Fixes [this alert](https://rilldata.slack.com/archives/C05TXA7QSTY/p1725466090360839) which was a false positive.
=> Fix error log on context cancelled in SQLStore -> DuckDB transporter

web-common/src/features/editor/Codespace.svelte
This is likely not causing any issues, but, just to be sure, a small change so that the localContent store is only "gotten" once and the warning conditional passes only on null and not undefined or an empty string.
=> tweak: remote content warning conditional

web-common/src/features/dashboards/proto-state/fromProto.ts, web-common/src/features/dashboards/proto-state/toProto.ts
We only save pivot state if pivot page is active. This removes the option of saving pivot state and explore state at the same time.
Since active page has a separate field we can always save pivot state.
=> fix: pivot state being removed if active page is changed

runtime/drivers/azure/object_store.go, runtime/drivers/gcs/object_store.go, runtime/drivers/s3/object_store.go
For object stores we first try with provided credentials and then with no credentials (to check for public buckets).
The returned error should always be the first error which can give better hints about missing keys/incorrect keys etc.
=> return initial authentication error for object stores

admin/database/database.go, admin/database/errors.go, admin/database/postgres/postgres.go, admin/database/validate.go, admin/server/alerts.go, admin/server/bookmarks.go, admin/server/github.go, admin/server/magic_tokens.go, admin/server/organizations.go, admin/server/projects.go, admin/server/reports.go, admin/server/repos.go, admin/server/server.go, admin/server/service.go, admin/server/usergroups.go, admin/server/users.go
This PR:
- Adds utility functions to `admin/database` for checking validation errors
- Adds handling of the `admin/database` errors to the fallback error handler in the gRPC server
- Changes many error cases away from explicit `codes.Internal` errors to non-annotated errors that will be handled by the fallback handler
The PR is not exhaustive and there are still many error cases that retain explicit error handling, some of them for justifiable errors (like needing to return `codes.Internal` for an unexpected not-found error), others because the expected behavior is not entirely clear and I'm erroring on the side of caution.
This PR was motivated by [this](https://rilldata.slack.com/archives/C05TXA7QSTY/p1725530133665909) false positive alert.
=> Admin: Make error codes for database errors more consistent

runtime/compilers/rillv1/parse_alert.go, runtime/compilers/rillv1/parse_model.go, runtime/compilers/rillv1/parse_report.go, runtime/compilers/rillv1/parse_source.go, runtime/compilers/rillv1/parser.go, runtime/compilers/rillv1/parser_test.go
This PR changes the `refresh:` YAML clause to ignore the `refresh.cron:` and `refresh.every:` properties in development (i.e. when running under `rill start` on `localhost`) unless `refresh.run_in_dev: true` is explicitly set.
Closes https://github.com/rilldata/rill-private-issues/issues/654
=> Disable cron refreshes in dev (i.e. on localhost)

runtime/compilers/rillv1/template.go, runtime/compilers/rillv1/template_test.go, runtime/drivers/duckdb/config.go, runtime/drivers/duckdb/duckdb.go, scripts/embed_duckdb_ext/main.go
This PR adds support for configuring native secrets in DuckDB using `init_sql` in a `duckdb.yaml` connector file.
This enables ingesting data from S3/GCS/Azure from DuckDB *models* (note that this is not needed for DuckDB *sources* due to some legacy hacks in the sources implementation that predate DuckDB's support for native secrets).
**Example:** DuckDB connector configuration that configures DuckDB to use S3 credentials from `~/.aws` on local and from Rill env variables on cloud:
```yaml
type: connector
driver: duckdb
init_sql: >
CREATE OR REPLACE SECRET s3 (
TYPE S3,
KEY_ID '{{ .vars.connector.s3.aws_access_key_id }}',
SECRET '{{ .vars.connector.s3.aws_secret_access_key }}',
REGION 'eu-north-1'
)
dev:
init_sql: >
CREATE OR REPLACE SECRET s3 (TYPE S3, PROVIDER CREDENTIAL_CHAIN)
```
=> DuckDB: Support configuring native secrets in DuckDB

web-common/src/features/alerts/delivery-tab/snooze.ts
closes [#5582](https://github.com/rilldata/rill/issues/5582)
=> fix: update alert snooze label to match functionality

web-common/src/features/dashboards/pivot/pivot-export.ts
If an `alias` is provided, then it needs to be used in the `sort` clause.
Closes https://github.com/rilldata/rill/issues/5578
=> Fix (Pivot Export): Use dimension `alias` in `sort` clause

web-common/src/features/entity-management/file-artifact.ts, web-local/src/routes/(application)/files/[...file]/+page.ts
This is a quick fix to close https://github.com/rilldata/rill-private-issues/issues/629. However, we should really refactor this to explicitly state _supported_ file types rather than _unsupported_ file types.
=> Fix (File Explorer): Specify more unsupported file types

web-common/src/features/dashboards/proto-state/dashboard-url-state.ts
The `dashboard` parameter in the URL can have different casing than the `MetricsView` name. This PR updates one instance to ensure case-insensitive comparison between the two.
=> Fix (URL state): capitalization bug

web-admin/src/routes/[organization]/[project]/-/invite/+page.svelte
After inviting some users on the invite page it doesnt make sense to still call the button `Skip`. As per the requirements updating to `Continue`.
=> fix: button copy on invite page after inviting some users

web-common/src/features/dashboards/show-hide-selectors.ts, web-common/src/features/dashboards/stores/dashboard-stores.ts
Currently when metrics view query is refetched we remove leaderboard measure if it is hidden. This is also triggered when the page is refereshed. This is not the intended behaviour anymore.
We also change the leaderboard measure if it was hidden. This is also not needed anymore.
More context: https://rilldata.slack.com/archives/CTCJ58H3M/p1725602517787789?thread_ts=1725586991.771069&cid=CTCJ58H3M
=> fix: leaderboard measure reset on a refresh if it was hidden

web-common/src/features/templates/kpi/KPITemplate.svelte
Since we removed `bg-white` from the higher order component we enforce it on the KPI to ensure background.
=> fix: bg-white for KPI

web-admin/src/features/dashboards/listing/DashboardsTable.svelte
On the Project's Dashboard list page, the search box wasn't working when it included one or more Custom Dashboards.
=> Fix search for Custom Dashboards

web-admin/src/features/alerts/metadata/AlertMetadata.svelte, web-admin/src/routes/[organization]/[project]/-/alerts/[alert]/open/+page.svelte
Alerts can be created without a dashboard through a YAML file artifact. While we do not have mocks for this, we should atleast not crash the app.
- Redirects users to alert page for emails for such alerts.
- The section in alerts page stating dashboard is removed for such alerts.
=> fix: alerts without an associated dashboard

web-admin/src/features/embeds/CanvasDashboardEmbed.svelte, web-admin/src/routes/[organization]/[project]/-/dashboards/[dashboard]/+page.svelte, web-common/src/features/file-explorer/new-files.ts
Defaulting to 24 columns as it's divisable by both thirds and quarters. We could go 12 as well if 24 seems to finegrain.
=> fix: default to 24 columns

web-common/src/features/dashboards/dashboard-utils.ts
Closes https://github.com/rilldata/rill-private-issues/issues/608
Use `validPercentOfTotal` as source of truth to validate if measure is summable. Also maintain support for `sum` and `count` for legacy dashboards not having the key in their spec.
=> Use `validPercentOfTotal` as source of truth

web-common/src/features/canvas-components/ComponentsHeader.svelte
Hides the inspector button the components editor as it currently does not do anything.
=> fix: hide inspector from components view

cli/cmd/project/connect_github.go, cli/cmd/project/deploy.go
Updating upload and github flow to have error handling when project already exists. Applies to `rill deploy` as well.
- During `rill project deploy` if project already deployed with github show an error.
- During `rill project connect-github` if project already deployed with github show an error and direct user to cloud UI to change the github.
=> fix: existing projects during `rill deploy`

web-common/src/features/canvas-dashboards/CanvasDashboardEmbed.svelte, web-common/src/features/canvas-dashboards/CanvasDashboardPreview.svelte, web-common/src/features/canvas-dashboards/DashboardWrapper.svelte
=> canvas dashboards: set max width

web-common/src/features/entity-management/ResourceWatcher.svelte, web-common/src/lib/throttler.ts, web-common/src/runtime-client/watch-request-client.ts
This PR adds improved idle detection timeout that closes the resource watchers (and displays a small banner) after two minutes of inactivity (keydown or mouse click). It also adds a priority inactivity detection that closes the watchers after 30 seconds if the tab's visibility has changed.
There are a few different scenarios that we can detect and set timeouts for:
1. The tab is no longer visible
2. A blur event has happened on the page, which does not necessarily mean it's no longer visible
3. No mouse click events
4. No keydown events
5. No mouse move events
6. IdleDetection API, though this is supported only in Chrome and in HTTPS contexts
=> improved idle detection

cli/pkg/cmdutil/archive.go, runtime/connections.go, runtime/drivers/admin/repo.go, runtime/drivers/file/file_store.go, runtime/drivers/file/repo.go, runtime/drivers/repo.go, runtime/reconcilers/model.go, runtime/reconcilers/source.go
Avoids a race condition where e.g. a `local_file` source may try to read a file in the Git repo before it's cloned.
=> Fix: Await repository clone before resolving the repository root path

web-common/src/features/dashboards/dimension-table/dimension-table-export-utils.ts
After our recent fix to allow hidden measures in leaderboard measure, export breaks in this scenario. While the sort column is selected as the hidden measure the list of measures is not updated.
This PR adds the selected measure even if it is hidden.
=> fix: selected measure not added to dimension table export

web-common/src/features/canvas-dashboards/Component.svelte, web-common/src/features/templates/TemplateRenderer.svelte, web-common/src/features/templates/select/Select.svelte
Support variable reference in filters of canvas components.
Can be tested with
```
kind: component
input:
- name: selection
type: string
value: Instacart
kpi:
metrics_view: Bids_Sample_Dash
time_range: P7D
filter: advertiser_name='{{ .args.selection }}'
measure: measure_2
comparison_range: P3D
```
=> feat: Enable variables in component filter

web-common/src/features/file-explorer/new-files.ts
Adds a background color to the first markdown component that is created as part of the default scaffolding.
=> nit: component background in scaffolding

web-common/src/components/forms/Select.svelte, web-common/src/features/canvas/Component.svelte, web-common/src/features/templates/select/Select.svelte
Adjusts title spacing and weights.
Adds white background to the select component.
=> fix: select bg and titles

web-common/src/features/dashboards/big-number/MeasureBigNumber.svelte
Fix #5522
https://www.notion.so/rilldata/KPI-Shouldn-t-react-to-on-hover-b68ff1927ba04036b01d509a750f1af3
https://github.com/user-attachments/assets/a1bbc174-f0b2-460e-8579-140623aaf0f3
=> Disable toggling for expanded big number

web-common/src/features/dashboards/filters/FilterChipsReadOnly.svelte
Dimensions do not necessarily always have a `column` property and may sometimes, instead, have `expression`. I believe we could safely remove this conditional entirely, though it may have been included for a reason I'm not aware of.
=> broaden conditional for readonly filter chips

runtime/drivers/snowflake/snowflake.go
Seems like previously it was loaded "by accident" through an unrelated import of the package.
=> Fix: Explicitly load the Snowflake `database/sql` driver

web-admin/src/features/embeds/TopNavigationBarEmbed.svelte, web-common/src/components/navigation/breadcrumbs/BreadcrumbItem.svelte
Addresses this [bug report in Slack](https://rilldata.slack.com/archives/CTZ8XBQ85/p1727874138762379).
(As an aside, at some point, we should merge the `TopNavigationBarEmbed` component into `TopNavigationBar`.)
=> Fix two casing bugs in breadcrumbs

runtime/drivers/azure/object_store.go, runtime/drivers/gcs/object_store.go, runtime/drivers/s3/object_store.go
Fixes the issue raised by [this alert](https://rilldata.slack.com/archives/C05TXA7QSTY/p1727868844887949).
=> Azure: Fix panic from nil iterator being returned without an error

web-common/src/features/canvas/AddComponentMenu.svelte, web-common/src/features/connectors/olap/TableMenuItems.svelte, web-common/src/features/connectors/olap/TableWorkspaceHeader.svelte, web-common/src/features/entity-management/AddAssetButton.svelte, web-common/src/features/file-explorer/new-files.ts, web-common/src/features/metrics-views/GoToDashboardButton.svelte, web-common/src/features/metrics-views/ai-generation/generateMetricsView.ts, web-common/src/features/models/navigation/ModelMenuItems.svelte, web-common/src/features/models/workspace/CreateDashboardButton.svelte, web-common/src/features/sources/modal/SourceImportedModal.svelte, web-common/src/features/sources/navigation/SourceMenuItems.svelte, web-local/src/routes/(application)/+layout.svelte, web-local/src/routes/+layout.svelte
"Generate dashboard" is a new option for Sources & Models. It does the following:
1. Creates a Metrics View file (with AI)
2. Creates a basic Explore file that references the new Metrics View
3. Navigates to the Explore Preview
This "Generate dashboard" action now is available in:
- The modal that pops up when a new Source has been ingested
- A Source's context menu in the File Explorer
- A Model's context menu in the File Explorer
- A Table's context menu in the Connector Explorer
Additionally, this PR removes "Generate chart" from the Source & Model menu items. "Generate chart" should be exclusively offered on top of Metrics Views.
=> Rill Developer: Add option to generate an Explore Dashboard from Sources, Models, and Tables

web-common/src/components/forms/Input.svelte, web-common/src/features/alerts/criteria-tab/CriteriaForm.svelte
Fix https://www.notion.so/rilldata/v0-50-0-QA-114ba33c8f5780bd897ecb99547ed623#114ba33c8f5780c29dbedd81e2cf7f8e
=> Fix criteria form

web-common/src/features/entity-management/ResourceWatcher.svelte, web-common/src/runtime-client/watch-request-client.ts
When an example project unpacks, the resource streaming endpoint closes. The application resource watcher, however, was not successfully reconnecting because the conditional check for the closed state (which ensures we don't try to reconnect when it has been intentionally closed) was not accessing the underlying store value.
=> fix: reconnect resource watcher on project unpack

web-common/src/components/forms/Input.svelte, web-common/src/features/visual-metrics-editing/MetricsTable.svelte, web-common/src/features/visual-metrics-editing/MetricsTableRow.svelte, web-common/src/features/visual-metrics-editing/lib.ts, web-common/src/features/workspaces/MetricsWorkspace.svelte, web-common/src/features/workspaces/VisualMetrics.svelte
- Sets placeholders for property dropdowns
- Sets minimum column size for `Name` and `Label`
- Updates the way inherited dimension names are pulled in and displayed
- Adds fallback when there are no valid time series columns in dataset
- Sets "humanize" as the default format_preset when adding a new measure
=> visual metrics uxqa fixes

web-common/src/features/metrics-views/ai-generation/generateMetricsView.ts
- Wait for the Metrics View resource before proceeding with generating an Explore
- If the resultant Explore file has an error, navigate to the Explore editor rather than the Explore preview
=> Fix (Autogenerate Explore): ensure Metrics View exists before proceeding with Explore generation

web-admin/src/features/embeds/TopNavigationBarEmbed.svelte, web-admin/src/routes/-/embed/+page.svelte, web-common/src/features/dashboards/selectors.ts
This PR solves two bugs for embeds with `navigation: true`:
1. List Explores not Metrics Views in the breadcrumb's dropdown menu
2. Don't show the `UnsupportedKind` component below the table of dashboards
=> Fix (Embeds): two navigation bugs due to the MetricsView-Explore split

cli/cmd/project/status.go, cli/cmd/sudo/project/search.go
If the `ProjectParser` resource itself has a reconcile error (such as if it fails to pull from Github), it was not being reported in `rill project status` and `rill sudo project search --status`.
=> CLI: Report parser reconcile errors in the status commands

web-common/src/features/entity-management/AddAssetButton.svelte
- Added dividers between sections
- "Metrics" -> "Metrics view"
- Fixed capitalization
- Moved "Component" ahead of "Canvas dashboard"
=> Nits: Touch-up the "Add" button's menu

web-common/src/components/editor/line-status/highlighter.ts, web-common/src/features/project/deploy-errors.ts
Fixes the below warnings emitted from Vite's build:
=> Fix Vite build warnings

web-common/src/features/entity-management/infer-resource-kind.ts, web-common/src/features/explores/ExploreEditor.svelte, web-common/src/features/workspaces/ExploreWorkspace.svelte
Editing an explore should reset the preview state to experience any change made. We were resetting using the explore name inferred from file path. If the explore contained an explicit name then it would fail to reset.
=> fix: explore state on rill developer not reset with explicit name on edit

web-common/src/features/canvas-components/ComponentsHeader.svelte, web-common/src/features/dashboards/granular-access-policies/useMockUsers.ts, web-common/src/features/editor/FileWorkspaceHeader.svelte, web-common/src/features/entity-management/RenameAssetModal.svelte, web-common/src/features/entity-management/file-artifact.ts, web-common/src/features/entity-management/file-path-utils.ts, web-common/src/features/entity-management/ui-actions.ts, web-common/src/features/file-explorer/FileExplorer.svelte, web-common/src/features/file-explorer/nav-entry-drag-drop-store.ts, web-local/tests/utils/sourceHelpers.ts
Previously, client-side, we were preventing files from being re-named to the same name as any other file in the project. Now, we merely prevent files from being re-named to the same name as another file in the same directory.
Addresses [this UXQA item](https://www.notion.so/rilldata/v0-50-0-QA-114ba33c8f5780bd897ecb99547ed623?pvs=4#119ba33c8f5780b082aafc64283468e3)
=> File Explorer: Remove client-side file rename constraint

web-common/src/features/file-explorer/new-files.ts, web-local/tests/explores/explores.spec.ts, web-local/tests/utils/dataSpecifcHelpers.ts, web-local/tests/utils/exploreHelpers.ts
By default, place Explore and Canvas files in `/dashboards`, rather than `/explore-dashboards` and `/canvas-dashboards` respectively.
=> Generate both Explore and Canvas files in `/dashboards`

web-common/src/features/dashboards/pivot/PivotTable.svelte
In absence of column dimensions, the total columns are the only columns present. In this case we do not want to bold the numbers.
=> fix: do not bold totals column without col dimensions

web-common/src/features/entity-management/file-artifact.ts, web-common/src/features/entity-management/file-artifacts.ts
A file specifying a legacy Metrics View generates 2 resources: a Metrics View and an Explore. However, the `FileArtifact` class (which impacts much client-side code) makes the assumption that a file is associated with 0 or 1 resource. 
In the `FileArtifact` class, for legacy Metrics View files, we've added a hack so that we ignore the generated Explore resource.
The original hack wrongly ignored the Explore resource for Explore files placed in the `/dashboards` directory.  (Because we previously assumed that any file placed in the `/dashboards` directory was a legacy Metrics View.)
The new hack identifies when an Explore resource is associated with a legacy Metrics View by checking to see if the file is already associated with a Metrics View. This should work because, for legacy Metrics …
=> Fix hack for legacy Metrics Views

web-common/src/features/dashboards/pivot/PivotTable.svelte, web-common/src/features/dashboards/pivot/pivot-column-width-utils.ts
Use data values along with label to estimate column width for measure columns in the pivot table.
Before
After
=> feat: estimate measure column width for pivot

web-common/src/features/dashboards/workspace/DeployProjectCTA.svelte, web-common/src/features/metrics-views/GoToDashboardButton.svelte, web-common/src/features/models/workspace/CreateDashboardButton.svelte, web-common/src/features/sources/workspace/SourceCTAs.svelte, web-common/src/features/workspaces/SourceWorkspace.svelte
Prevents collision of primary buttons in both the application and asset level headers. Also adds a dynamic Create/GoTo button for sources that matches similar buttons in other workspaces.
Consolidation of these dropdowns will come in a follow up PR.
=> resolve primary button collision

web-common/src/features/entity-management/entity-mappers.ts, web-common/src/features/entity-management/file-artifact.ts, web-common/src/features/visual-metrics-editing/lib.ts, web-common/src/features/workspaces/VisualMetrics.svelte
- We cannot assume that files in the `dashboards` folder are of type MetricsView
- If a resource kind has been previously determined, do not overwrite that when it can no longer be inferred
- Adds a check to the `VisualMetrics` surface to ensure the YAML items in a sequence are of the map type
=> fix: inferred resource behavior

runtime/server/generate_metrics_view.go
- Changes generated metrics views to use `model:` instead of `table:` when referencing pre-existing tables (even if they are not Rill models with matching YAML files).
- Prevents measure names from colliding with column names by appending a unique prefix:
- For AI-generated measure names, it appends `_measure` if there's a collision 
- For the non-AI measure names, which are always sums, it appends `_sum`
=> Metrics view generation: Use `model:` for pre-existing tables and prevent measure names that match a column name

web-common/src/components/button/ContextButton.svelte, web-common/src/features/connectors/ConnectorEntry.svelte, web-common/src/features/connectors/ConnectorExplorer.svelte, web-common/src/features/connectors/olap/TableEntry.svelte, web-common/src/features/connectors/olap/TableSchema.svelte, web-common/src/layout/config.ts, web-common/src/layout/navigation/Footer.svelte, web-common/src/layout/navigation/Navigation.svelte, web-common/src/layout/navigation/SurfaceControlButton.svelte, web-local/tests/file-explorer.spec.ts
- Sets both a smaller min and max width for the Navigation sidebar
- Adds VSCode-like key bindings for toggling the sidebar
- Changes the styling of the context menu trigger so that file names show a few more characters
- Changes the sizing behavior of the Connectors panel to better match similar elements in VSCode
- Removes troublesome(!) tooltip from SurfaceControlButton
- Changes the click target for TableEntry to match other similar UI elements
- Updates a few styles to better match Figma
- Changes Connectors panel caret to match other elements
=> navigation tweaks

web-common/src/features/connectors/code-utils.ts, web-common/src/features/sources/modal/AddDataForm.svelte, web-common/src/features/sources/modal/submitAddDataForm.ts, web-common/src/features/sources/modal/yupSchemas.ts, web-common/src/features/sources/sourceUtils.ts
This PR includes a collection of fixes for the OLAP connector forms:
- Ensures `port` isn't initialized to 0.
- Ensures Yup validation doesn't reject the `port` for being a string, not a number. (It's a string because we're using an `<input />` element with `type: string`, intentionally to avoid the `type: number` widget.)
- Removes fields with `undefined` values from the generated YAML.
- Correctly navigates to the new connector file when the connector `name` != `driver`.
=> Fix OLAP connector form

web-common/src/features/dashboards/pivot/PivotSidebar.svelte
Hide all grains which are smaller than the `smallest_time_grain` from the options in the pivot sidebar.
=> fix: hide grains smaller than smallest_time_grain from pivot sidebar

admin/admin.go, admin/worker/run_autoscaler.go, admin/worker/run_autoscaler_test.go, cli/cmd/admin/start.go
Introduce a new environment variable, `ScaleDownConstraints`, to allow conditional autoscaling down of Rill projects based on slot usage.
**Behavior:**
- **`ScaleDownConstraints == -1`**
- All scale-down operations are enabled (no constraints).
- **`ScaleDownConstraints == 0`**
- All scale-down operations are disabled.
- **`ScaleDownConstraints > 0`**
- Scale-down is allowed only for Rill projects where the current number of slots (`originSlots`) is less than or equal to `ScaleDownConstraints`.
Resolve Issue: [rilldata/rill-helm-charts#161](https://github.com/rilldata/rill-helm-charts/issues/161)
=> Introduce ScaleDownConstraints Environment Variable for Conditional Autoscaling Down

web-common/src/features/dashboards/filters/measure-filters/MeasureFilterBody.svelte
The short label for measure filter was not showing the correct symbol.
Before
After
=> fix: measure filter short labels

web-common/src/components/forms/InputLabel.svelte, web-common/src/features/visual-metrics-editing/Sidebar.svelte, web-common/src/features/visual-metrics-editing/lib.ts
- Prevents the Label input in the Sidebar from being filled with a value inferred from the `name` field.
- Narrows the max width for the hint tooltip
- Updates Label input tooltip language
=> fix: don't fill inferred label in visual metrics sidebar

admin/client/client.go, runtime/client/client.go
This PR adds exponential backoff retries for admin and runtime gRPC requests that fail with an "unavailable" status code.
This will hopefully mitigate occasional errors such as this recent example:
```
repo handshake failed: rpc error: code = Unavailable desc = unexpected HTTP status code received ...
```
Closes https://github.com/rilldata/rill-private-issues/issues/787
=> Retry when the admin or runtime service is unavailable

runtime/pkg/conncache/conncache.go, runtime/pkg/conncache/conncache_test.go
Imagine the following scenario:
1. We start acquiring a connection
2. We cancel the acquire before the connection finishes opening
- We don't cancel the opening connection itself since others may be waiting for it (and is also supposed to stay open in the connection cache)
3. We force evict the connection while it is still opening
- Since we can't close an opening connection, this marks the connection to be immediately closed once it has finished opening
4. We try to acquire the connection again while it is still opening and hasn't yet been evicted
The current connection cache will fail step 4 with `conncache: connection was immediately closed after being opened`. This happened recently in an issue where an instance was edited (triggering a controller restart and connection eviction) …
=> Connection cache: Support acquiring a connection that was force evicted while opening while it is still opening 

web-common/src/components/card/Card.svelte, web-common/src/features/welcome/ProjectCards.svelte, web-common/src/runtime-client/watch-request-client.ts
To address some concerns related to example project unpacking in certain situations, this PR makes the following changes:
- Reduce watch-request-client priority disconnect (which applies when the tab is put in the background) to 20 seconds
- Prevent multiple clicks on the same example project
- If `?redirect=true` is still in the URL after 5 seconds, reload the page
=> tweak redirect flow

web-common/src/components/data-types/Base.svelte, web-common/src/components/data-types/FormattedDataType.svelte, web-common/src/components/data-types/Interval.svelte, web-common/src/components/data-types/MeasureChange.svelte, web-common/src/components/data-types/Number.svelte, web-common/src/components/data-types/PercentageChange.svelte, web-common/src/components/data-types/Timestamp.svelte, web-common/src/components/data-types/Varchar.svelte, web-common/src/features/column-profile/column-types/details/TopK.svelte, web-common/src/lib/duckdb-data-types.ts
Add stronger type checks for formatting functions. Also use optional chaining to avoid fatal errors
https://rilldata.slack.com/archives/C01ADAYF1PZ/p1730159365544349
=> fix: stricter type checking for duck formating functions

runtime/drivers/slack/notifier.go
Splitting the fix from #6003 since that is blocked due to some design.
=> fix: broken template for slack reports notifier

web-admin/src/features/billing/banner/BillingBannerManagerForAdmins.svelte, web-common/src/components/banner/Banner.svelte
=> Banner nit

runtime/drivers/olap.go
Addresses the problem reported [here](https://rilldata.slack.com/archives/C02T907FEUB/p1730209589645439?thread_ts=1730209125.774299&cid=C02T907FEUB)
=> Fix ClickHouse timestamp format for comparison offsets

web-common/src/components/forms/FieldSwitcher.svelte, web-common/src/components/forms/Input.svelte, web-common/src/components/forms/InputLabel.svelte
Creates a new `FieldSwitcher` component that can be used outside of the `Input` component context and makes a few styling tweaks.
=> chore: input tweaks and FieldSwitcher component

admin/server/projects.go
There is middleware that returns context errors with the appropriate status codes, falling back to the internal error code for unknown errors. By returning errors directly instead of coercing them to strings, the middleware is able to handle them correctly.
This issue is prevalent across the code base, this PR does not tackle all instances of it, but it's a step in the right direction.
=> Remove internal status from ctx cancelled errors

web-common/src/features/dashboards/pivot/PivotExpandableCell.svelte
=> fix: prevent opening data viewer when pivot row is expanded

web-common/src/components/data-graphic/actions/scrub-action-factory.ts, web-common/src/features/file-explorer/nav-entry-drag-drop-store.ts
Remove calls of `preventDefault` on listeners scoped to the window object.
=> fix: remove global preventDefault calls

web-common/src/components/color-picker/ColorInput.svelte, web-common/src/components/color-picker/ColorSlider.svelte
Adds color picker components, but does not use them
=> feat: add color picker

runtime/health.go
closes https://github.com/rilldata/rill-private-issues/issues/877
=> In healthcheck, skip time_range_query for metrics views with no time dimension

web-common/src/features/dashboards/pivot/pivot-column-definition.ts
The loading cell was being formatted as time as such momentarily flashing values such as `NaN` or `0NaN`. This PR prevents formatting until we have a defined value
=> fix: time formating in pivot rows while loading

.github/workflows/go-test.yml, runtime/resolvers/testdata/metrics_comparisons.yaml
Adds tests for comparison metrics queries that have the time dimension as a dimension. Previously this was only tested for DuckDB, this PR adds resolver tests for it for all of DuckDB, Druid and ClickHouse.
This PR uses the new resolver test files support, which you can find more details about here: https://github.com/rilldata/rill/blob/main/runtime/resolvers/testdata/README.md
The tests here are not comprehensive for all comparison features, we'll be migrating and adding tests gradually. This PR addresses the test request here: https://github.com/rilldata/rill/pull/6004.
Currently the Druid test is failing, more details here: https://rilldata.slack.com/archives/CTCJ58H3M/p1730730758436969
=> Tests for time dimension comparisons for ClickHouse and Druid

README.md
Hello Rill team,
I'm the maintainer of [Anteon](https://github.com/getanteon/anteon). We have created Gurubase.io with the mission of building a centralized, open-source tool-focused knowledge base. Essentially, each "guru" is equipped with custom knowledge to answer user questions based on collected data related to that tool.
I wanted to update you that I've manually added the [Rill Guru](https://gurubase.io/g/rill) to Gurubase. Rill Guru uses the data from this repo and data from the [docs](https://docs.rilldata.com/) to answer questions by leveraging the LLM.
In this PR, I showcased the "Rill Guru" on the README. Please let me know your thoughts on this contribution.
Additionally, if you want me to disable Rill Guru in Gurubase, just let me know that's totally fine.
=> Introducing Rill Guru on Gurubase

admin/billing.go, admin/billing/README.MD, admin/billing/orb.go, admin/jobs/river/biller_event_handlers.go, admin/jobs/river/org_jobs.go, admin/jobs/river/subscription_handlers.go, admin/server/billing.go, runtime/pkg/email/email.go
- Send plan update email on plan change. cc @ericpgreen2 
- Product does not want random plan names like `Legacy MMX plan` etc. to be displayed so logic for display name as per @ericokuma requirements.
@AdityaHegde plan display name logic can be removed from frontend and rather use the `display_name` field directly on the Plan object.
=> send plan update email, plan display name logic

web-common/src/features/workspaces/MetricsWorkspace.svelte
Preview button and other actions use name from file name. We should instead use resource name similar to ExploreWorkspace.
=> fix: preview for old metrics with explicit name

web-common/src/components/editor/line-status/line-status-gutter.ts
We added a catch all error with line=-1. But our line number gutter that displays errors does not handle this. Updating the gutter to ignore such errors to avoid a crash in the plugin.
=> fix: line numbers being removed when there is an error in metrics/explore

web-common/src/features/themes/actions.ts
Properly sets the required CSS variables for setting primary and secondary theme colors across the dashboard. Note the change to pill, tabs and thumb element on the time series chart.
=> fix: theme color assignment

runtime/testruntime/connectors.go, runtime/testruntime/reconcile.go, runtime/testruntime/testruntime.go, runtime/validate.go, runtime/validate_test.go
This PR adds validation that prevents a ClickHouse-backed metrics view from having dimension names that collide with an underlying column name when and only when the dimension has a custom `expression:` or `unnest: true`. This is necessary because ClickHouse eagerly substitutes aliases, and without this validation, it leads to broken references to the underlying column in other dimensions/measures and where clauses.
This PR essentially implements the same constraint for dimensions as this PR added for measures: https://github.com/rilldata/rill/issues/5618. See it for details.
=> Prevent dimension names that match column names on ClickHouse if the dimension has a complex expression

package-lock.json, web-admin/src/client/utils.ts, web-admin/src/features/billing/Payment.svelte, web-admin/src/features/billing/plans/CancelledTeamPlan.svelte, web-admin/src/features/billing/plans/EnterprisePlan.svelte, web-admin/src/features/billing/plans/POCPlan.svelte, web-admin/src/features/billing/plans/Plan.svelte, web-admin/src/features/billing/plans/PlanQuotas.svelte, web-admin/src/features/billing/plans/TeamPlan.svelte, web-admin/src/features/billing/plans/TrialPlan.svelte, web-admin/src/features/billing/plans/utils.ts, web-admin/src/features/errors/error-utils.ts, web-admin/src/features/navigation/TopNavigationBar.svelte, web-common/src/features/project/ProjectDeployer.ts
=> fix(billing): Handle errored out metrics project request

web-common/src/features/dashboards/pivot/pivot-export.ts
We have a safeguard for dashboards without timeseries for every location except pivot. This PR doesnt add support for reports without timeseries but makes sure app doesnt crash.
=> fix: scheduled report creation in pivot for dashboards without timeseries

web-common/src/features/canvas-components/ComponentsHeader.svelte, web-common/src/features/editor/FileWorkspaceHeader.svelte, web-common/src/features/entity-management/file-selectors.ts, web-common/src/features/entity-management/ui-actions.ts, web-common/src/features/workspaces/CanvasDashboardWorkspace.svelte, web-common/src/features/workspaces/ExploreWorkspace.svelte, web-common/src/features/workspaces/MetricsWorkspace.svelte, web-common/src/features/workspaces/ModelWorkspace.svelte, web-common/src/features/workspaces/SourceWorkspace.svelte
Currently, when a user tries to rename a file to `new_name`, we check to see if any like resources (a Model, Metrics View, etc.) named `new_name` already exist. If so, we reject the file name change. One problem with this logic is that it prevents a file rename from `model.sql` to `model.yaml`.
This PR changes the logic so that we reject name changes only if the file name already exists in the given directory. This behavior matches that of a typical code editor.
Closes https://github.com/rilldata/rill/issues/5961
=> Fix: file renames

web-common/src/features/exports/ExportMenu.svelte
When the dashboard has no timestamp column configured reports dont work well. We should hide the button since the dialog is not opened anyway.
=> fix: Hide scheduled report button for dashboards with no timestamp column

cli/cmd/devtool/data/cloud-deps.docker-compose.yml
Mounting with ro converts file to directory. 
Could be a docker bug but I think`ro` indicates that host path is to be mounted as a directory.
=> fix: devtool start fails with config is a directory error

web-common/src/features/dashboards/dashboard-utils.ts, web-common/src/features/dashboards/leaderboard/Leaderboard.svelte, web-common/src/features/dashboards/leaderboard/LeaderboardRow.svelte, web-common/src/features/dashboards/leaderboard/leaderboard-utils.ts
closes #5282
For URI dimensions we need to add a measure to get the final value after templating is done. This PR replaces the current implementation of replacing the template in frontend to backend.
=> fix: templated uri dimension by making a request

admin/github.go
It seems `html_url` is not guaranteed to be present in all uninstall payloads so we rely on `fullName` to generate one.
The repository name can only contain ASCII letters, digits, and the characters ., -, and _.
=> fix: fix panic in github app uninstall flow

admin/database/postgres/migrations/0053.sql, admin/database/postgres/postgres.go
Our top navigation bar uses lower case resource name so if a bookmark was created with original case and navigated to using top bar the older bookmarks were not found anymore.
Making the bookmark query case insensitive since resource name is already case insensitive in our system.
=> fix: bookmark query by doing a case insensitive query

cli/cmd/project/refresh.go
Fixes an issue reported in [Slack](https://rilldata.slack.com/archives/CTZ8XBQ85/p1732007768377819).
=> Fix: Exclude inherited flags when checking if `rill project refresh` should default to `--all`

web-admin/src/features/billing/issues/getMessageForCancelledIssue.ts, web-admin/src/features/billing/plans/CancelledTeamPlan.svelte, web-admin/src/features/billing/plans/TeamPlan.svelte, web-admin/src/features/billing/plans/TrialPlan.svelte, web-admin/src/features/organizations/settings/OrgNameSettings.svelte, web-admin/src/routes/[organization]/-/upgrade-callback/+page.svelte, web-common/src/components/forms/Input.svelte, web-common/src/features/project/DeployError.svelte, web-common/src/lib/time/ranges/iso-ranges.ts, web-local/src/routes/(misc)/deploy/+page.svelte
=> fix: billing UI minor issues

runtime/drivers/duckdb/olap.go
A concurrent goroutine can start creating table which can make `os.RemoveAll` fail.
=> fix : remove table directory while holding tx lock

runtime/server/generate_metrics_view.go
We are generating metrics with additional spaces. Also `name` is missing in dimensioins.
```
version: 1
type: metrics_view
display_name: Ad Bids
model: ad_bids
timeseries: timestamp
dimensions:
- 
display_name: Publisher
column: publisher
- 
display_name: Domain
column: domain
measures:
- name: total_records
display_name: Total records
expression: COUNT(*)
description: ""
format_preset: humanize
- name: bid_price_sum
display_name: Sum of Bid Price
expression: SUM(bid_price)
description: ""
format_preset: humanize
```
Removing the new line before display_name and adding after type instead.
After,
```
version: 1
type: metrics_view 
display_name: Ad Bids
model: ad_bids
timeseries: timestamp
dimensions:
- name: publisher
display_name: Publisher
column: publisher
- name: domain
display_name: …
```
=> fix: autogenerate metrics indentation

web-admin/src/features/public-urls/CreatePublicURLForm.svelte, web-common/src/lib/actions/copy-to-clipboard.ts
Fix part of https://github.com/rilldata/rill-private-issues/issues/920.
Safari doesn't allow async clipboard copy unless it's directly triggered by a user interaction. Split the CTA into two separate actions: one for creation and another for copying to the clipboard.
=> Create public url and offer copy to clipboard cta

web-common/src/features/dashboards/dimension-table/DimensionDisplay.svelte, web-common/src/features/dashboards/leaderboard/Leaderboard.svelte, web-common/src/features/dashboards/leaderboard/leaderboard-utils.ts, web-common/src/features/dashboards/time-controls/comparison-pill/ComparisonPill.svelte
- Adjusts the `getSort` function to handle situations where the `leaderboardSortType` is not compatible with time comparison state
- When toggling timeComparison, reset the `leaderboardSortType` if incompatible with new state
=> fix: leaderboard column sorting behavior

web-admin/src/features/public-urls/DashboardPublicURLStateProvider.svelte, web-admin/src/routes/[organization]/[project]/-/share/[token]/+page.svelte
[Fixes this bug reported in Slack](https://rilldata.slack.com/archives/C01A9DYP013/p1732200296464789). Our URL state synchronization logic was mistakenly overwriting the `state` embedded in a Magic Auth Token.
This is a temporary fix that mirrors code from the Bookmarks feature. The coming [human-readable-state PR](https://github.com/rilldata/rill/pull/5675) will properly refactor how we initialize dashboard state.
=> Fix (Public URLs): state initialization

web-admin/src/features/organizations/OrganizationHero.svelte, web-admin/src/features/projects/ProjectCards.svelte, web-admin/src/routes/[organization]/+page.svelte
This CTA isn't needed now that we have a dedicated Users tab.
Before:
After:
=> Organizations: remove old CTA to add users via CLI

admin/server/billing.go
This prevents changing the case of name in case its changed while running request
=> use actual org name instead of req org name

admin/admin.go, admin/provisioner/clickhousestatic/provisioner.go, admin/provisioner/clickhousestatic/provisioner_test.go, admin/provisioner/kubernetes/kubernetes.go, admin/provisioner/provisioner.go, admin/provisioner/resources.go, admin/provisioner/static/static.go, cli/cmd/admin/start.go
This PR introduces a new provisioner resource for ClickHouse and implements a provisioner named `clickhouse-static`, which provisions ClickHouse access by creating a database and corresponding access-restricted user in a single ("static") multi-tenant ClickHouse service.
Example provisioner set for it:
```bash
RILL_ADMIN_PROVISIONER_SET_JSON='{"clickhouse": {"type": "clickhouse-static", "spec": {"dsn": "clickhouse://user:pass@host:9440?secure=true"}}}'
```
=> Clickhouse static provisioner

web-common/src/features/dashboards/time-controls/ComparisonSelector.svelte
Enabling compare dimension in time dimension details and trying to disable by selecting `No comparison dimension` option doesnt do anything.
Attaching the correct event listener to fix this.
=> fix: disabling compare dimension in time dimension details

runtime/pkg/email/email.go, runtime/pkg/email/templates/call_to_action.mjml, runtime/pkg/email/templates/gen/call_to_action.html, runtime/pkg/email/templates/gen/informational.html, runtime/pkg/email/templates/gen/welcome_to_team.html, runtime/pkg/email/templates/gen/welcome_to_trial.html, runtime/pkg/email/templates/informational.mjml, runtime/pkg/email/templates/welcome_to_team.mjml, runtime/pkg/email/templates/welcome_to_trial.mjml, web-admin/src/features/billing/plans/utils.ts, web-common/src/features/billing/issues.ts, web-common/src/features/project/ProjectDeployer.ts, web-common/src/features/project/deploy-errors.ts, web-local/src/routes/(misc)/deploy/+page.svelte
=> fix: billing email  and deploy paywall copy

web-common/src/features/dashboards/leaderboard/Leaderboard.svelte
For cases when the label of a dimension was not set, the leaderboard header was empty. This was because `<empty string> ? "id"` resolves to `<empty string>`
=> fix: leaderboard header for no label

web-common/src/features/dashboards/pivot/PivotTable.svelte, web-common/src/features/dashboards/pivot/pivot-data-config.ts, web-common/src/features/dashboards/pivot/pivot-data-store.ts, web-common/src/features/dashboards/pivot/pivot-export.ts, web-common/src/features/dashboards/pivot/types.ts, web-common/src/features/templates/table/selector.ts
Adds support for searchText as a parameter for the pivot data store.
Also moves the pivot config in it's own file.
We can also integrate the search to existing pivot UI but we would need to think through some UX consideration as search can only be applied to a single dimension.
=> feat: support for search in pivot data store

web-common/src/app.css, web-common/src/features/dashboards/state-managers/selectors/pivot.ts, web-common/src/features/dashboards/stores/dashboard-stores.ts, web-common/src/features/dashboards/workspace/DashboardWithProviders.svelte, web-common/src/features/explores/ExplorePreviewCTAs.svelte, web-common/src/features/visual-editing/MeasureDimensionSelector.svelte, web-common/src/features/visual-metrics-editing/MetricsTable.svelte, web-common/src/features/visual-metrics-editing/MetricsTableRow.svelte, web-common/src/features/visual-metrics-editing/Sidebar.svelte, web-common/src/features/visual-metrics-editing/lib.ts, web-common/src/features/workspaces/ExploreWorkspace.svelte, web-common/src/features/workspaces/VisualMetrics.svelte, web-local/src/routes/(viz)/explore/[name]/+page.svelte
- Fixes an issue where initially changing measure/dimension selector from "All" to "Subset" would not properly update internal state of the selected items
- Changes measure/dimension selector in visual explore editor to show display names instead of ids
- Swaps order of "Metrics view" and "Explore dashboard" dropdown items when previewing a dashboard
- Fixes an issue where the pivot surface was using the full set of dimensions from the underlying metrics view rather than the filtered set from the explore resource
- Reduces element size of docs link for measure/dimension selector
- Fixes an issue where time pills were being filtered out of the pivot surface on page refresh
Closes #6156
Closes #6173
=> 0.52 uxqa fixes

web-admin/src/features/navigation/TopNavigationBar.svelte, web-admin/src/routes/+layout.ts
After the refactors in Billings UI PR logged out users are getting a login page for public page. There is a 403 request for org which should be ignored. Another 403 for subscription that should not be called at all.
=> fix: logged out users getting a login page for public projects

web-admin/src/features/billing/Payment.svelte, web-admin/src/features/billing/plans/POCPlan.svelte, web-admin/src/features/billing/plans/Plan.svelte, web-admin/src/features/billing/plans/utils.ts, web-admin/src/routes/[organization]/-/settings/+layout.svelte
=> fix: issues with managed plan and sub/trial ended handing revert

web-common/src/layout/workspace/WorkspaceHeader.svelte
Failure to initialize the `editing` variable was crashing the app when refreshing a metrics page.
=> fix: uncaught error in header

web-common/src/features/dashboards/time-controls/time-control-store.ts
For any time range we infer a comparison time range. But we were not assigning it to `name` of `selectedComparisonTimeRange` but just `start` and `end` in our time store. This meant that any consumer of this store was thinking it was not set at all.
One place this was seen was in alerts. With a dashboard with a default time range that can have a comparison, toggling the comparison did not update the alert creation modal. Only after selecting an option from the comparison drop down it showed up.
=> fix: inferred comparison time range not being made available when a default time range is present

web-admin/src/features/projects/environment-variables/ActionsCell.svelte, web-admin/src/features/projects/environment-variables/ActivityCell.svelte, web-admin/src/features/projects/environment-variables/AddDialog.svelte, web-admin/src/features/projects/environment-variables/EditDialog.svelte, web-admin/src/features/projects/environment-variables/EnvironmentVariablesTable.svelte, web-admin/src/features/projects/environment-variables/KeyCell.svelte, web-admin/src/features/projects/environment-variables/types.ts, web-admin/src/features/projects/environment-variables/utils.ts, web-admin/src/routes/[organization]/[project]/-/settings/environment-variables/+page.svelte
closes https://github.com/rilldata/rill/issues/6150
https://www.notion.so/rilldata/Environment-Variables-management-UI-42304f145b07410d86c2a523496aa6bc
https://github.com/user-attachments/assets/3769feac-b5d4-43b4-9046-95b8b6a9c049
=> Allow variable creation with different target environments 

web-common/src/features/entity-management/WatchResourcesClient.ts
This shouldn't strictly be necessary, but this is a patch fix for the following bug:
1. Go to the Visual Explore Editing surface
2. Navigate to the upstream metrics view
3. Change a property (like the name of a dimension)
4. Navigate back to the Visual Explore Editing surface
The new name will not be reflected because the query used to create the underlying state management object (`useExploreValidSpec`) does not refetch. I believe this may be a bug related to our specific version of Svelte Query. It looks like we ran into this previously here: https://github.com/rilldata/rill/pull/2027#discussion_r1161672656
=> fix: refetch explore resource

web-common/src/features/metrics-views/create-and-preview-explore.ts, web-local/tests/breadcrumbs.spec.ts, web-local/tests/explores/dashboard-flow-test-setup.ts, web-local/tests/explores/explores.spec.ts, web-local/tests/explores/leaderboard-and-dim-table-sort.spec.ts, web-local/tests/explores/time-controls-from-config.spec.ts, web-local/tests/explores/visual-explore-editing.spec.ts, web-local/tests/metrics-editor.spec.ts, web-local/tests/utils/exploreHelpers.ts
On creation of an Explore dashboard, navigate to the visual explore editor rather than the full dashboard preview.
=> feat: navigate to visual explore editor

web-common/src/components/date-picker/Calendar.svelte, web-common/src/features/dashboards/time-controls/super-pill/components/CalendarPlusDateInput.svelte, web-common/src/features/dashboards/time-controls/super-pill/components/Comparison.svelte
Fixes an issue where the calendar input would not display in the Comparison Pill when `All Time` was selected.
=> fix: comparison calendar not showing

web-common/src/features/dashboards/time-dimension-details/TDDTable.svelte
We have moved to making `NONE` as the default format instead of `HUMANIZE` when there is no preset defined. 
For existing dashboards without any preset defined, this could lead to expanded measure values across the dashboard. We handle them gracefully across leaderboard, dimension table and pivot but these values were overlapping in TDD.
The lift to make the column size dynamic based on the formatted value (as done with other surfaces) is likely not a simple change.
In interest of getting the new formatting changes out for release, this is a temporary solution where we format the values in TDD similar to big number so there is no overlapping. This is only done when there is no formatting defined.
=> Use humanized formatting in TDD when formatting not defined

web-admin/src/routes/+layout.svelte, web-admin/src/routes/[organization]/[project]/+layout.svelte, web-common/src/features/connectors/olap/TableMenuItems.svelte, web-common/src/features/explores/PreviewButton.svelte, web-common/src/features/file-explorer/NavFile.svelte, web-common/src/features/metrics-views/MetricsViewMenuItems.svelte, web-common/src/features/metrics-views/ai-generation/generateMetricsView.ts, web-common/src/features/sources/navigation/SourceMenuItems.svelte, web-common/src/features/workspaces/SourceWorkspace.svelte, web-common/src/layout/navigation/navigation-utils.ts
There are some usage of the telemetry client which doesnt consider the fact that it could not be initialised. After moving dev to `disabled` this has become a lot more apparent.
=> fix: type error around telemetry client usage when analytics is disabled

web-admin/src/features/bookmarks/BookmarksDropdownMenuContent.svelte, web-common/src/features/dashboards/big-number/MeasureBigNumber.svelte, web-common/src/features/dashboards/state-managers/state-managers.ts, web-common/src/features/dashboards/stores/dashboard-store-defaults.ts, web-common/src/features/dashboards/stores/test-data/data.ts, web-common/src/features/dashboards/tab-bar/TabBar.svelte, web-common/src/features/dashboards/time-controls/time-control-store.spec.ts, web-common/src/features/dashboards/time-series/BackToExplore.svelte, web-common/src/features/dashboards/url-state/DashboardURLStateSyncWrapper.svelte, web-common/src/features/dashboards/url-state/convertExploreStateToURLSearchParams.ts, web-common/src/features/dashboards/url-state/explore-web-view-store.spec.ts, web-common/src/features/dashboards/url-state/explore-web-view-store.ts, web-common/src/features/dashboards/url-state/getDefaultExplorePreset.ts, web-common/src/features/dashboards/url-state/invalid-url-state-variations.spec.ts, web-common/src/features/dashboards/url-state/url-state-variations.spec.ts, web-common/src/features/explores/selectors.ts
=> fix: URL params UXQA items

web-common/src/features/dashboards/big-number/MeasuresContainer.svelte, web-common/src/features/dashboards/leaderboard/LeaderboardControls.svelte, web-common/src/features/dashboards/time-series/MetricsTimeSeriesCharts.svelte
Nullish coalescing operator was being used, but the field is returned as an empty string when undefined. 
Closes #6224
=> fix: displayname returned as empty string when undefined

docs/docs/reference/project-files/metrics-view.md
Not sure if necessary but based on Dhiraj showcase, might need some examples, we link the website but would be nice to able to reference one example via rill docs 
```
format_d3: "$,"
format_d3_locale: 
grouping: [3, 2]
currency: ["₹", ""]
```
=> docs / metrics view locale_d3 example

runtime/compilers/rillv1/parse_alert.go, runtime/compilers/rillv1/parse_canvas.go, runtime/compilers/rillv1/parse_component.go, runtime/compilers/rillv1/parse_explore.go, runtime/compilers/rillv1/parse_metrics_view.go, runtime/compilers/rillv1/parse_report.go, runtime/compilers/rillv1/parser_test.go, runtime/compilers/rillv1/util.go, runtime/compilers/rillv1/util_test.go, runtime/controller_test.go, runtime/queries/metricsview_aggregation_test.go, runtime/reconcilers/alert_test.go, runtime/testruntime/testdata/ad_bids/dashboards/ad_bids_metrics.yaml
This PR adds a default value for `display_name` for resources as well as a metrics view's dimensions and measures. The default is a humanized version of the resource's `name`. For example, if the name is `foo_bar`, the default display name becomes `Foo Bar`.
=> Make `display_name` default to humanized `name`

runtime/pkg/email/email.go, web-admin/src/routes/+layout.ts, web-common/src/features/project/ProjectDeployer.ts, web-local/src/routes/(misc)/deploy/+page.svelte
=> fix: Empty projects page for orgs with expired trial and other billing issues

web-common/src/features/dashboards/tab-bar/TabBar.svelte, web-common/src/features/dashboards/workspace/Dashboard.svelte
Moves use of `getStateManagers` out of the TabBar component.
=> tweak: update tab bar implementation

web-common/src/features/dashboards/time-controls/super-pill/SuperPill.svelte, web-common/src/features/dashboards/url-state/defaults.ts, web-common/src/features/dashboards/url-state/getDefaultExplorePreset.ts
- Default timezone is UTC when timezones is not defined in the yaml config.
- If the localIANA is not preset in the list of timezones then default to UTC if it is in the list otherwise select the 1st timezone.
=> fix: default timezone when timezones is not defined in yaml config

web-common/src/features/sources/modal/FileDrop.svelte, web-common/src/features/sources/modal/LocalSourceUpload.svelte, web-common/src/features/sources/modal/submitAddDataForm.ts
On the Welcome screen, a race condition was sometimes preventing navigation to the user's first source file. See code comment for more detail.
Partially addresses https://github.com/rilldata/rill-private-issues/issues/991
=> fix(Welcome screen): Avoid race condition after unpacking an empty project

web-common/src/layout/navigation/Navigation.svelte
Navigation sidebar opens and closes based on browser width, unless explicitly closed.
=> feat: reopen navigation sidebar

web-common/src/features/dashboards/config.ts, web-common/src/features/dashboards/time-series/MetricsTimeSeriesCharts.svelte, web-common/src/features/dashboards/time-series/TimeSeriesChartContainer.svelte, web-common/src/features/dashboards/workspace/Dashboard.svelte, web-common/src/layout/Resizer.svelte
Add a container resizer between timeseries and leaderboard container.
=> Feat: Add resizer for timeseries leaderboard split

runtime/metricsview/executor_validate.go
Contributes to https://github.com/rilldata/rill-private-issues/issues/1013 (but doesn't truly fix it)
=> Skip validation of measure schema if driver doesn't return a valid type

runtime/catalog_cache.go, runtime/reconcilers/alert.go, runtime/reconcilers/model.go, runtime/reconcilers/project_parser.go, runtime/reconcilers/refresh_trigger.go, runtime/reconcilers/report.go, runtime/reconcilers/source.go, runtime/testruntime/reconcile.go
Should fix [this issue reported in Slack](https://rilldata.slack.com/archives/CTCJ58H3M/p1733432211759179).
=> Runtime: Prevent resource protos from being mutated after being read

web-admin/src/features/dashboards/query-mappers/getDashboardFromAggregationRequest.ts, web-admin/src/features/dashboards/query-mappers/utils.ts, web-admin/src/routes/[organization]/[project]/-/alerts/[alert]/open/+page.svelte, web-common/src/features/alerts/EditAlertForm.svelte, web-common/src/features/dashboards/filters/measure-filters/measure-filter-entry.ts, web-common/src/features/dashboards/url-state/convertURLToExplorePreset.ts
=> fix: alerts opened with new url params.

web-common/src/features/entity-management/AddAssetButton.svelte, web-common/src/features/entity-management/WatchResourcesClient.ts, web-common/src/features/entity-management/dag-utils.ts, web-common/src/features/feature-flags.ts, web-common/src/features/welcome/ProjectCards.svelte
Reported in the [bug bash](https://www.notion.so/rilldata/Bug-Bash-Dec-2024-159ba33c8f578027970beb993567142f?pvs=4#159ba33c8f5780dab177dd5ba8af2ed5)
=> Don't show the "Source imported successfully" modal when unpacking example projects

web-common/src/components/forms/Select.svelte, web-common/src/features/alerts/criteria-tab/getTypeOptions.ts, web-common/src/features/dashboards/url-state/convertPresetToExploreState.ts
- When switching time ranges, comparison time range would reset.
- Just after switching on compare dimension toggling comparison time range would not apply.
- If comparison is disabled comparison based criteria was still allowed in alerts.
=> fix: comparison time ranges resetting when switching time ranges

admin/provisioner/clickhousestatic/provisioner.go, admin/provisioner/clickhousestatic/provisioner_test.go
When editing the `clickhouse.yaml` file with keystroke-by-keystroke editing, provisioning calls can be rapidly cancelled and retried. This surfaced an idempotency issue where calling `CREATE USER IF NOT EXISTS` did not use the generated random password, causing the generated DSN to be invalid. This PR fixes the problem by leveraging ClickHouse's support for adding multiple passwords to one user.
=> Fix the generated password not being idempotent in the ClickHouse provisioner

web-admin/src/routes/-/embed/+page.svelte
This PR removes the Scheduled Report option from the Export dropdown menu. [Bug report here](https://rilldata.slack.com/archives/C07596F82F9/p1734107833805879).
=> Disable control-plane features for embedded dashboards

runtime/drivers/clickhouse/olap.go, runtime/drivers/clickhouse/olap_test.go
This PR fixes syntax errors caused by incorrect handling of datetime values in partitions during query execution and ensures they are parsed correctly. It also improves security by using `bindvars` for part values.
Fixes - 
```
Error:      	Received unexpected error:
code: 62, message: Syntax error: failed at position 89 ('02'): 02:00:00 FROM "__rill_temp_replace_tbl_local_3bce15769a69ae070ab9e0bebc82e878". Expected one of: token, DoubleColon, OR, AND, IS NOT DISTINCT FROM, IS NULL, IS NOT NULL, BETWEEN, NOT BETWEEN, LIKE, ILIKE, NOT LIKE, NOT ILIKE, REGEXP, IN, NOT IN, GLOBAL IN, GLOBAL NOT IN, MOD, DIV
```
=> fix: use bindvars at replace partition

web-admin/src/features/navigation/TopNavigationBar.svelte, web-common/src/components/dropdown-menu/DropdownMenuCheckboxItem.svelte, web-common/src/components/navigation/breadcrumbs/BreadcrumbItem.svelte, web-common/src/components/navigation/breadcrumbs/types.ts
If a user is viewing the homepage of Project A, when the user hovers over Project B's name in the project breadcrumb dropdown menu, the dashboard list will change from Project A's to Project B's before navigation actually takes place.
Why:
- In the root `+layout.ts` file's loader function, we call `GetProject` to fetch a project's runtime information, _and we set the runtime information in a global store_. 
- Due to `data-sveltekit-preload-data`, this loader function is triggered when hovering over the link to Project B in the project breadcrumb's dropdown menu. The global runtime store switches from containing Project A's runtime to Project B's runtime.
- All mounted runtime queries are re-run for Project B.
For now, this PR disables `data-sveltekit-preload-data` for the project …
=> Fix: Prevent unintended data preloading when hovering project links in the breadcrumb menu

web-common/src/features/dashboards/workspace/Dashboard.svelte
A regression was introduced in https://github.com/rilldata/rill/pull/6256 where the TDD charts would not be full width
=> Fix: full width for TDD charts

runtime/drivers/clickhouse/context.go, runtime/drivers/clickhouse/olap_test.go
It seems post driver upgrade settings is not initialised by default.
=> fix panic in accessing settings in clickhouse driver

web-common/src/features/dashboards/workspace/Dashboard.svelte
Set basis to fix container sizes on double click.
=> fix: double click on timeseries explore resizer

runtime/compilers/rillv1/parse_rillyaml.go
Previously we ignored unknown properties when parsing `rill.yaml`, but now we error for unknown properties. Since `ignore_paths` was consumed outside the parser, it was considered an unknown property.
Fixes the issue reported here: https://rilldata.slack.com/archives/CTZ8XBQ85/p1734454960845279
=> Add `ignore_paths` to `rill.yaml` validation in the runtime parser

runtime/drivers/clickhouse/clickhouse.go
In my testing on local, running a query 100 times that returns 30K rows, native worked ~30% faster.
Also fixes https://github.com/rilldata/rill-private-issues/issues/1013 
The HTTP protocol does not return column types if empty results whereas native protocol does (Issue is already open in clickhouse).
=> fix : Clickhouse driver should always use native protocol unless a DSN is set directly

web-common/src/layout/workspace/WorkspaceHeader.svelte
Adds the ability to select these buttons using `page.getByLabel("Toggle table visibility")` and `page.getByLabel("Toggle inspector visibility")` when constructing Playwright tests
=> fix: add accessible labels for workspace toggles

runtime/compilers/rillv1/parse_alert.go, runtime/compilers/rillv1/parse_api.go, runtime/compilers/rillv1/parse_component.go, runtime/compilers/rillv1/parse_model.go, runtime/compilers/rillv1/parser_test.go, runtime/reconcilers/alert_test.go
Changes:
- If the `partitions:` resolver in a model is a `sql` resolver, it will default to the model's **input** connector
- If the `state:` resolver in a model is a `sql` resolver, it will default to the model's **output** connector
=> Intelligent default connectors for state and partition resolvers in models

web-common/src/features/dashboards/workspace/Dashboard.svelte
In this [file](https://github.com/rilldata/rill/blob/main/web-admin/src/routes/%5Borganization%5D/%5Bproject%5D/%2Blayout.svelte), we're refetching the project when the application tab is refocused. 
This refetch meant we were receiving a new JWT each time. The JWT is colocated in a store that also handles the host and instanceId variables, so updating one triggers a reactive update for all of them.
In our [state managers](https://github.com/rilldata/rill/blob/main/web-common/src/features/dashboards/state-managers/state-managers.ts), the explore spec and time range summary are dependent on the runtime store.
In Leaderboards, the primary aggregation query is dependent on an array of measures and the time range, which are derived from those queries. So, on window focus, the parameters were …
=> fix: query cancellation issue

cli/pkg/local/app.go
If another Rill is running, we fail with a "port blocked" error. However, there is a race condition where the health check that is used to check if we should open the browser may succeed before that error bubbles up. The health check succeeds too early because it actually ends up polling the already-running Rill. This PR fixes this by adding a small wait before the first health check.
Closes https://github.com/rilldata/rill-private-issues/issues/925
=> Fix browser opens in `rill start` when the port is taken

runtime/pkg/observability/observability.go
closes https://github.com/rilldata/rill/issues/6331
On a longer term we need to investigate on how this can be caught earlier. Didn't see either in prod servers or on my laptotp.
=> fix : resolve conflict schema URL error

web-admin/src/features/bookmarks/Bookmarks.svelte, web-admin/src/features/bookmarks/BookmarksDropdownMenuContent.svelte, web-admin/src/features/bookmarks/BookmarksDropdownMenuItem.svelte, web-admin/src/features/bookmarks/selectors.ts, web-common/src/features/dashboards/url-state/DashboardURLStateSync.svelte
- Disable delete while bookmark is being deleted. This to avoid multiple calls to delete per click.
- Editing a bookmark with filters only doesnt set the toggle to true.
- Entering a dashboard with no timeseries and a home bookmark doesnt load the dashboard
=> fix: bookmark interaction with url params

go.mod, go.sum
Based on the PR description the leak is small and it seems unlikely to cause OOMes but best to add the patch.
=> fix : patch for memory leaks in arrow parquet buffered writer 

web-admin/src/features/billing/plans/selectors.ts
Billing cycle end date already has a +1. So we dont need to add to it to get the next cycle start date.
This is the frontend change similar to #6349
=> fix: Do not add 1 to get next billing cycle start date

runtime/drivers/blob/parquetreader.go, runtime/drivers/file/model_executor_olap_self.go, runtime/drivers/snowflake/warehouse.go, runtime/queries/metricsview.go, runtime/resolvers/sql.go, runtime/server/queries_metrics_rows_test.go
The `CheckedAllocator` is expected to be used in test code only. Mostly adds extra overheads as well.
=> nit : Remove checked allocator in arrow code usages

runtime/drivers/duckdb/duckdb.go, runtime/drivers/duckdb/model_executor_sqlstore_self.go, runtime/drivers/duckdb/olap.go, runtime/drivers/duckdb/transporter_mysql_to_duckDB_test.go, runtime/drivers/duckdb/transporter_postgres_to_duckDB_test.go, runtime/drivers/mysql/mysql.go, runtime/drivers/postgres/postgres.go
subtask for https://github.com/rilldata/rill-private-issues/issues/854
- Adds a model executor that ingests data from postgres/mysql using duckdb extension.
- Also supports incremental ingestion.
Sample model yaml that ingests from postgres.
```
connector: postgres
sql: SELECT * FROM students 
dsn: "postgresql://postgres:postgres@localhost:5432/postgres"
output:
connector: duckdb
```
=> model executor for postgres and mysql to duckdb

admin/provisioner/clickhousestatic/provisioner.go, admin/provisioner/clickhousestatic/provisioner_test.go, cli/cmd/runtime/start.go, runtime/connection_cache.go, runtime/drivers/clickhouse/clickhouse.go, runtime/drivers/clickhouse/olap.go
- Adds a metric event named `clickhouse_estimated_size_bytes` giving the estimated disk size used by ClickHouse (limited to the tables the current user has access to).
- Adds an attribute `managed: true` to all events emitted from a Rill-managed ClickHouse connector. This enables billing logic to bill differently for externally managed ClickHouse connections.
- Adds last-used-on logic to the ClickHouse driver, which is used to only estimate the size when the database was recently used. This ensures we play nice with scale-to-zero ClickHouse.
- Adds a new grant to Rill-managed ClickHouse users to enable reporting disk usage.
- Adds support for configuring a `console` activity logger on the runtime for debugging activity event emission.
Contributes to …
=> Emit ClickHouse database size metrics

web-common/src/features/dashboards/url-state/convertPresetToExploreState.ts
We were setting only `selectedScrubRange` while loading from url. But our queries check `lastDefinedScrubRange`
=> fix: scrub range reload from url params

runtime/drivers/druid/druidsqldriver/druid_api_sql_driver.go
If dsn already has slash at the end then the cancellation query has double slashes and it does not work
=> fix druid query cancellation url if dsn has slash

runtime/connection_cache.go, runtime/drivers/gcs/gcs.go
refers to https://github.com/rilldata/rill/pull/6353#discussion_r1907452585
This is to identify if some external user is using GCS.
=> Add a log for gcs usage

cli/cmd/admin/admin.go, cli/cmd/devtool/devtool.go, cli/cmd/org/edit.go, cli/cmd/org/org_test.go, cli/cmd/root.go, cli/cmd/runtime/runtime.go, cli/cmd/sudo/sudo.go, cli/cmd/verify_install.go, cli/pkg/cmdutil/group.go
**Description**
`rill org edit` now allows for the editing of the organizations "Display Name"
```sh
rill org edit
? Select org to edit demo
? Do you want to update the display name Yes
? Enter the display name new-demo
? Do you want to update the description No
? Do you want to update the billing email No
Updated organization
NAME   CREATED AT
------ ---------------------
demo   2023-06-21 04:57:34
```
```sh
rill org show
Name: demo
Display Name: new-demo
```
Updates default help with command groupings
```sh
Work with Rill projects directly from the command line.
Usage:
rill [command]
Project
start          Build project and start web app
deploy         Deploy project to Rill Cloud
project        Manage projects
public-url     Manage public URLs
env            Manage variables for a …
```
=> Add help command grouping and org display name editing

web-common/src/features/entity-management/async-save-state.ts, web-common/src/features/entity-management/file-artifact.ts
Fixes an issue where saves taking longer than expected would erroneously trigger a file conflict warning.
- Extends buffer for ignoring save events
- Updates logic to account for this situation
=> fix: delayed save issue

runtime/pkg/activity/client.go
Since this is not a documented feature, it hasn't been tested much before. I did some additional QA and did not find a need for other changes.
Closes https://github.com/rilldata/rill-private-issues/issues/999
=> Fix panic if `analytics_enabled: false`

runtime/drivers/duckdb/duckdb.go, runtime/drivers/duckdb/model_executor_https_self.go, runtime/drivers/duckdb/model_executor_https_self_test.go, runtime/drivers/https/https.go
subtask for https://github.com/rilldata/rill-private-issues/issues/854
Adds a model executor that ingests data from https to duckdb.
Sample model file
```
connector: https
path: https://storage.googleapis.com/rilldata-public/mobile-demo-funnel.parquet
output:
connector: duckdb
```
=> feat : http to duckdb model executor

web-admin/src/routes/[organization]/[project]/explore/[dashboard]/+page.svelte
Upon merging PR https://github.com/rilldata/rill/pull/6410, I've noticed a bug where the dashboard hangs on initial load. 
Here's the video of a failed e2e test from the [Cloud e2e test PR](https://github.com/rilldata/rill/pull/6244):
https://github.com/user-attachments/assets/aae7f040-b434-413b-9bb7-dc5693a026c9
The problem appears to be a circular reference that leads to issues with Svelte reactivity. See the code comment above the new `isDashboardReconcilingForFirstTime()` function for more detail.
=> Fix initial load of Cloud dashboard

runtime/drivers/duckdb/duckdb.go
To be safe for the time being since we don't use any of them
=> DuckDB: Disable community extensions

web-common/src/features/entity-management/file-artifact.ts, web-common/src/features/visual-metrics-editing/EditControls.svelte, web-common/src/features/visual-metrics-editing/MetricsTable.svelte, web-common/src/features/visual-metrics-editing/MetricsTableRow.svelte, web-common/src/features/workspaces/VisualExploreEditing.svelte, web-common/src/features/workspaces/VisualMetrics.svelte, web-local/tests/metrics-editor.spec.ts
Private method `saveContent` was still being used in the Visual Metrics Editing surface, preventing the UI from updating after making certain changes. Updates surface to use the `updateEditorContent` method, which has an argument for saving in the same function call.
Also adds a test and necessary selector labels.
=> fix: save content method

web-admin/src/features/projects/status/ProjectResourcesTable.svelte, web-admin/src/features/projects/status/RefreshCell.svelte, web-admin/src/features/projects/status/ResourceErrorMessage.svelte, web-common/src/components/table/BasicTable.svelte
https://rilldata.slack.com/archives/C02T907FEUB/p1736947978246939
- Removes extraneous `}` character in `ResourceErrorMessage`
- Updates column sizings to gain a little more space where needed
- Adds `truncate` class to header cell
- Adds `truncate` class to date strings
=> tweak: resource table column sizing

cli/cmd/auth/login.go, cli/cmd/org/org.go, cli/cmd/org/switch.go
May be we should just set the default as 1000 since both UI and CLI use 1000 at several places.
=> fix(hacky bypass) org pagination for several commands

runtime/drivers/duckdb/duckdb.go, runtime/pkg/rduckdb/db.go
This is just a fix for release blocker. The permanent solution will be as follows:
1. Most of our settings are global configuration except `max_expression_depth`.
2. It seems extensions are now loaded at db level and not connection level. The following code now works:
```
_, err = conn1.ExecContext(context.Background(), "INSTALL spatial; LOAD spatial;")
if err != nil {
log.Fatal(err)
}
row := conn2.QueryRowContext(context.Background(), "SELECT ST_Area('POLYGON((0 0, 0 1, 1 1, 1 0, 0 0))'::GEOMETRY);")
var area float64
err = row.Scan(&area)
if err != nil {
log.Fatal(err)
}
log.Println(area)
```
3. Introduce two new options in `rduckdb` : 
a. `DBInitQueries` : Runs for db handle once. Extensions, global configurations and `init_sql` in connector config will be DBInitQueries.
b. …
=> fix : certain db level settings in duckdb can't be set again

web-admin/src/features/errors/error-utils.ts
Addresses [this concern from Slack](https://rilldata.slack.com/archives/C082M1C37T5/p1737028247235239?thread_ts=1736955047.910339&cid=C082M1C37T5)
=> Scope 500-level errors to components

web-common/src/features/dashboards/url-state/filters/converters.ts, web-common/src/features/dashboards/url-state/filters/expression.cjs, web-common/src/features/dashboards/url-state/filters/expression.ne, web-common/src/features/dashboards/url-state/filters/expression.spec.ts, web-common/src/features/dashboards/url-state/filters/post-processors.ts
URL filter param breaks when the dimension has array and object types. This adds support for parsing of such values.
=> fix: array and object filter values

web-common/src/features/dashboards/filters/measure-filters/MeasureFilter.svelte, web-common/src/features/dashboards/filters/measure-filters/MeasureFilterForm.svelte
Fixes an issue where dismissing an incomplete measure filter would not remove the pill from the filter bar.
Closes #6395
=> fix: measure filter dismiss flow

.github/workflows/docs-check.yml, cli/README.md, docs/docs/dummy.md, docs/docs/reference/cli/billing/billing.md, docs/docs/reference/cli/cli.md, docs/docs/reference/cli/deploy.md, docs/docs/reference/cli/docs/docs.md, docs/docs/reference/cli/env/env.md, docs/docs/reference/cli/login.md, docs/docs/reference/cli/logout.md, docs/docs/reference/cli/org/edit.md, docs/docs/reference/cli/org/org.md, docs/docs/reference/cli/org/show.md, docs/docs/reference/cli/org/upload-logo.md, docs/docs/reference/cli/project/project.md, docs/docs/reference/cli/public-url/public-url.md, docs/docs/reference/cli/service/service.md, docs/docs/reference/cli/start.md, docs/docs/reference/cli/uninstall.md, docs/docs/reference/cli/user/user.md, docs/docs/reference/cli/usergroup/usergroup.md, docs/docs/reference/cli/version.md, docs/docs/reference/cli/whoami.md
Update GitHub docs workflow to check if there were cli help menu changes.
=> Add Workflow and update cli documentation

runtime/drivers/clickhouse/olap.go
otherwise it was quoting the local table name like `ENGINE = Distributed('abc', 'default', '"table_local"', rand())` and queries were failing on it saying local table not found
=> use literals in distributed engine definition in ch

cli/cmd/deploy/deploy.go, cli/cmd/project/connect_github.go, cli/cmd/project/deploy.go, cli/pkg/local/project.go, cli/pkg/local/server.go
Closes https://github.com/rilldata/rill/issues/6365
=> Upload `.env` as part of (re)deploys

web-common/src/features/dashboards/url-state/convertExploreStateToPreset.ts, web-common/src/features/dashboards/url-state/convertPresetToExploreState.ts
Since we use comparison mode in explore preset there could be issues when both time and dimension comparison are enabled. Since we actually support for both to be present at the same time this fixes some edge cases with it. The main one is setting both and switching between pivot and explore.
=> fix: compare time and dimension conflicts in url param

web-common/src/features/dashboards/leaderboard/Leaderboard.svelte
Hide "(no available values)" text when leaderboard results are being fetched.
Closes https://github.com/rilldata/rill/issues/6367
=> fix: hide no available values text when fetching

runtime/drivers/clickhouse/clickhouse.go, runtime/drivers/clickhouse/embed.go
closes https://github.com/rilldata/rill-private-issues/issues/943
Also blocks change of port.
=> fix : only allow a single instance of embedded clickhouse server

docs/docs/home/FAQ.md, docs/docs/manage/account-management/billing.md
https://rilldata.slack.com/archives/C010H7G2YCA/p1737575370965029
=> adding enterprise plan info as discussed

admin/server/assets.go, admin/server/github.go, runtime/drivers/admin/admin.go, runtime/pkg/archive/archive.go
closes #6468
`.git` folder was getting added to the archive after disconnecting from github. `drivers.IsIgnored` expects a leading `/`.
Also there could already be projects with the `.git` folder. So handle this case when reconnecting to a new repo.
=> fix: reconnect to a different github failing with `remote already exists`

web-common/src/features/dashboards/leaderboard/LeaderboardControls.svelte, web-common/src/features/dashboards/state-managers/actions/measures.ts, web-common/src/features/dashboards/state-managers/selectors/measures.ts, web-common/src/features/dashboards/stores/test-data/data.ts, web-common/src/features/dashboards/stores/test-data/store-mutations.ts, web-common/src/features/dashboards/url-state/convertURLToExplorePreset.ts, web-common/src/features/dashboards/url-state/error-message-helpers.ts, web-common/src/features/dashboards/url-state/url-state-variations.spec.ts
closes #6342
We allow leaderboard sort by measure to be hidden. This looks weird when a dimension is expanded. We have decided to disallow sorting by a measure that is hidden to keep things consistent.
=> fix: Disallow sort by hidden measure in leaderboard

runtime/drivers/duckdb/config.go, runtime/drivers/duckdb/config_test.go, runtime/drivers/duckdb/duckdb.go, runtime/pkg/rduckdb/db.go, runtime/pkg/rduckdb/db_test.go
The default split of resources is 50/50 for reads and writes. The ratio can be used to change the split.
=> feat : Add a `read_write_ratio` for duckdb to split resources between serving and ETL

admin/worker/deployments_health_check.go
Hopefully prevents job timeouts, as seen here: https://rilldata.slack.com/archives/C05TXA7QSTY/p1737643082675709
=> Increase health check concurrency to 32

runtime/controller.go
We're seeing the current timeout of 10s being reached when complex models are being materialized. One hypothesis is that DuckDB needs more time than 10s to clean up temporary disk state in these cases. This PR increases the limit to 30s.
Note that 30s is quite high and we should beware if we observe signs of more force shutdowns. Even in Rill Developer, a slow graceful shutdown may cause the user to force shutdown instead.
=> Increase timeout for graceful controller shutdown to 30s

web-common/src/features/dashboards/url-state/DashboardURLStateSyncWrapper.svelte
Dashboards that lacked time series data were prevented from loading due to a conditional in `DashboardUrlStateSyncWrapper`
=> fix: embedded dashboards without time series

admin/database/postgres/postgres.go
Fixes this error when calling `DeleteMagicAuthTokens` with multiple tokens:
```
panic caught: expected to delete 1 row, but deleted 2
```
DataDog [link here](https://rill.datadoghq.com/logs?query=service%3Arill-cloud%20%40level%3Aerror%20-%22otel%20error%22%20container_name%3Acloud-admin-server%20-%40error%3A%22not%20authenticated%20as%20a%20user%22&agg_m=count&agg_m_source=base&agg_q=environment&agg_q_source=base&agg_t=count&clustering_pattern_field_path=message&cols=host%2Cservice&event=AwAAAZStGD-0po6FlQAAABhBWlN0R0VOU0FBRHVoS1pqTEh0X2ZRQUQAAAAkMDE5NGFkMWMtNmRiYS00MDQyLWIyNmEtZWQzNDNkNDVhZGExAAAdTg&fromUser=true&index=main&link_source=monitor_notif&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=desc&top_n=10&top_o=top&viz=stream&x_missing=true&from_ts=1738070582000&t …
=> Fix unwarranted panic in DeleteMagicAuthTokens

web-admin/src/features/navigation/TopNavigationBar.svelte
The problem:
Quick fix. Bumps the page size from 20 -> 100 on the `ListProjects` request.
=> fix (Breadcrumbs): Missing label for projects outside the first page

web-admin/src/features/public-urls/form-utils.ts, web-common/src/features/dashboards/dimension-table/DimensionDisplay.svelte, web-common/src/features/dashboards/leaderboard/Leaderboard.svelte, web-common/src/features/dashboards/leaderboard/LeaderboardDisplay.svelte, web-common/src/features/dashboards/state-managers/selectors/dashboard-queries.ts, web-common/src/features/dashboards/state-managers/selectors/measures.spec.ts, web-common/src/features/dashboards/state-managers/selectors/measures.ts, web-common/src/features/dashboards/time-series/timeseries-data-store.ts, web-common/src/features/dashboards/workspace/Dashboard.svelte
If a public url is created by selecting a computed measure but not the measure it is computed on, the dashboard fails to load since all required measures are not added to the token.
~~So we need to add all `referencedMeasures` to fields as well. This has a side effect of showing measures that were not selected.~~
We do not need to send the `referencedMeasures` for non-window computed measures.
=> fix: public urls with computed measures and dependant measures are hidden

docs/docs/build/connect/multiple-connectors.md, docs/docs/build/credentials/credentials.md, docs/docs/deploy/deploy-credentials.md, docs/docs/deploy/deploy-dashboard/_category_.yml, docs/docs/deploy/deploy-dashboard/deploy-dashboard.md, docs/docs/explore/alerts/slack.md, docs/docs/home/FAQ.md, docs/docs/manage/project-management/variables-and-credentials.md, docs/docs/reference/project-files/sources.md
Build/ configure local credentials
setting up creds for RD, 4 options,
mention to use .env when deploying to RC
Deploy/configure deployment credentials
More details on differnece between local creds and RC creds,
env is deployed with, else youll need to deploy then define creds using rill env configure
Manage/project-management/ configure environmental variables and credentials
fix references to these docs ++ nit
=> .env auto deploy doc updates

web-common/src/features/workspaces/VisualMetrics.svelte
When selecting a already selected model in the model dropdown we show a warning dialog.
This checks early if the new value was actually changed.
=> fix: dont show warning when not switching model

runtime/pkg/observability/observability.go
Added additional error handling to the observability shutdown callback. Additionally I added a call a [`.ForceFlush`](https://pkg.go.dev/go.opentelemetry.io/otel/sdk/trace#TracerProvider.ForceFlush) call on the provider in the hopes we can immediately push all spans that have not yet been exported.
=> Add additional error handling on OpenTel callback

web-admin/src/routes/[organization]/[project]/-/share/[token]/+page.ts, web-admin/src/routes/[organization]/[project]/explore/[dashboard]/+page.ts, web-common/src/features/dashboards/filters/Filters.svelte, web-common/src/features/dashboards/time-controls/rill-time-ranges.ts, web-common/src/features/dashboards/time-controls/time-control-store.ts, web-common/src/features/dashboards/url-state/DashboardURLStateSync.svelte, web-common/src/features/dashboards/url-state/DashboardURLStateSyncWrapper.svelte, web-common/src/features/dashboards/url-state/time-ranges/RillTime.ts, web-common/src/features/dashboards/url-state/time-ranges/parser.ts, web-common/src/features/dashboards/url-state/time-ranges/rill-time.cjs, web-common/src/features/dashboards/url-state/time-ranges/rill-time.ne, web-common/src/features/dashboards/url-state/time-ranges/rill-time.spec.ts, web-common/src/features/dashboards/url-state/url-state-variations.spec.ts, web-common/src/features/explores/selectors.ts, web-local/src/routes/(viz)/explore/[name]/+page.ts
=> fix: time UI integration issues

runtime/controller.go
Emiting reconcile_elapsed_ms metrics
=> Emiting reconcile_elapsed_ms metrics

web-common/src/features/canvas/components/util.ts, web-common/src/features/canvas/inspector/ComponentsEditor.svelte, web-common/src/features/canvas/inspector/VisualCanvasEditing.svelte, web-common/src/features/canvas/stores/canvas-component.ts, web-common/src/features/canvas/stores/canvas-spec.ts
Removes resource query from `ComponentsEditor` and subscribes to the canvas spec using store selectors
=> Canvas: use selector for canvas components on editing

runtime/compilers/rillv1/parse_rillyaml.go
It seems that at one point we also supposed `name:` in `rill.yaml`. Since we recently added validation for known keys, adding it to the type for safety.
=> Validation for deprecated `name:` field in `rill.yaml`

runtime/controller.go, runtime/drivers/registry.go, runtime/reconcilers/alert.go, runtime/reconcilers/api.go, runtime/reconcilers/canvas.go, runtime/reconcilers/component.go, runtime/reconcilers/connector.go, runtime/reconcilers/explore.go, runtime/reconcilers/metrics_view.go, runtime/reconcilers/migration.go, runtime/reconcilers/model.go, runtime/reconcilers/project_parser.go, runtime/reconcilers/pull_trigger.go, runtime/reconcilers/refresh_trigger.go, runtime/reconcilers/report.go, runtime/reconcilers/source.go, runtime/reconcilers/theme.go
Changes:
- Adds `rill.models.concurrent_execution_limit` as a config key with a default limit of 1.
- The limit applies to source and model resources, but is enforced separately for each type (since we'll soon unify the two it's not worth centralizing it)
- The limit only applies if there are expensive operations like ingestion or deletion, not for simple reconciles that just do integrity or refresh time checks.
Example for changing the limit to 3:
```
rill env set rill.models.concurrent_execution_limit 3
```
=> Support limiting the concurrency of source and model execution

web-common/src/features/workspaces/VisualMetrics.svelte
- Allow malformed items to generate a row in the table so that indexes remain consistent when reordering
- Remove items that are not of type YAMLMap after reordering
- Make editing changes based off a copy of the underlying item sequence
Closes #6571
=> fix: metrics table reordering

admin/jobs/river/org_jobs.go
Allow the custom handler to manage attempts instead of worker job.
Resolves: https://github.com/rilldata/rill-private-issues/issues/1101
=> Bug: Use Custom River Error Handler

web-common/src/features/dashboards/leaderboard/LeaderboardRow.svelte, web-common/src/features/dashboards/leaderboard/leaderboard-utils.spec.ts, web-common/src/features/dashboards/leaderboard/leaderboard-utils.ts
For certain cases dimension uri comes in as `0/1` instead of `false/true`. Until we figure out the query/data issue this fixes the UI crashing.
=> fix: dimension uri coming in as int instead of bool breaking UI

proto/gen/rill/runtime/v1/resources.pb.go, proto/gen/rill/runtime/v1/resources.pb.validate.go, proto/gen/rill/runtime/v1/runtime.swagger.yaml, proto/rill/runtime/v1/resources.proto, runtime/compilers/rillv1/parse_canvas.go, runtime/compilers/rillv1/parser_test.go, web-common/src/proto/gen/rill/runtime/v1/resources_pb.ts, web-common/src/runtime-client/gen/index.schemas.ts
Example:
```yaml
type: canvas
...
layout:
- 1, 2, 3
- 4, 5, 6
```
=> Add support for untyped `layout:` in the canvas YAML

web-common/src/features/canvas/components/charts/index.ts, web-common/src/features/canvas/components/kpi/KPI.svelte, web-common/src/features/canvas/components/kpi/index.ts, web-common/src/features/canvas/components/table/index.ts, web-common/src/features/canvas/inspector/ComponentsEditor.svelte, web-common/src/features/canvas/stores/canvas-time-control.ts, web-common/src/features/dashboards/time-controls/time-control-store.ts, web-common/src/features/file-explorer/new-files.ts
This PR 
- Removes the override time range so that new components inherit the global time ranges by default
- Support setting comparison mode as time in preset and use that as default for new canvas
- Respect comparison toggle for KPIs inhering comparison range from global filters
=> Canvas: activate comparison by default, use global time

runtime/queries/metricsview_aggregation.go, web-common/src/features/alerts/CreateAlertForm.svelte, web-common/src/features/alerts/form-utils.ts, web-common/src/features/dashboards/dimension-table/dimension-table-export-utils.ts, web-common/src/features/dashboards/pivot/pivot-export.ts, web-common/src/features/dashboards/time-controls/time-range-mappers.ts, web-common/src/features/dashboards/time-dimension-details/getTDDExportArgs.ts
=> fix: various time ranges issues in alerts

runtime/pkg/conncache/conncache.go, runtime/pkg/conncache/conncache_test.go
Fixes an issue introduced here: https://github.com/rilldata/rill/pull/6587
**Checklist:**
=> Fix panic when re-opening an errored connection

admin/billing/orb.go
Orb has lowered the max pagination limit to 100, any value more than this fails with validation error
=> set orb limit to 100

runtime/drivers/clickhouse/olap.go
closes https://github.com/rilldata/rill-private-issues/issues/1112
**Note** : This is a best effort cleanup and there are chances that views can still linger.
=> fix : minor tweaks to temporary view cleanups during clickhouse modeling

docs/docs/deploy/deploy-credentials.md, docs/docs/reference/project-files/metrics-view.md
Adding URI to reference docs
ref: https://github.com/rilldata/rill/pull/6580#event-16188207250
**Checklist:**
=> adding uri to reference

runtime/drivers/duckdb/duckdb.go, runtime/reconcilers/model.go, runtime/reconcilers/source.go
The default model and source timeout is now 3 hours so a connection can be held for 3 hours.
**Note** : A user can override with a longer timeout as well but that seems unlikely. 
**Checklist:**
=> fix : change duckdb connection held check to log after 3 hours

web-admin/src/features/billing/issues/useBillingIssueMessage.ts
closes #6617
When orgs are migrated to a managed/enterprise plan we do not clear all payment issues. Only the PaymentFailed is relevant to blocking the projects. So ignore others while showing the banner.
**Checklist:**
=> fix: orgs with migrated plans with existing payment issues

web-admin/src/features/projects/status/ProjectResources.svelte
Addresses [this Slack message](https://rilldata.slack.com/archives/C02T907FEUB/p1739190863189369). Follows https://github.com/rilldata/rill/pull/6568.
**Checklist:**
=> Admins should always see all resources on the Project Status page

web-admin/src/features/dashboards/share/ShareDashboardPopover.svelte, web-common/src/features/feature-flags.ts
Toggle to hide publicUrl.
**Checklist:**
=> feat: add toggle for hiding public url

cli/cmd/admin/start.go, cli/cmd/runtime/start.go, cli/pkg/local/app.go
Changes the Zap production loggers to use `zapcore.ISO8601TimeEncoder`, which has this format:
```
2006-01-02T15:04:05.000Z0700
```
=> Change zap timestamps to RFC3339Nano strings

admin/projects.go
This fixes an issue where project deletion after deployment creation leads to a foreign key error:
```
GET https://node-<id>.us-east1.gcp.runtime.rilldata.com/v1/ping giving up after 6 attempt(s);
ERROR: update or delete on table "projects" violates foreign key constraint "deployments_project_id_fkey" on table "deployments" (SQLSTATE 23503)
```
Since we now have relatively graceful handling and ability to retry deployment errors after the project is created, I think we can just remove the cleanup logic in the error cases.
=> Remove cleanup in error cases in CreateProject

runtime/drivers/file/repo_test.go, runtime/drivers/file/watcher.go
We are ignoring events for `ignorePaths` but ideally we should not watch them at all.
I still kept the check when processing events.
**Checklist:**
=> fix : Do not watch ignored paths in repo watcher

web-admin/src/features/scheduled-reports/metadata/RunNowButton.svelte
Report's run now button throws a type error while waiting for a new execution to show up. Adding a null check to make sure we do not break while the refetch is happening.
**Checklist:**
=> fix: report run now button throwing type error

web-common/src/features/dashboards/filters/Filters.svelte, web-common/src/features/dashboards/time-controls/time-control-store.ts, web-common/src/features/dashboards/time-controls/time-range-store.ts, web-common/src/features/dashboards/url-state/getDefaultExplorePreset.ts, web-common/src/lib/time/comparisons/index.ts
closes #1212
Our compare time range pill uses a different method than time-control-store. This leads to incorrect compare time range shown vs actually selected. Moving to using a single method to make sure things are consistant.
**Checklist:**
=> fix: default time comparison range being incorrect

web-common/src/components/data-graphic/utils.ts
The Rill Cloud Metrics project was occasionally crashing due to a histogram bug. It was reproducible when limiting a model's output to 0 records.
**Checklist:**
=> fix (Column Profiling): zero records triggered a histogram bug

cli/cmd/sudo/project/dump_resources.go, cli/cmd/sudo/project/project.go, cli/pkg/printer/resources.go
subtask for https://github.com/rilldata/rill-private-issues/issues/854
**Checklist:**
=> feat: Dump resources command for debuggability

admin/database/postgres/postgres.go
Fixes error in River Queue Logs. Logger expects a number. 
I swapped to `.QueryRowxContext()` as we only expect a single row to be returned from the count query.
**Checklist:**
=> Fix: River Trial Check error log

web-admin/src/features/organizations/users/AddUsersDialog.svelte, web-common/src/components/notifications/NotificationCenter.svelte
Closes #6655
- Fixed duplicate notifications by removing individual success/error messages from handleCreate and only showing consolidated notifications after all invites are processed
- Fixed failed invites being marked as successful by properly tracking failed/succeeded invites separately and only adding to succeeded array when the invite actually succeeds
- Prevent notification stacking by showing only one at a time
To test this PR by setting the org invite limit, `rill sudo quota set --org <org_name> --outstanding-invites 0`
https://github.com/user-attachments/assets/99cede5d-411c-4a97-8835-a5ada2b1667a
**Checklist:**
=> Prevent overlapping success/error notifications in users invite

.golangci.yml
its invalid as per schema https://golangci-lint.run/jsonschema/golangci.jsonschema.json, lint jobs are failing now. Adding it to `linters` level will require a lot of changes as its need a blank line before each return/break/continue.
=> remove invalid element

web-admin/src/features/billing/banner/BillingBannerManager.svelte, web-admin/src/features/billing/banner/BillingBannerManagerForAdmins.svelte, web-admin/src/features/billing/banner/BillingBannerManagerForViewers.svelte, web-admin/src/routes/[organization]/[project]/explore/[dashboard]/+page.svelte
closes https://github.com/rilldata/rill-private-issues/issues/1241
This PR fixes issues where billing banner component clears the banner from explore even if nothing is to be shown. This is not the full fix. We need a priority based stack system where new banners are temporarily shown and restored to previous banner.
**Checklist:**
=> fix: billing banner clearing explore banner

admin/server/users.go
To better audit usages of `rill sudo user assume` this logs the target email id.
**Checklist:**
=> fix: Add email from user assume to logs

web-common/src/features/dashboards/state-managers/selectors/dimension-table.ts
Updates the type from `V1MetricsViewTotalsResponse` to `V1MetricsViewAggregationResponse` to make it more clear that the frontend is no longer using the `MetricsViewTotals` API.
=> Nit: remove last reference to `MetricsViewTotals` API

admin/server/organizations.go, web-admin/tests/setup/setup.ts
This will make it easier to quickly see what's going wrong when the `setup` project fails.
**Checklist:**
=> refactor (e2e): break the `setup` suite into granular tests

web-admin/src/features/organizations/settings/FaviconSettings.svelte, web-admin/src/features/organizations/settings/LogoSettings.svelte, web-admin/src/routes/+layout.ts
After uploading/removing a logo/favicon org request is not invalidated in all cases. The usage of `depends` and `invalidate` is exactly how it is like the docs. Updating to have `[a-z]+:` prefix https://svelte.dev/docs/kit/$app-navigation#invalidate
**Checklist:**
=> fix: org invalidation after logo/favicon upload

cli/cmd/completion.go, cli/cmd/devtool/devtool.go, cli/cmd/query/query.go, cli/cmd/root.go, cli/cmd/sudo/sudo.go
**Changes:**
- Added validation so running `rill query` without any args doesn't fire off an empty SQL query
- Moved a few things around I noticed at the same time
**Checklist:**
=> CLI: Extra validation in `rill query` and reorder `rill -h`

web-local/playwright.config.ts
We only save trace of the tests on retry for web-local E2E. This never happens on CI so it is hard to debug failures there. Mimic web-admin's setting of `retain-on-failure` to better debug in the future.
**Checklist:**
=> fix: Save trace on failed tests for web-local E2E

cli/pkg/printer/resources.go
relates to: https://github.com/rilldata/rill/pull/6734
Sample Format outputs
```
rill query --sql "select ad_position, bid_floor, pub_name, app_or_site from auction_data_raw" --limit 3
```
`--format human`
```
AD POSITION     BID FLOOR   PUB NAME        APP OR SITE
--------------- ----------- --------------- -------------
Not Available   0.1218      GG Software     App
Not Available   0.425       Singular One    App
Not Available   0.89        Not Available   Site
```
`--format json`
```
[
{
"ad_position": "Not Available",
"app_or_site": "App",
"bid_floor": 0.1218,
"pub_name": "GG Software"
},
{
"ad_position": "Not Available",
"app_or_site": "App",
"bid_floor": 0.425,
"pub_name": "Singular One"
},
{
"ad_position": "Not Available",
"app_or_site": "Site",
"bid_floor": 0.89,
"pub_name": "Not …
```
=> fix: Support CSV and Table output for `rill query` --format

runtime/drivers/duckdb/duckdb.go
Some global properties are set in local scope by default.
Detailed explanation by Mark here : https://github.com/duckdblabs/rilldata/issues/27#issuecomment-2676155876
**Checklist:**
=> fix: global properties should be set with global scope

cli/cmd/start/start.go, runtime/server/queries_timeseries_test.go
Prompts the user if they are trying to run `rill start` in the homedir.
Still allowing `rill start .` as that seems intentional
**Checklist:**
=> fix: check for homedir on rill start

admin/worker/run_autoscaler.go
Logs to use `organization_name`
=> Use org name for autoscaler logs

web-admin/src/features/dashboards/listing/DashboardsTableCompositeCell.svelte, web-admin/src/features/dashboards/listing/LastRefreshedDate.svelte, web-admin/src/features/dashboards/listing/selectors.ts
Previously, the "last refreshed" date was only visible to project admins because it was stored on the `model` (admin-only access). Since PR #6735 replicated this date onto the `metricsView` (accessible to all users), this PR updates the UI to integrate with this new property and display the date to everyone.
**Checklist:**
=> feat (Explore): Show the "last refreshed" date to everyone

web-common/src/components/virtualized-table/core/Cell.svelte
https://github.com/rilldata/rill-private-issues/issues/1279
Do not dispatch `select-item` is shift key was pressed.
**Checklist:**
=> fix: do not select if shift key is used

web-admin/src/routes/[organization]/[project]/explore/[dashboard]/+page.svelte
[Discussed in Slack](https://rilldata.slack.com/archives/C02T907FEUB/p1740402458606639?thread_ts=1738937017.202969&cid=C02T907FEUB)
**Checklist:**
=> fix (Explore): Show error component when there's no valid `Explore` resource

web-common/src/features/dashboards/time-controls/new-time-controls.ts
While bucketing the time ranges from yaml we do not validate iso and throw an error if it fails. This is an issue for `inf` or `All time` defined in the yaml.
**Checklist:**
=> fix: all time in yaml crashing the app

web-admin/src/client/redirect-utils.ts, web-admin/src/routes/+layout.ts
Ensures users are always redirected to the login page when their auth token expires. Follows [#6733](https://github.com/rilldata/rill/pull/6733).
**Checklist:**
=> fix (Cloud UI): Always redirect to login when auth token expires

.github/workflows/web-test-e2e.yml, web-admin/tests/setup/setup.ts
Captures and uploads logs from the `admin` and `runtime` services. These'll help debug any failing tests. Like the Playwright reports, this log file can be found in the GitHub Action's summary "artifacts" section:
**Checklist:**
=> e2e: Capture logs from Go services

web-common/src/features/dashboards/pivot/pivot-table-transformations.ts
Pivot table in some cases crashed when sorted on a delta column for a measure within a column dimension.
Context : https://rilldata.slack.com/archives/CTCJ58H3M/p1740566509343249
**Checklist:**
=> fix: pivot sort on delta column

web-common/src/components/forms/Input.svelte, web-common/src/features/dashboards/filters/measure-filters/MeasureFilterForm.svelte
Force measure filter form errors to always display.
**Checklist:**
=> tweak: display measure error

web-common/src/features/scheduled-reports/time-utils.ts, web-common/src/features/scheduled-reports/utils.ts
If monthly part of a cron is `*` we are incorrectly parsing it as NaN. So switching to monthly in a report edit will make it NaN from then on.
**Checklist:**
=> fix: monthly parsing of report cron

web-common/src/features/canvas/components/charts/Chart.svelte, web-common/src/features/canvas/components/charts/builder.ts, web-common/src/features/canvas/components/charts/util.ts
https://www.notion.so/rilldata/Expression-parse-error-Roy-1a7ba33c8f57806e98a4fd434e77083a
Sanitize measure name used for identifying formatter. Likely a bug in Vega Lite where it does not support space in `formatType`
=> fix: support space in measure dimension names for charts

runtime/pkg/observability/logging.go
It seems datadog now allows OTEL kind of trace IDs.
Only thing is that it should be named `dd.trace_id` and `dd.span_id`. I plan to make this remapping as part of datadog pipeline.
=> skip setting datadog trace id

admin/server/billing.go
For manually migrated orgs, stripe customer id won't be present. Idea was 
- if they upgrade to Teams plan then we will create stripe customer for them and link it using cli. 
- If they upgrade to enterprise plan then its not needed
So perform force access before validation (for enterprise) so we don't hit stripe APIs.
=> check force access before performing plan validation

.github/workflows/go-lint.yml, admin/database/database.go, admin/database/postgres/postgres.go, admin/jobs/jobs.go, admin/jobs/noop.go, admin/jobs/river/org_jobs.go, admin/jobs/river/river.go, cli/cmd/devtool/data/cloud-deps.docker-compose.yml
This PR creates two jobs to assist with dangling resources. https://github.com/rilldata/rill/issues/6607
- **Job 1** Logs inactive organizations and hibernates projects. The criteria for the current logic is that an organization must  have no users.
- **Job 2** Enables inactive organizations to be deleted. This is only manual triggered at this time.
> Additionally adds pgweb to devtool containers
**Checklist:**
=> Fix: Jobs to clean Dangling Resources

web-common/src/components/data-graphic/guides/Axis.svelte, web-common/src/features/dashboards/time-series/MeasureChart.svelte, web-common/src/lib/number-formatting/format-measure-value.ts, web-common/src/lib/number-formatting/humanizer-types.ts, web-common/src/lib/number-formatting/strategies/per-range-axis-options.ts
https://github.com/rilldata/rill-private-issues/issues/1346
For axis formatting, replace `NumberKind` with measure formatter.
Create a new formatter context for `axis`
**Checklist:**
=> refac: create range spec for measure axis formatting

web-common/src/features/dashboards/pivot/pivot-merge-filters.spec.ts, web-common/src/features/dashboards/pivot/pivot-merge-filters.ts, web-common/src/features/dashboards/stores/filter-utils.ts
`mergeFilter` method is used in some places to easily apply additional filters on top of the global filter set. It was not handling both `in` and `not in` expressions for the same dimension.
Handling `in` and `not in` separately. Also supporting merging non-joiner expressions.
**Checklist:**
=> fix: `mergeFilter` not working as expected for `in` and `not in` expressions for same dimension

web-common/src/features/canvas/components/charts/area/spec.ts, web-common/src/features/canvas/components/charts/line-chart/spec.ts, web-common/src/features/templates/charts/utils.ts
The line and area charts would break when there were other special characters like `'`. This PR addresses it by escaping them.
**Checklist:**
=> Fix: handle special characters in charts

web-common/src/features/canvas/stores/canvas-component.ts, web-common/src/features/canvas/stores/time-control.ts
=> Fix: preserve local filters for canvas on refresh

.prettierignore, web-admin/.gitignore, web-admin/tests/embeds.spec.ts, web-admin/tests/explores.spec.ts, web-admin/tests/setup/projects/openrtb/README.md, web-admin/tests/setup/projects/openrtb/dashboards/auction_explore.yaml, web-admin/tests/setup/projects/openrtb/dashboards/bids_explore.yaml, web-admin/tests/setup/projects/openrtb/metrics/auction_metrics.yaml, web-admin/tests/setup/projects/openrtb/metrics/bids_metrics.yaml, web-admin/tests/setup/projects/openrtb/models/auction_data_model.sql, web-admin/tests/setup/projects/openrtb/models/bids_data_model.sql, web-admin/tests/setup/projects/openrtb/rill.yaml, web-admin/tests/setup/projects/openrtb/sources/auction_data_raw.yaml, web-admin/tests/setup/projects/openrtb/sources/bids_data_raw.yaml, web-admin/tests/setup/setup.ts, web-admin/tests/setup/teardown.ts
This PR embeds a dedicated OpenRTB project into `web-admin/tests` rather than re-use the OpenRTB project in the `rill-examples` repo.
Benefits:
- Downsamples the data source for faster ingestion.
- Provides a flexible space to expand test cases (see https://github.com/rilldata/rill/issues/6707) without impacting the example project.
- Simplifies global setup by eliminating the need to pull an external repo.
**Checklist:**
=> e2e (Cloud): Add dedicated test project

web-common/src/components/vega/VegaLiteRenderer.svelte
With an increased number of elements and custom tooltip objects in our charts, using SVG is causing subtle lag. In this PR, I’m switching Vega’s renderer from SVG to Canvas. I did some preliminary QA, and the performance appears to be improved.
**Checklist:**
=> Refac: Move to canvas from svg for vega charts

web-common/src/features/canvas/components/markdown/Markdown.svelte
Add style for markdown sections such as lists, horizontal lines etc.
**Checklist:**
=> Tweak: Canvas markdown styles

admin/server/server.go, runtime/server/server.go
[Cache unavailability should be a no-op for runtimes/admin](https://github.com/rilldata/rill-private-issues/issues/1274)
If the cache is unavailable, we can bypass the rate limiting middleware. This will avoid unnecessary errors from the middleware and only errors from the cache connection.
**Checklist:**
=> feat: skip rate limiting on cache connection error

web-common/src/components/vega/VegaLiteRenderer.svelte, web-common/src/features/canvas/components/charts/Chart.svelte, web-common/src/features/canvas/components/charts/area/spec.ts, web-common/src/features/canvas/components/charts/line-chart/spec.ts, web-common/src/features/canvas/components/charts/util.ts
The `canvas` renderer mode in Vega was hiding the `rule` mark in line and area charts on Canvas dashboards. However, it appeared to work fine for Explore dashboards.
As a stopgap fix for `release-0.57` this PR reverts area and line charts back to `svg`. Further debugging is needed to determine the exact issue. My guess is that on Canvas dashboards, we might not be setting the chart container's size or bounds correctly.
**Checklist:**
=> fix: rule placement in canvas area chart

web-common/src/features/dashboards/time-controls/time-range-store.ts, web-common/src/features/dashboards/url-state/convertExploreStateToURLSearchParams.ts, web-common/src/features/dashboards/url-state/convertURLToExplorePreset.ts, web-common/src/features/dashboards/url-state/url-state-variations.spec.ts
More details: https://www.notion.so/rilldata/Custom-default-time-range-returns-undefined-comparison-range-1b0ba33c8f5780c1aba1dedba800ecaf
When the selected default time range is non-standard then the comparison time range is not defined. It is ok to set it to previous period in this case.
**Checklist:**
=> fix: default comparison when a non-standard time range is selected as default

runtime/metricsview/query.go, runtime/pkg/mapstructureutil/mapstructureutil.go, runtime/resolvers/metrics.go, runtime/resolvers/testdata/metrics_comparisons.yaml
Without the fix, test will use cached results from previous query and thus fail. Cause of this failure as well -https://github.com/rilldata/rill/actions/runs/13655204432/job/38178639449
=> add structs to mv query cache key

web-common/src/features/canvas/components/table/TableTemplate.svelte, web-common/src/features/canvas/components/table/util.ts
Clears all table cache on destroy
**Checklist:**
- [] Covered by tests
=> Canvas: clear all table cache on unmount

web-common/src/lib/arrayUtils.spec.ts, web-common/src/lib/arrayUtils.ts
closes https://github.com/rilldata/rill-private-issues/issues/1359
This lead to weird interactions when list of dimensions/measures has duplicates.
**Checklist:**
=> Fix: Handle duplicates in arrayUnorderedEquals

admin/database/database.go, admin/database/postgres/migrations/0065.sql, admin/database/postgres/postgres.go, admin/server/projects.go, admin/server/rbac_test.go, admin/user.go
**Changes:**
- When a project-level invite is created, it automatically creates an org-level guest invite as well (unless another org-level invite already exists)
- When removing an org-level invite, it automatically removes all project-level invites as well
Contributes to https://github.com/rilldata/rill/issues/6578
**Checklist:**
=> Connect project invites to org invites

runtime/catalog_cache.go
After this [change](https://github.com/rilldata/rill/pull/6661) runtime will not return a resource with type `Source` so this backward compatibility check should not be required.
This check breaks backward compatibility because during the first start existing sources has to be present in catalog till they are deleted and recreated as models.
=> fix: existing projects with sources doesn't work due to missing source in catalog

runtime/reconcilers/explore.go, runtime/reconcilers/explore_test.go
Issue: https://github.com/rilldata/rill/issues/6559
https://github.com/user-attachments/assets/cf52f293-f3ed-4604-9b78-5cef1a114cd8
> Expected flow works the same in local and cloud
```yaml
type: explore
title: "Programmatic Ads Auction"
metrics_view: auction_metrics
dimensions: '*'
measures: '*'
security:
access: "{{ .user.admin }} OR '{{ .user.domain }}' == 'rilldata.com'"
time_zones:
- America/Los_Angeles
- America/Chicago
- America/New_York
- Europe/London
- Europe/Paris
embeds:
hide_pivot: true
defaults:
measures:
- requests
- avg_bid_floor
- 1d_qps
dimensions:
- app_site_name
- app_site_cat
- ad_size
- device_state
time_range: P7D
---
version: 1
model: "auction_data_model"
type: metrics_view
timeseries: "__time"
smallest_time_grain: "hour"
security:
access: true
row_filter: > …
```
=> fix: Derived explore security policies

package-lock.json
Updates the `browserlist` database (and removes this warning from our build process)
=> chore (deps): Update `browerslist` db

web-common/src/features/canvas/ComponentHeader.svelte, web-common/src/features/canvas/stores/canvas-entity.ts
https://www.notion.so/rilldata/Comparisons-do-not-work-when-local-comparison-is-on-but-global-comparison-is-off-1b4ba33c8f5780589f9dd73de15afea9?pvs=23
- Follow local filter's comparison toggle 
- Increase `z-index` for local filters icon so that it's visible over KPI grid
**Checklist:**
=> fix: follow local filters comparison toggle

runtime/compilers/rillv1/parse_canvas.go, web-admin/src/routes/[organization]/[project]/-/dashboards/[dashboard]/+page.svelte
https://www.notion.so/rilldata/In-Rill-cloud-Canvas-does-not-change-the-tab-header-1b4ba33c8f578049be59d4737b12db90
**Checklist:**
=> fix: add header title for canvas

web-common/src/components/vega/vega-config.ts, web-common/src/features/canvas/AddComponentDropdown.svelte, web-common/src/features/canvas/components/charts/area/spec.ts, web-common/src/features/canvas/components/charts/index.ts
- Do not use normalized 100% stacked bar chart when a new chart is added
- Use time as the default dimension for charts
- Orient Y axis to the left of the chart
**Checklist:**
=> Canvas: Chart improvements

web-common/src/features/dashboards/dashboard-utils.ts
The keyword "custom" was still being used for canvas paths.
=> fix: incorrect url path for canvas hrefs

web-common/src/features/canvas/AddComponentDropdown.svelte, web-common/src/features/canvas/components/charts/query.ts, web-common/src/features/dashboards/pivot/pivot-merge-filters.spec.ts, web-common/src/features/dashboards/pivot/pivot-merge-filters.ts
Ref issue: https://www.notion.so/rilldata/Chart-filters-don-t-seem-to-be-working-1b4ba33c8f5780efbd4aebd740b852b1
**Checklist:**
=> fix: merging expressions with (i)like and subquery filters removing them instead of retaining them

web-common/src/features/connectors/olap/createModel.ts, web-common/src/features/dashboards/url-state/filters/converters.ts, web-common/src/features/entity-management/name-utils.ts, web-common/src/lib/string-utils.ts
Addresses [this Slack report](https://rilldata.slack.com/archives/C02T907FEUB/p1741981598994669)
**Checklist:**
=> fix (Models): Escape non-standard table names

web-common/src/features/canvas/components/image/Image.svelte, web-common/src/features/canvas/components/image/index.ts, web-common/src/features/canvas/components/image/util.ts, web-common/src/features/canvas/components/markdown/index.ts, web-common/src/features/canvas/components/markdown/util.ts, web-common/src/features/canvas/inspector/AlignmentInput.svelte, web-common/src/features/canvas/inspector/ParamMapper.svelte, web-common/src/features/canvas/inspector/types.ts
https://www.notion.so/rilldata/Add-alignment-buttons-from-markdown-to-Image-sidebar-Currently-it-s-always-center-aligned-1b4ba33c8f578043bd8bc55faef14f58
**Checklist:**
=> feat: add alignment input for image

runtime/drivers/duckdb/model_executor_motherduck_self.go, runtime/drivers/duckdb/model_executor_self.go, runtime/drivers/duckdb/model_manager.go, runtime/drivers/duckdb/olap.go, runtime/drivers/olap.go, runtime/pkg/rduckdb/db.go, runtime/pkg/rduckdb/db_test.go
This is in continuation of this [PR](https://github.com/rilldata/rill/pull/6862). Fixing models as well.
**Checklist:**
=> fix motherduck duckdb model executor

web-common/src/features/file-explorer/new-files.ts
`title`is deprecated, use `display_name` instead
**Checklist:**
=> fix: use display name instead of title

runtime/drivers/clickhouse/clickhouse.go, runtime/drivers/druid/druid.go, runtime/drivers/pinot/pinot.go
Instead of hardcoding here - https://github.com/rilldata/rill/pull/6935 lets make it configurable. Would have liked to use `*int` for this config as `0` means unlimited but we already have this as `int` in clickhouse configs since sometime. (Not sure if anybody is setting it otherwise can convert all to pointers)
=> make max open conns configurable

runtime/drivers/duckdb/model_executor_objectstore_self.go
Previously we expected the endpoint of type `https://<>`
Duckdb expects the endpoint of type `<>` i.e. without scheme.
**Checklist:**
=> fix: backward compatibility for s3 compatibile servers with duckdb

web-common/src/features/canvas/stores/time-control.ts
https://www.notion.so/rilldata/Canvas-breaks-for-metrics_views-without-time-column-1b4ba33c8f5780ceb114f19172ada1d3
**Checklist:**
=> Fix: disable time summary query for metrics without time dimension

web-common/src/features/dashboards/time-controls/super-pill/components/Comparison.svelte, web-common/src/features/dashboards/time-controls/time-range-store.ts, web-common/src/lib/time/types.ts
The process by which default comparison periods were being derived was returning `undefined` when the primary time range was one not listed in the Explore YAML `time_ranges` list. So, `CUSTOM` or a `default_time_range`, implicit time range or URL time range that was not in the list.
Because of that, the `Calendar` component (via the `Comparison` component) was falling back to DateTime.now() instead of the end of the primary interval. As such, when selecting dates, the local time zone was being used instead of the selected time zone.
This is a patch fix. The code requires significant refactoring, some of which will be addressed by rillTime.
**Checklist:**
=> fix: comparison fallbacks

web-common/src/features/connectors/olap/DatabaseExplorer.svelte, web-common/src/features/connectors/olap/selectors.ts
Reverts a small regression introduced in https://github.com/rilldata/rill/pull/6774
**Checklist:**
=> fix (Connector Explorer): Don't hide OLAP tables when there's no explicit `database`

runtime/compilers/rillv1/parse_metrics_view.go, runtime/compilers/rillv1/template.go, runtime/compilers/rillv1/template_test.go, runtime/connections.go, runtime/reconcilers/migration.go, runtime/reconcilers/model.go, runtime/resolvers/glob.go, runtime/resolvers/sql.go, runtime/security.go, runtime/server/canvases.go
https://github.com/rilldata/rill-private-issues/issues/1372
Currently we don't throw error if variables are missing. I see following [TODO](https://github.com/rilldata/rill/blob/48e0d184db14844251677f5bff287b7b5e55e8a5/runtime/compilers/rillv1/template.go#L257) for the same. 
This is definitely problematic for connectors and leads to bad user experience as highlighted in the issue.
**Checklist:**
=> throw error on missing template keys for connectors

web-common/src/features/canvas/components/charts/util.ts, web-common/src/features/canvas/components/markdown/Markdown.svelte
- Align p tags in markdown as per alignment
- Use "over" in chart title when x Axis is Time
**Checklist:**
=> Canvas: nit fixes

web-common/src/features/feature-flags.ts
Address https://www.notion.so/rilldata/Allow-this-feature-flag-to-be-used-simultaneously-with-leaderboardMeasureCount-feature-flag-1bdba33c8f5780488d2bca320dc69215
When an invalid flag is encountered, the function returns immediately instead of continuing to process the remaining valid flags. We will skip that flag and continue processing the remaining flags to fix this.
To repro:
1. Check out `bgh/drag-poc`
2. Apply this in the `rill.yaml`
```
features:
- reorderMeasuresDimensions
```
3. With this PR, it will now process the `reorderMeasuresDimensions` instead of early returning from the function.
**BTW**
- `leaderboardMeasureCount` is only available in https://github.com/rilldata/rill/pull/6816
- `reorderMeasuresDimensions` is only available in https://github.com/rilldata/rill/pull/6949 …
=> Process remaining valid flags

web-common/src/components/data-types/Base.svelte, web-common/src/components/data-types/FormattedDataType.svelte, web-common/src/components/data-types/Number.svelte
The `Base` component is currently used in contexts where it's possible to render hundreds or thousands of elements. There is an effort to remove the need for this formatter component and/or virtualize in places where it is used, but, in the meantime, we should not be querying the DOM for this info. If the bounding info is still needed in places where fewer elements are being rendered, a wrapper element can be used.
=> tweak: remove bounding client binding

admin/server/reports.go, cli/cmd/devtool/data/cloud-deps.docker-compose.yml
Resolves one more edge case where user who accidentally sign up to Rill get open link and they can request access when they open the report link. Main issue happens if admins accidentally accepts the request assuming they are giving access just to the report.
=> check project perms for report open link

web-common/src/features/dashboards/leaderboard/Leaderboard.svelte, web-common/src/features/dashboards/leaderboard/LeaderboardDisplay.svelte, web-common/src/features/dashboards/leaderboard/LeaderboardRow.svelte, web-common/src/features/dashboards/state-managers/selectors/data-formatting.ts
Reported by https://rilldata.slack.com/archives/C02T907FEUB/p1743004498455459
Closes https://github.com/rilldata/rill-private-issues/issues/1459
After [the recent changes in multiple metrics](https://github.com/rilldata/rill/pull/6816), it has come to our attention that the measure formatting still relies on the active measure. When the `leaderboardMeasureCount` flag is enabled, we want to use each measure's own formatter rather than relying on the active measure's format.
See the recording:
https://github.com/user-attachments/assets/fb6ae8a1-237d-49ba-b7cc-f5e160bf7ed3
**Checklist:**
=> Hotfix: measures formatter

web-common/src/features/dashboards/filters/Filters.svelte
The `as of` element was using the end of the currently selected time range as its reference rather than the overall bounds of the dataset. This was a holdover from a previous version of this element was not the intended behavior for release.
**Checklist:**
=> fix: incorrect as of reference

runtime/drivers/duckdb/model_executor_self_file.go, runtime/drivers/duckdb/model_executor_self_file_test.go, runtime/drivers/duckdb/testdata/expected_export/expected_output.csv
Closed https://github.com/rilldata/rill/issues/6765
actually there are some more inconsistencies in out csv apart from date which can only be solve when we use duckdb export for both. we can handle in separately 
we can check the inconsistencies with 
vimdiff runtime/drivers/duckdb/testdata/expected_export/expected_output.csv runtime/drivers/file/testdata/expected_export/expected_output.csv
**Checklist:**
=> output datetime inconsistance in csv export output from duck vs file

admin/server/server.go, runtime/pkg/ratelimit/ratelimiter.go, runtime/server/server.go
Checks the error returned from the calls to `s.limiter.Limit` and allow requests to proceed on cache server connection errors.
Resolves: https://github.com/rilldata/rill-private-issues/issues/1392
**Checklist:**
=> Allow requests to proceed on cache server connection errors

runtime/drivers/registry.go
When we saw OOMes on projects ingesting from Snowflake, there was no limit on concurrent execution and the parquet row buffer group size to be kept in memory was 512MB which has now been reduced to [64MB](https://github.com/rilldata/rill/blob/88dc93d0058026090c3cd4eea2f778de4c380ee5/runtime/drivers/snowflake/warehouse.go#L30-L31)
Lets experiment with 5 and reduce for projects where we see OOMes.
=> increase default maximum number of concurrent model executions to 5

docs/docs/reference/project-files/canvas-dashboards.md, runtime/compilers/rillv1/parse_canvas.go, web-admin/src/routes/[organization]/[project]/canvas/[dashboard]/+page.svelte, web-local/src/routes/(viz)/canvas/[name]/+page.svelte
Adds `banner` to canvas. Was already present in proto.
**Checklist:**
=> fest: add banner to canvas

web-common/src/components/vega/VegaRenderer.svelte, web-common/src/components/vega/vega-embed-options.ts
Post https://github.com/rilldata/rill/pull/6988 TDD Vega charts are not rendering any marks. This is a hotfix to disable expression interpreter for Vega charts until we can debug what is going wrong.
**Checklist:**
=> fix: empty Vega chart for TDD

web-admin/src/features/scheduled-reports/metadata/ReportMetadata.svelte, web-common/src/features/exports/ExportMenu.svelte, web-common/src/features/scheduled-reports/ScheduledReportDialog.svelte, web-common/src/features/scheduled-reports/utils.ts
Now, if for some reason the Scheduled Report query cannot be constructed, we disable the Scheduled Report menu item.
This is a fairly minimal, incremental fix to avoid malformed reports. A further improvement could be to ensure that the various calls to `getQuery` passed into the `<ExportMenu />` cannot return `undefined` in the first place.
[Addresses this Slack thread](https://rilldata.slack.com/archives/C02T907FEUB/p1743003794456339)
**Checklist:**
=> fix (Reports): safer typing to prevent malformed reports

web-local/tests/setup/base.ts
This appears to have solved some of the issues with test flakiness in web-local, especially when running them on my local machine.
=> test: add global timeout

runtime/runtime.go
The problem is that `r.Instance(ctx, instanceID)` returns the same cached value/pointer to all callers. So to avoid race conditions, it must not be mutated directly.
=> Clone instance before mutating it in `UpdateInstanceConnector`

runtime/drivers/duckdb/olap.go, runtime/resolvers/testdata/models_incremental_duckdb.yaml, runtime/resolvers/testdata/s3_connector.yaml
This bug surfaced after we started setting `pre_exec` automatically for models that contain `s3://`.
**Checklist:**
=> Fix incremental inserts being skipped when a `pre_exec` is configured for the `merge` strategy on DuckDB

web-common/src/features/canvas/CanvasBuilder.svelte, web-common/src/features/canvas/CanvasDashboardEmbed.svelte, web-common/src/features/canvas/EditableCanvasRow.svelte, web-common/src/features/canvas/ElementDivider.svelte, web-common/src/features/canvas/RowDropZone.svelte, web-common/src/features/canvas/RowWrapper.svelte, web-common/src/features/canvas/layout-util.ts, web-common/src/features/workspaces/CanvasWorkspace.svelte
- Creates a new `EditableCanvasRow` component that houses the resizing and rendering logic
- Renames `RowBasedCanvas` to `CanvasBuilder`
- Creates a shared store to track the current mouse position
- New `EditableCanvasRow` component manages its own column/row resizing state rather than co-opting the spec object
- Fixes an issue where multiple resizing events in quick succession would cause unnecessary updates
- Uses the existing `activeDivider` store to capture whether or not a row or column is being resized
- Variable renaming for clarity
**Checklist:**
=> refac(canvas): column and row resizing

web-admin/src/features/embeds/init-embed-public-api.ts, web-common/src/features/dashboards/url-state/convertExploreStateToURLSearchParams.ts
Splitting https://github.com/rilldata/rill/pull/6964 into smaller PRs.
This deals with improvements to `convertExploreStateToURLSearchParams` to avoid sending extra params when compression is not needed.
**Checklist:**
=> Improve url compression function signature

web-common/src/features/dashboards/leaderboard/Leaderboard.svelte, web-common/src/features/dashboards/leaderboard/LeaderboardDisplay.svelte, web-common/src/features/dashboards/leaderboard/LeaderboardHeader.svelte, web-common/src/features/dashboards/leaderboard/LeaderboardRow.svelte, web-common/src/features/dashboards/state-managers/selectors/active-measure.ts, web-common/src/features/dashboards/state-managers/selectors/measures.ts, web-common/src/features/dashboards/workspace/Dashboard.svelte
Closes #7008
When using the leaderboard measure count feature flag, NaN values were appearing in the percent of total column. This was happening because we were querying totals for `leaderboardMeasureNames` but displaying data for `visibleMeasures`, causing a mismatch where some measures didn't have corresponding totals.
- Updated the totals query in `Leaderboard.svelte` to use `visibleMeasures` instead of `leaderboardMeasureNames` when `leaderboardMeasureCountFeatureFlag` is true
- Modified the `leaderboardTotals` calculation to use the same set of measures as the totals query
- Ensured consistent measure selection between data and totals queries
**Reviewers**
You must enable `leaderboardMeasureCount` and `reorderMeasuresDimensions` to test this branch properly.
**Checklist:**
=> Use visibleMeasures for querying and sorting in `leaderboardMeasureCount`

web-common/src/components/menu/DashboardMetricsDraggableList.svelte, web-common/src/features/dashboards/leaderboard/LeaderboardControls.svelte, web-common/src/features/dashboards/time-series/MetricsTimeSeriesCharts.svelte, web-common/src/features/feature-flags.ts, web-local/tests/explores/dimension-and-measure-selection.spec.ts
To lift the feature flag for `reorderMeasuresDimensions` in `release-0.59`
**Checklist:**
=> Remove `reorderMeasuresDimensions` flag

web-common/src/features/dashboards/leaderboard/Leaderboard.svelte, web-common/src/features/dashboards/leaderboard/LeaderboardHeader.svelte, web-common/src/features/dashboards/leaderboard/LeaderboardRow.svelte
Fixes https://www.notion.so/rilldata/Background-bar-charts-seem-broken-1c8ba33c8f5780f69e8bf5c93447a315 and https://www.notion.so/rilldata/Blue-bars-showing-inaccurately-1c8ba33c8f57817e9411f82cc8d696fc
Also reported in https://rilldata.slack.com/archives/C087E4NS7FH/p1743541702913749
1 measure
1+ measures
**Checklist:**
=> Fix leaderboard bg gradients

web-admin/src/components/layout/ContentContainer.svelte, web-admin/src/features/organizations/OrganizationHero.svelte, web-admin/src/routes/[organization]/+page.svelte
Currently, the organization page does not correctly handle many projects. See the background color change in the "demo" organization:
Fixed by this PR.
**Checklist:**
=> fix (Org Projects): Handle overflow

web-common/src/features/dashboards/leaderboard/LeaderboardControls.svelte, web-common/src/features/dashboards/time-series/MetricsTimeSeriesCharts.svelte
Due to a bad merge select all measures/dimensions is broken on `release-0.58` branch
**Checklist:**
=> fix: select all measures/dimensions in version 0.58

web-common/src/features/dashboards/leaderboard/Leaderboard.svelte, web-common/src/features/dashboards/leaderboard/LeaderboardDisplay.svelte, web-common/src/features/dashboards/state-managers/actions/core-actions.ts
https://rilldata.slack.com/archives/C02T907FEUB/p1743691556738219?thread_ts=1743689026.881769&cid=C02T907FEUB
**Before**
1 measure count, all visible measures are being ran
**After**
the network calls are now based on the leaderboard measures (selected measure count)
https://github.com/user-attachments/assets/857ef1df-cca5-4811-b63c-1ca1db998295
**Checklist:**
=> Perf fix: leaderboard measures requests

.github/workflows/web-test-e2e.yml, web-admin/src/components/layout/ContentContainer.svelte, web-admin/tests/setup/setup.ts
This is an attempt to fix unstable e2e OpenRTB project deploy. Earlier it was stuck at getting dashboard listing. Now after adding a refresh there it gets stuck at getting the last refreshed which is available after reconcile is finished.
1. Locally the resources do reconcile after a long time. This PR stabilised the setup locally.
2. On CI there is still an issue with `sqlite_scanner` which seems to be blocking this. Pre-loading duckdb extensions as a temp fix.
**Checklist:**
=> fix: unstable e2e cloud setup

web-common/src/components/menu/DashboardMetricsDraggableList.svelte
https://rilldata.slack.com/archives/C02T907FEUB/p1743704699843549?thread_ts=1743689026.881769&cid=C02T907FEUB
This pull request expands the clickable area for hidden items within the `DashboardMetricsDraggableList`. As a result, users can now deselect a hidden item not only by clicking the eye icon but also by interacting with the list item itself.
https://github.com/user-attachments/assets/0e808ff1-9edb-45b6-86da-3e9da2895aa5
**Checklist:**
=> Ability to deselect hidden item

runtime/drivers/duckdb/duckdb.go
Not sure but feel like some not install sqlite is not full finished and load sqlite run. Trying changing the order of install and load so give some time between install and load
Closes [#1505](https://github.com/rilldata/rill-private-issues/issues/1505)
**Checklist:**
=> change_install_and_load_order

web-admin/src/features/bookmarks/BookmarksDropdownMenuItem.svelte, web-admin/tests/bookmarks.spec.ts
Currently, the bookmark tests cannot be run twice because there's no teardown. This PR adds tests to delete the bookmarks, so that the test suite can be run twice-in-a-row.
**Checklist:**
=> e2e (Bookmarks): Add tests to delete bookmarks

runtime/parser/parse_metrics_view.go
`allow_custom_timerange` was introduced for explore and canvas dashboards which defaults to true.
It was missing for legacy dashboards, this PR adds a always true custom timerange for legacy dashboards.
**Checklist:**
=> fix: allows show custom of legacy dashboards

web-common/src/features/workspaces/ModelWorkspace.svelte
Previously:
Now:
[Reported in Slack](https://rilldata.slack.com/archives/C02T907FEUB/p1744214629290899)
**Checklist:**
=> fix (Models): Always show the output table preview, even if a partition has errors

web-common/src/features/dashboards/state-managers/selectors/dimensions.ts
https://rilldata.slack.com/archives/C02T907FEUB/p1744127176140839
This pull request attempts to fix the typerror issue where visible dimensions are undefined.
**Checklist:**
=> Handle undefined visible dimensions check

web-common/src/components/menu/DashboardMetricsDraggableList.svelte
Clicking on the eye icon in measure/dimension drop down in the hidden list triggers twice.
**Checklist:**
=> fix: clicking on eye icon to show measure/dimension triggering twice

web-common/src/components/menu/DashboardMetricsDraggableList.svelte
Reported in https://rilldata.slack.com/archives/C02T907FEUB/p1744295510607029
This pull request fixes the styling tweak of long draggable list item names by truncation.
https://github.com/user-attachments/assets/2f4d42d3-54bf-437c-88d0-9b140b6a90ff
**Checklist:**
=> hotfix: truncate long draggable list item names

web-common/src/features/canvas/components/leaderboard/LeaderboardDisplay.svelte, web-common/src/features/canvas/components/leaderboard/index.ts
- Fix E2E error for canvas leaderboards
- Removes the reference of explore state managers in canvas leaderboards.
**Checklist:**
=> fix: remove explore state managers from canvas leaderboards

web-common/src/features/dashboards/state-managers/actions/measures.ts, web-common/src/features/dashboards/state-managers/selectors/leaderboard.ts, web-common/src/features/dashboards/url-state/url-state-variations.spec.ts
This pull request ensures that leaderboard measures now respect the order of visible measures.﻿
Closes https://www.notion.so/rilldata/Order-of-Measures-in-Leaderboard-grid-don-t-match-the-order-of-measures-in-the-measure-dropdown-1d2ba33c8f578028a0a6fc0016758cb2
This will not be cherry-picked if we haven't branched out for the new release.
https://github.com/user-attachments/assets/581fd935-7557-4d99-b4e3-ef4a49c711b2
**Checklist:**
=> fix: respect leaderboard measure names based on visible measures

web-common/src/features/dashboards/url-state/convert-partial-explore-state-to-url-params.ts, web-common/src/features/dashboards/url-state/explore-web-view-specific-url-params.ts, web-common/src/features/dashboards/url-state/url-params-strip-utils.spec.ts, web-common/src/features/dashboards/url-state/url-params-strip-utils.ts
We have a default set of params that we strip from the url. But we do not take into account the difference in view. This is an issue only for pivot since there is an overlap in param name but they mean different things.
We should revisit the stripping and look at doing it using explore state directly.
**Checklist:**
=> fix: default params strippings for non-explore views

admin/deployments.go, admin/projects.go
This PR changes calls to `UpdateDeployment` to a) run concurrently, b) not exit early if an update errors, c) only return an error if the prod deployment errored.
This fixes a recent issue where a broken non-prod deployment was blocking deploys and variable updates.
Closes https://github.com/rilldata/rill-private-issues/issues/1580
**Checklist:**
=> Prevent a broken deployment from blocking updates to healthy deployments

eslint.config.js, package-lock.json, package.json, web-common/tsconfig.json
This PR upgrades the Vitest ESLint plugin to the latest version and properly integrates it into our ESLint configuration.
(The PR also makes a small edit to the `web-common/tsconfig.json`, which mistakenly regressed in another PR's bad merge.) 
**Checklist:**
=> chore: Upgrade and use the Vitest ESLint plugin

web-admin/tests/setup/projects/openrtb/metrics/bids_metrics.yaml
Close [#1553](https://github.com/rilldata/rill-private-issues/issues/1553)
Actually, the null-like value appears at the top because it's not a real `NULL` — it's a `NaN`. We later convert it to `NULL` in the Go code. According to the DuckDB documentation:
`NaN compares equal to NaN and is greater than any other floating-point number.`
This means NaN will sort higher than any valid numeric value, which explains why it shows up first in sorted results.
**Checklist:**
=> handle divide by zero causing null value to appear on top

admin/server/github.go
Closed [#1590](https://github.com/rilldata/rill-private-issues/issues/1590)
**Checklist:**
<div id='description'>
<h3>Summary by Bito</h3>
This PR enhances the GitHub integration component by modifying error handling to properly ignore NoErrAlreadyUpToDate errors. The change prevents unnecessary error propagation when remote repositories are already up-to-date during push operations, improving the overall robustness of Git operations.
<br>
<br>
<b>Unit tests added</b>: False
<br>
<br>
<b>Estimated effort to review (1-5, lower is better)</b>: 1
</div>
=> Ignore NoErrAlreadyUpToDate error

web-common/src/features/dashboards/leaderboard/Leaderboard.svelte, web-common/src/features/dashboards/leaderboard/LeaderboardRow.svelte
Fixes https://github.com/rilldata/rill-private-issues/issues/1592
This pull request restores the gradients behavior prior to the implementation of the multiple measures first pass. See screenshots below for reference. In single selection, the gradients extend across both the dimension and measure cells. For multiple selections, the gradients are limited to their respective measure cells.
**Gradients behavior in 0.56:**
**Gradients behavior in the latest main (after multiple metrics first + second pass):**
**Gradients behavior in this branch:**
**Checklist:**
<div id='description'>
<h3>Summary by Bito</h3>
This pull request fixes gradient issues in leaderboard components by restoring proper behavior for single measure selection. The changes ensure gradients extend correctly across …
=> Fix dimension and measure gradients in single measure selection

web-common/src/components/search/Search.svelte, web-common/src/features/dashboards/filters/dimension-filters/DimensionFilter.svelte, web-common/src/features/dashboards/filters/dimension-filters/dimension-search-text-utils.ts, web-common/src/features/dashboards/filters/dimension-filters/split-dimension-search-text.spec.ts
Fixes a few issues with dimension search,
1. Auto height of search text has incorrect initial height. Tweaking the logic to start from the correct initial height.
2. Refreshing the page doesnt populate the search.
3. If we refresh on the page after using "in-list" search with values with comma, the selection becomes invalid. This is because after getting the value from filter we always join using a comma. Updating this to join using newline if any value has a comma.
**Checklist:**
=> fix: edge cases with dimension search

runtime/drivers/duckdb/config.go, runtime/drivers/duckdb/config_test.go, runtime/drivers/duckdb/crud.go, runtime/drivers/duckdb/duckdb.go, runtime/drivers/duckdb/model_executor_motherduck_self.go, runtime/drivers/duckdb/model_executor_objectstore_self.go, runtime/drivers/duckdb/model_executor_self.go, runtime/drivers/duckdb/model_manager.go, runtime/pkg/rduckdb/db.go, runtime/pkg/rduckdb/db_test.go, runtime/resolvers/testdata/azure_connector.yaml, runtime/resolvers/testdata/gcs_connector.yaml, runtime/resolvers/testdata/s3_connector.yaml, scripts/embed_duckdb_ext/main.go
Facing some race condition wrt wal file deletion in duckdb on concurrent writes.
**Checklist:**
=> Revert concurrent writes in duckdb

web-common/src/features/dashboards/state-managers/actions/leaderboard.ts
If Show context for all measures is set to true and time comparison is off. Toggle it on to save the user one click.
**Checklist:**
=> fix: toggle on comparisons

runtime/drivers/athena/athena.go, runtime/drivers/azure/azure.go, runtime/drivers/bigquery/bigquery.go, runtime/drivers/clickhouse/clickhouse.go, runtime/drivers/druid/druid.go, runtime/drivers/duckdb/duckdb.go, runtime/drivers/gcs/gcs.go, runtime/drivers/https/https.go, runtime/drivers/mysql/mysql.go, runtime/drivers/pinot/pinot.go, runtime/drivers/postgres/postgres.go, runtime/drivers/redshift/redshift.go, runtime/drivers/s3/s3.go, runtime/drivers/salesforce/salesforce.go, runtime/drivers/snowflake/snowflake.go, runtime/drivers/sqlite/sqlite.go, web-common/src/features/sources/modal/yupSchemas.ts
Our backend schema for Pinot connectors changed, yet we hadn't updated our frontend schema that we use for form validation. This PR updates the frontend `yup` schema, so that the two match.
Going forward, we should consider moving toward a common JSON Schema that can be used by both the backend & frontend.
Addresses [this Slack report](https://rilldata.slack.com/archives/CTZ8XBQ85/p1745423185035169)
**Checklist:**
=> fix (Pinot): Update client-side `yup` schema

runtime/pkg/rilltime/rilltime.go, runtime/pkg/rilltime/rilltime_test.go, runtime/pkg/timeutil/timeutil.go
1. `0D` should be equal to `D~` instead of `-1D`. This makes `-1D`, `0D` and `+1D` consistent.
2. Also update the timezone for the new syntax. With some fixes to certain scenarios.
**Checklist:**
=> fix: 0<grain> and timezones in the new rill time syntax

runtime/pkg/email/templates/alert_fail.mjml, runtime/pkg/email/templates/alert_status.mjml, runtime/pkg/email/templates/call_to_action.mjml, runtime/pkg/email/templates/gen/alert_fail.html, runtime/pkg/email/templates/gen/alert_status.html, runtime/pkg/email/templates/gen/call_to_action.html, runtime/pkg/email/templates/gen/informational.html, runtime/pkg/email/templates/gen/project_access_request.html, runtime/pkg/email/templates/gen/scheduled_report.html, runtime/pkg/email/templates/gen/welcome_to_team.html, runtime/pkg/email/templates/gen/welcome_to_trial.html, runtime/pkg/email/templates/informational.mjml, runtime/pkg/email/templates/project_access_request.mjml, runtime/pkg/email/templates/scheduled_report.mjml, runtime/pkg/email/templates/welcome_to_team.mjml, runtime/pkg/email/templates/welcome_to_trial.mjml
Updates email footers to 2025
**Checklist:**
=> fix: updating footer to 2025

web-common/src/features/dashboards/pivot/pivot-export.ts
This enables the ability to sort in time when exporting in flat table mode.
**Checklist:**
=> fix: time sorting for export in flat table

web-common/src/features/dashboards/big-number/MeasuresContainer.svelte
The code that gets the big number value for dashboards without timestamp column is not reactive to response. Update the component so that it re-renders on a re-fetch.
**Checklist:**
=> fix: no big number for dashbaord without timestamp column

web-common/src/components/vega/util.ts, web-common/src/features/canvas/components/charts/Chart.svelte, web-common/src/features/canvas/components/charts/builder.ts, web-common/src/features/canvas/components/charts/cartesian-charts/area/spec.ts, web-common/src/features/canvas/components/charts/cartesian-charts/line-chart/spec.ts, web-common/src/features/canvas/components/charts/selector.ts, web-common/src/features/canvas/components/charts/util.ts, web-common/src/features/canvas/stores/canvas-component.ts, web-common/src/features/dashboards/time-dimension-details/charts/patch-vega-spec.ts, web-common/src/features/templates/charts/grouped-comparison-bar.ts, web-common/src/features/templates/charts/stacked-area.ts, web-common/src/features/templates/charts/stacked-grouped-bar.ts, web-common/src/features/templates/charts/utils.ts
Explore on `main` branch was crashing due to a dependency error originating from `web-common/src/features/canvas/components/util.ts`. This PR moves shared util methods out of canvas utils.
**Checklist:**
=> fix: move vega utils out of canvas utils

web-common/src/features/canvas/CanvasBuilder.svelte, web-common/src/features/canvas/EditableCanvasRow.svelte, web-common/src/features/canvas/inspector/ParamMapper.svelte, web-common/src/features/canvas/layout-util.ts
Edits in the `ComponentEditor` sidebar to values controlled by text inputs do not update the YAML until the input element is blurred. However, `preventDefault` was being called when selecting a widget (for a reason that is no longer necessary). 
Because of this, if a user changed the value of an input element, but then immediately selected a component to move, the input element would not be blurred until the widget was dropped in the new location. This update function was being called on an outdated version of the component (a symptom of not having stable IDs) and would place the update parameters in the wrong location in the YAML.
**Checklist:**
=> fix(canvas): moving items while editing

runtime/drivers/clickhouse/crud.go, runtime/resolvers/resolvers_test.go, runtime/resolvers/testdata/athena_connector.yaml, runtime/resolvers/testdata/clickhouse_cluster.yaml, runtime/resolvers/testdata/models_clickhouse_cluster.yaml, runtime/resolvers/testdata/snowflake_connector.yaml, runtime/testruntime/connectors.go, runtime/testruntime/testruntime.go
When the temp table is renamed, it currently ends up declaring the distributed table with too many quotes, i.e. `'"mymodel"'` instead of `'mymodel'`:
```
CREATE OR REPLACE TABLE "mymodel" ON CLUSTER "mycluster" (...) Engine = Distributed('mycluster', 'default', '"mymodel"', rand())
```
**Checklist:**
=> Fix rename of distributed Clickhouse table

web-common/src/features/canvas/components/leaderboard/LeaderboardDisplay.svelte
Maintain the original order of dimensions in the leaderboards on Canvas.
**Checklist:**
=> fix: preserve leaderboard dimension order in canvas

web-common/src/features/dashboards/dimension-table/dimension-table-export.ts, web-common/src/features/dashboards/pivot/pivot-export.ts, web-common/src/features/dashboards/time-dimension-details/tdd-export.ts
This PR changes the way we provide time ranges to the `Export` API _for on-demand (non-scheduled) exports_. 
Previously, we provided a time range expression (e.g. `P7D`, `rill-MTD`) and amended it by also specifying an `endDate`.  (This amendment attempted to ensure consistency with the data shown in the UI, but the approach was faulty).
Now, we pass in the `startTime` and `endTime` from the `timeControlsStore`. Currently, the `timeControlsStore` resolves time range expressions client-side. However, in the future, we should use the backend's `MetricsViewTimeRanges` API to resolve time ranges.
Closes https://github.com/rilldata/rill-private-issues/issues/1650
**Checklist:**
=> fix (Exports): Simplify time ranges for on-demand exports

web-admin/src/routes/[organization]/-/users/+page.svelte
Include the org invites when all is selected
https://github.com/user-attachments/assets/f4c88587-463e-4ab2-a1b5-5501c53e1407
**Checklist:**
=> hotfix: include pending invites when all is filtered in org users table

web-common/src/features/dashboards/url-state/compression.ts
closes https://github.com/rilldata/rill-private-issues/issues/1653
By default the compression library we use added modified time. So running compression for the same input gave different values for different times.
This caused issues with our url state sync, since it things url changed and resets the dashboard state. Any state not stored in the url gets reset during this. Pivot's expanded state is one such state.
**Checklist:**
=> fix: issues with gzip params being inconsistent causing some dashboard config not persisting

runtime/reconcilers/canvas_test.go
Fix: Canvas Metrics View Time Consistency flaky test
**Checklist:**
=> Fix: Canvas Metrics View Time Consistency flaky test

web-common/src/features/canvas/filters/CanvasFilters.svelte, web-common/src/features/canvas/inspector/filters/DimensionFiltersInput.svelte, web-common/src/features/dashboards/filters/Filters.svelte, web-common/src/features/dashboards/filters/dimension-filters/DimensionFilter.svelte, web-common/src/features/dashboards/filters/dimension-filters/dimension-filter-values.ts
This pull request fixes an issue where the dimension filter dropdown wasn't respecting active filters from other dimensions and measure thresholds. When opening a dimension filter dropdown, it should show values that are consistent with all other active filters. Closes https://github.com/rilldata/rill-private-issues/issues/1608
https://github.com/user-attachments/assets/c8df74e9-9765-4f54-844d-81d38a7fc3c2
**Checklist:**
=> Filtered dimension filters

web-admin/src/features/organizations/users/OrgGroupsTable.svelte, web-admin/src/features/organizations/users/OrgUsersTable.svelte, web-common/src/components/avatar/Avatar.svelte
This pull request sets an intrinsic dimension to the avatar when the avatar URL is being loaded so that users won't see the shrunk avatar size. Additionally, the column percentage widths in the organization tables have been adjusted. Closes https://github.com/rilldata/rill/issues/7250
**Checklist:**
=> Org table avatar and columns width hotfix

web-admin/src/components/table/ResourceHeader.svelte, web-admin/src/features/organizations/users/OrgUsersTable.svelte, web-admin/src/features/public-urls/PublicURLsTable.svelte, web-common/src/components/table/BasicTable.svelte
This pull request ensures the table headers have a consistent 14px font size.
**Checklist:**
=> Consistent table header size

web-common/src/features/canvas/components/charts/circular-charts/CircularChart.ts, web-common/src/features/canvas/components/charts/circular-charts/pie.ts
Instead of `px` values, switch to percentage input for inner radius of circular charts. This ensures that the inner circle scales well as the container scales.
**Checklist:**
=> tweak: support percentage for pie chart inner radius

runtime/resolvers/resolvers_test.go, runtime/resolvers/testdata/metrics_lookup_clickhouse.yaml
This is pending permanent resolution as tracked in https://github.com/rilldata/rill-private-issues/issues/1674
=> Temporarily skip flaky ClickHouse lookup test

runtime/drivers/clickhouse/model_executor_localfile_self.go, runtime/drivers/clickhouse/model_executor_self.go, runtime/drivers/clickhouse/model_executor_self_test.go, runtime/drivers/clickhouse/model_manager.go, runtime/testruntime/testruntime.go
It's an easy mistake to make and since dictionaries can be considered a kind of materialization, I think we should just allow it.
**Checklist:**
=> Allow `materialize: true` with `type: dictionary` in ClickHouse models

go.mod, go.sum
=> fix: Patch go-duckdb for timestamp_ns, timestamp_ms and timestamp_s support

web-admin/src/features/public-urls/CreatePublicURLForm.svelte, web-common/src/components/forms/Select.svelte, web-common/src/features/dashboards/filters/measure-filters/MeasureFilterForm.svelte
This pull request addresses a bug where the popover goes out of view when the "set expiration" action is triggered.﻿
Before
https://github.com/user-attachments/assets/5fc7f113-f4ab-43a6-ace4-cfadde509b27
After
https://github.com/user-attachments/assets/97ca360f-624b-4bb6-a0b7-20845248e5c3
**Checklist:**
=> Fixed calendar popover for public url

runtime/pkg/duckdbsql/ast_traversal.go
closes https://github.com/rilldata/rill-private-issues/issues/1684
**Checklist:**
=> fix: duckdbsql traversal panics on parsing `read_..` fns with empty args

web-admin/src/routes/[organization]/+layout.ts, web-admin/src/routes/[organization]/+page.ts
When a superuser calls `GetOrganization` for an org they don’t belong to, the API returns a `200` with no org `permissions`. This leads to a broken org page:
Previously, we had assumed the API would return a `403`, but it doesn't in this case. This PR adds an explicit check in the frontend for the `readOrg` permission. If it's `false`, we now show a `403` access denied page instead of rendering a broken UI:
**Checklist:**
=> fix (Org page): show `403` for superusers lacking `readOrg` permission

web-common/src/features/dashboards/state-managers/loaders/DashboardStateDataLoader.ts, web-common/src/features/dashboards/url-state/clean-url-params.ts
Temporary fix for embeds where yaml defaults are not loaded.
**Checklist:**
=> fix: yaml defaults not loaded in embed

web-common/orval.config.ts, web-common/src/features/models/partitions/PartitionsTable.svelte, web-common/src/runtime-client/fetchWrapper.ts, web-common/src/runtime-client/gen/runtime-service/runtime-service.ts, web-local/tests/models/incremental.spec.ts, web-local/tests/models/models.spec.ts
Previously, the infinite query for model partitions would pass `pageToken=1` on the first page request, which is invalid—`1` is not a valid page token. This caused the first page to fail with the error `failed to parse page token: illegal base64 data at input byte 0`. [Reported in Slack here](https://rilldata.slack.com/archives/C02T907FEUB/p1747052031539429).
This PR:
- Updates the query logic to omit `pageToken` entirely on the first page. 
- Improves error handling to actually surface the API errors in the UI.
- Adds an e2e test to prevent basic regressions of the Partitions Browser
**Before**
Request URL: `http://localhost:9009/v1/instances/default/models/model/partitions?pageToken=1`
**After**
Request URL: `http://localhost:9009/v1/instances/default/models/model/partitions` …
=> fix (Incremental models): don't pass invalid `pageToken` on first load of partitions

web-common/src/features/dashboards/stores/test-data/store-mutations.ts, web-common/src/features/dashboards/url-state/convertPresetToExploreState.ts, web-common/src/features/dashboards/url-state/url-state-variations.spec.ts
When there is only grain in the url then we are not adding it to the state. Since we have the cascading merge now, we can just keep the grain and the rest will be filled in.
**Checklist:**
=> fix: grain not persisting when it is the only thing in url

runtime/drivers/clickhouse/clickhouse.go, runtime/drivers/clickhouse/context.go, runtime/drivers/clickhouse/crud.go, runtime/drivers/clickhouse/model_executor_localfile_self.go, runtime/drivers/clickhouse/model_executor_objectstore_self.go, runtime/drivers/clickhouse/model_executor_self.go, runtime/drivers/clickhouse/model_executor_self_test.go, runtime/drivers/clickhouse/model_manager.go, runtime/drivers/clickhouse/olap.go, runtime/drivers/clickhouse/olap_test.go, runtime/drivers/duckdb/model_executor_localfile_self.go, runtime/drivers/models.go, runtime/reconcilers/model.go, runtime/resolvers/resolvers_test.go, runtime/testruntime/reconcile.go
This PR makes partitioned Clickhouse models use the `partition_overwrite` strategy by default. It does so by automatically injecting a column named `__rill_partition` with the current partition ID into the model's `SELECT` statement. After this change, the simplest possible incremental and partitioned Clickhouse model looks like this:
```yaml
type: model
incremental: true
partitions:
glob: s3://bucket/path/**
sql: SELECT * FROM s3('{{.partition.uri}}')
```
Contributes to https://github.com/rilldata/rill-private-issues/issues/1632
**Other changes:**
- Fixes an issue where some config overrides where not handled when DSN was passed.
- Uses `ReplicatedMergeTree` by default instead of `MergeTree` for Clickhouse tables on clusters.
- Renames `connector.settings_override` to …
=> Clickhouse: partition overwrite by default + refactors

runtime/drivers/clickhouse/clickhouse.go, runtime/drivers/clickhouse/information_schema.go
**This is just a quick fix till we can fix this properly via UI**
Sample YAML :
```
type: connector
driver: clickhouse
host: "localhost"
port: 9000
database_whitelist: default, system, information_schema
```
**Checklist:**
=> hacky way to limit the database listed in table list for clickhouse

docs/docs/reference/project-files/canvas-dashboards.md, web-common/src/features/canvas/components/charts/circular-charts/CircularChart.ts, web-common/src/features/canvas/components/charts/index.ts, web-common/src/features/canvas/components/charts/types.ts, web-common/src/features/canvas/components/charts/util.ts, web-common/src/features/canvas/components/util.ts, web-common/src/features/canvas/inspector/chart/ChartTypeSelector.svelte, web-common/src/features/canvas/layout-util.ts, web-local/tests/canvas/charts.spec.ts
Default to donut chart instead of pie when a circular chart is added.
**Checklist:**
=> tweak: default to donut instead of pie chart

web-common/src/features/dashboards/leaderboard/Leaderboard.svelte, web-common/src/features/dashboards/leaderboard/LeaderboardHeader.svelte
This pull request improves the tooltips on dimension headers, making them appear only when the header text is truncated.
https://github.com/user-attachments/assets/ddfbe87a-7805-45a5-93a8-5b7d712bf7f7
**Checklist:**
=> [APP-66] Leaderboard tooltip

web-common/src/features/dashboards/big-number/BigNumberTooltipContent.svelte, web-common/src/features/dashboards/big-number/MeasureBigNumber.svelte
This pull request shrinks the big number tooltip to only the first line, unbolded.
**Checklist:**
=> [APP-65] Tweak big number measure tooltip

runtime/metricsview/executor_validate_test.go, runtime/parser/parse_model.go, runtime/parser/parse_model_test.go, runtime/resolvers/testdata/azure_connector.yaml, runtime/resolvers/testdata/gcs_connector.yaml, runtime/resolvers/testdata/metrics_comparisons.yaml, runtime/resolvers/testdata/metrics_null_filling.yaml, runtime/resolvers/testdata/metrics_sql_clickhouse.yaml, runtime/resolvers/testdata/mysql_connector.yaml, runtime/resolvers/testdata/postgres_connector.yaml, runtime/resolvers/testdata/s3_connector.yaml, runtime/resolvers/testdata/snowflake_connector.yaml, runtime/testruntime/connectors.go
A model's output connector currently defaults to the input connector. This PR changes that default to the project's OLAP connector.
After this change, a model like this outputs to DuckDB:
```yaml
type: model
connector: bigquery
sql: SELECT * FROM `project.dataset.table`
```
This makes it equivalent to the `type: source` statement (which is implemented as a model that outputs to the project's default OLAP), enabling `type: source` to be deprecated entirely.
If you are using multiple OLAPs, you now need to always specify an `output.connector` when building models on non-default OLAPs:
```yaml
type: model
connector: clickhouse
sql: SELECT ... FROM tbl
output:
connector: clickhouse
```
**Checklist:**
=> Make models output to the default OLAP by default

web-admin/src/routes/-/embed/+page.svelte, web-admin/tests/embeds.spec.ts, web-common/src/components/navigation/breadcrumbs/BreadcrumbItem.svelte
Url params sync assumes that the current url params are for the dashboard. For embed since we do not actually navigate the url params from previous dashboard will be loaded into the new navigated dashboard.
Adding basic url based navigation for embed. This cleans the url and retains just the resource and type.
**Checklist:**
=> Move embed navigation to url params based navigation

web-common/src/features/canvas/components/charts/heatmap-charts/HeatmapChart.ts
https://linear.app/rilldata/issue/APP-84/heatmap-chart-failing-when-an-unnested-dimension-is-used-on-the-x-axis
**Checklist:**
=> fix: locally scope dimension for heatmap queries

cli/cmd/project/connect_github.go, cli/pkg/cmdutil/githelper.go, cli/pkg/gitutil/gitutil.go
=> fix : allow empty commits while creating rill managed repo first time

web-admin/src/features/dashboards/query-mappers/utils.ts
When alert/report is opened in browser, execution time is not persisted in the url state. So the dashboard has the latest data instead of when the alert/report was triggered.
We do not have the support for `<time_range> as of <timestamp>` support just yet. So until that support is merged and out of feature flag we need to convert the range to custom time range.
**Checklist:**
=> fix: alerts and reports not honouring execution time when "Opened in browser"

web-common/src/features/exports/ExportMenu.svelte
=> chore: Remove unused CSS to fix Vite build warning

web-common/src/components/virtualized-table/core/Cell.svelte, web-common/src/features/canvas/components/leaderboard/LeaderboardDisplay.svelte, web-common/src/features/dashboards/leaderboard/Leaderboard.svelte, web-common/src/features/dashboards/leaderboard/LeaderboardDisplay.svelte, web-common/src/features/dashboards/leaderboard/LeaderboardRow.svelte, web-common/src/features/dashboards/leaderboard/LeaderboardTooltipContent.svelte
This pull request consolidates 2 tooltips appearing in the leaderboard to only one `title` tooltip. See demo.
https://github.com/user-attachments/assets/2fc6b33e-1615-468b-b80d-69be54859a48
https://github.com/user-attachments/assets/39060a2c-1963-47b1-a810-9c13d701bc7f
**Checklist:**
=> [APP-69] Fix: Hover shows two tooltips in different formats

web-admin/src/features/embeds/ExploreEmbed.svelte, web-admin/src/routes/-/embed/+page.svelte, web-common/src/features/dashboards/state-managers/loaders/DashboardStateDataLoader.ts, web-common/src/features/dashboards/state-managers/loaders/DashboardStateManager.svelte, web-common/src/features/dashboards/state-managers/loaders/DashboardStateSync.ts
Dashboard settings in embed should not persist across page loads, including navigating to and from the embedded iframe in the same tab.
1. Disable local storage all together in embedded context.
2. Clear session storage when navigated to a dashboard for the 1st time.
**Checklist:**
=> fix: dashboard settings persisting across page loads in embed

web-common/src/components/tooltip/Tooltip.svelte
Address https://rilldata.slack.com/archives/C04AGHL77PS/p1748606730991179
This pull request removes the extra div that was wrapping `<Tooltip />`, causing a misalignment in the Chip.
**Checklist:**
=> Fix: Remove extra div from tooltip

runtime/parser/parse_rillyaml.go
Adds canvas and api resource types to rill.yaml defaults
**Checklist:**
=> feat: add canvas and api to defaults

runtime/drivers/pinot/olap.go, runtime/drivers/pinot/pinot.go
Add option to override query timeout as cluster default timeout may be too small and we may not have control to change it
**Checklist:**
=> allow overriding pinot cluster query timeout

web-admin/src/features/projects/user-management/OrgUserGroupSetRole.svelte, web-admin/src/features/projects/user-management/UserSetRole.svelte, web-admin/src/features/projects/user-management/UsergroupSetRole.svelte
Disables the role dropdown for current user in the share project popover
**Checklist:**
=> fix: disables the ability to change your own role

docs/docs/explore/mcp.md, go.mod, go.sum, runtime/server/mcp.go, runtime/server/server.go, web-admin/src/features/ai/MCPConfigSection.svelte
**Changes:**
- Moves from SSE server to Streamable HTTP – removes `/sse` from the endpoints (backwards compatible)
- Adds metrics view descriptions in the `list_metrics_views` tool
- Integrates `ai_context:` configured in `rill.yaml` or the metrics view YAML
**Examples:**
```yaml
ai_context: You should start every response with a joke.
type: metrics_view
display_name: Bids Metrics
ai_context: >
Before querying this metrics view, ask the user a riddle.
Only proceed with the query if the user gives the correct answer.
Do not tell them the answer or provide any hints.
If they get the answer wrong three times, lock them out and DO NOT allow them to make further queries.
```
**Checklist:**
=> MCP server improvements

web-common/src/components/forms/Input.svelte, web-common/src/features/canvas/components/charts/builder.ts, web-common/src/features/canvas/components/charts/cartesian-charts/CartesianChart.ts, web-common/src/features/canvas/components/charts/types.ts, web-common/src/features/canvas/inspector/chart/FieldConfigPopover.svelte, web-common/src/features/canvas/inspector/types.ts
https://linear.app/rilldata/issue/ENG-555/set-minmax-for-y-axis
Adds min and max axis selector for bar and line charts.
**Checklist:**
=> ENG-555: feat: add axis range selector for charts

web-admin/src/features/telemetry/RillAdminTelemetryClient.ts, web-admin/src/features/telemetry/initCloudMetrics.ts
This PR introduces batching for Cloud telemetry requests to avoid performing an auth check (and associated Postgres queries) on every single telemetry event. This reduces unnecessary load on our admin service's database.
Context: [Slack thread](https://rilldata.slack.com/archives/C01190F1R1D/p1749489954472719).
**Checklist:**
=> perf (telemetry): Batch telemetry requests to reduce auth load

web-admin/src/routes/[organization]/[project]/canvas/[dashboard]/+page.svelte
hotfix for checking null in resource query for canvas.
**Checklist:**
=> fix: add null check for canvas resource

web-common/src/metrics/ErrorEventHandler.ts
Follows https://github.com/rilldata/rill/pull/7431
**Checklist:**
=> fix (telemetry): Ignore `unhandledrejection` events that originate from browser extensions

web-admin/src/features/projects/github/ConnectToGithubButton.svelte
A refactor that changed the button API had missed a button in deploy journey: https://github.com/rilldata/rill/pull/7394
A bugfix updated this as the flow was broken on main: https://github.com/rilldata/rill/pull/7421
But only the bugfix was cherry picked hence the flow was broken.
**Checklist:**
=> Revert the change needed for refactor not in 64

runtime/server/generate_metrics_view.go
Adds time columns as dimensions to auto generated metric views and explores.
Trims leading spaces from display names.
**Checklist:**
=> fix: append timecolumns as dimensions

runtime/pkg/activity/client.go, runtime/pkg/activity/event.go, runtime/pkg/activity/event_test.go
https://linear.app/rilldata/issue/ENG-758/truncate-large-events-before-emitting-metrics
Fixes events are too large errors
**Checklist:**
=> Add event truncation for oversized telemetry data

docs/package.json, package-lock.json
Docs were failing to build on local and CI because of a missing dep: `sass` missing build dependency
**Checklist:**
=> Fix: docs missing build dependency

web-admin/src/features/organizations/constants.ts, web-admin/src/features/organizations/users/CreateUserGroupDialog.svelte, web-admin/src/features/organizations/users/EditUserGroupDialog.svelte
Closes https://linear.app/rilldata/issue/ENG-818/cannot-add-users-to-user-group-when-group-name-has-underscores
This pull request aligns the user group validation in the edit and create user group dialogs with the slug validation used in the CLI.﻿
https://github.com/rilldata/rill/blob/main/admin/database/database.go#L622
https://github.com/rilldata/rill/blob/main/admin/database/validate.go#L57
**Checklist:**
=> Fix inconsistent user group name validation

web-common/src/components/forms/SubmissionError.svelte, web-common/src/features/connectors/olap/test-connection.ts, web-common/src/features/sources/errors/ErrorPane.svelte, web-common/src/features/sources/errors/constants.ts, web-common/src/features/sources/errors/errors.ts, web-common/src/features/sources/modal/AddDataForm.svelte, web-common/src/features/sources/modal/submitAddDataForm.ts, web-common/src/features/sources/source-telemetry.ts
Closes https://linear.app/rilldata/issue/APP-88/improve-connector-form-errors and https://linear.app/rilldata/issue/APP-87/improve-error-handling-in-rd-for-connector
Reference from https://www.notion.so/rilldata/Improve-Connector-form-errors-1f2ba33c8f5780db892cf59cea5f9726
This pull request improves the ClickHouse error messages reported by users. We've updated the `testOLAPConnector` to receive the connector name rather than the new connector name. This ensures that when we test the connection. We're testing against the exact connector name rather than the incremented names. In addition to adding human readable error message handling for ClickHouse, we've also modified the SubmissionError component according to [the design](https://www.notion.so/rilldata/Improve-Connector-form-errors-1f2 …
=> Clickhouse human readable error message and design improvement

runtime/server/controller.go, runtime/server/repos.go, web-local/tests/olap-connectors.spec.ts
Fixes connectors not immediately resolving on model creation. Added close event server on watch errors in WatchResourcesHandler and WatchFilesHandler. 
**Checklist:**
=> bug: Fix connectors not immediately resolving on model creation

admin/provisioner/clickhousestatic/provisioner.go, admin/provisioner/clickhousestatic/provisioner_test.go
Support DSN from environment variable in ClickHouse provisioner
```
{"clickhouse":{"spec":{"dsn_env":"RILL_MANAGED_CLICKHOUSE"}, ...snip
```
**Checklist:**
=> Support DSN from environment variable in Clickhouse provisioner

web-admin/src/features/projects/environment-variables/AddDialog.svelte, web-admin/src/features/public-urls/CreatePublicURLForm.svelte
We moved the click even to `onClick` from `on:click`. A couple of components were missed.
Used regex `<Button[^>]*on:click` to find them.
**Checklist:**
=> fix: event listener for button component using old attribute

web-common/src/components/combobox/Combobox.svelte
Resolves https://linear.app/rilldata/issue/APP-144/removing-all-users-from-user-group-doesnt-uncheck-options-in-the
This pull request updates reactive selection logic so the combobox always reflects the current selection, including when the selection is empty. This fixes an issue where removing all users from a user group did not visually uncheck all options in the dropdown.
https://github.com/user-attachments/assets/878a1b21-4989-471a-81b9-a24e16542b80
**Checklist:**
=> Updates reactive options in combobox

web-common/src/components/menu/DashboardMetricsDraggableList.svelte
This pull request addresses a bug where hiding or showing a dimension or measure would not immediately update the list in the UI.
When toggling the visibility of dimensions or measures in the "Shown dimensions" or "Hidden dimensions" lists, the UI would sometimes not update correctly. This was due to the use of array indices as keys in Svelte's {#each} blocks, which can cause DOM update issues when the list changes.
- Changed the {#each} blocks for `filteredSelectedItems` and `filteredHiddenItems` in `DashboardMetricsDraggableList.svelte` to use the unique dimension/measure ID as the key instead of the index.
- This ensures Svelte can correctly track and update each item, so the UI always reflects the current state after toggling.
Resolves …
=> Stable keys for draggable list

runtime/drivers/olap.go, runtime/metricsview/ast.go, runtime/metricsview/astexpr.go, runtime/metricsview/astsql.go, runtime/metricsview/executor_rewrite_approx_comparisons.go
Fixes https://linear.app/rilldata/issue/PLAT-13/error-when-applying-dynamic-filter-in-disco-dashboard
Its an alternate way of handling arrays and workaround for https://github.com/ClickHouse/ClickHouse/issues/80703
Ref - https://clickhouse.com/docs/sql-reference/statements/select/array-join
**Checklist:**
=> better unnest handling for clickhouse

admin/worker/run_autoscaler.go
Temporarily disabling the autoscaler. Let's re-enable when all resets have been removed.
=> Disable the autoscaler

runtime/resolvers/metrics_sql.go, runtime/resolvers/metrics_sql_test.go
Enable the application to merge global filter state into the metrics SQL queries.
**Checklist:**
=> Add additional WHERE clause support for metrics SQL resolver

.github/workflows/cli-release.yml, Makefile, cli/pkg/installscript/installscript.go
Make rill upgrade forward compatible
```bash
rill upgrade --version v0.65.4
rill upgrade --version v0.58.7
rill upgrade --nightly
```
**Checklist:**
=> Make rill upgrade command forward compatible

web-admin/src/features/projects/status/ActionsCell.svelte, web-admin/src/features/projects/status/RefreshResourceConfirmDialog.svelte
Closes https://linear.app/rilldata/issue/APP-47/project-status-page-add-menu-item-for-incremental-model-refresh
References
https://github.com/rilldata/rill/blob/main/cli/cmd/project/refresh.go
https://docs.rilldata.com/reference/cli/project/refresh#rill-project-refresh
This pull request adds support for both "full refresh" and "incremental refresh" actions for models in Rill Cloud. The model refresh logic in the project resources status table is updated to use the correct API payload: instead of incorrectly using the all or allFull flags for individual model refreshes, the code now sends a models array with the model name and a full flag to indicate the refresh type. This ensures only the selected model is refreshed, matching backend expectations. Additionally, the refresh confirmation …
=> Support Full and Incremental Model Refresh in Rill Cloud

docs/docs/build/advanced-models/advanced-models.md, docs/docs/hidden/yaml/connector.md, docs/docs/hidden/yaml/model.md, docs/docs/reference/project-files/advanced-models.md, package-lock.json, runtime/drivers/duckdb/config.go, runtime/drivers/duckdb/duckdb.go, runtime/parser/schema/project.schema.yaml
Closes [#PLAT-17](https://linear.app/rilldata/issue/PLAT-17/deprecate-boot-queries-and-run-init-sql-per-handle-instead-of-per)
**Checklist:**
=> Deprecate boot_queries and run init_sql per handle instead of per connection

admin/provisioner/clickhousestatic/provisioner.go, admin/provisioner/clickhousestatic/provisioner_test.go
Currently we use a uuid as the table name `rill_uuid` this PR changes that to a more human readable string `rill_org_project_uuid`
```
new: rill_acme_corp_my_project_9b32f48044d142a18e4634367e13a277
old: rill_9b32f48044d142a18e4634367e13a277
```
**Checklist:**
=> Adjust ClickHouse static provisioner naming `rill_org_project_uuid`

runtime/metricsview/executor.go
Only include time dimension in schema query once if its defined in the dimension list. This causes issues with CH as it does not allow duplicate alias.
**Checklist:**
=> fix alias conflict for clickhouse schema validation query

runtime/server/query_resolver.go
Handle error when converting meta field to struct in query resolver
**Checklist:**
=> Handle error when converting meta field to struct in query resolver

web-common/src/features/canvas/stores/time-control.ts
Fixes https://linear.app/rilldata/issue/APP-196/bug-kpi-component-shows-null-value-incorrectly
**Checklist:**
=> fix: time range for canvas for single data point

docs/package.json, package-lock.json
Removes the `sidebar` package and its dependency the `bootstrap` package, which [Dependabot called out as having a Moderate vulnerability](https://github.com/rilldata/rill/security/dependabot/187). The `sidebar` package was not actually used anywhere in our docs.
=> chore(docs): Remove unused `sidebar` dependency

web-common/src/features/dashboards/url-state/convertLegacyStateToExplorePreset.ts
Addressed https://rilldata.slack.com/archives/C02T907FEUB/p1752159312066389
Fixed https://github.com/rilldata/rill/blob/main/web-common/src/features/dashboards/url-state/convertLegacyStateToExplorePreset.ts#L138
This pull request ensures that when a public URL is generated or visited with a custom time range (via the legacy proto state parameter), the custom range is correctly serialized and deserialized. Specifically, if the proto state contains a custom time range, the timeStart and timeEnd fields are now encoded as ISO strings in the URL, allowing the dashboard to restore and display the user's selected custom range accurately.
https://github.com/user-attachments/assets/60302e7a-4f54-44e8-8f8e-5fca60f83d34
Reviewer - create a public URL with custom range, open the public URL. You …
=> Hotfix for custom tr public url

web-common/src/components/searchable-filter-menu/SearchableMenuContent.svelte, web-common/src/features/alerts/AlertForm.svelte, web-common/src/features/canvas/filters/CanvasComparisonPill.svelte, web-common/src/features/dashboards/filters/FilterButton.svelte, web-common/src/features/dashboards/filters/dimension-filters/DimensionFilter.svelte, web-common/src/features/dashboards/filters/measure-filters/MeasureFilter.svelte, web-common/src/features/dashboards/filters/measure-filters/MeasureFilterForm.svelte, web-common/src/features/dashboards/time-controls/TimeGrainSelector.svelte, web-common/src/features/dashboards/time-controls/comparison-pill/ComparisonPill.svelte, web-common/src/features/dashboards/time-controls/super-pill/SuperPill.svelte, web-common/src/features/dashboards/time-controls/super-pill/components/Comparison.svelte, web-common/src/features/dashboards/time-controls/super-pill/components/RangePicker.svelte, web-common/src/features/dashboards/time-controls/super-pill/components/Zone.svelte, web-common/src/features/scheduled-reports/BaseScheduledReportForm.svelte, web-common/src/features/scheduled-reports/FiltersForm.svelte, web-common/src/features/scheduled-reports/ScheduledReportDialog.svelte
1. Time range dropdown border color doesnt match dropdown other places.
2. Changing measure in alert doesnt automatically update the criteria's measure.
3. Pin dropdown in report to top since the controls are below half way mark of screen.
4. Set the dialog width of report to match alert.
**Checklist:**
=> fix: Misc UXQA alert/reprot filter edit issues

web-common/src/features/alerts/AlertForm.svelte
Changing measure broken criteria while editing alerts. We need to update the criteria array to be a new object for it to take effect.
**Checklist:**
=> fix: alert crtieria broken in edit when changing measure

web-admin/src/features/alerts/EditAlert.svelte, web-admin/src/features/alerts/metadata/AlertMetadata.svelte, web-admin/src/features/scheduled-reports/metadata/ReportMetadata.svelte, web-common/src/features/dashboards/selectors.ts, web-common/src/features/scheduled-reports/BaseScheduledReportForm.svelte
We need a lot of info from dashboard when editing report or alert. So if the dashboard is broken then we need to disable editing.
**Checklist:**
=> fix: editing report/alert for broken dashboards

web-common/src/features/dashboards/state-managers/loaders/DashboardStateSync.ts
There is a race condition during dashboard init where both `replaceState` and `goto` get called. This adds 2 history events.
Moving the mutex update after goto happens to avoid this.
**Checklist:**
=> fix: race condition during dashboard init causing additional url history entries

docs/src/css/custom.scss
=> docs: Tweak sidebar spacing between sections

web-common/src/features/canvas/stores/time-control.ts
Fixes an issue with appropriately determining the minimum time grain for multiple metrics views.
**Checklist:**
=> fix: min time grain derivation

web-common/src/features/canvas/components/charts/BaseChart.ts, web-common/src/features/canvas/components/charts/util.ts, web-common/src/features/canvas/explore-link/canvas-explore-transformer.ts
Instead of linking all canvas charts to pivot, we now check for certain chart types if they can be mapped to time dimension detail table. On a match we redirect to TDD instead.
**Checklist:**
=> feat: link canvas temporal charts to TDD

web-common/src/features/canvas/components/charts/cartesian-charts/CartesianChart.ts, web-common/src/features/canvas/components/charts/heatmap-charts/HeatmapChart.ts
The main query depends on the topN query results to apply filtering. When topN queries kept previous data, thisdependency chain became stale.
Removing `keepPreviousData` ensures that:
- topN queries immediately show loading/undefined state when parameters change
- The main chart query is disabled until fresh topN data is available
- No stale filtering is applied to the chart data
https://rilldata.slack.com/archives/C02T907FEUB/p1752606705698349
**Checklist:**
=> fix: do not keep previous data for topN chart queries

web-admin/src/features/organizations/users/CreateUserGroupDialog.svelte, web-admin/src/features/organizations/users/EditUserGroupDialog.svelte
Closes https://linear.app/rilldata/issue/APP-139/user-group-name-invalid-error-message-only-appears-when-field-is-not
- Shows errors on input rather than on blur
- Reset tainted form on close
- Disable submission button on group name error
**Checklist:**
=> Invalid group name fixes

runtime/resolvers/metrics_sql.go, runtime/resolvers/metrics_sql_test.go
Similar to the `additional_where` field this PR enables a way to merge the time range and timezone state to a metrics_sql query.
**Checklist:**
=> Support additional time range with metrics sql

runtime/queries/proto.go
We set `end` to `executionTime` while running an alert. But with rill time we need to update the time range to use `as of <execution_time>`
**Checklist:**
=> fix: alert execution when rill time syntax is used

web-admin/src/client/redirect-utils.ts, web-admin/src/features/authentication/SignIn.svelte
The login button in `SignIn.svelte` was using `redirectToLogin()` which throws a SvelteKit redirect. This works in load functions but fails when called from component event handlers, causing the login button to not work properly.
Closes [PLAT-141](https://linear.app/rilldata/issue/PLAT-141/log-in-sign-up-button-does-not-work-when-in-a-logged-out-state)
**Checklist:**
=> Fix "Log-in / Sign Up" button click handler

runtime/server/canvases.go, runtime/server/canvases_test.go
Extract metrics views from components metrics sql. This will enable the canvas resolver to return a full list of metrics view referenced by all the components
Using the `Open RTB Ads` sample
```yaml
type: canvas
display_name: Test
defaults:
time_range: PT24H
comparison_mode: time
rows:
- items:
- kpi:
metrics_sql: SELECT app_site_name FROM auction_metrics
width: 12
height: 40px
- items:
- bar_chart:
metrics_view: bids_metrics
color: hsl(246, 66%, 50%)
x:
type: temporal
field: __time
sort: -y
limit: 20
y:
type: quantitative
field: video_completion_rate
zeroBasedOrigin: true
width: 12
```
Sample canvas resolver 
```json
{
"canvas": {},
"resolvedComponents": {},
"referencedMetricsViews": {
"auction_metrics": {},
"bids_metrics": {}
}
}
```
**Checklist:**
=> Add metrics view used in metrics_sql to canvas resolver

web-common/src/components/vega/VegaLiteRenderer.svelte, web-common/src/components/vega/VegaRenderer.svelte, web-common/src/components/vega/vega-tooltip.ts
Fixes https://linear.app/rilldata/issue/PLAT-145/ghost-tool-tips-persist-when-navigating-between-tdd-and-explore
Adds checks for previous tooltip element before mounting new tooltips. Adds additional check on container for `mouseleave` event
**Checklist:**
=> fix: ghost tooltips from time dimension detail charts

web-common/src/features/connectors/olap/TableMenuItems.svelte, web-common/src/features/connectors/olap/selectors.ts, web-common/src/features/entity-management/AddAssetButton.svelte, web-common/src/features/feature-flags.ts, web-common/src/features/metrics-views/editor/Placeholder.svelte, web-common/src/features/sources/modal/AddDataModal.svelte, web-common/src/features/workspaces/MetricsWorkspace.svelte, web-common/src/features/workspaces/VisualMetrics.svelte
This PR removes the `clickhouseModeling` feature flag in favor of the application's own assessment of whether or not the OLAP connector supports modeling. Modeling is currently supported in these cases:
1. The OLAP engine is DuckDB
2. The OLAP engine is Rill-managed (e.g. Rill-managed ClickHouse)
3. The OLAP engine is running in `readwrite` mode
Addresses [this Slack request](https://rilldata.slack.com/archives/C02T907FEUB/p1753697369166259)
**Checklist:**
=> feat (OLAP connectors): Replace `clickhouseModeling` feature flag with a dynamic check for modeling support

docs/docs/home/home.md, docs/docs/reference/api/_category_.yml, docs/docs/reference/connectors/_category_.yml, docs/docs/reference/project-files/_category_.yml, docs/docs/reference/project-files/advanced-models.md, docs/docs/reference/project-files/connectors.md, docs/docs/reference/project-files/models.md, docs/docs/reference/project-files/sources.md, docs/src/css/_headings.scss, docs/src/css/_variables.scss
New order of Reference (in prep to move Connectors to Docs)
- Project FIles
- OLAP Engines
- Connectors
- CLI Usage
Rill Extensions
- Reorderd the Project Files with Connectors First (first item in the experience). 
- Added a deprecated note in source and have them look at model YAML instead
- Model YAML has a snippet on why YAML vs SQL 
Didn't add:
- MotherDuck as an OLAP engine, but it makes sense to and will do it in the future
Notes on PR:
Took the chance to recreate our **connector YAML** in preparation for the new connector experience and the importance to have this clearly defined and allow user to easily copy and paste the sample connector (or use the UI). There's a lot of parameters that we dont have documented anywhere and the **reference** should be the place for it. (not docs …
=> Changes to Reference

web-admin/src/features/projects/status/ActionsCell.svelte, web-admin/src/features/projects/status/ProjectResources.svelte, web-admin/src/features/projects/status/ProjectResourcesTable.svelte, web-admin/src/features/public-urls/CreatePublicURLForm.svelte
This PR changes the actions cell visibility logic in the project resources table. Previously, the actions cell was hidden for the entire table when any resource was reconciling. Now, it only hides the actions cell for individual rows where that specific resource is reconciling. In addition to that, when you run an incremental refresh on one resource and open another resource's actions dropdown, both the dropdown and any subsequent dialog will stay open even when the first resource finishes running and updates the table data.
Closes https://linear.app/rilldata/issue/APP-232/project-status-page-dont-hide-model-refresh-button-when-a-different
https://github.com/user-attachments/assets/1bd7ce83-94bb-4c48-9068-28f71f58a3d2
**Checklist:**
=> Do not hide actions cell for non-reconciling resources

web-common/src/features/feature-flags.ts
When switching between projects, feature flags weren't properly resetting to their default values. If Project A had `chat: true` and Project B had no chat flag set, the chat flag would remain `true` instead of resetting to its default `false` value.
Partly addresses [this Slack report](https://rilldata.slack.com/archives/C08RDR9Q26P/p1753859766565959)
**Checklist:**
=> Fix feature flags not resetting to defaults when switching projects

web-local/tests/canvas/global-dimension-filters.spec.ts, web-local/tests/canvas/global-time-filters.spec.ts
Add global filters run through for canvas
**Checklist:**
=> chore: add e2e canvas global filters test

web-common/src/features/dashboards/pivot/time-pill-store.ts
When the the min time grain is same as the grain being check, it was not being added to `validGrains`
=> fix: missing grain for time pivot chips

runtime/queries/metricsview_aggregation.go
Fixes partial results for timeseries request because of default limit 
**Checklist:**
=> no default limit for timeseries request

web-common/src/features/dashboards/time-controls/time-range-mappers.ts
Selecting previous complete time ranges is interpreted incorrectly when opened in UI. The downloaded report is correct, just the UI's interpretation of the created report.
Mapping from V1TimeRange to our format was not handling an edge case. 
**Checklist:**
=> fix: previous complete reports generation

runtime/drivers/redshift/warehouse.go
[ENG-858: Unable to view redshift table model properly](https://linear.app/rilldata/issue/ENG-858/unable-to-view-redshift-table-model-properly)
**Checklist:**
=> Fix panic in cleanup when query failed on redshift

runtime/drivers/olap.go, runtime/metricsview/ast.go
Use timezone while creating time buckets
**Checklist:**
=> [PLAT-159] use timezone with time spine

runtime/resolvers/metricsview_time_range.go
Add time dimension to `metricsview_time_range` resolver cache key as alternate time dimensions can be used now to query APIs. Mostly affects mcp client doing mv time range query with alternate time dim.
**Checklist:**
=> add time dimension to resolver cache key

web-admin/src/features/billing/contact/ChangeBillingContactDialog.svelte, web-admin/src/routes/[organization]/-/users/groups/+page.svelte
This PR resolves the pagination issue where user search bars in group management dialogs only showed the first 20 users, preventing users from finding and adding users beyond that limit in their organization.
Closes https://linear.app/rilldata/issue/APP-252/user-search-bar-does-not-paginate-beyond-first-20-users
**Checklist:**
=> Use infinite query when listing org users

cli/cmd/project/logs.go
Fixes [PLAT-134: Fix `rill project logs` exceeding gRPC message size](https://linear.app/rilldata/issue/PLAT-134/fix-rill-project-logs-exceeding-grpc-message-size)
Tested by pointing rill project log to local runtime.
Before fix failed with
```
Error: failed to get logs: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (15733798 vs. 4194304) (ResourceExhausted)
```
After fix working fine.
No need to change server side send message size as its already int max by default.
**Checklist:**
=> Increasing grpc received message size

web-common/src/features/canvas/filters/CanvasFilters.svelte, web-common/src/features/canvas/inspector/filters/DimensionFiltersInput.svelte, web-common/src/features/canvas/stores/filters.ts, web-common/src/features/dashboards/filters/Filters.svelte, web-common/src/features/dashboards/filters/dimension-filters/DimensionFilter.svelte, web-common/src/features/dashboards/state-managers/actions/dimension-filters.ts, web-common/src/features/dashboards/stores/Filters.ts, web-common/src/features/dashboards/stores/filter-utils.ts, web-common/src/features/scheduled-reports/FiltersForm.svelte
In dimension filter dropdown, select all does it one at a time. This leads to gzip calculation to happen one at a time. With a large set of values this slows down and crashes the app.
Moveing to using a multi select method so that all the values are toggled at once.
**Checklist:**
=> fix: selecting all on a high cardinality dimension in dimension filter drop down crashes the app

web-common/src/features/dashboards/aggregation-request-builder.ts, web-common/src/features/dashboards/filters/measure-filters/measure-filter-entry.ts, web-common/src/features/dashboards/time-controls/time-range-mappers.ts, web-common/src/features/explore-mappers/utils.ts, web-common/src/features/scheduled-reports/FiltersForm.svelte
We cant really do correct comparison without some additional rill time syntax support. So temporarily disabling comparisons in alerts an reports.
**Checklist:**
=> fix: Disable comparison with rill time in alerts and reports

web-common/src/features/dashboards/time-series/annotations-selectors.ts
We are making a call for annotations even when we know for sure the metrics view has no annotations defined.
**Checklist:**
=> Fix: unnecessary annotations API call when metrics view has no annotations defined

Makefile
Only keeps the example projects that are actually used in the UI to reduce file size.
=> chore: keep only relevant examples

go.mod, go.sum, runtime/server/mcp_server.go, runtime/server/mcp_test.go
[Building MCP servers for ChatGPT and API integrations ](https://platform.openai.com/docs/mcp) Docs
For our tools to work with ChatGPT Connectors or deep research, we needed to supply an interface to two tools `search` and `fetch`
Additional context in the attached issue
**Checklist:**
=> Add support for openAI mcp connector

web-common/src/features/canvas/LocalFiltersHeader.svelte, web-common/src/features/canvas/inspector/filters/TimeFiltersInput.svelte, web-common/src/features/canvas/stores/time-control.ts, web-common/src/features/dashboards/filters/Filters.svelte, web-common/src/features/dashboards/filters/TimeRangeReadOnly.svelte, web-common/src/features/dashboards/time-controls/super-pill/SuperPill.svelte, web-common/src/features/dashboards/time-controls/super-pill/components/RangePicker.svelte, web-common/src/features/dashboards/time-controls/super-pill/new-time-dropdown/RangePickerV2.svelte, web-common/src/features/dashboards/time-controls/time-control-store.ts, web-common/src/features/scheduled-reports/FiltersForm.svelte, web-common/src/lib/time/new-grains.ts
- Fixes an issue where local time filters on Canvas would not display their human readable label
- Fixes an issue where the `smallest_time_grain` value could not be selected as the aggregation grain on Explore
- Fixes an issue where range tooltips would not render properly on the Canvas editing surface
**Checklist:**
=> fix: time syntax beta issues

web-common/src/lib/duckdb-data-types.ts
Addresses [this Slack report](https://rilldata.slack.com/archives/C02T907FEUB/p1754381965384539?thread_ts=1754323698.573649&cid=C02T907FEUB)
Before, the DuckDB `TIMESTAMP_S`, `TIMESTAMP_MS`, and `TIMESTAMP_NS` types did not show up in the column profiler:
Now they do:
... and here's the output of a more complex model that shows more clearly that the data viz is working correctly:
**Checklist:**
=> fix (Column profiles): Show timestamp profiles for certain DuckDB types

docs/src/css/_sidebar.scss, docs/src/css/_variables.scss
onhover: when hovering the side bar illuminates
onClick: on select the text bolds, and illuminates disappears
This way is a bit less noisy on the side bar. 
**Checklist:**
=> [DOCS] Add navigational side bar

web-common/src/features/scheduled-reports/ScheduledReportDialog.svelte
Backend checks if atleast one of email recipient or slack user or slack channel is provided in reports. Matching UI validation to be this way.
**Checklist:**
=> fix: report recipient valdiation to match backend parser validation

web-common/src/features/dashboards/workspace/DeployProjectCTA.svelte, web-common/src/features/project/RemoteProjectManager.svelte
There was a regression during update flow changes where remote git change dialog was not triggered. Updating the flow to show the dialog when user hits deploy in both create/update project cases.
**Checklist:**
=> fix: remote changes check not showing up during update flow

web-common/src/features/dashboards/time-series/MetricsTimeSeriesCharts.svelte, web-common/src/lib/time/new-grains.ts
- Changes aggregation grain label rendering to lowercase
- Fixes a bug where metrics views without a `smallest_time_grain` (or one set to a value smaller than `minute`) would crash when opening the menu
**Checklist:**
=> fix: aggregation dropdown rendering

web-common/src/components/data-types/Base.svelte, web-common/src/components/virtualized-table/core/Cell.svelte, web-common/src/features/dashboards/leaderboard/LeaderboardRow.svelte
This PR adds the ability to select text in unexpanded/expanded table cells. Fixes https://linear.app/rilldata/issue/APP-300/ability-to-copy-leaderboard-value
https://github.com/user-attachments/assets/28b61692-4b58-4b0e-91df-015609d443fd
**Checklist:**
=> Ability to select text Leaderboard cell value

web-common/src/features/sources/modal/constants.ts
This PR updates the label of Self-hosted ClickHouse. Closes https://linear.app/rilldata/issue/APP-271/update-label-self-managed-clickhouse-to-self-hosted-clickhouse
**Checklist:**
=> Update label of Self-hosted ClickHouse

runtime/drivers/duckdb/config.go, runtime/drivers/duckdb/duckdb.go
We should auto install motherduck when connector is motherduck
https://linear.app/rilldata/issue/APP-304/add-schema-name-input-field-to-motherduck#comment-c6cec213
Below format will work now.
```
type: connector
driver: motherduck
token: '{{ .env.connector.motherduck.token }}'
path: "md:sample_data"
schema_name: kaggle
```
**Checklist:**
=> Install motherduck extension and set token when connector is motherduck

web-common/src/components/forms/Input.svelte, web-common/src/components/forms/Select.svelte, web-local/src/routes/(misc)/deploy/organization/select/+page.svelte
To better support https://github.com/rilldata/rill/pull/7778 we need some improvements to the select input.
1. Generalise the `Add Option` section and add support for it in `Input` component as well.
2. Add loading state when options will be loading.
**Checklist:**
=> feat: Move `Add Option` within component for select input

web-common/src/runtime-client/watch-request-client.ts
Out of view throttle timeout was incorrectly set in https://github.com/rilldata/rill/pull/7862 for testing. This reverts that and correctly sets a longer timeout.
**Checklist:**
=> fix(rill dev): out of view throttle timeout being incorrect

web-common/src/components/forms/SubmissionError.svelte
Closes https://linear.app/rilldata/issue/PLAT-194/full-error-msg-is-not-displayed-in-connector-form
**Checklist:**
=> Fix overflow submission error

runtime/parser/init.go, runtime/parser/init_test.go
The `InitEmpty` function will no longer create any connector files during project initialization, preventing the generation of duckdb.yaml or other connector YAML files. This allows the UI to handle connector creation through user-guided initialization.
**Checklist:**
=> Remove conditional connector file creation for DuckDB OLAP engine

runtime/drivers/clickhouse/clickhouse.go, runtime/drivers/clickhouse/clickhouse_test.go
This change allows managed ClickHouse instances to connect properly using the DSN provided by the provisioner, fixing the connection issue that was preventing managed ClickHouse support from working. I Adjusted `validate()` to preserve the DSN when it's provided (likely by the provisioner) while still clearing conflicting individual connection properties.
- Provisioner-provided DSNs are preserved in managed mode
- Conflicting individual connection properties are still cleared to prevent configuration conflicts
Relates to: https://github.com/rilldata/rill/pull/7811#pullrequestreview-3196209491
**Checklist:**
=> Preserve DSN when in managed mode

web-common/src/features/canvas/components/charts/circular-charts/CircularChart.ts, web-common/src/features/canvas/components/charts/circular-charts/pie.ts, web-common/src/features/canvas/components/charts/types.ts, web-common/src/features/canvas/inspector/chart/field-config/FieldConfigPopover.svelte, web-common/src/features/canvas/inspector/types.ts
- Add toggle to show and hide totals value in the centre.
- Responsive font size for totals value
- Reorder params to put measure dropdown and inner radius input above color
Addresses some issues from https://linear.app/rilldata/issue/APP-341/improvements-to-donut-chart
**Checklist:**
=> refac: donut chart improvements

runtime/pkg/rduckdb/db.go, runtime/pkg/rduckdb/db_test.go
Currently it leaves an empty directory on view creation failures
**Checklist:**
=> fix : view directory does not gets cleaned during failures

web-common/src/features/sources/modal/AddClickHouseForm.svelte
This PR resolves the issue where ClickHouse Cloud DSN submission failed with:
'no clickhouse connection configured: dsn, host or managed: true must be set'" Resolved https://linear.app/rilldata/issue/APP-380/when-creating-chc-with-dsn-parameter-file-generated-no-dsn-in-env
Tested parameters and dsn form submissions of the Self-hosted and ClickHouse Cloud options.
ClickHouse Cloud DSN
https://github.com/user-attachments/assets/59b66644-176f-439b-9be5-94c81ba29990
ClickHouse Cloud parse error
https://github.com/user-attachments/assets/69fb9455-79ad-47af-9c80-4fb621931215
Parameters Form
**Checklist:**
=> Clickhouse Cloud Hotfix

web-common/src/features/sources/modal/AddDataModal.svelte, web-common/src/features/sources/modal/RequestConnectorForm.svelte
This PR tweaks the layout of add data modal from 3 to 4 columns.
Closes https://linear.app/rilldata/issue/APP-381/add-source-modal-is-currently-3-column-grid-layout-needs-4-column-grid
https://github.com/user-attachments/assets/140eb385-07fd-4541-b9b0-7155a9d206c4
**Checklist:**
=> Add Data Modal Layout

admin/server/projects.go, cli/cmd/project/edit.go
`rill project edit --remote-url https://github.com/k-anshul/git-transfer --project git-transfer`
closes https://linear.app/rilldata/issue/PLAT-226/cli-flag-to-allow-user-to-edit-git-remote-url
**Checklist:**
=> feat : Allow user to edit git-remote 

runtime/pkg/rilltime/rilltime.go, runtime/pkg/rilltime/rilltime_test.go
Legacy iso truncated by the smallest grain in iso only. This is how old ISO resolution worked.
We are changing this behaviour to instead be a add a unit before truncating.
**Checklist:**
=> fix(rilltime): ceil legacy iso instead of truncating

web-common/src/features/dashboards/time-controls/new-time-controls.ts, web-common/src/features/dashboards/time-controls/super-pill/components/RangeDisplay.svelte, web-common/src/features/dashboards/time-controls/super-pill/new-time-dropdown/RangePickerV2.svelte, web-common/src/lib/time/ranges/formatter.ts
- Hides `as of` dropdown when viewing an All Time range
- Fixes an issue where going from All time to another range would set the reference point to `now`
- Applies `as of` clause when submitting a time string via the text input i.e. `-4d to -3d as of watermark/d` now sets the as of dropdown to `watermark` and `day`
- Maintains properties of existing `as of` selector when submitting via text input i.e. `-4d to -3d` (Previously, these were all interpreted as `as of now`)
**Checklist:**
=> chore: rilltime tweaks

docs/docs/connect/olap/clickhouse.md, runtime/drivers/clickhouse/clickhouse.go, runtime/drivers/clickhouse/crud.go, runtime/drivers/clickhouse/olap_test.go
Adds option to run `OPTIMIZE` on ClickHouse temporary tables. This PR enables '[optimization](https://clickhouse.com/docs/sql-reference/statements/optimize)' of temporary tables before partition replacement operations. 
```yaml
type: connector
driver: clickhouse
managed: true
optimize_temporary_tables_before_partition_replace: true # default: false
```
**Checklist:**
=> Add option to run OPTIMIZE on the temporary table 

web-common/src/features/canvas/components/charts/builder.ts, web-common/src/features/canvas/components/charts/heatmap-charts/HeatmapChart.ts, web-common/src/features/canvas/components/charts/heatmap-charts/spec.ts, web-common/src/features/canvas/components/charts/types.ts, web-common/src/features/canvas/components/charts/util.ts, web-common/src/features/canvas/inspector/chart/PositionalFieldConfig.svelte, web-common/src/features/canvas/inspector/chart/field-config/ColorRangeSelector.svelte, web-common/src/features/canvas/inspector/types.ts
Add a scheme and range toggle under Color selector for heatmap charts.
The scheme tab has a list of preset color schemes. The range tab has a start and end color value which the user can tweak.
https://linear.app/rilldata/issue/APP-295/support-custom-chart-colors-for-heatmaps-and-pie-charts
**Checklist:**
=> feat:add color range config to heatmap

web-common/src/features/dashboards/pivot/PivotExpandableCell.svelte
Adds back the caret for sub-levels to always be visible for Pivot. Users weren't finding it when we only displayed it on hover
**Checklist:**
=> fix: adds back the caret for pivot

runtime/metricsview/ast.go, runtime/metricsview/metricssql/filter_parser.go, runtime/metricsview/metricssql/filter_parser_test.go, runtime/metricsview/metricssql/parser.go, runtime/metricsview/metricssql/parser_test.go, runtime/metricsview/metricssql/time_range_parser.go, runtime/queries/metricsview_aggregation.go, runtime/queries/proto.go, runtime/resolvers/builtin_metrics_sql_test.go, runtime/resolvers/metrics_sql.go, runtime/server/canvases.go, runtime/server/server.go
This PR refactors the package `runtime/metricsview/metricssql` so it no longer has a dependency on the `runtime` package. This enables it to be imported and used in more places through the codebase.
This change was motivated by the need to parse metrics SQL filters in the `runtime/parser` package. This now becomes possible like this:
```go
expr, err := metricssql.ParseFilter(metricsSQLFilter)
if err != nil { ... }
pb := metricsview.ExpressionToProto(expr)
```
**Checklist:**
=> Refactor package `metricssql` to avoid circular dependencies

runtime/drivers/duckdb/duckdb.go
[PLAT-256: Fix pivot exports for external OLAPs with `mode: readonly`](https://linear.app/rilldata/issue/PLAT-256/fix-pivot-exports-for-external-olaps-with-mode-readonly)
**Checklist:**
=> Fixing export failing in readonly mode

web-admin/src/routes/-/embed/+layout.svelte
disable adminserver to hide reports in embeds
**Checklist:**
=> fix: disable adminServer flag

runtime/drivers/registry.go, runtime/registry_test.go, web-common/src/features/feature-flags.ts, web-common/src/layout/ApplicationHeader.svelte, web-local/src/routes/+layout.svelte
For self managed git it can be confusing sometimes when the remote changes popup shows up. As a temporary fix for non-github integrations we are adding a `deploy` flag to disable all deploy related actions in rill cloud.
We need a follow to only show the remote changes popup when the local folder has just a rill managed remote.
**Checklist:**
=> feat: add flag to disable deploy actions

web-common/src/features/sources/modal/FileDrop.svelte, web-common/src/features/sources/modal/LocalSourceUpload.svelte, web-common/src/features/sources/modal/submitAddDataForm.ts, web-common/src/features/welcome/is-project-initialized.ts, web-local/tests/init.spec.ts, web-local/tests/rill-yaml.spec.ts
This PR adds explicit olap configuration when using unpack empty services. The handled cases can be found in https://www.notion.so/rilldata/Project-init-olap_connector-Behaviors-278ba33c8f5780a5bda1d44314bc306f
**Checklist:**
=> Fix `olap_connector` for various project init flows

web-common/src/features/canvas/LocalFiltersHeader.svelte, web-common/src/features/canvas/components/BaseCanvasComponent.ts, web-common/src/features/canvas/components/charts/Chart.svelte, web-common/src/features/canvas/components/charts/cartesian-charts/CartesianChart.ts, web-common/src/features/canvas/components/charts/combo-charts/ComboChart.ts, web-common/src/features/canvas/components/charts/funnel-charts/FunnelChart.ts, web-common/src/features/canvas/components/charts/selector.ts, web-common/src/features/canvas/components/charts/types.ts, web-common/src/features/canvas/components/charts/validate.ts, web-common/src/features/canvas/components/kpi/KPIProvider.svelte, web-common/src/features/canvas/components/kpi/selector.ts, web-common/src/features/canvas/components/leaderboard/LeaderboardDisplay.svelte, web-common/src/features/canvas/components/pivot/CanvasPivotDisplay.svelte, web-common/src/features/canvas/components/pivot/index.ts, web-common/src/features/canvas/components/pivot/util.ts, web-common/src/features/canvas/filters/CanvasFilters.svelte, web-common/src/features/canvas/inspector/PageEditor.svelte, web-common/src/features/canvas/inspector/chart/ChartTypeSelector.svelte, web-common/src/features/canvas/inspector/chart/PositionalFieldConfig.svelte, web-common/src/features/canvas/inspector/fields/SingleFieldInput.svelte, web-common/src/features/canvas/inspector/filters/DimensionFiltersInput.svelte, web-common/src/features/canvas/inspector/filters/TimeFiltersInput.svelte, web-common/src/features/canvas/inspector/selectors.ts, web-common/src/features/canvas/stores/canvas-entity.ts, web-common/src/features/canvas/stores/filters.ts, web-common/src/features/canvas/stores/metrics-view-selectors.ts, web-common/src/features/metrics-views/metrics-view-selectors.ts
Converts the `spec` store to a simple readable of the canvas resource. Created a new metrics selector store which is agnostic of canvas.
**Checklist:**
=> refac: pull out metric view selectors from canvas spec

web-common/src/features/canvas/components/charts/Chart.svelte, web-common/src/features/canvas/components/charts/builder.ts, web-common/src/features/canvas/components/charts/cartesian-charts/area/spec.ts, web-common/src/features/canvas/components/charts/cartesian-charts/bar-chart/spec.ts, web-common/src/features/canvas/components/charts/cartesian-charts/line-chart/spec.ts, web-common/src/features/canvas/components/charts/cartesian-charts/multi-metric-chart.ts, web-common/src/features/canvas/components/charts/cartesian-charts/stacked-bar/default.ts, web-common/src/features/canvas/components/charts/cartesian-charts/stacked-bar/normalized.ts, web-common/src/features/canvas/components/charts/circular-charts/pie.ts, web-common/src/features/canvas/components/charts/combo-charts/spec.ts, web-common/src/features/canvas/components/charts/selector.ts, web-common/src/features/canvas/components/charts/types.ts, web-common/src/features/dashboards/time-series/chart-colors.ts
For dark mode update colors for highlight bar and donut total
**Checklist:**
=> tweak: update dark mode colors for canvas charts

web-common/src/features/dashboards/leaderboard/LeaderboardControls.svelte
This PR only displays "Show context for all measures" toggle when multiple measures are selected. The toggle is still intact in the Dimension Table. Closes https://linear.app/rilldata/issue/APP-448/fix-show-context-for-all-measures-customer-bug
https://github.com/user-attachments/assets/049bc79c-39ff-4d09-b9ef-d0fa027b50a0
**Checklist:**
=> Display "show context for all measures" toggle when multiple measures are selected in Leaderboard

web-common/src/features/alerts/alert-preview-data.ts, web-common/src/features/dashboards/time-controls/time-range-mappers.ts
Until we have https://github.com/rilldata/rill/pull/8032 in, we need to use old iso ranges for comparisons.
**Checklist:**
=> fix: legacy iso time range comparisions in reports

web-admin/src/features/embeds/init-embed-public-api.ts, web-admin/src/routes/-/embed/+layout.ts, web-admin/tests/embeds.spec.ts, web-common/tests/fixtures/rill-cloud-fixtures.ts, web-common/tests/utils/generate-embed.ts
After the navigation refactor initial embed state no longer applied to dashboards. This makes sure those are retained after initial redirect.
**Checklist:**
=> fix: initial embed state not applying to dashboard
